Repository mozilla-mobile/android-components, pull requests merged in 2018-12, with the labels that each got.

#1524 [glean] Fixes Bugs 1497879, 1497892 - Add counter metric type to glean
  components/service/glean/src/main/java/mozilla/components/service/glean/CounterMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/CountersStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/StorageEngineManager.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/StringsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/UuidsStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/CounterMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/CountersStorageEngineTest.kt
Labels: 🕵️‍♀️ needs review

#1565 Add changelog for new errorpage localization [ci skip]
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1566 [glean] Document the pings available out of the box [ci skip]
  components/service/glean/README.md
  components/service/glean/docs/baseline.md
  components/service/glean/docs/pings.md
Labels: 🕵️‍♀️ needs review

#1568 Closes #1567: Don't show private sessions in awesomebar
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProviderTest.kt
Labels: 🛬 needs landing

#1590 Closes #1577: Request Desktop checkbox doesn't show selected state
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/SimpleBrowserMenuCheckbox.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/SimpleBrowserMenuCheckboxTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#1381 Bug 1493942 - enable snapshots releases
  .taskcluster.yml
  automation/taskcluster/decision_task_release.py
  automation/taskcluster/decision_task_snapshot_release.py
  automation/taskcluster/lib/module_definitions.py
  automation/taskcluster/lib/tasks.py
  automation/taskcluster/lib/util.py
  automation/taskcluster/schedule_snapshot_release.py
  publish.gradle
Labels: ⏳ work in progress

#1595 Issue #1396: CustomTabsService: Implement mayLaunchUrl()
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-servo/src/main/java/mozilla/components/browser/engine/servo/ServoEngine.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngine.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Engine.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/AbstractCustomTabsService.kt
  components/feature/customtabs/src/test/java/AbstractCustomTabsServiceTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1605 Closes #1546: Draw url box background behind site security icon..
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
Labels: 🕵️‍♀️ needs review

#1617 Closes #1613: Add FullScreen Feature
  components/feature/session/src/main/java/mozilla/components/feature/session/FullScreenFeature.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/FullScreenFeatureTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1620 Update changelog code snippet [ci skip]
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1631 Closes #1629: System - Notify observers when desktop mode changes.
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
Labels: 🕵️‍♀️ needs review
