Repository mozilla-mobile/android-components, pull requests merged in 2018-11, with the labels that each got.

#1247 Correct README.md file for ui-fonts component dependency [ci skip]
  components/ui/fonts/README.md
Labels: 🛬 needs landing

#1245 Issue #1181: Update deprecated coroutines for FxA
  components/service/firefox-accounts/README.md
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Config.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt
  samples/firefox-accounts/src/main/java/org/mozilla/samples/fxa/MainActivity.kt
  samples/sync-logins/src/main/java/org/mozilla/samples/sync/logins/MainActivity.kt
Labels: 🛬 needs landing

#1232 Issue #1109: concept-awesomebar: Introduce weights, suspend onInputChanged() and add shouldClearSuggestions..
  components/concept/awesomebar/src/main/java/mozilla/components/concept/awesomebar/AwesomeBar.kt
Labels: ✏️ needs changes

#1248 Closes #1242: Add suggestion API to concept-storage + basic implementation
  components/browser/storage-memory/src/main/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorage.kt
  components/browser/storage-memory/src/test/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorageTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt
Labels: 🕵️‍♀️ needs review

#1260 Issue #1109: browser-awesomebar: A customizable awesome bar implementation for browsers.
  README.md
  automation/taskcluster/artifacts.yml
  components/browser/awesomebar/README.md
  components/browser/awesomebar/build.gradle
  components/browser/awesomebar/proguard-rules.pro
  components/browser/awesomebar/src/main/AndroidManifest.xml
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/BrowserAwesomeBar.kt
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/SuggestionViewHolder.kt
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/SuggestionsAdapter.kt
  components/browser/awesomebar/src/main/res/layout/mozac_browser_awesomebar_chip.xml
  components/browser/awesomebar/src/main/res/layout/mozac_browser_awesomebar_item_chips.xml
  components/browser/awesomebar/src/main/res/layout/mozac_browser_awesomebar_item_generic.xml
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/BrowserAwesomeBarTest.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/SuggestionViewHolderTest.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/SuggestionsAdapterTest.kt
  components/browser/awesomebar/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  settings.gradle
Labels: 🛬 needs landing

#1261 Issue #1109: feature-awesomebar: Connecting a concept-awesomebar with…
  README.md
  automation/taskcluster/artifacts.yml
  components/feature/awesomebar/README.md
  components/feature/awesomebar/build.gradle
  components/feature/awesomebar/proguard-rules.pro
  components/feature/awesomebar/src/main/AndroidManifest.xml
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/AwesomeBarFeatureTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  settings.gradle
Labels: 🛬 needs landing

#1251 Closes #755: Replace Toolbar Actions from resouces to Drawables.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  components/concept/toolbar/build.gradle
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/concept/toolbar/src/test/java/mozilla/components/concept/toolbar/ActionButtonTest.kt
  components/concept/toolbar/src/test/java/mozilla/components/concept/toolbar/ActionImageTest.kt
  components/concept/toolbar/src/test/java/mozilla/components/concept/toolbar/ActionSpaceTest.kt
  components/concept/toolbar/src/test/java/mozilla/components/concept/toolbar/ActionToggleButtonTest.kt
  samples/toolbar/src/main/java/org/mozilla/samples/toolbar/SampleToolbarHelpers.kt
  samples/toolbar/src/main/java/org/mozilla/samples/toolbar/ToolbarActivity.kt
Labels: 🕵️‍♀️ needs review

#1282 Add browser-storage-sync readme and mention it in global readme. [ci skip]
  README.md
  components/browser/storage-sync/README.md
Labels: 🕵️‍♀️ needs review

#1280 Add domain suggestions to concept-storage and its implementations
  components/browser/storage-memory/build.gradle
  components/browser/storage-memory/src/main/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorage.kt
  components/browser/storage-memory/src/test/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorageTest.kt
  components/browser/storage-sync/build.gradle
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt
  components/feature/storage/src/test/java/mozilla/components/feature/storage/HistoryTrackingFeatureTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/DomainMatcher.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DomainMatcherTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#1299 Closes #1297: Add a HistoryStorage-powered suggestion provider to feature-awesomebar.
  components/feature/awesomebar/build.gradle
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/AwesomeBarFeatureTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProviderTest.kt
Labels: 🛬 needs landing

#1304 Update GeckoView Nightly to 65.0.20181107100135.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1313 Add new Kotlin version to changelog. [ci skip]
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1312 docs: Update jekyll and rubyzip [ci skip].
  docs/Gemfile
  docs/Gemfile.lock
Labels: 🕵️‍♀️ needs review

#1316 Gradle: Remove experimental block for Coroutines
  build.gradle
Labels: 🛬 needs landing

#1310 Closes #1252: Webfont blocking is controlled by both policy and setting.
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/matcher/UrlMatcher.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/matcher/UrlMatcherTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#1323 Issue #1021: Add new `concept-fetch` component.
  README.md
  components/concept/fetch/README.md
  components/concept/fetch/build.gradle
  components/concept/fetch/proguard-rules.pro
  components/concept/fetch/src/main/AndroidManifest.xml
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Client.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Headers.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Request.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Response.kt
  components/concept/fetch/src/test/java/mozilla/components/concept/fetch/ClientTest.kt
  components/concept/fetch/src/test/java/mozilla/components/concept/fetch/HeadersTest.kt
  components/concept/fetch/src/test/java/mozilla/components/concept/fetch/RequestTest.kt
  components/concept/fetch/src/test/java/mozilla/components/concept/fetch/ResponseTest.kt
  components/concept/fetch/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  settings.gradle
Labels: 🕵️‍♀️ needs review

#1315 Closes #1314: Make AwesomeBar styleable.
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/BrowserAwesomeBar.kt
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/SuggestionViewHolder.kt
  components/browser/awesomebar/src/main/res/layout/mozac_browser_awesomebar_chip.xml
  components/browser/awesomebar/src/main/res/layout/mozac_browser_awesomebar_item_chips.xml
  components/browser/awesomebar/src/main/res/layout/mozac_browser_awesomebar_item_generic.xml
  components/browser/awesomebar/src/main/res/values/attrs.xml
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/SuggestionViewHolderTest.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/SuggestionsAdapterTest.kt
Labels: 🕵️‍♀️ needs review

#1324 Issue #1303: Move CustomTabService to new feature component: feature-customtabs.
  README.md
  components/browser/session/src/main/java/mozilla/components/browser/session/tab/CustomTabsService.kt
  components/feature/customtabs/README.md
  components/feature/customtabs/build.gradle
  components/feature/customtabs/proguard-rules.pro
  components/feature/customtabs/src/main/AndroidManifest.xml
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsService.kt
  components/feature/customtabs/src/test/java/CustomTabsServiceTest.kt
  settings.gradle
Labels: 🕵️‍♀️ needs review

#1306 Fix mozilla/glean_parser#12 Upgrade glean_parser if at the incorrect version
  components/service/glean/scripts/sdk_generator.gradle
Labels: 🛬 needs landing

#1330 Issue #1327: (tooling-fetch-tests): A generic test suite for components that implement concept-fetch..
  components/tooling/fetch-tests/README.md
  components/tooling/fetch-tests/build.gradle
  components/tooling/fetch-tests/src/main/AndroidManifest.xml
  components/tooling/fetch-tests/src/main/java/mozilla/components/tooling/fetch/tests/FetchTestCases.kt
  settings.gradle
Labels: 🕵️‍♀️ needs review

#1344 Update Docker image to version 1.9..
  .taskcluster.yml
  automation/taskcluster/decision_task.py
  automation/taskcluster/lib/tasks.py
Labels: 🕵️‍♀️ needs review

#1345 Update GeckoView Nightly to 65.0.20181113100051.
  buildSrc/src/main/java/Gecko.kt
  docs/changelog.md
Labels: 🛬 needs landing

#1332 Wrap new synchronous logins API (from a-s) in an async version
  buildSrc/src/main/java/Dependencies.kt
  components/service/sync-logins/README.md
  components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/AsyncLoginsStorage.kt
  components/service/sync-logins/src/test/java/mozilla/components/service/sync/logins/SyncLoginsTest.kt
  samples/sync-logins/src/main/java/org/mozilla/samples/sync/logins/MainActivity.kt
  samples/sync-logins/src/main/java/org/mozilla/samples/sync/logins/SyncLoginsClient.kt
Labels: ✏️ needs changes

#1361 Issue #1348: (tooling-fetch-tests) Ignore external jars when running lint.
  components/tooling/fetch-tests/build.gradle
  components/tooling/fetch-tests/lint.xml
Labels: 🕵️‍♀️ needs review

#1360 Closes #1291: Gradle: Enable parallel execution.
  gradle.properties
Labels: 🕵️‍♀️ needs review

#1362 Add details on how to add maven repository [ci skip]
  README.md
Labels: 🕵️‍♀️ needs review

#1359 Delineates line in gradle output with module JSON
  automation/taskcluster/lib/module_definitions.py
  build.gradle
Labels: 🕵️‍♀️ needs review

#1355 Split application services gradle projects versions
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#1331 Issue #1325: (lib-fetch-httpurlconnection): A concept-fetch implementation using HttpURLConnection.
  README.md
  components/lib/fetch-httpurlconnection/README.md
  components/lib/fetch-httpurlconnection/build.gradle
  components/lib/fetch-httpurlconnection/proguard-rules.pro
  components/lib/fetch-httpurlconnection/src/main/AndroidManifest.xml
  components/lib/fetch-httpurlconnection/src/main/java/mozilla/components/lib/fetch/httpurlconnection/HttpURLConnectionClient.kt
  components/lib/fetch-httpurlconnection/src/test/java/mozilla/components/lib/fetch/httpurlconnection/HttpUrlConnectionFetchTestCases.kt
  components/tooling/fetch-tests/src/main/java/mozilla/components/tooling/fetch/tests/FetchTestCases.kt
  settings.gradle
Labels: ✏️ needs changes

#1174 Introduced detekt checks in samples module
  build.gradle
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashActivity.kt
  samples/dataprotect/src/main/java/org/mozilla/samples/dataprotect/Constants.kt
  samples/dataprotect/src/main/java/org/mozilla/samples/dataprotect/MainActivity.kt
  samples/dataprotect/src/main/java/org/mozilla/samples/dataprotect/ProtectedDataAdapter.kt
  samples/sync-logins/src/main/java/org/mozilla/samples/sync/logins/MainActivity.kt
  samples/sync-logins/src/main/java/org/mozilla/samples/sync/logins/SyncLoginsClient.kt
  samples/toolbar/src/main/java/org/mozilla/samples/toolbar/SampleToolbarHelpers.kt
  samples/toolbar/src/main/java/org/mozilla/samples/toolbar/ToolbarActivity.kt
Labels: 🛬 needs landing

#1389 Closes #1356: Introduce consumable stream for session fields
  components/support/base/src/main/java/mozilla/components/support/base/observer/Consumable.kt
  components/support/base/src/test/java/mozilla/components/support/base/observer/ConsumableTest.kt
Labels: 🛬 needs landing

#1352 Added debounce() method and tests
  components/support/ktx/build.gradle
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/CoroutineScope.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/CoroutineScopeTest.kt
Labels: 🕵️‍♀️ needs review

#1406 Update GeckoView Nightly to 65.0.20181116100120.
  buildSrc/src/main/java/Gecko.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1412 [glean] Remove splits from the glean sample app
  samples/glean/build.gradle
Labels: 🛬 needs landing

#1414 Update changelog [ci skip]
  docs/changelog.md
Labels: 🛬 needs landing

#1421 Closes #1420: Use `filesDir` as the parent folder for the places database file
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Connection.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
Labels: 🕵️‍♀️ needs review

#1415 Closes #1333: Implementing onCrash in Gecko Release/nightly/beta
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1419 Fixes #1366: Don't use private org.mozilla.gecko.
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/ThreadUtils.kt
Labels: 🕵️‍♀️ needs review

#1449 Closes #1446: Giving correct parameters to guessFileName when a file name is null in Gecko Release/nightly/beta
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-beta/src/test/java/org/mozilla/geckoview/MockWebResponseInfo.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/test/java/org/mozilla/geckoview/MockWebResponseInfo.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/org/mozilla/geckoview/MockWebResponseInfo.kt
Labels: 🕵️‍♀️ needs review

#1460 close #1270: Updated BrowserToolbar.ToggleButton and BrowserToolbar.Button .
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
Labels: 🕵️‍♀️ needs review

#1429 Closes #1403: Add a private browsing icon [ci skip]
  components/ui/icons/src/main/res/drawable/mozac_ic_private_browsing.xml
Labels: 🛬 needs landing

#1454 Closes #1451: Provide tab filter to TabsFeature.
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsFeature.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenter.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsFeatureTest.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenterTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1464 Update Kotlin to 1.3.10..
  buildSrc/src/main/java/Dependencies.kt
  docs/changelog.md
Labels: 🛬 needs landing

#1477 Issue #1428: SessionStorageTest: Fix flaky test.
  components/browser/session/src/test/java/mozilla/components/browser/session/storage/SessionStorageTest.kt
Labels: 🛬 needs landing

#1466 Closes #1311: notify observers of navigation change sooner
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
Labels: 🛬 needs landing

#1478 Fix customtabs support in sample browser
  samples/browser/build.gradle
  samples/browser/src/main/AndroidManifest.xml
Labels: in progress, 🛬 needs landing

#1474 Removing DownloadDialogListener class from feature-downloads
  components/feature/downloads/README.md
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragment.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragmentTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: in progress, 🛬 needs landing

#1482 [glean] 1507790: Use . rather than _ as a category delimiter
  components/service/glean/build.gradle
  components/service/glean/scripts/sdk_generator.gradle
  samples/glean/metrics.yaml
Labels: 🕵️‍♀️ needs review

#1479 Use Robolectric 4.0.2
  buildSrc/src/main/java/Dependencies.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  components/service/glean/build.gradle
  components/service/glean/src/test/java/mozilla/components/service/glean/EventMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/StringMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/UuidMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/firstrun/FileFirstRunDetectorTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/EventsStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/GenericScalarStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/StorageEngineManagerTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/StringsStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/UuidsStorageEngineTest.kt
  components/support/base/src/test/java/mozilla/components/support/base/log/logger/LoggerTest.kt
Labels: 🕵️‍♀️ needs review

#1486 Closes #1485: browser-domains: Move new classes to "autocomplete" sub package....
  components/browser/domains/src/main/java/mozilla/components/browser/domains/autocomplete/Providers.kt
  components/browser/domains/src/test/java/mozilla/components/browser/domains/ProvidersTest.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeature.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/toolbar/src/main/java/org/mozilla/samples/toolbar/ToolbarActivity.kt
Labels: 🕵️‍♀️ needs review

#1437 Closes #1434: Add support for choice html element for GeckoEngine
  README.md
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/Choice.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/README.md
  components/feature/prompts/build.gradle
  components/feature/prompts/proguard-rules.pro
  components/feature/prompts/src/main/AndroidManifest.xml
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/ChoiceAdapter.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/ChoiceDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_choice_dialogs.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_choice_group_item.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_menu_choice_item.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_menu_separator_choice_item.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_multiple_choice_item.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_single_choice_item.xml
  components/feature/prompts/src/main/res/values/strings.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/ChoiceDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/feature/prompts/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  docs/changelog.md
  samples/browser/build.gradle
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
  settings.gradle
Labels: 🕵️‍♀️ needs review

#1509 CODEOWNERS: Make telemetry group owner of glean sample app [ci skip].
  CODEOWNERS
Labels: 🕵️‍♀️ needs review

#1507 Add awesome bar to sample browser.
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/BrowserAwesomeBar.kt
  samples/browser/build.gradle
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/res/layout/fragment_browser.xml
Labels: 🕵️‍♀️ needs review

#1517 Closes #1513: browser-toolbar: Use AppCompat widgets.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
Labels: 🕵️‍♀️ needs review

#1505 Bug 1508227 - Provide a better example for using Glean
  samples/glean/src/main/AndroidManifest.xml
  samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/MainActivity.kt
Labels: 🕵️‍♀️ needs review

#1519 Blog: Allow linking to external articles. [ci skip]
  docs/_includes/post_detail.html
  docs/_layouts/home.html
  docs/_posts/2018-11-05-creating-a-simple-browser.md
Labels: 🕵️‍♀️ needs review

#1516 browser-awesomebar: Allow search suggestions to span multiple rows...
  components/browser/awesomebar/build.gradle
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/BrowserAwesomeBar.kt
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/SuggestionViewHolder.kt
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/layout/FlowLayout.kt
  components/browser/awesomebar/src/main/res/layout/mozac_browser_awesomebar_item_chips.xml
  components/browser/awesomebar/src/main/res/values/attrs.xml
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/SuggestionViewHolderTest.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/SuggestionsAdapterTest.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/layout/FlowLayoutTest.kt
Labels: 🕵️‍♀️ needs review

#1496 Do not depend on JNA directly.
  buildSrc/src/main/java/Dependencies.kt
  components/browser/storage-sync/build.gradle
  components/service/firefox-accounts/build.gradle
  components/service/firefox-accounts/lint.xml
  components/service/firefox-accounts/proguard-rules-consumer.pro
  components/service/sync-logins/build.gradle
  components/service/sync-logins/lint.xml
  components/service/sync-logins/proguard-rules-consumer.pro
Labels: 🛑 blocked

#1497 [glean] Run the API off the main thread by default.
  components/service/glean/src/main/java/mozilla/components/service/glean/Dispatchers.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/EventMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/StringMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/UuidMetricType.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/DispatchersTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/EventMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/FakeDispatchersInTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/StringMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/UuidMetricTypeTest.kt
Labels: 🕵️‍♀️ needs review

#1527 Allow custom combiner functions in GenericScalarStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/GenericScalarStorageEngine.kt
Labels: 🕵️‍♀️ needs review

#1521 Closes #1520: Allow styling of browser-tabstray component and display title if available..
  components/browser/tabstray/build.gradle
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/BrowserTabsTray.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabsAdapter.kt
  components/browser/tabstray/src/main/res/layout/mozac_browser_tabstray_item.xml
  components/browser/tabstray/src/main/res/values/attrs.xml
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/BrowserTabsTrayTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabViewHolderTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabsAdapterTest.kt
  samples/browser/src/main/res/layout/fragment_tabstray.xml
Labels: 🕵️‍♀️ needs review

#1525 Closes #1395: Implement CustomTabsService.warmup()..
  components/feature/customtabs/build.gradle
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/AbstractCustomTabsService.kt
  components/feature/customtabs/src/test/java/AbstractCustomTabsServiceTest.kt
  docs/changelog.md
  samples/browser/src/main/AndroidManifest.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/customtabs/CustomTabsService.kt
Labels: 🕵️‍♀️ needs review
