Repository mozilla-mobile/android-components, pull requests merged in 2019-02, with the labels that each got.

#1925 Closes #1881: Add additional test case for "urlBoxView" measure and layout.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
Labels: 🕵️‍♀️ needs review

#1735 [glean] Remove cookies from HTTP requests when uploading pings
  components/service/glean/src/main/java/mozilla/components/service/glean/net/HttpPingUploader.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/net/HttpPingUploaderTest.kt
Labels: 🕵️‍♀️ needs review

#1938 Closes #1935: Fix Downloads not working with Custom Tabs.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1924 Closes #1923: Perform haptic feedback when showing context menu.
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFeature.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuFeatureTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#1879 [glean] 1505395, 1523331: Generate specific metrics into the library's namespace.
  components/service/glean/scripts/sdk_generator.gradle
  components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/ping/BaselinePing.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/scheduler/GleanLifecycleObserver.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/MainActivity.kt
Labels: 🕵️‍♀️ needs review

#1967 EngineViewPresenter: Only subscribe to SessionManager if not tracking a fixed session.
  components/feature/session/src/main/java/mozilla/components/feature/session/EngineViewPresenter.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/EngineViewPresenterTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1964 Closes #1815: Adding support for JavaScript prompts on SystemEngineView
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1965 [glean] Add the `locale` field to the baseline ping
  components/service/glean/metrics.yaml
  components/service/glean/src/main/java/mozilla/components/service/glean/ping/BaselinePing.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/ping/BaselinePingTest.kt
Labels: 🕵️‍♀️ needs review

#1990 Isse #1976: Create shared interface for search use cases.
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  components/feature/intent/src/main/java/mozilla/components/feature/intent/IntentProcessor.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/SearchUseCases.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/SearchUseCasesTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1997 Add ui-doorhanger component for displaying floating "heads-up" popups.
  .buildconfig.yml
  README.md
  components/ui/doorhanger/README.md
  components/ui/doorhanger/build.gradle
  components/ui/doorhanger/proguard-rules.pro
  components/ui/doorhanger/src/main/AndroidManifest.xml
  components/ui/doorhanger/src/main/java/mozilla/components/ui/doorhanger/Doorhanger.kt
  components/ui/doorhanger/src/main/res/layout/mozac_ui_doorhanger_wrapper.xml
  components/ui/doorhanger/src/test/java/mozilla/components/ui/doorhanger/DoorhangerTest.kt
  components/ui/doorhanger/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1922 Perform browser-toolbar autocompletion off the UI thread
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/BrowserAwesomeBar.kt
  components/browser/domains/src/main/java/mozilla/components/browser/domains/autocomplete/Providers.kt
  components/browser/storage-memory/src/main/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/toolbar/build.gradle
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/AsyncFilterListenerTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/edit/EditToolbarTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/AutocompleteDelegate.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeature.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1963 Closes #1472: Adding support for JavaScript confirm dialogs
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/MultiButtonDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/MultiButtonDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2018 Update Kotlin to 1.3.21..
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#2027 Closes #2026: Ignoring schemes that are not https or http when downloading a file.
  components/feature/downloads/build.gradle
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadManager.kt
  components/feature/downloads/src/main/res/values/strings.xml
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadManagerTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2017 Sitepermissions location.
  components/feature/sitepermissions/README.md
  components/feature/sitepermissions/build.gradle
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/main/res/layout/mozac_feature_site_permissions_single_option.xml
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/ui/doorhanger/src/main/java/mozilla/components/ui/doorhanger/DoorhangerPrompt.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#2049 Issue #2038: Add browser-icons component for loading and storing website icons.
  .buildconfig.yml
  README.md
  components/browser/icons/README.md
  components/browser/icons/build.gradle
  components/browser/icons/proguard-rules.pro
  components/browser/icons/src/main/AndroidManifest.xml
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/Icon.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/IconRequest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/generator/DefaultIconGenerator.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/generator/IconGenerator.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/BrowserIconsTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/generator/DefaultIconGeneratorTest.kt
  components/browser/icons/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2058 Do not delay closing of tabs tray.
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsTrayInteractor.kt
Labels: 🕵️‍♀️ needs review

#2064 Issue #2062: SessionManager: Allow calling restore() with empty snapshot.
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2053 Add initial "facts" to browser-toolbar component.
  components/browser/toolbar/README.md
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/facts/ToolbarFacts.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/edit/EditToolbarTest.kt
  components/support/base/README.md
  components/support/base/src/main/java/mozilla/components/support/base/facts/Facts.kt
  components/support/base/src/main/java/mozilla/components/support/base/facts/processor/CollectionProcessor.kt
Labels: 🕵️‍♀️ needs review

#2070 Closes #1814: Adding support for onJsConfirm dialogs in SystemEngine
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2073 Closes #2072: Adding default id to toolbar urlView...
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/res/values/ids.xml
Labels: 🕵️‍♀️ needs review

#2085 Issue #2054: EditToolbar: Use CENTER scale type for cancel button in edit mode.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
Labels: 🕵️‍♀️ needs review

#2055 Closes #1954: Adding UI for notification content permission.
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
Labels: 🕵️‍♀️ needs review

#2083 Closes #2023: browser-toolbar: Allow theming of autocomplete suggestions foreground/background colors..
  components/browser/toolbar/README.md
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/res/values/attrs_browser_toolbar.xml
  components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2082 Closes #2077: Toolbar: Allow returning Boolean from "URL commit listener" to control switching to display mode.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarFeature.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarInteractor.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  docs/changelog.md
  samples/toolbar/src/main/java/org/mozilla/samples/toolbar/ToolbarActivity.kt
Labels: 🕵️‍♀️ needs review

#2091 Closes #2078: Add "Browsers" helper class.
  components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2108 Closes #814: browser-toolbar: Make fading edge length configurable.
  components/browser/toolbar/README.md
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/res/values/attrs_browser_toolbar.xml
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2111 Issue #2109: Change "url" property from String to CharSequence.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
Labels: 🛬 needs landing

#2110 PublicSuffixList: Fix naming of "public suffix plus one".
  components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixList.kt
Labels: 🛬 needs landing

#2101 Closes #2099: ToolbarPresenter: Display empty state.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarPresenter.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarPresenterTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2106 Add blog posting about session storage options. [ci skip]
  docs/_posts/2019-02-19-saving-state.md
  docs/assets/images/blog/session-bundles.png
Labels: 🕵️‍♀️ needs review

#2118 Issue #2087: Update to GeckoView Nightly 67.0.20190220040540.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequestTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequestTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequestTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/permission/PermissionRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/permission/PermissionRequestTest.kt
Labels: 🕵️‍♀️ needs review

#2119 Closes #2098: support-utils: Add unit tests for Browsers class..
  components/support/utils/build.gradle
  components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/BrowsersTest.kt
Labels: 🕵️‍♀️ needs review

#2089 Update to Robolectric 4.2
  buildSrc/src/main/java/Dependencies.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/browser/search/build.gradle
  components/browser/search/src/test/java/mozilla/components/browser/search/SearchEngineManagerTest.kt
Labels: ✏️ needs changes

#2120 [glean] Create a way for glean test API functions to await async IO operations
  components/service/glean/src/main/java/mozilla/components/service/glean/BooleanMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/CommonMetricData.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/CounterMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/DatetimeMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/EventMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/StringListMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/StringMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/UuidMetricType.kt
Labels: <glean>

#2149 browser-engine-gecko-*: Explicitly set autofill flag.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1874 Build docker images in taskcluster
  .gitignore
  .taskcluster.yml
  automation/docker/build/Dockerfile
  automation/docker/build/requirements.txt
  automation/docker/build/requirements.txt.in
  automation/docker/decision/Dockerfile
  automation/docker/decision/requirements.txt
  automation/docker/decision/requirements.txt.in
  automation/taskcluster/decision_task.py
  automation/taskcluster/lib/tasks.py
  automation/taskcluster/schedule_snapshot_release.py
Labels: ⏳ work in progress

#2169 Update dependencies.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#1973 [glean]Use WorkManager for uploading glean pings
  buildSrc/src/main/java/Dependencies.kt
  components/service/glean/build.gradle
  components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/scheduler/GleanLifecycleObserver.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/scheduler/PingScheduler.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/scheduler/PingUploadWorker.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/EventsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/PingStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/BooleanMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/CounterMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/EventMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/StringListMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/StringMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TestLifeCycleOwner.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TestUtil.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TimespanMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/UuidMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/scheduler/PingSchedulerTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/scheduler/PingUploadWorkerTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/EventsStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/PingStorageEngineTest.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/MainActivity.kt
Labels: <glean>

#2158 Remove backpage.com from domains
  components/browser/domains/src/main/assets/domains/global
Labels: 🛑 blocked

#2178 Revert "Build docker images in taskcluster"
  .gitignore
  .taskcluster.yml
  automation/docker/Dockerfile
  automation/docker/build/requirements.txt
  automation/docker/build/requirements.txt.in
  automation/docker/decision/Dockerfile
  automation/docker/decision/requirements.txt
  automation/docker/decision/requirements.txt.in
  automation/taskcluster/decision_task.py
  automation/taskcluster/lib/tasks.py
  automation/taskcluster/schedule_snapshot_release.py
Labels: 🛑 blocked

#2182 Issue 2109: feature-toolbar: Add option to color "registrable domain".
  buildSrc/src/main/java/Dependencies.kt
  components/feature/toolbar/build.gradle
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarFeature.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarPresenter.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/internal/URLRenderer.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarPresenterTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/internal/URLRendererTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2155 Closes #2150: Add engine API to install WebExtensions
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Engine.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineTest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/webextension/WebExtensionTest.kt
  docs/changelog.md
  samples/browser/src/geckoNightly/java/org/mozilla/samples/browser/Components.kt
  samples/browser/src/main/assets/extensions/borderify/borderify.js
  samples/browser/src/main/assets/extensions/borderify/manifest.json
Labels: 🕵️‍♀️ needs review

#2176 Use WorkManager for uploading glean pings v2
  buildSrc/src/main/java/Dependencies.kt
  components/service/glean/build.gradle
  components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/scheduler/PingUploadWorker.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/EventsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/PingStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TestUtil.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/scheduler/PingUploadWorkerTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/EventsStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/PingStorageEngineTest.kt
Labels: <glean>

#1933 Use stable IDs for awesomebar suggestions; retain suggestions on the screen
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/BrowserAwesomeBar.kt
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/SuggestionsAdapter.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/BrowserAwesomeBarTest.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/SuggestionsAdapterTest.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/layout/DefaultSuggestionViewHolderTest.kt
  components/concept/awesomebar/src/main/java/mozilla/components/concept/awesomebar/AwesomeBar.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review
