Repository mozilla-mobile/android-components, pull requests merged in 2019-03, with the labels that each got.

#2215 Implement persistent storage for Ping lifetime metrics
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/GenericScalarStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/LabeledMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/BooleansStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/CountersStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/DatetimesStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/GenericScalarStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/StringListsStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/StringsStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/TimespansStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/UuidsStorageEngineTest.kt
Labels: <glean>

#2233 Update glean ping documentation[ci skip]
  components/service/glean/docs/baseline.md
  components/service/glean/docs/events.md
  components/service/glean/docs/metrics.md
  components/service/glean/docs/pings.md
Labels: <glean>

#2237 Closes #2236: BrowserMenuImageText's TextView should be have importan…
  components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_text.xml
Labels: 🛬 needs landing

#2234 Closes #2231 Check if CustomTabToolbarFeature initialized in onBackPressed
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#2252 GeckoView update (20190305-140759)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#2199 Closes #2121: Adding db for saving site permissions.
  components/feature/sitepermissions/build.gradle
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissions.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsStorage.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDao.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDatabase.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsEntity.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsStorageTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/db/SitePermissionEntityTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/db/StatusConverterTest.kt
Labels: 🕵️‍♀️ needs review

#2230 Move value validation and correction from MetricTypes to StorageEngines
  components/service/glean/src/main/java/mozilla/components/service/glean/CounterMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/DatetimeMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/EventMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/StringListMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/StringMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/CountersStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/EventsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/StringListsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/StringsStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/CounterMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/DatetimeMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/EventMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/StringListMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/StringMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/CountersStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/DatetimesStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/EventsStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/StringListsStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/StringsStorageEngineTest.kt
Labels: <glean>

#2257 Issue #2080: Extract website icon resources via WebExtension.
  components/browser/icons/build.gradle
  components/browser/icons/src/main/assets/extensions/browser-icons/icons.js
  components/browser/icons/src/main/assets/extensions/browser-icons/manifest.json
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  samples/browser/src/geckoNightly/java/org/mozilla/samples/browser/Components.kt
Labels: 🕵️‍♀️ needs review

#2266 Closes #2265: Validating null or empty headers in the download manager
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadManager.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadManagerTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2268 Implement a testing API for glean experiments
  components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/ExperimentsStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/EventMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TestUtil.kt
Labels: <glean>

#2274 Closes #2040: Create decoder for decoding ICO files.
  components/browser/icons/build.gradle
  components/browser/icons/src/androidTest/java/components/browser/icons/ICOIconDecoderTest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/IconRequest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/ICOIconDecoder.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/IconDecoder.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/ico/IconDirectoryEntry.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/Utils.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/decoder/ICOIconDecoderTest.kt
  components/browser/icons/src/test/resources/ico/golem_favicon.ico
  components/browser/icons/src/test/resources/ico/microsoft_favicon.ico
  components/browser/icons/src/test/resources/ico/nvidia_favicon.ico
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/ByteArray.kt
Labels: 🕵️‍♀️ needs review

#2322 0.46 release prep [ci skip]
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2299 Closes #2290: Expose WebAppManifest in Session.
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/manifest/WebAppManifest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2326 Removing "SNAPSHOT" word from 0.46.0 in the changelog [ci skip]
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2211 Close #2201 - Adds TwoStateButton in BrowserMenuItemToolbar
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuItemToolbar.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuItemToolbarTest.kt
  docs/changelog.md
  samples/toolbar/src/main/java/org/mozilla/samples/toolbar/ToolbarActivity.kt
Labels: 🕵️‍♀️ needs review

#2339 Closes #2332: Add WebAppManifestParser for creating WebAppManifest from JSON.
  components/browser/session/src/main/java/mozilla/components/browser/session/manifest/WebAppManifest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/manifest/WebAppManifestParser.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/manifest/WebAppManifestParserTest.kt
  components/browser/session/src/test/resources/manifests/example_google.json
  components/browser/session/src/test/resources/manifests/example_mdn.json
  components/browser/session/src/test/resources/manifests/invalid_json.json
  components/browser/session/src/test/resources/manifests/minimal.json
  components/browser/session/src/test/resources/manifests/spec_typical.json
  components/browser/session/src/test/resources/manifests/twitter_mobile.json
  components/browser/session/src/test/resources/manifests/unusual.json
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2343 Issue #2340: Add component for landing PWA related code.
  .buildconfig.yml
  README.md
  components/feature/pwa/README.md
  components/feature/pwa/build.gradle
  components/feature/pwa/proguard-rules.pro
  components/feature/pwa/src/main/AndroidManifest.xml
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/Placeholder.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/PlaceholderTest.kt
  components/feature/pwa/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: 🕵️‍♀️ needs review

#2334 [glean] Implement the new "metrics" ping scheduling mechanism
  buildSrc/src/main/java/Dependencies.kt
  components/service/glean/docs/pings/metrics.md
  components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/scheduler/GleanLifecycleObserver.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/scheduler/MetricsPingScheduler.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/utils/DateUtils.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TestUtil.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/scheduler/MetricsPingSchedulerTest.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/MainActivity.kt
Labels: <glean>

#2367 Update GeckoView Nightly to 67.0.20190315093917.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
Labels: 🕵️‍♀️ needs review

#2370 Closes #2207: Adding helper to detect if we are running in the main process...
  components/support/ktx/build.gradle
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/ContextTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2355 Issue #2291: Add extension method for applying orientation modes.
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/Placeholder.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/Activity.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/PlaceholderTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/ActivityKtTest.kt
Labels: 🕵️‍♀️ needs review

#2398 0.47 release prep [ci skip]
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2401 Gradle: Print more helpful test report to stdout.
  build.gradle
Labels: 🕵️‍♀️ needs review

#2250 Integrate site permissions storage.
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt
  components/feature/sitepermissions/build.gradle
  components/feature/sitepermissions/schemas/mozilla.components.feature.sitepermissions.db.SitePermissionsDatabase/1.json
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissions.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/main/res/values/strings.xml
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/db/StatusConverterTest.kt
Labels: 🕵️‍♀️ needs review

#2431 Issue #2404: Print logcat to stdout while running unit tests.
  build.gradle
  components/support/base/src/main/java/mozilla/components/support/base/log/Log.kt
Labels: 🕵️‍♀️ needs review

#2425 Closes #2407: Throw RuntimeException if GeckoRuntime is shutting down unsolicited.
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2372 Closes #2368: SearchSuggestionProvider: Allow setting a limit.
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2433 Issue #2368: Changelog: Move SearchSuggestionProvider entry to 0.48.0. [ci skip]
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2417 Closes #2315: Adding support for site configurations permissions...
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsRules.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsRulesTest.kt
Labels: 🕵️‍♀️ needs review

#2434 Closes #2426: Updating apostrophes on Site Permissions prompts....
  components/feature/sitepermissions/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#2424 Issue #1845: Expose list of media in Session.
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMediaController.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMediaDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaControllerTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaDelegateTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/media/Media.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/media/MediaTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2388 PWA: Add activities for routing and handling standalone/fullscreen apps.
  components/feature/pwa/README.md
  components/feature/pwa/build.gradle
  components/feature/pwa/src/main/AndroidManifest.xml
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/AbstractWebAppShellActivity.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppLauncherActivity.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/AbstractWebAppShellActivityTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppLauncherActivityTest.kt
Labels: 🕵️‍♀️ needs review

#2447 Add glean test API documentation [ci skip]
  components/service/glean/README.md
  components/service/glean/docs/metrics/testing-metrics.md
Labels: <glean>

#2500 Reduce glean test impact
  components/service/glean/src/test/java/mozilla/components/service/glean/ping/PingMakerTest.kt
Labels: <glean>

#2492 Issue #2039: Add data classes for icon resources
  components/browser/icons/src/main/java/mozilla/components/browser/icons/IconRequest.kt
Labels: 🕵️‍♀️ needs review

#2491 Closes #2487: Added support for Beta and Stable channels for GV version verifier plugin..
  build.gradle
  buildSrc/src/main/java/GVNightlyVersionVerifierPlugin.kt
  buildSrc/src/main/java/GVVersionVerifierPlugin.kt
Labels: 🛬 needs landing

#2517 [glean] Update glean docs and mention the `client_info` section [ci skip]
  components/service/glean/README.md
  components/service/glean/docs/pings/baseline.md
  components/service/glean/docs/pings/pings.md
Labels: <glean>

#2441 Implement glean ping tagging for "debug view".
  components/service/glean/README.md
  components/service/glean/src/main/java/mozilla/components/service/glean/config/Configuration.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/debug/GleanDebugActivity.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/net/HttpPingUploader.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TestUtil.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/debug/GleanDebugActivityTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/net/HttpPingUploaderTest.kt
Labels: <glean>

#2515 Closes #2514: Bump appservices to 0.22.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#2539 [glean] Make glean's `HttpPingUploader` logs more helpful
  components/service/glean/src/main/java/mozilla/components/service/glean/net/HttpPingUploader.kt
Labels: <glean>

#2516 Add the "app_channel" field to glean pings' `client_info`
  components/service/glean/README.md
  components/service/glean/build.gradle
  components/service/glean/docs/pings/pings.md
  components/service/glean/metrics.yaml
  components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/config/Configuration.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
Labels: <glean>

#2554 Update to Docker image 1.16.
  .taskcluster.yml
  automation/taskcluster/lib/tasks.py
Labels: 🕵️‍♀️ needs review

#2529 Add deleteVisit API to HistoryStorage
  components/browser/storage-memory/src/main/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorage.kt
  components/browser/storage-memory/src/test/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorageTest.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/HistoryDelegateTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2550 [glean] Fix a few intermittents in glean tests.
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/PingStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/EventsStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/PingStorageEngineTest.kt
Labels: <glean>

#2546 Closes #175: BrowserToolbar: Add support for "edit actions"..
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/internal/ActionWrapper.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/internal/ToolbarUtils.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/edit/EditToolbarTest.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2558 Refactor GenericScalarStorageEngine and ScalarType to remove "Scalar"
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/BooleansStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/CountersStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/DatetimesStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/GenericStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/StringListsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/StringsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/TimespansStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/TimingDistributionsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/UuidsStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/LabeledMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/GenericStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/MockGenericStorageEngine.kt
Labels: <glean>

#2556 Closes #171: BrowserToolbar: Allow setting listener on site security icon.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2557 Closes #2497: Update GeckoView Nightly to 68.0.20190329094433 and new state API.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionState.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionStateTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2553 1536141: Send events as objects rather than arrays
  components/service/glean/build.gradle
  components/service/glean/docs/pings/events.md
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/EventsStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/EventsStorageEngineTest.kt
Labels: <glean>
