Repository mozilla-mobile/android-components, pull requests merged in 2019-04, with the labels that each got.

#2573 Refactor and remove Baseline.kt from service-glean
  components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/ping/BaselinePing.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/utils/LocaleUtils.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/ping/BaselinePingTest.kt
Labels: <glean>

#2586 Closes #2585: concept-fetch: Add support for interceptors...
  components/concept/fetch/README.md
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/interceptor/Interceptor.kt
  components/concept/fetch/src/test/java/mozilla/components/concept/fetch/interceptor/InterceptorTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2588 Issue #2571: Add option to recover from crashed sessions...
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-servo/src/main/java/mozilla/components/browser/engine/servo/ServoEngineSession.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2598 Update changelog for 0.49.0 release [ci skip].
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2587 [glean] Move `MetricsPingWorker` out of `MetricsPingScheduler`
  components/service/glean/src/main/java/mozilla/components/service/glean/scheduler/MetricsPingScheduler.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/scheduler/MetricsPingSchedulerTest.kt
Labels: <glean>

#2593 Await ping serialization before enqueueing PingUploadWorker.
  components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/EventsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/PingStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/scheduler/MetricsPingSchedulerTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/EventsStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/PingStorageEngineTest.kt
Labels: <glean>

#2626 Glean: fix an issue in testing background pings
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TestUtil.kt
Labels: <glean>

#2612 Move prompt string under discussion out of l10n, fixes #2541
  components/feature/prompts/src/main/res/values/quarantined_strings.xml
  components/feature/prompts/src/main/res/values/strings.xml
Labels: 🌐 L10N

#2627 1538745: Make TimingDistributionData.values use Int as key
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/TimingDistributionsStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/metrics/TimingDistributionMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/TimingDistributionsStorageEngineTest.kt
Labels: <glean>

#2618 Glean: Limit timing distribution's range property to exactly 2 elements
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/TimingDistributionsStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/TimingDistributionsStorageEngineTest.kt
Labels: <glean>

#2629 Restrict the exposed `Configuration` fields
  components/service/glean/src/main/java/mozilla/components/service/glean/config/Configuration.kt
Labels: <glean>

#2628 Closes #2060: browser-icons: Create loader for data uris.
  components/browser/icons/src/androidTest/java/mozilla/components/browser/icons/OnDeviceBrowserIconsTest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/Icon.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/DataUriIconLoader.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/loader/DataUriIconLoaderTest.kt
Labels: 🕵️‍♀️ needs review

#2634 Issue #2487: update_geckoview.sh: Add support for updating all GeckoView channels (nightly, beta, release).
  automation/taskcluster/action/update_geckoview.sh
Labels: 🕵️‍♀️ needs review

#2639 Import l10n from android-l10n.
  components/browser/engine-system/src/main/res/values-it/strings.xml
  components/browser/toolbar/src/main/res/values-de/strings.xml
  components/browser/toolbar/src/main/res/values-it/strings.xml
  components/browser/toolbar/src/main/res/values-zh-rCN/strings.xml
  components/feature/contextmenu/src/main/res/values-it/strings.xml
  components/feature/customtabs/src/main/res/values-it/strings.xml
  components/feature/downloads/src/main/res/values-de/strings.xml
  components/feature/downloads/src/main/res/values-it/strings.xml
  components/feature/downloads/src/main/res/values-zh-rCN/strings.xml
  components/feature/findinpage/src/main/res/values-it/strings.xml
  components/feature/prompts/src/main/res/values-it/strings.xml
  components/feature/sitepermissions/src/main/res/values-de/strings.xml
  components/feature/sitepermissions/src/main/res/values-it/strings.xml
  components/feature/sitepermissions/src/main/res/values-zh-rCN/strings.xml
  components/feature/tabs/src/main/res/values-it/strings.xml
  components/lib/crash/src/main/res/values-it/strings.xml
  components/support/ktx/src/main/res/values-it/strings.xml
Labels: 🌐 L10N

#2649 Closes #494: Expose icon (Bitmap) in Session.
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
Labels: 🕵️‍♀️ needs review

#2669 Closes #2656 #2657 Remove multiple hardware from camera and microphone prompts
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/feature/sitepermissions/build.gradle
  components/feature/sitepermissions/schemas/mozilla.components.feature.sitepermissions.db.SitePermissionsDatabase/2.json
  components/feature/sitepermissions/src/androidTest/java/mozilla/components/feature/sitepermissions/db/OnDeviceSitePermissionsStorageTest.kt
  components/feature/sitepermissions/src/androidTest/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDaoTest.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissions.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsRules.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsStorage.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDatabase.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsEntity.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsRulesTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsStorageTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/db/SitePermissionEntityTest.kt
Labels: 🕵️‍♀️ needs review

#2693 Closes #2687: Added support for deleting all site permissions and get paged all site permissions..
  components/feature/sitepermissions/build.gradle
  components/feature/sitepermissions/src/androidTest/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDaoTest.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsStorage.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDao.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsStorageTest.kt
Labels: 🛬 needs landing

#2703 Expose automaticLanguageAdjustment, and automatically detect the locale.
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/integration/LocaleSettingUpdater.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/integration/SettingUpdater.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/integration/SettingUpdaterTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2741 Update ktlint to 0.31.0.
  build.gradle
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/matcher/ReversibleString.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/decoder/ICOIconDecoderTest.kt
  components/feature/sync/src/main/java/mozilla/components/feature/sync/BackgroundSyncManager.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt
Labels: 🕵️‍♀️ needs review

#2737 Closes #2736: Update GeckoView Nightly to 68.0.20190414095735..
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2750 Closes #2439: Tests creating GeckoView instance block indefinitely
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt
Labels: 🛬 needs landing

#2745 Closes #2744: Centers titleView and urlView when both are displayed
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
Labels: 🛬 needs landing

#2755 GeckoView update (nightly) (20190416-141309).
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#2731 Bump application-services component version to 0.25.2
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#2765 Closes #2044: browser-icons: Cache loaded icons in memory.
  components/browser/icons/build.gradle
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/Icon.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/DataUriIconLoader.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/HttpIconLoader.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/IconLoader.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/MemoryIconLoader.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/preparer/IconPreprarer.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/preparer/MemoryIconPreparer.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/IconProcessor.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/MemoryIconProcessor.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/MemoryCache.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/BrowserIconsTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/loader/DataUriIconLoaderTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/loader/HttpIconLoaderTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/loader/MemoryIconLoaderTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/preparer/MemoryIconPreparerTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/processor/MemoryIconProcessorTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/utils/MemoryCacheTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2709 For #2708 - Adds BookmarksStorageSuggestionProvider
  components/browser/storage-memory/src/main/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorage.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/StorageUtils.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2786 Make sure metric recording happens in the expected order
  components/service/glean/src/main/java/mozilla/components/service/glean/Dispatchers.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/DispatchersTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TestUtil.kt
Labels: <glean>

#2783 Closes #2771: Only clear Session.searchTerms after request initiated by the user.
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarPresenter.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2739 Update to Kotlin 1.3.30 and Coroutines 1.2.0.
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/service/firefox-accounts/build.gradle
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
Labels: 🕵️‍♀️ needs review

#2770 Closes #2428: Update strings after L10N review.
  components/browser/engine-system/src/main/res/values/strings.xml
  components/ui/tabcounter/src/main/res/layout/mozac_ui_tabcounter_layout.xml
  components/ui/tabcounter/src/main/res/values-de/strings.xml
  components/ui/tabcounter/src/main/res/values-es/strings.xml
  components/ui/tabcounter/src/main/res/values-fr/strings.xml
  components/ui/tabcounter/src/main/res/values-it/strings.xml
  components/ui/tabcounter/src/main/res/values-ja/strings.xml
  components/ui/tabcounter/src/main/res/values-ko/strings.xml
  components/ui/tabcounter/src/main/res/values-zh-rCN/strings.xml
  components/ui/tabcounter/src/main/res/values-zh-rTW/strings.xml
  components/ui/tabcounter/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#2833 Glean doc improvements [ci skip]
  components/service/glean/README.md
  components/service/glean/docs/pings/custom.md
Labels: <glean>

#2842 Persist FxA account state via the persistence callback
  components/concept/sync/src/main/java/mozilla/components/concept/sync/OAuthAccount.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/AccountStorage.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaAccountManager.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2869 Update GeckoView to 68.0.20190428094048.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
Labels: 🕵️‍♀️ needs review

#2872 GeckoView update (nightly) (20190429-141420)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#2870 Issue #2796: Update to Docker image version 1.17.
  .taskcluster.yml
  automation/taskcluster/lib/tasks.py
Labels: 🕵️‍♀️ needs review

#2876 Closes #2706: Do not remember site permissions in private browsing.
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review
