Repository mozilla-mobile/android-components, pull requests merged in 2019-01, with the labels that each got.

#1632 Closes #1603: Add switch menu item.
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuCheckbox.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuCompoundButton.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuSwitch.kt
  components/browser/menu/src/main/res/layout/mozac_browser_menu_item_checkbox.xml
  components/browser/menu/src/main/res/layout/mozac_browser_menu_item_switch.xml
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuCheckboxTest.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuCompoundButtonTest.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuSwitchTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#1642 Issue #1012: service-telemetry: Replace http client with concept-fetch
  components/service/telemetry/build.gradle
  components/service/telemetry/src/main/java/org/mozilla/telemetry/net/DebugLogClient.kt
  components/service/telemetry/src/main/java/org/mozilla/telemetry/net/HttpURLConnectionTelemetryClient.java
  components/service/telemetry/src/main/java/org/mozilla/telemetry/net/TelemetryClient.java
  components/service/telemetry/src/main/java/org/mozilla/telemetry/net/TelemetryClient.kt
  components/service/telemetry/src/test/java/org/mozilla/telemetry/TelemetryTest.java
  components/service/telemetry/src/test/java/org/mozilla/telemetry/net/DebugLogClientTest.java
  components/service/telemetry/src/test/java/org/mozilla/telemetry/net/HttpUrlConnectionTelemetryClientTest.java
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1643 feature-customtabs: Execute warmup() on main thread.
  components/feature/customtabs/build.gradle
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/AbstractCustomTabsService.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1655 [glean] Mention the data-review process in the glean README [ci skip]
  components/service/glean/README.md
  components/service/glean/metrics.yaml
Labels: 🕵️‍♀️ needs review

#1670 Fix error in 0.37.0 changelog. [ci skip]
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1636 Closes #1504: Add support for alert popup in WebView
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/main/res/values/strings.xml
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1660 Closes #1647: Improve URL toolbar autocompletion matching
  components/browser/storage-memory/src/test/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorageTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/DomainMatcher.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DomainMatcherTest.kt
Labels: 🕵️‍♀️ needs review

#1476 [glean] Implement the "timespan" metric type in glean
  components/service/glean/scripts/sdk_generator.gradle
  components/service/glean/src/main/java/mozilla/components/service/glean/TimeUnit.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/TimespanMetricType.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/CountersStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/GenericScalarStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/StorageEngineManager.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/StringListsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/StringsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/TimespansStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/UuidsStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TimespanMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/GenericScalarStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/TimespansStorageEngineTest.kt
  samples/glean/metrics.yaml
  samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/MainActivity.kt
Labels: 🕵️‍♀️ needs review

#1672 Update version of GeckoView Nightly to 66.0.20190107093040.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
Labels: 🕵️‍♀️ needs review

#1689 Allow easy configuration of gradle dependency substitution for A-S
  settings.gradle
Labels: 🕵️‍♀️ needs review

#1701 Switch to android.net.Uri in domain matching logic
  components/browser/storage-memory/src/test/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorageTest.kt
  components/feature/toolbar/build.gradle
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/support/utils/build.gradle
  components/support/utils/src/main/java/mozilla/components/support/utils/DomainMatcher.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DomainMatcherTest.kt
Labels: 🕵️‍♀️ needs review

#1706 AutoSave: Do not block on background save.
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/AutoSave.kt
Labels: 🕵️‍♀️ needs review

#1702 Closes #1470: Add support for Authentication dialogs.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/AuthenticationDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_prompt_auth_prompt.xml
  components/feature/prompts/src/main/res/values/strings.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/AuthenticationDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1703 Add FxaException.Network documentation
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaException.kt
Labels: 🛑 blocked

#1716 Adding password toggle button to the authentication dialog.
  components/feature/prompts/src/main/res/layout/mozac_feature_prompt_auth_prompt.xml
Labels: 🕵️‍♀️ needs review

#1715 Closes #1469: Added support for input type color
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/ColorPickerDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/DatePickerDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_color_item.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_color_picker_dialogs.xml
  components/feature/prompts/src/main/res/values/strings.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/ColorPickerDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/DatePickerDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1656 Closes #1530: Add support for html input datetime-local and time for GeckoEngine
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/DatePickerDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/TimePickerDialogFragment.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_date_time_picker.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_time_picker.xml
  components/feature/prompts/src/main/res/values/strings.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/DatePickerDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/TimePickerDialogFragmentTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1665 Closes #1664: Use BrowserFragment.onCreateView instead of onViewCreated
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🛬 needs landing

#1721 Closes #1681 - Add ClipboardSuggestionProvider for providing URL suggestions from clipboard.
  buildSrc/src/main/java/Dependencies.kt
  components/browser/awesomebar/build.gradle
  components/browser/engine-gecko-beta/build.gradle
  components/browser/engine-gecko-nightly/build.gradle
  components/browser/engine-gecko/build.gradle
  components/browser/engine-system/build.gradle
  components/browser/tabstray/build.gradle
  components/concept/awesomebar/src/main/java/mozilla/components/concept/awesomebar/AwesomeBar.kt
  components/feature/awesomebar/build.gradle
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/AwesomeBarFeatureTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProviderTest.kt
  components/feature/prompts/build.gradle
  components/feature/session-bundling/build.gradle
  components/service/glean/build.gradle
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#1736 [glean] Pin the Miniconda3 version to 4.5.11
  components/service/glean/scripts/sdk_generator.gradle
Labels: 🕵️‍♀️ needs review

#1737 [glean] Implement the `duration` field
  components/service/glean/docs/baseline.md
  components/service/glean/metrics.yaml
  components/service/glean/src/main/java/mozilla/components/service/glean/scheduler/GleanLifecycleObserver.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/GenericScalarStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/TimespansStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/TimespansStorageEngineTest.kt
Labels: 🕵️‍♀️ needs review

#1741 [glean] Remove the "sessions" field from the baseline ping
  components/service/glean/docs/baseline.md
  components/service/glean/metrics.yaml
  components/service/glean/src/main/java/mozilla/components/service/glean/scheduler/GleanLifecycleObserver.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
Labels: 🕵️‍♀️ needs review

#1754 Link to dependencies and configurations from changelog.
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1756 Closes #1744: Support "UP" and "DOWN" orientations in browser-menu
  components/browser/menu/build.gradle
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/BrowserMenuTest.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1772 Closes #1771: Adding support for single choice items with sub-menus group
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/ChoiceAdapter.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/ChoiceDialogFragmentTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1668 Introduce simple, generic API for collecting "facts" emmitted by components.
  components/support/base/build.gradle
  components/support/base/src/main/java/mozilla/components/support/base/facts/Action.kt
  components/support/base/src/main/java/mozilla/components/support/base/facts/Fact.kt
  components/support/base/src/main/java/mozilla/components/support/base/facts/FactProcessor.kt
  components/support/base/src/main/java/mozilla/components/support/base/facts/Facts.kt
  components/support/base/src/main/java/mozilla/components/support/base/facts/processor/LogFactProcessor.kt
  components/support/base/src/test/java/mozilla/components/support/base/facts/FactProcessorTest.kt
  components/support/base/src/test/java/mozilla/components/support/base/facts/FactTest.kt
  components/support/base/src/test/java/mozilla/components/support/base/facts/FactsTest.kt
  components/support/base/src/test/java/mozilla/components/support/base/facts/processor/LogFactProcessorTest.kt
Labels: 🕵️‍♀️ needs review

#1775 Issue #95: Introduce new component for reading and accessing the public suffix list.
  .buildconfig.yml
  README.md
  components/lib/publicsuffixlist/README.md
  components/lib/publicsuffixlist/build.gradle
  components/lib/publicsuffixlist/proguard-rules.pro
  components/lib/publicsuffixlist/src/main/AndroidManifest.xml
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
  components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixList.kt
  components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixListData.kt
  components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixListLoader.kt
  components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/ext/ByteArray.kt
  components/lib/publicsuffixlist/src/test/java/mozilla/components/lib/publicsuffixlist/PublicSuffixListTest.kt
Labels: 🕵️‍♀️ needs review

#1782 Closes #1399: Add action button to Custom Tabs
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
Labels: 🕵️‍♀️ needs review

#1796 Closes #1784: Fix incomplete kdoc on PublicSuffixList class.
  components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixList.kt
Labels: 🕵️‍♀️ needs review

#1792 Closes #1776: Add gradle task for updating public suffix list.
  .gitattributes
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/plugins/PublicSuffixListPlugin.kt
  components/lib/publicsuffixlist/build.gradle
Labels: 🕵️‍♀️ needs review

#1805 Closes #1789: Introduce pull request template. [ci skip]
  .github/pull_request_template.md
Labels: 🕵️‍♀️ needs review

#1804 Issue #1783: Update kdoc in "facts" package (support-base).
  components/support/base/src/main/java/mozilla/components/support/base/facts/Action.kt
  components/support/base/src/main/java/mozilla/components/support/base/facts/FactProcessor.kt
Labels: 🕵️‍♀️ needs review

#1803 Closes #1790: Add public suffix list update to changelog. [ci skip]
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1809 Closes #1777: ByteArray.binarySearch: Compare unsigned bytes..
  components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/ext/ByteArray.kt
  components/lib/publicsuffixlist/src/test/java/mozilla/components/lib/publicsuffixlist/PublicSuffixListTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1807 Issue #1779: SearchSuggestionProvider: Add option to show one item per search suggestion.
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/SuggestionViewHolder.kt
  components/browser/awesomebar/src/main/res/layout/mozac_browser_awesomebar_item_generic.xml
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1817 Closes #1816: Disable not implemented js prompts in SystemEngine.
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1834 Issue #1813: AwesomeBarFeature: Allow defining custom start/stop hooks.
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/AwesomeBarFeatureTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1838 Issue #1835: Allow SessionUseCases and SearchUseCases to be used without selected session.
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProviderTest.kt
  components/feature/search/build.gradle
  components/feature/search/src/main/java/mozilla/components/feature/search/SearchUseCases.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/SearchUseCasesTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#1863 Closes #448 R-B:Not allowing text behind the security icon be selectable
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  docs/changelog.md
Labels: 🛬 needs landing

#1888 Closes #1887: Addressing some nits from the find in page feature component that were pending in #1858.
  .buildconfig.yml
  components/feature/findinpage/README.md
  components/feature/findinpage/src/main/java/mozilla/components/feature/findinpage/FindInPageFeature.kt
  components/feature/findinpage/src/main/java/mozilla/components/feature/findinpage/FindInPageView.kt
  components/feature/findinpage/src/test/java/FindInPageFeatureTest.kt
  components/feature/findinpage/src/test/java/FindInPageViewTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#1906 [glean] Add whiteboard tag to Glean bugzilla link [ci skip]
  components/service/glean/README.md
Labels: <glean>

#1896 AutoSave: Save state after removing all sessions.
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/AutoSave.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/storage/SessionStorageTest.kt
Labels: 🕵️‍♀️ needs review
