Repository mozilla-mobile/android-components, pull requests merged in 2019-11, with the labels that each got.

#4919 Closes #3486 - Implement Web Share API
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/ShareData.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/share/ShareDelegate.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/share/DefaultShareDelegateTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt
  docs/changelog.md
Labels: ✏️ needs changes

#4684 Closes #4679 - lower download notification importance for Android O+
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt
  docs/changelog.md
Labels: 🛬 needs landing

#4961 Docs update (20191105-121227) [ci skip]
  docs/api/alltypes/index.md
  docs/api/index.md
  docs/api/mozilla.components.browser.engine.gecko.prompt/-g-e-c-k-o_-p-r-o-m-p-t_-s-h-a-r-e_-r-e-s-u-l-t.md
  docs/api/mozilla.components.browser.engine.gecko.prompt/index.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine/index.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine/register-web-notification-delegate.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine/register-web-push-delegate.md
  docs/api/mozilla.components.concept.engine.prompt/-prompt-request/-dismissible/index.md
  docs/api/mozilla.components.concept.engine.prompt/-prompt-request/-dismissible/on-dismiss.md
  docs/api/mozilla.components.concept.engine.prompt/-prompt-request/-share/-init-.md
  docs/api/mozilla.components.concept.engine.prompt/-prompt-request/-share/data.md
  docs/api/mozilla.components.concept.engine.prompt/-prompt-request/-share/index.md
  docs/api/mozilla.components.concept.engine.prompt/-prompt-request/-share/on-dismiss.md
  docs/api/mozilla.components.concept.engine.prompt/-prompt-request/-share/on-failure.md
  docs/api/mozilla.components.concept.engine.prompt/-prompt-request/-share/on-success.md
  docs/api/mozilla.components.concept.engine.prompt/-prompt-request/index.md
  docs/api/mozilla.components.concept.engine.prompt/-share-data/-init-.md
  docs/api/mozilla.components.concept.engine.prompt/-share-data/index.md
  docs/api/mozilla.components.concept.engine.prompt/-share-data/text.md
  docs/api/mozilla.components.concept.engine.prompt/-share-data/title.md
  docs/api/mozilla.components.concept.engine.prompt/-share-data/url.md
  docs/api/mozilla.components.concept.engine.prompt/index.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-delegate/index.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-delegate/on-get-subscription.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-delegate/on-subscribe.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-delegate/on-unsubscribe.md
  docs/api/mozilla.components.feature.downloads/-simple-download-dialog-fragment/-k-e-y_-d-o-w-n-l-o-a-d_-t-e-x-t.md
  docs/api/mozilla.components.feature.downloads/-simple-download-dialog-fragment/-k-e-y_-t-h-e-m-e_-i-d.md
  docs/api/mozilla.components.feature.downloads/-simple-download-dialog-fragment/-k-e-y_-t-i-t-l-e_-t-e-x-t.md
  docs/api/mozilla.components.feature.downloads/-simple-download-dialog-fragment/new-instance.md
  docs/api/mozilla.components.feature.prompts.share/-default-share-delegate/-init-.md
  docs/api/mozilla.components.feature.prompts.share/-default-share-delegate/index.md
  docs/api/mozilla.components.feature.prompts.share/-default-share-delegate/show-share-sheet.md
  docs/api/mozilla.components.feature.prompts.share/-share-delegate/index.md
  docs/api/mozilla.components.feature.prompts.share/-share-delegate/show-share-sheet.md
  docs/api/mozilla.components.feature.prompts.share/index.md
  docs/api/mozilla.components.feature.prompts/-prompt-feature/-init-.md
  docs/api/mozilla.components.feature.prompts/-prompt-feature/index.md
  docs/api/mozilla.components.feature.prompts/-prompt-feature/on-activity-result.md
  docs/api/mozilla.components.feature.prompts/-prompt-feature/on-cancel.md
  docs/api/mozilla.components.feature.prompts/-prompt-feature/on-clear.md
  docs/api/mozilla.components.feature.prompts/-prompt-feature/on-confirm.md
  docs/api/mozilla.components.feature.prompts/-prompt-feature/on-need-to-request-permissions.md
  docs/api/mozilla.components.feature.prompts/-prompt-feature/on-permissions-result.md
  docs/api/mozilla.components.feature.prompts/-prompt-feature/start.md
  docs/api/mozilla.components.feature.prompts/-prompt-feature/stop.md
  docs/api/mozilla.components.support.ktx.android.content/app-name.md
  docs/api/mozilla.components.support.ktx.android.content/app-version-name.md
  docs/api/mozilla.components.support.ktx.android.content/get-color-from-attr.md
  docs/api/mozilla.components.support.ktx.android.content/has-camera.md
  docs/api/mozilla.components.support.ktx.android.content/is-main-process.md
  docs/api/mozilla.components.support.ktx.android.content/is-o-s-on-low-memory.md
  docs/api/mozilla.components.support.ktx.android.content/is-permission-granted.md
  docs/api/mozilla.components.support.ktx.android.content/is-screen-reader-enabled.md
  docs/api/mozilla.components.support.ktx.android.content/run-only-in-main-process.md
  docs/api/mozilla.components.support.ktx.android.content/share.md
  docs/api/package-list
Labels: 🛬 needs landing

#4968 Closes #4803: TrackingProtectionIconView: Assign individual drawables instead of using state list drawable.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconView.kt
  components/browser/toolbar/src/main/res/drawable/mozac_tracking_protection_state_list.xml
  components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml
  components/browser/toolbar/src/main/res/values/attrs_browser_toolbar.xml
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
Labels: 🕵️‍♀️ needs review

#4962 GeckoView update (nightly) (20191105-141113)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#4996 GeckoView update (beta) (20191107-141548)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#4995 Docs update (20191107-122543) [ci skip]
  docs/api/alltypes/index.md
  docs/api/mozilla.components.browser.session/-session/-observer/index.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/-init-.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/fallback-url.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/has-external-app.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/has-fallback.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/index.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/info.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/is-fallback.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/is-installable.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/is-redirect.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/web-url.md
  docs/api/mozilla.components.feature.app.links/-app-links-feature/-init-.md
  docs/api/mozilla.components.feature.app.links/-app-links-feature/index.md
  docs/api/mozilla.components.feature.app.links/-app-links-feature/start.md
  docs/api/mozilla.components.feature.app.links/-app-links-feature/stop.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/-open-app-link-redirect/index.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/-open-app-link-redirect/invoke.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/app-link-redirect.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/intercepted-app-link-redirect.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/open-app-link.md
  docs/api/mozilla.components.feature.pwa.feature/-manifest-update-feature/-init-.md
  docs/api/mozilla.components.feature.pwa.feature/-manifest-update-feature/index.md
  docs/api/mozilla.components.feature.pwa.feature/-manifest-update-feature/on-web-app-manifest-changed.md
  docs/api/mozilla.components.feature.pwa.feature/-manifest-update-feature/start.md
  docs/api/mozilla.components.feature.pwa.feature/-manifest-update-feature/stop.md
  docs/api/mozilla.components.feature.pwa.feature/index.md
  docs/api/mozilla.components.feature.pwa/-manifest-storage/-init-.md
  docs/api/mozilla.components.feature.pwa/-manifest-storage/index.md
  docs/api/mozilla.components.feature.pwa/-manifest-storage/load-manifest.md
  docs/api/mozilla.components.feature.pwa/-manifest-storage/remove-manifests.md
  docs/api/mozilla.components.feature.pwa/-manifest-storage/save-manifest.md
  docs/api/mozilla.components.feature.pwa/-manifest-storage/update-manifest.md
  docs/api/mozilla.components.feature.pwa/-s-h-o-r-t-c-u-t_-c-a-t-e-g-o-r-y.md
  docs/api/mozilla.components.feature.pwa/-web-app-shortcut-manager/-init-.md
  docs/api/mozilla.components.feature.pwa/-web-app-shortcut-manager/build-basic-shortcut.md
  docs/api/mozilla.components.feature.pwa/-web-app-shortcut-manager/build-web-app-shortcut.md
  docs/api/mozilla.components.feature.pwa/-web-app-shortcut-manager/find-shortcut.md
  docs/api/mozilla.components.feature.pwa/-web-app-shortcut-manager/index.md
  docs/api/mozilla.components.feature.pwa/-web-app-shortcut-manager/request-pin-shortcut.md
  docs/api/mozilla.components.feature.pwa/-web-app-shortcut-manager/uninstall-shortcuts.md
  docs/api/mozilla.components.feature.pwa/-web-app-shortcut-manager/update-shortcuts.md
  docs/api/mozilla.components.feature.pwa/-web-app-use-cases/-add-to-homescreen-use-case/index.md
  docs/api/mozilla.components.feature.pwa/-web-app-use-cases/-add-to-homescreen-use-case/invoke.md
  docs/api/mozilla.components.feature.pwa/-web-app-use-cases/-init-.md
  docs/api/mozilla.components.feature.pwa/-web-app-use-cases/add-to-homescreen.md
  docs/api/mozilla.components.feature.pwa/-web-app-use-cases/index.md
  docs/api/mozilla.components.feature.pwa/-web-app-use-cases/is-installable.md
  docs/api/mozilla.components.feature.pwa/-web-app-use-cases/is-pinning-supported.md
  docs/api/mozilla.components.feature.pwa/index.md
  docs/api/mozilla.components.lib.dataprotect/generate-encryption-key.md
  docs/api/mozilla.components.lib.dataprotect/index.md
  docs/api/mozilla.components.support.base.feature/-lifecycle-aware-feature/index.md
Labels: 🛬 needs landing

#4990 Closes issue #4871: Provide a mapping for translations of permissions from AMO API.
  components/feature/addons/src/main/java/mozilla/components/feature/addons/AddOn.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/AddOnTest.kt
Labels: 🕵️‍♀️ needs review

#5002 Closes #4792: Add UI for add-on permissions.
  components/ui/icons/src/main/res/drawable/mozac_ic_information.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_preferences.xml
  samples/browser/src/main/AndroidManifest.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddOnsFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/InstalledAddOnDetailsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/PermissionsDetailsActivity.kt
  samples/browser/src/main/res/drawable/mozac_ic_permissions.xml
  samples/browser/src/main/res/layout/activity_add_on_permissions.xml
  samples/browser/src/main/res/layout/activity_installed_add_on_details.xml
  samples/browser/src/main/res/layout/add_ons_permission_item.xml
  samples/browser/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#4742 Closes #4151: Add enum for SitePermissions types
  components/feature/sitepermissions/build.gradle
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissions.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#5010 Closes #4987: feature-downloads: Emit facts.
  components/feature/downloads/README.md
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/facts/DownloadsFacts.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/support/base/src/main/java/mozilla/components/support/base/facts/Action.kt
Labels: 🕵️‍♀️ needs review

#5031 For #5021: Adds failure case for openFile
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#4997 Issue #4983: Add code for migrating Gecko related files.
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/GeckoMigration.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/MigrationResultsStore.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/GeckoMigrationTest.kt
  components/support/migration/src/test/resources/combined/basic/prefs.js
  components/support/migration/src/test/resources/empty/empty.txt
Labels: 🕵️‍♀️ needs review

#4974 Add library for P2P communication and sample app
  .buildconfig.yml
  README.md
  buildSrc/src/main/java/Dependencies.kt
  components/lib/nearby/README.md
  components/lib/nearby/build.gradle
  components/lib/nearby/proguard-rules.pro
  components/lib/nearby/src/main/AndroidManifest.xml
  components/lib/nearby/src/main/java/mozilla/components/lib/nearby/NearbyConnection.kt
  components/lib/nearby/src/test/java/mozilla/components/lib/nearby/NearbyConnectionTest.kt
  components/lib/nearby/src/test/java/mozilla/components/lib/nearby/VoidTask.kt
  components/lib/nearby/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  docs/changelog.md
  samples/nearby-chat/README.md
  samples/nearby-chat/build.gradle
  samples/nearby-chat/lint.xml
  samples/nearby-chat/proguard-rules.pro
  samples/nearby-chat/src/main/AndroidManifest.xml
  samples/nearby-chat/src/main/java/org/mozilla/samples/nearby/chat/MainActivity.kt
  samples/nearby-chat/src/main/res/drawable-v24/ic_launcher_foreground.xml
  samples/nearby-chat/src/main/res/drawable/ic_launcher_background.xml
  samples/nearby-chat/src/main/res/layout/activity_main.xml
  samples/nearby-chat/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  samples/nearby-chat/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  samples/nearby-chat/src/main/res/mipmap-hdpi/ic_launcher.png
  samples/nearby-chat/src/main/res/mipmap-hdpi/ic_launcher_round.png
  samples/nearby-chat/src/main/res/mipmap-mdpi/ic_launcher.png
  samples/nearby-chat/src/main/res/mipmap-mdpi/ic_launcher_round.png
  samples/nearby-chat/src/main/res/mipmap-xhdpi/ic_launcher.png
  samples/nearby-chat/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  samples/nearby-chat/src/main/res/mipmap-xxhdpi/ic_launcher.png
  samples/nearby-chat/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  samples/nearby-chat/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  samples/nearby-chat/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  samples/nearby-chat/src/main/res/values/colors.xml
  samples/nearby-chat/src/main/res/values/strings.xml
  samples/nearby-chat/src/main/res/values/styles.xml
Labels: ✏️ needs changes

#5055 Update GeckoView Nightly to 72.0.20191113095525.
  buildSrc/src/main/java/Gecko.kt
Labels: 🕵️‍♀️ needs review

#5065 Closes #4935: Tracking protection state not updated on browser session
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenterTest.kt
  components/support/base/src/main/java/mozilla/components/support/base/observer/Observable.kt
  components/support/base/src/main/java/mozilla/components/support/base/observer/ObserverRegistry.kt
  components/support/base/src/test/java/mozilla/components/support/base/observer/ObserverRegistryTest.kt
Labels: 🕵️‍♀️ needs review

#4991 Closes #4950: Enable Launching URL in Third Party Application
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/request/LoadRequestMetadata.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  config/detekt-baseline.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#5085 Public Suffix List update (20191117-140615)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#5086 GeckoView update (nightly) (20191117-140637)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5089 GeckoView update (nightly) (20191118-140600)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5088 GeckoView update (beta) (20191118-140410)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5082 Closes #4993: Add tag to notifications for WebNotification
  components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/WebNotificationFeature.kt
Labels: 🛬 needs landing

#5098 Closes #5034: Add release 18.0.1 to changelog.
  docs/changelog.md
Labels: 🛬 needs landing

#5092 Closes #5091: Fix clashing file providers in feature-prompts and feature-downloads.
  components/browser/state/src/main/java/mozilla/components/browser/state/state/content/DownloadState.kt
  components/feature/downloads/src/main/AndroidManifest.xml
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/provider/FileProvider.kt
  components/feature/downloads/src/main/res/xml/feature_downloads_file_paths.xml
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/feature/prompts/src/main/AndroidManifest.xml
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/MimeType.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/provider/FileProvider.kt
  components/feature/prompts/src/main/res/xml/feature_prompts_file_paths.xml
  components/feature/prompts/src/main/res/xml/file_paths.xml
  docs/changelog.md
  samples/browser/src/main/AndroidManifest.xml
  samples/browser/src/main/res/xml/file_paths.xml
Labels: 🕵️‍♀️ needs review

#5064 Closes #5041: Fix migration post-processing to understand FxA migrations
  components/support/migration/src/main/java/mozilla/components/support/migration/MigrationResultsStore.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecMigratorTest.kt
Labels: 🕵️‍♀️ needs review

#5110 Closes #5036: Add dialog for accepting addon permissions
  components/feature/addons/build.gradle
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddOnsFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/PermissionsDialogFragment.kt
  samples/browser/src/main/res/layout/fragment_dialog_addon_permissions.xml
  samples/browser/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#5121 Closes #5090: Wire up GeckoView action delegate for BrowserActions
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Engine.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/BrowserAction.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/accounts/src/test/java/mozilla/components/feature/accounts/FxaWebChannelFeatureTest.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/WebExtensionToolbarAction.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/WebExtensionToolbarFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/WebExtensionToolbarTest.kt
  components/support/webextensions/build.gradle
  components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionControllerTest.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
Labels: 🕵️‍♀️ needs review

#5140 GeckoView update (beta) (20191125-140548)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5125 Closes #4398: Add reader state to browser-state
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/SessionExtensions.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/ext/SessionExtensionsTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ReaderStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ReaderState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/ReaderActionTest.kt
Labels: 🛬 needs landing

#5158 Bug 1587765 - Support UTF-8 characters in commit messages
  .taskcluster.yml
Labels: 🛬 needs landing, 🤖 automation

#5159 AbstractFetchDownloadService: Remove notifications when task gets removed.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
Labels: 🛬 needs landing

#5151 Fixes #5150: Passes most recent download state to notification
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing

#5163 Closes #5145: Remove INFO Tag from Socorro Java Stack Trace
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/CrashReporterService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
Labels: 🛬 needs landing

#5157 For mozilla-mobile/fenix#5540: add 'no internet' error
  components/browser/errorpages/src/main/java/mozilla/components/browser/errorpages/ErrorPages.kt
  components/browser/errorpages/src/main/res/values/strings.xml
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#5169 For #5168: fix autocomplete on text block deletion
  components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
  components/ui/autocomplete/src/test/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditTextTest.kt
Labels: 🛬 needs landing

#5156 Closes #5155: Don't drop 'failure' details for FxaMigrationException
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecFxaMigration.kt
Labels: 🛬 needs landing

#5173 Update to Kotlin 1.3.61.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#5172 Closes #5166: SessionStorageTest: Keep reference to lifecycle owner during test run.
  components/browser/session/src/test/java/mozilla/components/browser/session/storage/SessionStorageTest.kt
Labels: 🕵️‍♀️ needs review

#5185 Docs update (20191128-120543) [ci skip]
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/-init-.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/app-intent.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/fallback-url.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/has-external-app.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/has-fallback.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/has-marketplace-intent.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/index.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/info.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/is-installable.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/is-redirect.md
  docs/api/mozilla.components.feature.app.links/-app-link-redirect/marketplace-intent.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/-open-app-link-redirect/index.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/-open-app-link-redirect/invoke.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/-open-marketplace-intent/index.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/-open-marketplace-intent/invoke.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/app-link-redirect.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/index.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/intercepted-app-link-redirect.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/open-app-link.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/open-marketplace-intent.md
  docs/api/mozilla.components.support.migration/-fxa-migration-result/-failure/-failed-to-sign-into-authenticated-account/index.md
  docs/api/mozilla.components.support.migration/-fxa-migration-result/-failure/-failed-to-sign-into-authenticated-account/to-string.md
Labels: 🛬 needs landing

#5180 For issue #4546 Add installed and recommended sections to the addon manager page.
  components/feature/addons/src/main/java/mozilla/components/feature/addons/AddOn.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddOnsFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/InstalledAddOnDetailsActivity.kt
  samples/browser/src/main/res/layout/activity_installed_add_on_details.xml
  samples/browser/src/main/res/layout/add_ons_item.xml
  samples/browser/src/main/res/layout/addons_section_item.xml
  samples/browser/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#5142 Issue #4879: Add service for running migration in background.
  components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
Labels: 🕵️‍♀️ needs review

#5165 For #5127: Add Debugging Code to Help Determine Crash Cause.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
Labels: 🕵️‍♀️ needs review
