Repository mozilla-mobile/android-components, pull requests merged in 2019-09, with the labels that each got.

#4267 Use UUID for custom tab config ID in PWA
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabConfigHelper.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/WebAppManifest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/WebAppManifestKtTest.kt
Labels: 🛬 needs landing

#4276 Add blog posting explaining browser-state plans. [ci skip]
  docs/_posts/2019-09-02-browser-state.md
Labels: 🕵️‍♀️ needs review

#4294 Issue #4284: Add DownloadState to browser-state.
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/content/DownloadState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
Labels: 🕵️‍♀️ needs review

#4249 Closes #4213: Use the social strict tracking protection list when the TrackingProtectionPolicy.strict() is set
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  docs/changelog.md
Labels: 🌟 feature, 🕵️‍♀️ needs review

#4304 Import strings from android-l10n
  components/browser/errorpages/src/main/res/values-tr/strings.xml
  components/browser/toolbar/src/main/res/values-es-rAR/strings.xml
  components/browser/toolbar/src/main/res/values-sk/strings.xml
  components/feature/downloads/src/main/res/values-sk/strings.xml
  components/feature/findinpage/src/main/res/values-tr/strings.xml
  components/feature/media/src/main/res/values-sk/strings.xml
  components/feature/prompts/src/main/res/values-sk/strings.xml
  components/feature/prompts/src/main/res/values-tr/strings.xml
  components/lib/crash/src/main/res/values-sk/strings.xml
Labels: import-l10n

#4263 Closes #4311: Remove Top and Bottom Padding Causing Issues with Text Alignment and Clipping
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/browser/toolbar/src/main/res/values/dimens.xml
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/edit/EditToolbarTest.kt
Labels: 🕵️‍♀️ needs review

#4316 Closes #4165: Add more logging for push
  components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4327 Flow.ifChanged(): Added variant that takes a mapping function.
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlinx/coroutines/flow/Flow.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlinx/coroutines/flow/FlowKtTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4333 Issue #4244: Add id of tab to intent launched from media notification.
  components/feature/media/src/main/java/mozilla/components/feature/media/MediaFeature.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/notification/MediaNotificationTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#4351 Closes #4161: Make MediaState extension methods visible for consuming apps.
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/MediaState.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/ext/MediaStateKtTest.kt
Labels: 🕵️‍♀️ needs review

#4363 Closes #4349: Align default tracking protection policies with Firefox Desktop policies.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4366 Issue #4353: MediaStateMachine: Lower state update delay to 100ms.
  components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt
Labels: 🕵️‍♀️ needs review

#3949 Issue #2295 - Convert WebNotification to Notification
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webnotifications/WebNotification.kt
  components/feature/webnotifications/build.gradle
  components/feature/webnotifications/src/main/java/mozilla/components/feature/notifications/Placeholder.kt
  components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/NativeNotificationBridge.kt
  components/feature/webnotifications/src/test/java/mozilla/components/feature/notifications/PlaceholderTest.kt
  components/feature/webnotifications/src/test/java/mozilla/components/feature/webnotifications/NativeNotificationBridgeTest.kt
Labels: ✏️ needs changes

#4375 Proper 'matches' permission for webchannel extension manifest
  components/feature/accounts/src/main/assets/extensions/fxawebchannel/manifest.json
Labels: 🕵️‍♀️ needs review

#4380 Update AndroidX dependencies.
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  components/feature/downloads/build.gradle
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaService.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/AlertDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/AuthenticationDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/ColorPickerDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/MultiButtonDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/TextPromptDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/TimePickerDialogFragment.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/AlertDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/AuthenticationDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/ColorPickerDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/MultiButtonDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/TextPromptDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/TimePickerDialogFragmentTest.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/FragmentKtTest.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/StoreExtensionsKtTest.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/ViewKtTest.kt
  components/support/base/src/test/java/mozilla/components/support/base/observer/ObserverRegistryTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
  samples/firefox-accounts/src/main/java/org/mozilla/samples/fxa/MainActivity.kt
  samples/sync-logins/src/main/java/org/mozilla/samples/sync/logins/MainActivity.kt
  samples/sync/src/main/java/org/mozilla/samples/sync/MainActivity.kt
Labels: 🕵️‍♀️ needs review

#4390 Closes #4282: Migrate feature-downloads to use browser-state.
  components/feature/downloads/build.gradle
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadDialogFragment.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsUseCases.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragment.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ext/DownloadState.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ext/Intent.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/AndroidDownloadManager.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/DownloadManager.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadDialogFragmentTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/AndroidDownloadManagerTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/FetchDownloadManagerTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#4326 Closes #3213: Add Extension Function for Toolbar TextViews to Adjust …
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/widget/TextView.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/widget/TextViewTest.kt
Labels: 🛬 needs landing

#4408 Update detekt to version 1.0.1.
  build.gradle
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/FilePicker.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/TimePickerDialogFragment.kt
Labels: 🛬 needs landing

#4407 Migrate feature-contextmenu to use browser-state.
  components/browser/awesomebar/build.gradle
  components/browser/state/src/main/java/mozilla/components/browser/state/selector/Selectors.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/selector/SelectorsKtTest.kt
  components/feature/contextmenu/build.gradle
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFeature.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFragment.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuUseCases.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuFeatureTest.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuFragmentTest.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuObserverTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#4430 Closes #4428: Remove fingerprint from the tracking protection recommended policy.
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
Labels: 🕵️‍♀️ needs review

#4436 Closes #4335: Stop playback and remove media notification if app task gets removed.
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/MediaState.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaService.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/ext/MediaStateKtTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaServiceTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/state/MediaStateMachineTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4400 Preserve parent id during convert from tab session to state
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/SessionExtensions.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/ext/SessionExtensionsTest.kt
Labels: 🕵️‍♀️ needs review

#4434 Closes #4425 Remove Padding When Both URL and Title is Visible In Bro…
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/widget/TextView.kt
Labels: 🕵️‍♀️ needs review

#4456 Closes #4391: Adapt the color of the tracking protection icon on custom tabs.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
  docs/changelog.md
Labels: <customtabs>, 🌟 feature, 🕵️‍♀️ needs review

#4461 Closes #846. Add detekt rule to check license header in kotlin files.
  .buildconfig.yml
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  components/tooling/detekt/README.md
  components/tooling/detekt/build.gradle
  components/tooling/detekt/src/main/kotlin/mozilla/components/tooling/detekt/MozillaRuleSetProvider.kt
  components/tooling/detekt/src/main/kotlin/mozilla/components/tooling/detekt/ProjectLicenseRule.kt
  components/tooling/detekt/src/main/resources/META-INF/services/io.gitlab.arturbosch.detekt.api.RuleSetProvider
  components/tooling/detekt/src/test/kotlin/ProjectLicenseRuleTest.kt
  config/detekt-baseline.xml
  config/detekt.yml
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4494 Closes #4396: feature-media: Emit facts.
  components/feature/media/README.md
  components/feature/media/src/main/java/mozilla/components/feature/media/MediaFeature.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/facts/MediaFacts.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaService.kt
  components/support/base/src/main/java/mozilla/components/support/base/facts/Action.kt
Labels: 🕵️‍♀️ needs review

#4482 Issue #4241: FennecSessionMigration: First iteration of code to import "open tabs" from Fennec into an AC-based app.
  components/support/migration/build.gradle
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecProfile.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecSessionMigration.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/MigrationResult.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecSessionMigrationTest.kt
  components/support/migration/src/test/resources/sessions/broken-json/sessionstore.bak
  components/support/migration/src/test/resources/sessions/broken-json/sessionstore.js
  components/support/migration/src/test/resources/sessions/no-windows/sessionstore.js
  components/support/migration/src/test/resources/sessions/test-case1/sessionstore.js
  components/support/migration/src/test/resources/sessions/test-case2/sessionstore.bak
  components/support/migration/src/test/resources/sessions/test-case2/sessionstore.js
Labels: 🕵️‍♀️ needs review

#4501 Closes #4406: Add TrackingProtectionUseCases
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Engine.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/content/blocking/TrackerLog.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/TrackingProtectionUseCasesTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4509 For #76, #77. Enable `UndocumentedPublic*` detekt rules.
  config/detekt-baseline.xml
  config/detekt.yml
Labels: ✏️ needs changes

#4521 Closes #4483: Move "ignore media with short duration" inside MediaStateMachine.
  components/feature/media/src/main/java/mozilla/components/feature/media/MediaFeature.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/Media.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/MediaState.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/MockMedia.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/state/MediaStateMachineTest.kt
Labels: 🕵️‍♀️ needs review

#4506 Issue #4421: Remove download property from Session.
  components/browser/session/src/main/java/mozilla/components/browser/session/Download.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SelectionAwareSessionObserverTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuUseCases.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuFeatureTest.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsUseCases.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragmentTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#4496 Import strings from android-l10n.
  components/browser/engine-system/src/main/res/values-da/strings.xml
  components/browser/errorpages/src/main/res/values-da/strings.xml
  components/browser/errorpages/src/main/res/values-in/strings.xml
  components/browser/errorpages/src/main/res/values-ta/strings.xml
  components/browser/toolbar/src/main/res/values-da/strings.xml
  components/browser/toolbar/src/main/res/values-es-rES/strings.xml
  components/browser/toolbar/src/main/res/values-es/strings.xml
  components/browser/toolbar/src/main/res/values-pa-rIN/strings.xml
  components/browser/toolbar/src/main/res/values-sk/strings.xml
  components/browser/toolbar/src/main/res/values-vi/strings.xml
  components/feature/app-links/src/main/res/values-da/strings.xml
  components/feature/contextmenu/src/main/res/values-cs/strings.xml
  components/feature/contextmenu/src/main/res/values-da/strings.xml
  components/feature/contextmenu/src/main/res/values-de/strings.xml
  components/feature/contextmenu/src/main/res/values-es-rAR/strings.xml
  components/feature/contextmenu/src/main/res/values-es-rES/strings.xml
  components/feature/contextmenu/src/main/res/values-es/strings.xml
  components/feature/contextmenu/src/main/res/values-eu/strings.xml
  components/feature/contextmenu/src/main/res/values-fi/strings.xml
  components/feature/contextmenu/src/main/res/values-fr/strings.xml
  components/feature/contextmenu/src/main/res/values-hu/strings.xml
  components/feature/contextmenu/src/main/res/values-in/strings.xml
  components/feature/contextmenu/src/main/res/values-it/strings.xml
  components/feature/contextmenu/src/main/res/values-ja/strings.xml
  components/feature/contextmenu/src/main/res/values-ko/strings.xml
  components/feature/contextmenu/src/main/res/values-nb-rNO/strings.xml
  components/feature/contextmenu/src/main/res/values-nl/strings.xml
  components/feature/contextmenu/src/main/res/values-nn-rNO/strings.xml
  components/feature/contextmenu/src/main/res/values-pa-rIN/strings.xml
  components/feature/contextmenu/src/main/res/values-pl/strings.xml
  components/feature/contextmenu/src/main/res/values-ru/strings.xml
  components/feature/contextmenu/src/main/res/values-sk/strings.xml
  components/feature/contextmenu/src/main/res/values-sv-rSE/strings.xml
  components/feature/contextmenu/src/main/res/values-tr/strings.xml
  components/feature/contextmenu/src/main/res/values-vi/strings.xml
  components/feature/contextmenu/src/main/res/values-zh-rCN/strings.xml
  components/feature/contextmenu/src/main/res/values-zh-rTW/strings.xml
  components/feature/customtabs/src/main/res/values-da/strings.xml
  components/feature/downloads/src/main/res/values-da/strings.xml
  components/feature/downloads/src/main/res/values-es-rES/strings.xml
  components/feature/downloads/src/main/res/values-es/strings.xml
  components/feature/findinpage/src/main/res/values-da/strings.xml
  components/feature/findinpage/src/main/res/values-ta/strings.xml
  components/feature/media/src/main/res/values-da/strings.xml
  components/feature/media/src/main/res/values-es-rES/strings.xml
  components/feature/media/src/main/res/values-es/strings.xml
  components/feature/prompts/src/main/res/values-da/strings.xml
  components/feature/prompts/src/main/res/values-es-rES/strings.xml
  components/feature/prompts/src/main/res/values-es/strings.xml
  components/feature/prompts/src/main/res/values-ta/strings.xml
  components/feature/readerview/src/main/res/values-da/strings.xml
  components/feature/sitepermissions/src/main/res/values-da/strings.xml
  components/feature/tabs/src/main/res/values-da/strings.xml
  components/lib/crash/src/main/res/values-da/strings.xml
  components/lib/crash/src/main/res/values-es/strings.xml
  components/lib/crash/src/main/res/values-zh-rCN/strings.xml
  components/support/ktx/src/main/res/values-da/strings.xml
Labels: import-l10n

#4395 Uplift Theme.resolveAttribute from Fenix
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuHighlightableItem.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuItemToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/MenuButton.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/toolbar/TabCounterToolbarButton.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/res/Theme.kt
  components/support/ktx/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  docs/changelog.md
Labels: ✏️ needs changes

#4561 Import strings from android-l10n
  components/feature/contextmenu/src/main/res/values-cs/strings.xml
  components/feature/contextmenu/src/main/res/values-it/strings.xml
  components/feature/findinpage/src/main/res/values-vi/strings.xml
Labels: import-l10n

#4554 For issue #3264 Add api for interacting with the tracking protection exceptions
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/AtomicFile.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Engine.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/content/blocking/TrackingProtectionExceptionStorage.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/TrackingProtectionUseCasesTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/util/AtomicFile.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/util/AtomicFileTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4569 Add tests to feature-customtabs
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/AbstractCustomTabsService.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/feature/OriginVerifierFeature.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/AbstractCustomTabsServiceTest.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabWindowFeatureTest.kt
Labels: 🕵️‍♀️ needs review

#4581 Import strings from android-l10n
  components/browser/errorpages/src/main/res/values-fi/strings.xml
  components/browser/toolbar/src/main/res/values-fi/strings.xml
  components/feature/contextmenu/src/main/res/values-fi/strings.xml
  components/feature/contextmenu/src/main/res/values-fr/strings.xml
  components/feature/contextmenu/src/main/res/values-pl/strings.xml
  components/feature/prompts/src/main/res/values-fi/strings.xml
Labels: import-l10n
