Repository mozilla-mobile/android-components, pull requests merged in 2019-10, with the labels that each got.

#4609 Fix find in page not working with fresh install
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
Labels: 🕵️‍♀️ needs review

#4643 Import strings from android-l10n
  components/browser/errorpages/src/main/res/values-tr/strings.xml
  components/browser/errorpages/src/main/res/values-vi/strings.xml
  components/browser/toolbar/src/main/res/values-in/strings.xml
  components/feature/contextmenu/src/main/res/values-in/strings.xml
Labels: import-l10n

#4577 For issue #3264 Display the OFF_FOR_A_SITE tracking protection state.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TrackingProtectionStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TrackingProtectionState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TrackingProtectionActionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarPresenter.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarPresenterTest.kt
Labels: 🕵️‍♀️ needs review

#4658 Auto-publication workflow support
  publish.gradle
  substitute-local-ac.gradle
Labels: 🕵️‍♀️ needs review

#4688 Set version to 17.0.0.
  .buildconfig.yml
Labels: 🛬 needs landing

#4598 For issue #4369 Use MATCH_ALL flag when resolving browsers
  components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt
Labels: 🛬 needs landing

#4694 Docs update (20191009-121304) [ci skip]
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-a-d-b-l-o-c-k_-b-r-o-w-s-e-r.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-a-n-d-r-o-i-d_-s-t-o-c-k_-b-r-o-w-s-e-r.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-b-r-a-v-e_-b-r-o-w-s-e-r.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-c-h-r-o-m-e-r.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-c-h-r-o-m-e.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-c-h-r-o-m-e_-b-e-t-a.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-c-h-r-o-m-e_-c-a-n-a-r-y.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-c-h-r-o-m-e_-d-e-v.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-c-h-r-o-m-e_-l-o-c-a-l_-b-u-i-l-d.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-c-h-r-o-m-i-u-m_-l-o-c-a-l_-b-u-i-l-d.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-c-l-i-q-z.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-d-o-l-p-h-i-n_-b-r-o-w-s-e-r.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-d-u-c-k-d-u-c-k-g-o.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-f-e-n-i-x_-d-e-b-u-g.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-f-e-n-i-x_-p-r-e-v-i-e-w.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-f-i-r-e-f-o-x.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-f-i-r-e-f-o-x_-a-u-r-o-r-a.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-f-i-r-e-f-o-x_-b-e-t-a.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-f-i-r-e-f-o-x_-f-d-r-o-i-d.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-f-i-r-e-f-o-x_-l-i-t-e.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-f-i-r-e-f-o-x_-n-i-g-h-t-l-y.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-f-l-y-n-x.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-g-h-o-s-t-e-r-y_-b-r-o-w-s-e-r.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-l-i-n-k_-b-u-b-b-l-e.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-m-i-c-r-o-s-o-f-t_-e-d-g-e.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-o-p-e-r-a.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-o-p-e-r-a_-b-e-t-a.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-o-p-e-r-a_-m-i-n-i.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-o-p-e-r-a_-m-i-n-i_-b-e-t-a.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-o-r-f-o-x.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-r-e-f-e-r-e-n-c-e_-b-r-o-w-s-e-r.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-r-e-f-e-r-e-n-c-e_-b-r-o-w-s-e-r_-d-e-b-u-g.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-s-a-m-s-u-n-g_-i-n-t-e-r-n-e-t.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-s-a-m-s-u-n-g_-i-n-t-e-r-n-e-t_-b-e-t-a.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-t-o-r_-b-r-o-w-s-e-r_-a-l-p-h-a.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-u-c_-b-r-o-w-s-e-r.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/-u-c_-b-r-o-w-s-e-r_-m-i-n-i.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/index.md
  docs/api/mozilla.components.support.utils/-browsers/-known-browser/package-name.md
  docs/api/mozilla.components.support.utils/-browsers/all.md
  docs/api/mozilla.components.support.utils/-browsers/default-browser.md
  docs/api/mozilla.components.support.utils/-browsers/firefox-branded-browser.md
  docs/api/mozilla.components.support.utils/-browsers/for-url.md
  docs/api/mozilla.components.support.utils/-browsers/has-firefox-branded-browser-installed.md
  docs/api/mozilla.components.support.utils/-browsers/has-multiple-third-party-browsers.md
  docs/api/mozilla.components.support.utils/-browsers/has-third-party-default-browser.md
  docs/api/mozilla.components.support.utils/-browsers/index.md
  docs/api/mozilla.components.support.utils/-browsers/installed-browsers.md
  docs/api/mozilla.components.support.utils/-browsers/is-default-browser.md
  docs/api/mozilla.components.support.utils/-browsers/is-firefox-default-browser.md
  docs/api/mozilla.components.support.utils/-browsers/is-installed.md
Labels: 🛬 needs landing

#4634 Add more descriptive instructions to README.md [ci skip]
  README.md
Labels: ✏️ needs changes

#4649 Closes #4636 - Add ShareTarget data class
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/parser/ShareTargetParser.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/parser/WebAppManifestIconParser.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/manifest/WebAppManifestParserTest.kt
  components/concept/engine/src/test/resources/manifests/minimal_share_target.json
  components/concept/engine/src/test/resources/manifests/squoosh.json
  components/concept/engine/src/test/resources/manifests/unusual.json
  docs/changelog.md
Labels: 🛬 needs landing

#4657 Closes #2887: Allow reporting exceptions without crashing
  components/lib/crash/metrics.yaml
  components/lib/crash/src/main/java/mozilla/components/lib/crash/Crash.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/CrashReporterService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/GleanCrashReporterService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/ExceptionHandlerTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/GleanCrashReporterServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SendCrashReportServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SentryServiceTest.kt
  docs/changelog.md
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashApplication.kt
Labels: 🕵️‍♀️ needs review

#4683 No issue: bump a-s to 0.41.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#4707 For #4672: Fix background ripple of Switch in BrowserMenuImageSwitch
  components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_switch.xml
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4268 Pass redirect source and target flags to history tracking delegates
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/browser/storage-memory/src/main/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorage.kt
  components/browser/storage-memory/src/test/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorageTest.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/history/HistoryTrackingDelegate.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProviderTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/HistoryDelegate.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/HistoryDelegateTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4739 Closes #3720: Incorrect selection notification when session removed
  components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
Labels: 🕵️‍♀️ needs review

#4788 Abstract away activity/fragment in prompt feature
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/FilePicker.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptContainer.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/res/values/ids.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/FilePickerTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptContainerTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#4773 Closes #4749: Fix for bug 1522829
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabIntentProcessorTest.kt
  components/feature/intent/src/test/java/mozilla/components/feature/intent/processing/TabIntentProcessorTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
Labels: 🕵️‍♀️ needs review

#4789 Use interface with PromptDialogFragment
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/ConfirmDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/AlertDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/AuthenticationDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/ChoiceDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/ColorPickerDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/ConfirmDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/DatePickerDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/MultiButtonDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/TextPromptDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/TimePickerDialogFragmentTest.kt
Labels: 🛬 needs landing

#4584 For #4583 Avoid icon engine in suggestion being cut off in RTL
  components/browser/awesomebar/src/main/res/layout/mozac_browser_awesomebar_item_generic.xml
Labels: 🕵️‍♀️ needs review

#4748 For #4747 Added menu animations for RTL layout direction
  components/browser/menu/src/main/res/anim-ldrtl/menu_enter_bottom.xml
  components/browser/menu/src/main/res/anim-ldrtl/menu_enter_top.xml
Labels: 🕵️‍♀️ needs review

#4806 For #4804 Fix RTL issues
  components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_switch.xml
  components/browser/menu/src/main/res/layout/mozac_browser_menu_item_simple.xml
Labels: 🛬 needs landing

#4813 Add externalAppType field
  components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabConfig.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabConfigHelper.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/WebAppManifest.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/intent/TrustedWebActivityIntentProcessor.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/intent/TrustedWebActivityIntentProcessorTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#4778 Update experimenter docs to use staging server, because the dev server is dead
  components/service/experiments/README.md
Labels: 🛬 needs landing

#4849 Add test and build tips to top-level README [CI skip]
  README.md
Labels: 🛬 needs landing

#4850 GeckoView update (nightly) (20191025-141049)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#4837 Public Suffix List update (20191023-141447)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#4840 Closes #4827: SessionUseCasesTest: Rename misleading test data
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
Labels: 🛬 needs landing

#4852 Add documentation for merge day process.
  docs/contribute/merge_day.md
  docs/contributing.md
Labels: 🕵️‍♀️ needs review

#4821 Use onTouchEventForResult
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
Labels: 🕵️‍♀️ needs review

#4831 Closes #4830: DownloadsFeature: Consume download from state if download is started without confirmation dialog.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
Labels: 🛬 needs landing

#4860 For issue #4839: update tracking protection policies.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
Labels: 🕵️‍♀️ needs review

#4768 Closes #2295, #4549: Implement Web Notification Feature
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Engine.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webnotifications/WebNotification.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webnotifications/WebNotificationDelegate.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt
  components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/NativeNotificationBridge.kt
  components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/WebNotificationFeature.kt
  components/feature/webnotifications/src/main/res/values/strings.xml
  components/feature/webnotifications/src/test/java/mozilla/components/feature/webnotifications/NativeNotificationBridgeTest.kt
  components/feature/webnotifications/src/test/java/mozilla/components/feature/webnotifications/WebNotificationFeatureTest.kt
  docs/changelog.md
  samples/browser/build.gradle
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/res/drawable/ic_notification.xml
Labels: 🕵️‍♀️ needs review

#4885 Closes #4884 Move Web Notifications Feature Changelog to Correct Version
  docs/changelog.md
Labels: 🕵️‍♀️ needs review
