Repository mozilla-mobile/android-components, pull requests merged in 2019-12, with the labels that each got.

#5212 GeckoView update (nightly) (20191202-140548)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5202 Closes #5201: Use Web Notification Tag as Notification Tag
  components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/WebNotificationFeature.kt
Labels: 🛬 needs landing

#5192 Closes #5177: Support App Links Redirect that Opens URL in Non Browser App If Available
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#5222 Fix sample-sync-logins to work with new dataprotect requirement.
  samples/sync-logins/build.gradle
  samples/sync-logins/src/main/java/org/mozilla/samples/sync/logins/MainActivity.kt
Labels: 🛬 needs landing

#5230 Closes #5229: Remove the Need to Have Atleast One Engine Observer to Load URI
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
Labels: 🛬 needs landing

#5233 Docs update (20191204-120723) [ci skip]
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-session/handle-long-click.md
Labels: 🛬 needs landing

#5167 Closes #4790: Add AddOnSettingsActivity
  samples/browser/src/main/AndroidManifest.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddOnSettingsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/InstalledAddOnDetailsActivity.kt
  samples/browser/src/main/res/layout/activity_add_on_settings.xml
  samples/browser/src/main/res/layout/fragment_add_on_settings.xml
Labels: ✏️ needs changes

#5254 Closes #5253: Intermittent test failure in WebExtensionSupportTest
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
Labels: 🛬 needs landing

#5181 Update Android Gradle plugin and Gradle version.
  buildSrc/src/main/java/Dependencies.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/SessionStorage.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Headers.kt
  components/feature/push/src/main/java/mozilla/components/feature/push/Connection.kt
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt
  components/tooling/fetch-tests/src/main/java/mozilla/components/tooling/fetch/tests/FetchTestCases.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: 🕵️‍♀️ needs review

#5277 Public Suffix List update (20191210-140721)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#5227 For #5145: Check for Null or Empty Stack Trace Before Reporting Crash to Socorro
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/CrashReporterService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
Labels: 🕵️‍♀️ needs review

#5298 GeckoView update (beta) (20191212-140728)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5297 GeckoView update (nightly) (20191212-140801)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5273 Closes #4529: Add method to wait for all dispatched actions to complete
  .buildconfig.yml
  README.md
  components/feature/contextmenu/build.gradle
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  components/feature/downloads/build.gradle
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  components/feature/prompts/build.gradle
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/support/test-libstate/README.md
  components/support/test-libstate/build.gradle
  components/support/test-libstate/src/main/AndroidManifest.xml
  components/support/test-libstate/src/main/java/mozilla/components/support/test/libstate/ext/Store.kt
  components/support/test-libstate/src/test/java/mozilla/components/support/test/libstate/ext/StoreTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#5310 Update Kotlin Coroutines to 1.3.3.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#5321 GeckoView update (nightly) (20191215-140729)
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/docs/metrics.md
Labels: 🛬 needs landing

#5325 GeckoView update (beta) (20191216-140732)
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/docs/metrics.md
Labels: 🛬 needs landing

#5326 GeckoView update (nightly) (20191216-140737)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5332 Update to detekt 1.2.2.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#5337 Add addons strings in l10n to be localized
  components/feature/addons/src/main/res/values/strings.xml
  l10n.toml
  samples/browser/src/main/AndroidManifest.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonDetailsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/InstalledAddonDetailsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/PermissionsDialogFragment.kt
  samples/browser/src/main/res/layout/activity_add_on_details.xml
  samples/browser/src/main/res/layout/activity_add_on_permissions.xml
  samples/browser/src/main/res/layout/activity_installed_add_on_details.xml
  samples/browser/src/main/res/layout/add_ons_item.xml
  samples/browser/src/main/res/layout/fragment_dialog_addon_permissions.xml
  samples/browser/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#5292 Closes #5243: Split AppLinksFeature into feature and interceptor
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/request/LaunchIntentMetadata.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/request/LoadRequestMetadata.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/request/RequestInterceptor.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/request/RequestInterceptorTest.kt
  components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeature.kt
  components/feature/accounts/src/test/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeatureTest.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/RedirectDialogFragment.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  config/detekt-baseline.xml
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonSettingsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/request/SampleRequestInterceptor.kt
Labels: 🕵️‍♀️ needs review

#5282 For #5280 - expose clear method of LocaleManager
  components/support/locale/src/main/java/mozilla/components/support/locale/LocaleManager.kt
  components/support/locale/src/test/java/mozilla/components/support/locale/LocaleManagerTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#5353 Closes #5349: Add WebExtensionController to gecko native web ext constructor
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
Labels: 🕵️‍♀️ needs review

#5334 Closes #5329: FennecMigrator: Use startForegroundService().
  components/support/migration/src/main/AndroidManifest.xml
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
Labels: 🕵️‍♀️ needs review

#5366 GeckoView update (beta) (20191219-140824)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5363 Docs update (20191219-121117) [ci skip]
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-web-extension/-init-.md
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-web-extension/index.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine/disable-web-extension.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine/enable-web-extension.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine/uninstall-web-extension.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine/update-web-extension.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-c-a-n-c-e-l.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-o-p-e-n.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-p-a-u-s-e.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-r-e-s-u-m-e.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-t-r-y_-a-g-a-i-n.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-e-x-t-r-a_-d-o-w-n-l-o-a-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-e-x-t-r-a_-d-o-w-n-l-o-a-d_-s-t-a-t-u-s.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/open-file.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-bookmarks-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-gecko-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-history-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-logins-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-open-tabs-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-settings-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/build.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-bookmarks.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-fxa.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-gecko.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-history.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-logins.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-open-tabs.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-settings.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/migrate-async.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/start-migration-service-if-needed.md
  docs/api/mozilla.components.support.migration/-migration/-bookmarks.md
  docs/api/mozilla.components.support.migration/-migration/-fx-a.md
  docs/api/mozilla.components.support.migration/-migration/-gecko.md
  docs/api/mozilla.components.support.migration/-migration/-history.md
  docs/api/mozilla.components.support.migration/-migration/-logins.md
  docs/api/mozilla.components.support.migration/-migration/-open-tabs.md
  docs/api/mozilla.components.support.migration/-migration/-settings.md
  docs/api/mozilla.components.support.migration/-migration/current-version.md
  docs/api/mozilla.components.support.migration/-migration/index.md
  docs/api/mozilla.components.support.migration/-versioned-migration/index.md
  docs/api/mozilla.components.support.migration/-versioned-migration/migration.md
  docs/api/mozilla.components.support.migration/-versioned-migration/version.md
Labels: 🛬 needs landing

#5365 GeckoView update (nightly) (20191219-140817)
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/docs/metrics.md
Labels: 🛬 needs landing

#5361 Closes #5346: Make sure crashes from rust's login import do not affect migration
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecLoginsMigration.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecLoginsMigrationTest.kt
Labels: 🛬 needs landing

#5350 Regenerate metrics.md. (Sorry, not sorry)
  components/browser/engine-gecko/docs/metrics.md
  components/lib/crash/docs/metrics.md
Labels: 🛬 needs landing

#5357 Closes #5112: Allow App to Specify Behavior when App Intent Failed to Launch.
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  config/detekt-baseline.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#5299 For #5296 Improve a11y for error pages
  components/browser/errorpages/src/main/java/mozilla/components/browser/errorpages/ErrorPages.kt
  components/browser/errorpages/src/main/res/raw/error_pages.html
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#5360 Closes #5315 - Create a Top Sites storage component
  .buildconfig.yml
  README.md
  components/feature/top-sites/README.md
  components/feature/top-sites/build.gradle
  components/feature/top-sites/proguard-rules.pro
  components/feature/top-sites/schemas/mozilla.components.feature.top.sites.db.TopSiteDatabase/1.json
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/TopSiteStorageTest.kt
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/db/TopSiteDaoTest.kt
  components/feature/top-sites/src/main/AndroidManifest.xml
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSite.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSiteStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/adapter/TopSiteAdapter.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/db/TopSiteDao.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/db/TopSiteDatabase.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/db/TopSiteEntity.kt
  components/feature/top-sites/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: 🕵️‍♀️ needs review

#5378 Closes #5351: Use Info level for caught exception crashes in Sentry reports.
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt
Labels: 🛬 needs landing

#5381 Issue #4928: Gradle: Force jacoco out of process..
  gradle.properties
Labels: 🛬 needs landing

#5331 Update Android Gradle Plugin to version 3.5.3.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#5285 Closes #5284: Adds progress bar to download notification
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing

#5429 GeckoView update (nightly) (20191230-140626)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5430 GeckoView update (beta) (20191230-140707)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5428 Docs update (20191230-120738) [ci skip]
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-c-a-n-c-e-l.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-o-p-e-n.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-p-a-u-s-e.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-r-e-s-u-m-e.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-t-r-y_-a-g-a-i-n.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/-a-c-t-i-v-e.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/-c-a-n-c-e-l-l-e-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/-c-o-m-p-l-e-t-e-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/-f-a-i-l-e-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/-p-a-u-s-e-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/index.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-e-x-t-r-a_-d-o-w-n-l-o-a-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-e-x-t-r-a_-d-o-w-n-l-o-a-d_-s-t-a-t-u-s.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/http-client.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/index.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/on-bind.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/on-destroy.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/on-start-command.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/on-task-removed.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/open-file.md
Labels: 🛬 needs landing

#5414 Add getDrawableWithTint helper
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt
  docs/changelog.md
Labels: 🛬 needs landing

#5409 Closes #5408 - Remove manifest when out of scope
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
Labels: 🛬 needs landing
