Repository mozilla-mobile/android-components, pull requests merged in 2019-05, with the labels that each got.

#2780 Update Gradle to 5.3.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: 🕵️‍♀️ needs review

#2912 Show website icon in browser-tabstray.
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  components/browser/tabstray/src/main/res/layout/mozac_browser_tabstray_item.xml
Labels: 🕵️‍♀️ needs review

#2947 GeckoView update (beta) (20190508-141122)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#2949 Issue #2883: Allow creating and restoring snapshots of single sessions.
  components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/AtomicFile.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/SnapshotSerializer.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/ext/AtomicFileKtTest.kt
Labels: 🕵️‍♀️ needs review

#2946 Issue #2883: Introduce TabCollectionWithTabs data type for joining over collections and tabs
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/db/TabCollectionDaoTest.kt
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/db/TabDaoTest.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/db/TabCollectionDao.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/db/TabCollectionWithTabs.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/db/TabDao.kt
Labels: 🕵️‍♀️ needs review

#2968 Update Kotlin to 1.3.31 and Coroutines to 1.2.1.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#2970 Closes #2978 runWithSessionIdOrSelected incorrectly runs for provided AND selected session.
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
Labels: 🛬 needs landing

#2973 Issue #2080: Extract website icon resources via WebExtension.
  components/browser/icons/build.gradle
  components/browser/icons/src/main/assets/extensions/browser-icons/icons.js
  components/browser/icons/src/main/assets/extensions/browser-icons/manifest.json
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/AllSessionsObserver.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/IconMessageHandler.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/IconSessionObserver.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/extension/AllSessionsObserverTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/extension/IconMessageHandlerTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/extension/IconSessionObserverTest.kt
  samples/browser/src/geckoNightly/java/org/mozilla/samples/browser/Components.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#2983 Update jacoco to 0.8.4.
  build.gradle
Labels: 🕵️‍♀️ needs review

#2987 Closes #2969: MessageHandler.onMessage requires non-null return value
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
Labels: 🛬 needs landing

#2919 Make Glean mock webserver reply 200 to all requests
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TestUtil.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/debug/GleanDebugActivityTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/net/HttpPingUploaderTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/private/PingTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/scheduler/MetricsPingSchedulerTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/EventsStorageEngineTest.kt
Labels: <glean>

#2981 (Documentation) Fix broken links to Photon Design System[ci-skip]
  docs/components.md
Labels: 🛬 needs landing

#2993 For #2346. Enable kotlin warningsAsErrors for `browser-awesomebar`.
  buildSrc/src/main/java/KotlinCompiler.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/BrowserAwesomeBarTest.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/layout/IconLoaderTest.kt
  components/browser/awesomebar/src/test/java/mozilla/utils/coroutines.kt
Labels: 🛬 needs landing

#3000 Import strings from android-l10n
  components/browser/engine-system/src/main/res/values-de/strings.xml
  components/browser/engine-system/src/main/res/values-es-rES/strings.xml
  components/browser/engine-system/src/main/res/values-es/strings.xml
  components/browser/engine-system/src/main/res/values-fr/strings.xml
  components/browser/engine-system/src/main/res/values-it/strings.xml
  components/browser/engine-system/src/main/res/values-ru/strings.xml
  components/feature/readerview/src/main/res/values-de/strings.xml
  components/feature/readerview/src/main/res/values-es-rES/strings.xml
  components/feature/readerview/src/main/res/values-es/strings.xml
  components/feature/readerview/src/main/res/values-fr/strings.xml
  components/feature/readerview/src/main/res/values-it/strings.xml
  components/feature/readerview/src/main/res/values-ru/strings.xml
  components/feature/sitepermissions/src/main/res/values-de/strings.xml
  components/feature/sitepermissions/src/main/res/values-es-rES/strings.xml
  components/feature/sitepermissions/src/main/res/values-es/strings.xml
  components/feature/sitepermissions/src/main/res/values-fr/strings.xml
  components/feature/sitepermissions/src/main/res/values-it/strings.xml
  components/feature/sitepermissions/src/main/res/values-ru/strings.xml
Labels: import-l10n, 🛬 needs landing

#3004 Closes #2675: Add EngineViewBottomBehavior to dynamically update vertical clipping when toolbar scrolls away.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-servo/src/main/java/mozilla/components/browser/engine/servo/ServoEngineView.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineViewTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/behavior/EngineViewBottomBehavior.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/behavior/EngineViewBottomBehaviorTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3005 Closes #2979: Support preserving classes in readerized output [ci skip]
  components/feature/readerview/src/main/assets/extensions/readerview/readerview.js
Labels: 🛬 needs landing

#3016 Closes #3015 - Make QrFragment clickable / focusable
  components/feature/qr/src/main/res/layout/fragment_layout.xml
Labels: 🕵️‍♀️ needs review

#3012 Closes #3009: Provide file:/// based uris to GeckoView onFilePrompt..
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#3010 Closes #2898: Do not clear title and icon if URL hasn't changed.
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3020 Closes #2763: Apply timeouts when loading icons.
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/HttpIconLoader.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/loader/HttpIconLoaderTest.kt
Labels: 🛬 needs landing

#3021 Make TrackingProtectionPolicy immutable
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
Labels: ⌨️ code

#3023 Add TabCollectionStorage.getCollections() to get LiveData list of collections.
  buildSrc/src/main/java/Dependencies.kt
  components/feature/tab-collections/build.gradle
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/TabCollectionStorageTest.kt
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/db/TabCollectionDaoTest.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/TabCollectionStorage.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/db/TabCollectionDao.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/db/TabCollectionWithTabs.kt
Labels: 🕵️‍♀️ needs review

#3024 Closes #2825: ContextMenuCandidate: Allow injecting custom SnackbarDelegate….
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3028 Closes #1628. Hide built-in WebView zoom controls in `engine-system`.
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3039 Added TabCollectionStorage.getTabCollectionsCount()..
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/TabCollectionStorageTest.kt
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/db/TabCollectionDaoTest.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/TabCollectionStorage.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/db/TabCollectionDao.kt
Labels: 🕵️‍♀️ needs review

#3041 Closes #2725: Add safe browsing categories to TrackingProtectionPolicy.
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#2890 glean: 1547967: Support additional ping metadata
  components/service/glean/docs/metrics/adding-new-metrics.md
  components/service/glean/docs/pings/custom.md
  components/service/glean/pings.yaml
  components/service/glean/scripts/sdk_generator.gradle
  samples/glean/metrics.yaml
  samples/glean/pings.yaml
Labels: <glean>

#3057 Import strings from android-l10n
  components/browser/engine-system/src/main/res/values-ja/strings.xml
  components/feature/readerview/src/main/res/values-ja/strings.xml
  components/feature/readerview/src/main/res/values-ko/strings.xml
  components/feature/sitepermissions/src/main/res/values-ja/strings.xml
Labels: import-l10n

#3064 For #3063 - Added no matches text color attr and show 0/0 for no matches.
  components/feature/findinpage/README.md
  components/feature/findinpage/src/main/java/mozilla/components/feature/findinpage/view/FindInPageBar.kt
  components/feature/findinpage/src/main/res/values/attrs.xml
  components/feature/findinpage/src/test/java/mozilla/components/feature/findinpage/view/FindInPageBarTest.kt
  docs/changelog.md
  samples/browser/src/main/res/layout/fragment_browser.xml
Labels: 🕵️‍♀️ needs review

#3069 Closes #3026: Add fontSizeFactor and fontInflationEnabled settings
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt
Labels: 🛬 needs landing

#3043 [★☆☆] For #2346. Add `testContext` providing for tests.
  components/support/test/build.gradle
  components/support/test/src/main/java/mozilla/components/support/test/robolectric/Extensions.kt
  components/support/test/src/test/java/mozilla/components/support/test/robolectric/ExtensionsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3072 Closes #2957: Bump a-s version to 0.28.1
  buildSrc/src/main/java/Dependencies.kt
  components/concept/sync/src/main/java/mozilla/components/concept/sync/Devices.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
Labels: 🕵️‍♀️ needs review

#3071 Move public version of AllSessionsObserver to browser-session.
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/AllSessionsObserver.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/utils/AllSessionsObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/utils/AllSessionsObserverTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3047 Closes #3046: Using the SessionIdOrSelected when reattaching the download dialog.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
Labels: <download>, 🛬 needs landing

#3042 #3038 Improving workaround for uploading files
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
Labels: 🕵️‍♀️ needs review

#3081 For #2346. Enable kotlin warningsAsErrors for `support-utils` module.
  buildSrc/src/main/java/KotlinCompiler.kt
  components/support/utils/build.gradle
  components/support/utils/src/main/java/mozilla/components/support/utils/DomainMatcher.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/StatusBarUtils.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/StorageUtils.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/ThreadUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/BrowsersTest.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DomainMatcherTest.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/StorageUtilsTest.kt
Labels: ✏️ needs changes

#3088 Closes #2449: Add feature-media component.
  .buildconfig.yml
  components/feature/media/README.md
  components/feature/media/build.gradle
  components/feature/media/proguard-rules.pro
  components/feature/media/src/main/AndroidManifest.xml
  components/feature/media/src/main/java/mozilla/components/feature/media/Placeholder.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/PlaceholderTest.kt
  components/feature/media/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: 🕵️‍♀️ needs review

#3067 BrowserAwesomeBar: Only call onInputChanged() after onInputStarted() and allow provider to return suggestions from onInputStarted()
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/BrowserAwesomeBar.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/BrowserAwesomeBarTest.kt
  components/concept/awesomebar/src/main/java/mozilla/components/concept/awesomebar/AwesomeBar.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProviderTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3103 Add security policy.
  .github/SECURITY.md
Labels: 🕵️‍♀️ needs review

#3109 Closes #3104: Handle IOException in HttpIconLoader.
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/HttpIconLoader.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/loader/HttpIconLoaderTest.kt
Labels: 🛬 needs landing

#3106 Update GeckoView Nightly to 69.0.20190524095337..
  buildSrc/src/main/java/Gecko.kt
Labels: 🕵️‍♀️ needs review

#3114 Add applink strings to error pages [ci skip]
  components/browser/errorpages/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#3136 Update GeckoView Nightly to 69.0.20190527095441.
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#3134 For #2346. Enable kotlin warningsAsErrors for `service-firefox-accounts` module.
  buildSrc/src/main/java/KotlinCompiler.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/manager/PollingDeviceManagerTest.kt
Labels: 🛬 needs landing

#3130 For #2346. Enable kotlin warningsAsErrors for `feature-toolbar` module.
  buildSrc/src/main/java/KotlinCompiler.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarPresenterTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/internal/URLRendererTest.kt
Labels: 🛬 needs landing

#3141 Use GeckoResult in coroutines seamlessly
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoResult.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoResultTest.kt
Labels: <engine-gecko>

#3140 Use public LifecycleObserver instead of internal
  components/support/base/src/main/java/mozilla/components/support/base/observer/ObserverRegistry.kt
  components/support/base/src/test/java/mozilla/components/support/base/observer/ObserverRegistryTest.kt
Labels: ⌨️ code

#3044 [★☆☆] For #2346. Enable kotlin warningsAsErrors for `tooling-lint` module.
  buildSrc/src/main/java/KotlinCompiler.kt
  components/tooling/lint/src/main/java/mozilla/components/tooling/lint/LintLogChecks.kt
  components/tooling/lint/src/test/java/mozilla/components/tooling/lint/LintLogChecksTest.kt
Labels: 🛬 needs landing

#3123 For #2346. Enable kotlin warningsAsErrors for `samples-toolbar` module.
  buildSrc/src/main/java/KotlinCompiler.kt
  samples/toolbar/src/main/java/org/mozilla/samples/toolbar/SampleToolbarHelpers.kt
Labels: 🛬 needs landing

#3145 Remove overscroll effect in menu
  components/browser/menu/src/main/res/layout/mozac_browser_menu.xml
  docs/changelog.md
Labels: <menu>

#3129 For #2346. Enable kotlin warningsAsErrors for `feature-session` module.
  buildSrc/src/main/java/KotlinCompiler.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/PictureInPictureFeature.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/CoordinateScrollingFeatureTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/EngineViewPresenterTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/FullScreenFeatureTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/HistoryDelegateTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/PictureInPictureFeatureTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionFeatureTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SettingsUseCasesTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/behavior/EngineViewBottomBehaviorTest.kt
Labels: ✏️ needs changes

#3155 Closes #3154: Reject all no supported site permissions
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
Labels: 🕵️‍♀️ needs review

#3142 Closes #3137: Add helper for for providing unique and stable noticiation ids.
  components/support/base/README.md
  components/support/base/src/main/java/mozilla/components/support/base/ids/NotificationIds.kt
  components/support/base/src/main/java/mozilla/components/support/base/ids/SharedIds.kt
  components/support/base/src/test/java/mozilla/components/support/base/notification/NotificationIdsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3144 Closes #3118: Add option to remove all tab collections and their tabs.
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/TabCollectionStorageTest.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/TabCollectionStorage.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/db/TabEntity.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3160 Import strings from android-l10n
  components/browser/errorpages/src/main/res/values-de/strings.xml
  components/browser/errorpages/src/main/res/values-it/strings.xml
  components/browser/errorpages/src/main/res/values-zh-rCN/strings.xml
  components/browser/errorpages/src/main/res/values-zh-rTW/strings.xml
  components/feature/media/src/main/res/values-de/strings.xml
  components/feature/media/src/main/res/values-it/strings.xml
  components/feature/media/src/main/res/values-zh-rCN/strings.xml
  components/feature/media/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n, 🛬 needs landing

#3148 Closes #1828 - Update WebAppManifest from engine
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/build.gradle
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/manifest/WebAppManifestParserTest.kt
  components/concept/engine/src/test/resources/manifests/example_google.json
  components/concept/engine/src/test/resources/manifests/example_mdn.json
  components/concept/engine/src/test/resources/manifests/invalid_json.json
  components/concept/engine/src/test/resources/manifests/minimal.json
  components/concept/engine/src/test/resources/manifests/spec_typical.json
  components/concept/engine/src/test/resources/manifests/twitter_mobile.json
  components/concept/engine/src/test/resources/manifests/unusual.json
  components/concept/engine/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/AbstractWebAppShellActivity.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppLauncherActivity.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/Activity.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/AbstractWebAppShellActivityTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppLauncherActivityTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/ActivityKtTest.kt
  docs/changelog.md
Labels: <session>

#3152 Closes #3151 - Init clearView as gone
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/edit/EditToolbarTest.kt
Labels: 🕵️‍♀️ needs review

#3147 Closes #1824 - Pull to Refresh
  .buildconfig.yml
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/session/README.md
  components/feature/session/src/main/java/mozilla/components/feature/session/SwipeRefreshFeature.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SwipeRefreshFeatureTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
  samples/browser/src/main/res/layout/fragment_browser.xml
Labels: 🌟 feature

#2990 Closes #888: Use PixelCopy API on Oreo+
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/View.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ViewTest.kt
  components/support/test/src/main/java/mozilla/components/support/test/robolectric/shadow/PixelCopyShadow.kt
Labels: 🕵️‍♀️ needs review

#3090 Expand labeled metrics to allow for dotted snake-case labels.
  components/service/glean/scripts/sdk_generator.gradle
  components/service/glean/src/main/java/mozilla/components/service/glean/private/LabeledMetricType.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/private/LabeledMetricTypeTest.kt
Labels: <glean>

#3198 For #2346. Enable kotlin warningsAsErrors for `feature-sitepermissions` module.
  buildSrc/src/main/java/KotlinCompiler.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsDialogFragmentTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsRulesTest.kt
Labels: 🛬 needs landing

#3192 Closes #3110: Upgrade Work Manager dependency.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review
