Repository mozilla-mobile/android-components, pull requests merged in 2019-06, with the labels that each got.

#3183 For #2346. Enable kotlin warningsAsErrors for `browser-engine-servo` module.
  buildSrc/src/main/java/KotlinCompiler.kt
  components/browser/engine-servo/src/main/java/mozilla/components/browser/engine/servo/ServoEngineSessionState.kt
  components/browser/engine-servo/src/test/java/mozilla/components/browser/engine/servo/ServoEngineSessionStateTest.kt
  components/browser/engine-servo/src/test/java/mozilla/components/browser/engine/servo/ServoEngineSessionTest.kt
  components/support/test/src/main/java/mozilla/components/support/test/Mock.kt
Labels: 🛬 needs landing

#3208 Implement canScrollVerticallyUp in gecko beta
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3200 For #2346. Enable kotlin warningsAsErrors for `feature-downloads` module.
  buildSrc/src/main/java/KotlinCompiler.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadDialogFragmentTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadManagerTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragmentTest.kt
Labels: 🛬 needs landing

#3220 Issue #1447 - Depend on "fat" GeckoView build from browser-engine-gecko-nightly.
  automation/taskcluster/androidTest/ui-test.sh
  automation/taskcluster/decision_task.py
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/build.gradle
  components/lib/crash/build.gradle
  docs/changelog.md
  samples/browser/build.gradle
Labels: 🕵️‍♀️ needs review

#3223 Parse web app manifest icon purpose as set
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/manifest/WebAppManifestParserTest.kt
  components/concept/engine/src/test/resources/manifests/unusual.json
Labels: <pwa>

#3178 Closes #3146: Refresh devices after updating device name
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3229 ﻿Improvements to PromptFeature
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
Labels: 🕵️‍♀️ needs review

#3222 Closes #3206: Add nullability checks to sync dispatcher.
  components/feature/sync/src/main/java/mozilla/components/feature/sync/BackgroundSyncManager.kt
  components/feature/sync/src/test/java/mozilla/components/feature/sync/GeneralSyncManagerTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3225 Fix UI test job error trigger
  automation/taskcluster/androidTest/ui-test.sh
Labels: ✅ testing, 🐞 bug, 🛬 needs landing, 🤖 automation

#3215 Closes #3195: Ignore UrlParseFailed exceptions coming out of places
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3240 Import strings from android-l10n
  components/browser/errorpages/src/main/res/values-es-rES/strings.xml
  components/browser/errorpages/src/main/res/values-es/strings.xml
  components/browser/errorpages/src/main/res/values-fr/strings.xml
  components/browser/errorpages/src/main/res/values-ko/strings.xml
  components/browser/errorpages/src/main/res/values-ru/strings.xml
  components/feature/app-links/src/main/res/values-de/strings.xml
  components/feature/app-links/src/main/res/values-fr/strings.xml
  components/feature/app-links/src/main/res/values-it/strings.xml
  components/feature/app-links/src/main/res/values-zh-rCN/strings.xml
  components/feature/app-links/src/main/res/values-zh-rTW/strings.xml
  components/feature/media/src/main/res/values-es-rES/strings.xml
  components/feature/media/src/main/res/values-es/strings.xml
  components/feature/media/src/main/res/values-fr/strings.xml
  components/feature/media/src/main/res/values-ko/strings.xml
  components/feature/media/src/main/res/values-ru/strings.xml
Labels: import-l10n, 🛬 needs landing

#3242 Gradle: zipMavenArtifacts wait for publish to be finished.
  automation/taskcluster/decision_task.py
  publish.gradle
Labels: 🕵️‍♀️ needs review

#3243 Update GeckoView Nightly to 69.0.20190604034844.
  buildSrc/src/main/java/Gecko.kt
Labels: 🕵️‍♀️ needs review

#3186 For #2346. Enable kotlin warningsAsErrors for `support-test` module.
  buildSrc/src/main/java/KotlinCompiler.kt
  components/support/test/src/main/java/mozilla/components/support/test/KArgumentCaptor.kt
  components/support/test/src/main/java/mozilla/components/support/test/robolectric/Extensions.kt
  components/support/test/src/main/java/mozilla/components/support/test/robolectric/Permissions.kt
  components/support/test/src/main/java/mozilla/components/support/test/robolectric/shadow/PixelCopyShadow.kt
  components/support/test/src/test/java/PermissionsTest.kt
  components/support/test/src/test/java/mozilla/components/support/test/robolectric/ExtensionsTest.kt
  components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounter.kt
Labels: 🛬 needs landing

#3201 For #2346. Enable kotlin warningsAsErrors for `feature-accounts` module..
  buildSrc/src/main/java/KotlinCompiler.kt
  components/feature/accounts/src/test/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeatureTest.kt
Labels: 🛬 needs landing

#3185 Fixes #3032 - Add animation for browser-menu
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt
  components/browser/menu/src/main/res/anim/menu_enter_bottom.xml
  components/browser/menu/src/main/res/anim/menu_enter_top.xml
  components/browser/menu/src/main/res/anim/menu_exit.xml
  components/browser/menu/src/main/res/values/style.xml
  docs/changelog.md
Labels: <menu>, 🛬 needs landing, 🧙‍♂️ Needs UX Feedback

#3275 CrashRecoveryUseCase: Allow restoring list of sessions and all crashed sessions.
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
Labels: 🕵️‍♀️ needs review

#3290 DiskCache: Synchronize cache writes. Bail out if cache cannot be written.
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/DiskCache.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3271 Turn on ComplexMethod `ignoreSingleWhenExpression` lint rule
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSessionState.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/ico/IconDirectoryEntry.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/pipeline/IconResourceComparator.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Types.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/Activity.kt
  components/lib/jexl/src/main/java/mozilla/components/lib/jexl/parser/Parser.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaDeviceManager.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/StorageEngineManager.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/Map.kt
  config/detekt.yml
Labels: ⌨️ code, 🛬 needs landing

#3224 Use only one `Size` class for HTML sizes attribute
  components/browser/icons/src/androidTest/java/mozilla/components/browser/icons/OnDeviceBrowserIconsTest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/IconRequest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/IconMessage.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/BrowserIconsTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/extension/IconMessageHandlerTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/extension/IconMessageKtTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/pipeline/IconResourceComparatorTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/utils/DiskCacheTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/Size.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/manifest/SizeTest.kt
Labels: <icons>

#3317 Fixes #162 - Replace Drawable.toBitmap with core-ktx
  buildSrc/src/main/java/Dependencies.kt
  components/feature/awesomebar/build.gradle
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
  components/support/ktx/build.gradle
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/graphics/drawable/Drawable.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/org/json/JSONObject.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/View.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/ContextTest.kt
  docs/changelog.md
Labels: <ktx>

#3330 Add check to ensure Glean is only initialized on the main process.
  components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
Labels: <glean>

#3320 Issue #1968 - Convert DownloadManager to interface
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Response.kt
  components/feature/downloads/build.gradle
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/AndroidDownloadManager.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/DownloadManager.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/AndroidDownloadManagerTest.kt
Labels: <download>

#3346 Fix for intermittent test failures in Glean
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/TestUtil.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/private/PingTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/scheduler/MetricsPingSchedulerTest.kt
Labels: <glean>

#3372 For #1481. Use androidx runner in `support-ktx`.
  components/support/ktx/build.gradle
  components/support/ktx/gradle.properties
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/ContextTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/res/AssetManagerTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/res/ResourcesTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/graphics/BitmapKtTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/net/UriTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/org/json/JSONArrayTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/org/json/JSONObjectTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/os/StrictModeTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/util/Base64Test.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/MotionEventKtTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ViewTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/java/io/FileKtTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/MapTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt
Labels: 🛬 needs landing

#3324 Closes #3211: Added endOfMenuAlwaysVisible to BrowserMenu.show.
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenuBuilder.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/BrowserMenuTest.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3375 For #1481. Use androidx runner in `ui-autocomplete`.
  components/ui/autocomplete/build.gradle
  components/ui/autocomplete/gradle.properties
  components/ui/autocomplete/src/test/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditTextTest.kt
Labels: 🛬 needs landing

#3374 For #1481. Use androidx runner in `support-utils`.
  components/support/utils/build.gradle
  components/support/utils/gradle.properties
  components/support/utils/src/test/java/mozilla/components/support/utils/BrowsersTest.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/ColorUtilsTest.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DomainMatcherTest.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/SafeIntentTest.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/URLStringUtilsTest.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/WebURLFinderTest.java
Labels: 🛬 needs landing

#3367 For #1481. Use androidx runner in `service-firefox-accounts`.
  components/service/firefox-accounts/build.gradle
  components/service/firefox-accounts/gradle.properties
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
Labels: 🛬 needs landing

#3354 For #1481. Use androidx runner in `browser-storage-sync`.
  components/browser/storage-sync/build.gradle
  components/browser/storage-sync/gradle.properties
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorageTest.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
Labels: ✏️ needs changes

#3379 Fix intermittent test in Glean.
  components/service/glean/src/test/java/mozilla/components/service/glean/scheduler/MetricsPingSchedulerTest.kt
Labels: <glean>

#3386 Update GeckoView Nightly to 69.0.20190610093815.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequestTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/permission/PermissionRequest.kt
Labels: 🕵️‍♀️ needs review

#3392 TabAdapter/TabCollectionAdapter: Implement equals() and hashCode().
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/adapter/TabAdapter.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/adapter/TabCollectionAdapter.kt
Labels: 🛬 needs landing

#3305 Import strings from android-l10n
  components/browser/errorpages/src/main/res/values-es-rES/strings.xml
  components/browser/errorpages/src/main/res/values-zh-rCN/strings.xml
  components/feature/app-links/src/main/res/values-es-rES/strings.xml
  components/feature/app-links/src/main/res/values-es/strings.xml
  components/feature/app-links/src/main/res/values-ja/strings.xml
  components/feature/app-links/src/main/res/values-ko/strings.xml
  components/feature/app-links/src/main/res/values-ru/strings.xml
  components/feature/app-links/src/main/res/values-zh-rCN/strings.xml
  components/feature/contextmenu/src/main/res/values-zh-rCN/strings.xml
  components/feature/media/src/main/res/values-ja/strings.xml
  components/feature/readerview/src/main/res/values-es-rES/strings.xml
  components/feature/readerview/src/main/res/values-zh-rCN/strings.xml
  components/feature/sitepermissions/src/main/res/values-zh-rCN/strings.xml
  components/support/ktx/src/main/res/values-es-rES/strings.xml
Labels: import-l10n

#3382 For #1481. Use androidx runner in `feature-app-links`.
  components/feature/app-links/build.gradle
  components/feature/app-links/gradle.properties
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing

#3378 For #1481. Use androidx runner in `ui-tabcounter`.
  components/ui/tabcounter/build.gradle
  components/ui/tabcounter/gradle.properties
  components/ui/tabcounter/src/test/java/mozilla/components/ui/tabcounter/TabCounterTest.kt
Labels: 🛬 needs landing

#3414 Use Android Components Docker image 1.18.
  .taskcluster.yml
  automation/taskcluster/lib/tasks.py
Labels: 🕵️‍♀️ needs review

#3279 Replace TimePicker and DatePicker with Dialogs
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/TimePickerDialogFragment.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_date_picker.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_date_time_picker.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_time_picker.xml
  components/feature/prompts/src/main/res/values-de/strings.xml
  components/feature/prompts/src/main/res/values-es-rES/strings.xml
  components/feature/prompts/src/main/res/values-es/strings.xml
  components/feature/prompts/src/main/res/values-fr/strings.xml
  components/feature/prompts/src/main/res/values-it/strings.xml
  components/feature/prompts/src/main/res/values-ja/strings.xml
  components/feature/prompts/src/main/res/values-ko/strings.xml
  components/feature/prompts/src/main/res/values-ru/strings.xml
  components/feature/prompts/src/main/res/values-zh-rCN/strings.xml
  components/feature/prompts/src/main/res/values-zh-rTW/strings.xml
  components/feature/prompts/src/main/res/values/strings.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/TimePickerDialogFragmentTest.kt
Labels: <prompts>

#3411 Issue #3302: TabCollectionStorage: Order TabCollections by the time they were last updated.
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/db/TabCollectionDao.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3436 Import strings from android-l10n
  components/feature/app-links/src/main/res/values-ru/strings.xml
  components/feature/prompts/src/main/res/values-de/strings.xml
  components/feature/prompts/src/main/res/values-es-rES/strings.xml
  components/feature/prompts/src/main/res/values-es/strings.xml
  components/feature/prompts/src/main/res/values-fr/strings.xml
  components/feature/prompts/src/main/res/values-it/strings.xml
  components/feature/prompts/src/main/res/values-ja/strings.xml
  components/feature/prompts/src/main/res/values-ko/strings.xml
  components/feature/prompts/src/main/res/values-ru/strings.xml
  components/feature/prompts/src/main/res/values-zh-rCN/strings.xml
  components/feature/prompts/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#3253 Closes #3101 - Support highlighting menu button
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuHighlightableItem.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuImageText.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuHighlightableItemTest.kt
  components/browser/toolbar/build.gradle
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/MenuButton.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/browser/toolbar/src/main/res/drawable/mozac_menu_indicator.xml
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/MenuButtonTest.kt
Labels: 🛬 needs landing

#3339 Closes #2043 - Add ColorProcessor from Fennec
  buildSrc/src/main/java/Dependencies.kt
  components/browser/icons/build.gradle
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/AndroidIconDecoder.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/ColorProcessor.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/processor/ColorProcessorTest.kt
Labels: <icons>

#3446 Add changelog for BrowserMenuHighlightableItem [ci skip]
  docs/changelog.md
Labels: 🛬 needs landing

#3485 Closes #3424 - Check if session is installable
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/manifest/WebAppManifestParserTest.kt
  components/concept/engine/src/test/resources/manifests/invalid_missing_name.json
  components/concept/engine/src/test/resources/manifests/minimal_short_name.json
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/Session.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/SessionKtTest.kt
Labels: <pwa>

#3452 Move ui-icons fill to resource
  components/ui/icons/src/main/res/drawable/mozac_ic_arrowhead_down.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_arrowhead_up.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_back.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_check.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_clear.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_close.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_delete.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_device_desktop.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_device_mobile.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_download.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_font.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_forward.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_globe.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_grid.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_info.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_link.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_location.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_lock.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_menu.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_microphone.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_mozilla.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_new.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_notification.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_open_in.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_pin.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_pin_filled.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_private_browsing.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_reader_mode.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_refresh.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_reorder.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_rocket.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_rocket_filled.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_search.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_select_all.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_share.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_stop.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_sync.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_tab.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_tab_new.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_video.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_warning.xml
  components/ui/icons/src/main/res/values/colors.xml
Labels: <icons>

#3491 Style PWA in recents screen
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/AbstractWebAppShellActivity.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppLauncherActivity.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/WebAppManifest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppLauncherActivityTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/WebAppManifestKtTest.kt
Labels: <pwa>

#3295 Closes #2041 - Add ResizingProcessor
  components/browser/icons/src/androidTest/java/mozilla/components/browser/icons/OnDeviceBrowserIconsTest.kt
  components/browser/icons/src/androidTest/java/mozilla/components/browser/icons/decoder/ICOIconDecoderTest.kt
  components/browser/icons/src/androidTest/java/mozilla/components/browser/icons/decoder/OnDeviceAndroidIconDecoderTest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/DesiredSize.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/Icon.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/AndroidIconDecoder.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/ICOIconDecoder.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/IconDecoder.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/ColorProcessor.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/DiskIconProcessor.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/IconProcessor.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/MemoryIconProcessor.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/ResizingProcessor.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/DiskCache.kt
  components/browser/icons/src/main/res/values/dimens.xml
  components/browser/icons/src/test/java/mozilla/components/browser/icons/BrowserIconsTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/decoder/AndroidIconDecoderTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/decoder/ICOIconDecoderTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/generator/DefaultIconGeneratorTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/processor/ColorProcessorTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/processor/DiskIconProcessorTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/processor/MemoryIconProcessorTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/processor/ResizingProcessorTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/utils/MemoryCacheTest.kt
Labels: <icons>

#3482 For #3473. Get rid of detekt baseline.
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/graphics/Bitmap.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/Char.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/ColorUtils.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/SafeBundle.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/SafeIntent.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/WebURLFinder.kt
  components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
  config/detekt-baseline.xml
Labels: 🛬 needs landing

#3504 Remove app services dependency from firebase component
  components/lib/push-firebase/build.gradle
Labels: 🛬 needs landing

#3498 Theme the PWA activity
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/manifest/WebAppManifestParserTest.kt
  components/concept/engine/src/test/resources/manifests/example_mdn.json
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/AbstractWebAppShellActivity.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Activity.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/ColorUtils.kt
Labels: <pwa>

#3499 Closes #3496: Add new lib-push-amazon component
  .buildconfig.yml
  components/lib/push-amazon/README.md
  components/lib/push-amazon/build.gradle
  components/lib/push-amazon/proguard-rules.pro
  components/lib/push-amazon/src/main/AndroidManifest.xml
  components/lib/push-amazon/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: 🕵️‍♀️ needs review

#3497 Import strings from android-l10n
  components/browser/engine-system/src/main/res/values-zh-rCN/strings.xml
  components/browser/errorpages/src/main/res/values-zh-rCN/strings.xml
  components/browser/toolbar/src/main/res/values-zh-rCN/strings.xml
  components/feature/prompts/src/main/res/values-zh-rCN/strings.xml
Labels: import-l10n

#3471 Fixes #2784. Update android gradle plugin to `3.4.1`.
  buildSrc/src/main/java/Dependencies.kt
  samples/toolbar/src/main/res/drawable/pageaction_background.xml
Labels: 🛬 needs landing

#3463 Fixes #790. Add `isScreenReaderEnabled` ktx-extension.
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/ContextKtTest.kt
  docs/changelog.md
Labels: ✏️ needs changes

#3470 Add deprecation blog post link to changelog entry. [ci-skip]
  docs/changelog.md
Labels: ✏️ needs changes

#3518 Add documentation for lib-state
  components/lib/state/README.md
  components/lib/state/src/main/java/mozilla/components/lib/state/Action.kt
  components/lib/state/src/main/java/mozilla/components/lib/state/Store.kt
Labels: <state>

#3514 Fixes #2605 - Replace pxToDp with dpToPx
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/BrowserAwesomeBar.kt
  components/browser/awesomebar/src/main/res/values/colors.xml
  components/browser/awesomebar/src/main/res/values/dimens.xml
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/layout/DefaultSuggestionViewHolderTest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/generator/DefaultIconGenerator.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/generator/DefaultIconGeneratorTest.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuItemToolbar.kt
  components/browser/menu/src/main/res/values/dimens.xml
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/MenuButton.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/browser/toolbar/src/main/res/values/dimens.xml
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/res/Resources.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/util/DisplayMetrics.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/View.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/util/DisplayMetricsTest.kt
  docs/changelog.md
  samples/toolbar/src/main/java/org/mozilla/samples/toolbar/ToolbarActivity.kt
Labels: <ktx>, ⌨️ code

#3537 Update Docker image to version 1.19.
  .taskcluster.yml
  automation/taskcluster/lib/tasks.py
Labels: 🕵️‍♀️ needs review

#3523 Restructure (reduced) BrowserState and add tests.
  components/browser/state/build.gradle
  components/browser/state/src/main/java/mozilla/components/browser/session/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/session/reducer/BrowserReducers.kt
  components/browser/state/src/main/java/mozilla/components/browser/session/selector/Selectors.kt
  components/browser/state/src/main/java/mozilla/components/browser/session/state/DownloadState.kt
  components/browser/state/src/main/java/mozilla/components/browser/session/state/SessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/session/state/SourceState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/CustomTabListReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/selector/Selectors.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/SecurityInfoState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/SessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/store/BrowserStore.kt
  components/browser/state/src/test/java/mozilla/components/browser/session/action/SessionListActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/session/store/BrowserStoreTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/CustomTabListActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/selector/SelectorsKtTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/store/BrowserStoreTest.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/StoreTest.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/StoreExtensionsKtTest.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/helpers/HelpersKtTest.kt
  components/support/test/build.gradle
  components/support/test/src/main/java/mozilla/components/support/test/ext/Job.kt
Labels: 🕵️‍♀️ needs review

#3542 PublicSuffixListData: Handle empty labels.
  components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixListData.kt
  components/lib/publicsuffixlist/src/test/java/mozilla/components/lib/publicsuffixlist/PublicSuffixListTest.kt
Labels: 🕵️‍♀️ needs review

#3543 Issue #3529: Dispatch actions from SessionManager for add/remove/select..
  components/browser/session/build.gradle
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/BrowserStoreExtensions.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/SessionExtensions.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
Labels: 🕵️‍♀️ needs review

#3548 Closes #3545: EngineVersion: Remove named groups
  components/concept/engine/src/main/java/mozilla/components/concept/engine/utils/EngineVersion.kt
Labels: 🕵️‍♀️ needs review

#3554 Closes #3525: browser-state: Auto-select first tab
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/store/BrowserStoreTest.kt
Labels: 🛬 needs landing

#3552 Closes #3533: browser-state: Dispatch actions from Session
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/SessionExtensions.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
Labels: 🛬 needs landing

#3536 Issue #2047: browser-icons: Ship with tippy-top-sites top 200 list for icon resource lookup..
  components/browser/icons/src/main/assets/mozac.browser.icons/icons-top200.json
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/IconRequest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/IconMessage.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/pipeline/IconResourceComparator.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/preparer/TippyTopIconPreparer.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/preparer/TippyTopIconPreparerTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3570 Closes #3526: Update selected tab id after selected tab is removed.
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
Labels: 🕵️‍♀️ needs review

#3547 Store browser-icons constants in res
  components/browser/icons/build.gradle
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/IconRequest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/generator/DefaultIconGenerator.kt
  components/browser/icons/src/main/res/values/colors.xml
  components/browser/icons/src/main/res/values/dimens.xml
  components/browser/icons/src/test/java/mozilla/components/browser/icons/generator/DefaultIconGeneratorTest.kt
Labels: <icons>, ⌨️ code

#3553 Use interface with features that need permissions
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFeature.kt
  components/feature/qr/src/test/java/mozilla/components/feature/qr/QrFeatureTest.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsRulesTest.kt
  components/support/base/src/main/java/mozilla/components/support/base/feature/PermissionsFeature.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: <base>, ⌨️ code

#3495 Closes #3211: Support endOfMenuAlwaysVisible for Android 6 and below.
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/BrowserMenuTest.kt
Labels: 🕵️‍♀️ needs review

#3513 Use operator keyword in UseCases
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/intent/src/main/java/mozilla/components/feature/intent/IntentProcessor.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/SearchUseCases.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/SearchUseCasesTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/FullScreenFeature.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionFeature.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SettingsUseCases.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SwipeRefreshFeature.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SettingsUseCasesTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: ⌨️ code
