Repository mozilla-mobile/android-components, pull requests merged in 2019-07, with the labels that each got.

#3595 Deprecate View.isVisible in favour of Android KTX
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/feature/prompts/build.gradle
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/TextPromptDialogFragmentTest.kt
  components/feature/readerview/build.gradle
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/internal/ReaderViewControlsPresenter.kt
  components/feature/sitepermissions/build.gradle
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsDialogFragmentTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/View.kt
Labels: <ktx>

#3614 For #2740. Update `detekt` to `1.0.0-RC16`.
  build.gradle
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Connection.kt
  components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt
  config/detekt.yml
  samples/sync-logins/src/main/java/org/mozilla/samples/sync/logins/MainActivity.kt
Labels: 🛬 needs landing

#3608 Closes #3606: browser-engine-gecko-nightly: Add GeckoView as "api" dependency.
  components/browser/engine-gecko-nightly/build.gradle
Labels: 🕵️‍♀️ needs review

#3627 Issue #3602: Add EngineView.release() for manually releasing session from view.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-servo/src/main/java/mozilla/components/browser/engine/servo/ServoEngineView.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineViewTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SwipeRefreshFeatureTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/behavior/EngineViewBottomBehaviorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3641 Issue mozilla-mobile/fenix#773 - Add to homescreen
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ManifestStorage.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppUseCases.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/Session.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppShortcutManagerTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/SessionKtTest.kt
  samples/browser/build.gradle
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: <pwa>

#3651 Closes #3621: sample browser: Add simple UI test that loads a website.
  buildSrc/src/main/java/Dependencies.kt
  samples/browser/build.gradle
  samples/browser/src/androidTest/assets/index.html
  samples/browser/src/androidTest/java/org/mozilla/samples/browser/SmokeTests.kt
  samples/browser/src/androidTest/java/org/mozilla/samples/browser/rules/WebserverRule.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#3655 Closes #3643: Add localization comment to mozac_lib_crash_notification_action_report.
  components/lib/crash/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#3635 Import strings from android-l10n
  components/lib/crash/src/main/res/values-de/strings.xml
  components/lib/crash/src/main/res/values-zh-rCN/strings.xml
  components/lib/crash/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#3628 Closes #3584: Api for supporting language switch.
  .buildconfig.yml
  components/support/base/src/main/res/values/strings.xml
  components/support/locale/README.md
  components/support/locale/build.gradle
  components/support/locale/gradle.properties
  components/support/locale/proguard-rules.pro
  components/support/locale/src/main/AndroidManifest.xml
  components/support/locale/src/main/java/mozilla/components/support/locale/Extensions.kt
  components/support/locale/src/main/java/mozilla/components/support/locale/LocaleAwareAppCompatActivity.kt
  components/support/locale/src/main/java/mozilla/components/support/locale/LocaleAwareApplication.kt
  components/support/locale/src/main/java/mozilla/components/support/locale/LocaleManager.kt
  components/support/locale/src/test/java/mozilla/components/support/locale/LocaleManagerTest.kt
Labels: 🕵️‍♀️ needs review

#3263 Read web app manifest in browser-icons
  components/browser/icons/src/main/java/mozilla/components/browser/icons/Icon.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/IconRequest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/IconMessage.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/WebAppManifest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/pipeline/IconResourceComparator.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/Size.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/manifest/SizeTest.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/Session.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/org/json/JSONArray.kt
Labels: <icons>, <pwa>, 🕵️‍♀️ needs review

#3665 Issue #3481 - Use setPrimaryClip
  components/browser/search/src/main/java/mozilla/components/browser/search/provider/AssetsSearchEngineProvider.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProviderTest.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
Labels: Q

#3661 Closes #3567: BrowserStore/SessionManager: Make result of "nearby" tab selection match.
  components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
Labels: 🕵️‍♀️ needs review

#3657 Closes #3566: Remove "default session" behavior from SessionManager..
  components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/storage/SessionStorageTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#3671 Issue #3481 - Support Q in browser components
  components/browser/domains/src/test/java/mozilla/components/browser/domains/BaseDomainAutocompleteProviderTest.kt
  components/browser/domains/src/test/java/mozilla/components/browser/domains/DomainAutoCompleteProviderTest.kt
  components/browser/search/src/test/java/mozilla/components/browser/search/ParseSearchPluginsTest.kt
  samples/dataprotect/src/main/java/org/mozilla/samples/dataprotect/MainActivity.kt
Labels: <dataprotect>, <domains>, <search>, Q

#3670 Issue #3481 - Support compling to Q in Glean
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/EventsStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/GenericStorageEngine.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/storages/TimespansStorageEngine.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/GleanTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/ping/PingMakerTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/private/DatetimeMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/private/LabeledMetricTypeTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/DatetimesStorageEngineTest.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/storages/EventsStorageEngineTest.kt
Labels: <glean>, Q

#3159 Fixes #2587 - Show camera inside file prompt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/src/main/AndroidManifest.xml
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/FilePicker.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/MimeType.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/res/xml/file_paths.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/FilePickerTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/MimeTypeTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  docs/changelog.md
Labels: <prompts>, 🕵️‍♀️ needs review

#3682 Import strings from android-l10n
  components/lib/crash/src/main/res/values-es-rES/strings.xml
  components/lib/crash/src/main/res/values-es/strings.xml
  components/lib/crash/src/main/res/values-fr/strings.xml
  components/lib/crash/src/main/res/values-it/strings.xml
  components/lib/crash/src/main/res/values-ja/strings.xml
  components/lib/crash/src/main/res/values-ko/strings.xml
  components/lib/crash/src/main/res/values-ru/strings.xml
Labels: import-l10n

#3684 Add putCompoundDrawablesRelative support function
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/TextView.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/TextViewTest.kt
  docs/changelog.md
Labels: <ktx>

#3588 Issue #3480 - Port Fennec basic color picker
  components/feature/prompts/build.gradle
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/BasicColorAdapter.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/ColorPickerDialogFragment.kt
  components/feature/prompts/src/main/res/drawable-hdpi/color_picker_row_bg.9.png
  components/feature/prompts/src/main/res/drawable-mdpi/color_picker_row_bg.9.png
  components/feature/prompts/src/main/res/drawable-xhdpi/color_picker_row_bg.9.png
  components/feature/prompts/src/main/res/drawable-xxhdpi/color_picker_row_bg.9.png
  components/feature/prompts/src/main/res/drawable/color_picker_checkmark.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_color_item.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_color_picker_dialogs.xml
  components/feature/prompts/src/main/res/values/colors.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/ColorPickerDialogFragmentTest.kt
  docs/changelog.md
Labels: <prompts>

#3319 Replace String.toUri with core-ktx
  components/browser/engine-system/build.gradle
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/icons/build.gradle
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/HttpIconLoader.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/preparer/TippyTopIconPreparer.kt
  components/feature/sitepermissions/build.gradle
  components/feature/sitepermissions/src/androidTest/java/mozilla/components/feature/sitepermissions/db/OnDeviceSitePermissionsStorageTest.kt
  components/feature/sitepermissions/src/androidTest/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDaoTest.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/toolbar/build.gradle
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/internal/URLRenderer.kt
  components/service/pocket/build.gradle
  components/service/pocket/src/main/java/mozilla/components/service/pocket/PocketListenURLs.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/PocketURLs.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/PocketEndpointRawTest.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/PocketListenEndpointRawTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/net/UriTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt
  docs/changelog.md
Labels: <ktx>, 🕵️‍♀️ needs review

#3683 Deprecated View.isGone, View.isInvisible
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/View.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ViewTest.kt
  docs/changelog.md
Labels: <ktx>, ⌨️ code

#3669 Closes #2450: Add MediaNotificationFeature to display notification while web content media is playing.
  components/feature/media/build.gradle
  components/feature/media/src/main/AndroidManifest.xml
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotificationFeature.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaService.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaState.kt
  components/feature/media/src/main/res/drawable/mozac_feature_media_paused.xml
  components/feature/media/src/main/res/drawable/mozac_feature_media_playing.xml
  components/feature/media/src/test/java/mozilla/components/feature/media/notification/MediaNotificationFeatureTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/notification/MediaNotificationTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaServiceTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#3699 Use deprecated annotation for pxToDp
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/res/Resources.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/net/Uri.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/util/DisplayMetrics.kt
Labels: <ktx>

#3706 Fixes #3705 - Fix conflicting authorities
  components/feature/prompts/src/main/AndroidManifest.xml
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/MimeType.kt
Labels: <prompts>

#3698 Closes #3524: browser-state: Prevent duplicated tabs (id)
  components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/utils/AllSessionsObserverTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/store/BrowserStoreExceptionTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProviderTest.kt
Labels: 🕵️‍♀️ needs review

#3710 Add flag for PWA support
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppUseCases.kt
Labels: <pwa>

#3726 Closes #3673 - Add custom download icon
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/res/drawable/mozac_feature_download_ic_download.xml
  components/feature/downloads/src/main/res/drawable/mozac_feature_download_ic_download_anim0.xml
  components/feature/downloads/src/main/res/drawable/mozac_feature_download_ic_download_anim1.xml
  components/feature/downloads/src/main/res/drawable/mozac_feature_download_ic_download_anim2.xml
  components/feature/downloads/src/main/res/drawable/mozac_feature_download_ic_download_anim3.xml
  components/feature/downloads/src/main/res/drawable/mozac_feature_download_ic_download_anim4.xml
  components/feature/downloads/src/main/res/drawable/mozac_feature_download_ic_download_anim5.xml
  docs/changelog.md
Labels: <download>

#3742 Issue #3481 - Fix null checks for Q
  components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/TabCollectionStorageTest.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/Crash.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/debug/ExperimentsDebugActivity.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
Labels: Q

#3746 Closes #3639: browser-state: Add onLowMemory behavior
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/SessionExtensions.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/SystemReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/SystemActionTest.kt
Labels: 🕵️‍♀️ needs review

#3745 Closes #3743: Adding TrackingProtectionPolicy.CookiePolicy.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3749 Closes #3738: Depend on "fat" GeckoView build from browser-engine-gecko-beta.
  automation/taskcluster/decision_task.py
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/build.gradle
  components/browser/engine-gecko/build.gradle
  docs/changelog.md
  samples/browser/build.gradle
Labels: 🕵️‍♀️ needs review

#3730 Add helper for one-time OnGlobalLayoutListener
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/BrowserMenuTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/View.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ViewTest.kt
  components/ui/tabcounter/build.gradle
  components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounter.kt
  docs/changelog.md
Labels: <ktx>

#3399 Clean up magic numbers
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/ico/IconDirectoryEntry.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/generator/DefaultIconGenerator.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Response.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/ColorPickerDialogFragment.kt
  components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt
  components/lib/jexl/src/main/java/mozilla/components/lib/jexl/grammar/Grammar.kt
  components/service/telemetry/src/main/java/org/mozilla/telemetry/net/TelemetryClient.kt
  samples/toolbar/src/main/java/org/mozilla/samples/toolbar/SampleToolbarHelpers.kt
  samples/toolbar/src/main/java/org/mozilla/samples/toolbar/ToolbarActivity.kt
  samples/toolbar/src/main/res/values/colors.xml
Labels: ⌨️ code, 🕵️‍♀️ needs review

#3709 Break apart different BrowserFragment versions
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionFeature.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/CustomTabActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/CustomTabBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/WebAppBrowserFragment.kt
Labels: :iphone: sample, <customtabs>, <pwa>

#3771 Import strings from android-l10n
  components/feature/downloads/src/main/res/values-de/strings.xml
  components/feature/downloads/src/main/res/values-es/strings.xml
  components/feature/downloads/src/main/res/values-fr/strings.xml
  components/feature/downloads/src/main/res/values-it/strings.xml
  components/feature/downloads/src/main/res/values-ru/strings.xml
  components/feature/downloads/src/main/res/values-zh-rCN/strings.xml
  components/feature/downloads/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#3752 Closes #3691 - disable app-links for links on the same host as current
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
Labels: 🛬 needs landing

#3667 Closes #3481 - Increase compileSdkVersion to 29
  buildSrc/src/main/java/Config.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ext/Context.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/BasicColorAdapter.kt
  docs/changelog.md
Labels: Q

#3796 PR checklist: Add milestone [ci skip]
  .github/pull_request_template.md
Labels: 🕵️‍♀️ needs review

#3694 Add glide-style icon loading function
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/CancelOnDetach.kt
  components/browser/icons/src/main/res/values/tags.xml
  components/browser/icons/src/test/java/mozilla/components/browser/icons/BrowserIconsTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/utils/CancelOnDetachTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3674 Closes #3207 - Generate PWA launcher icons
  components/browser/icons/build.gradle
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/IconRequest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/WebAppManifest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/generator/DefaultIconGenerator.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/AdaptiveIconProcessor.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/ResizingProcessor.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/IconDiskCache.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/IconMemoryCache.kt
  components/browser/icons/src/main/res/values/dimens.xml
  components/browser/icons/src/test/java/mozilla/components/browser/icons/pipeline/IconResourceComparatorTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/processor/AdaptiveIconProcessorTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/processor/ColorProcessorTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/processor/ResizingProcessorTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/utils/IconDiskCacheTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/utils/IconMemoryCacheTest.kt
  components/feature/pwa/build.gradle
  components/feature/pwa/src/main/AndroidManifest.xml
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppUseCases.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppShortcutManagerTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: <icons>, <pwa>, 🕵️‍♀️ needs review

#3798 Import strings from android-l10n
  components/browser/engine-system/src/main/res/values-sv-rSE/strings.xml
  components/browser/errorpages/src/main/res/values-eu/strings.xml
  components/browser/errorpages/src/main/res/values-sv-rSE/strings.xml
  components/browser/toolbar/src/main/res/values-eu/strings.xml
  components/browser/toolbar/src/main/res/values-sv-rSE/strings.xml
  components/feature/app-links/src/main/res/values-eu/strings.xml
  components/feature/app-links/src/main/res/values-sv-rSE/strings.xml
  components/feature/contextmenu/src/main/res/values-sv-rSE/strings.xml
  components/feature/customtabs/src/main/res/values-sv-rSE/strings.xml
  components/feature/downloads/src/main/res/values-sv-rSE/strings.xml
  components/feature/media/src/main/res/values-sv-rSE/strings.xml
  components/feature/prompts/src/main/res/values-sv-rSE/strings.xml
  components/feature/readerview/src/main/res/values-sv-rSE/strings.xml
  components/feature/sitepermissions/src/main/res/values-sv-rSE/strings.xml
  components/feature/tabs/src/main/res/values-sv-rSE/strings.xml
  components/lib/crash/src/main/res/values-sv-rSE/strings.xml
  components/support/ktx/src/main/res/values-sv-rSE/strings.xml
  l10n.toml
Labels: import-l10n

#3777 Closes #3528: Validate (initial) Store state
  components/browser/state/src/main/java/mozilla/components/browser/state/store/BrowserStore.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/store/BrowserStoreTest.kt
Labels: 🕵️‍♀️ needs review

#3804 Closes #3788: Expose to which category a blocked tracker belongs
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SelectionAwareSessionObserverTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/content/blocking/Tracker.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3823 Fixes #3516 - Use response to determine file name
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Download.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Headers.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadDialogFragment.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ext/Download.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ext/Intent.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/AndroidDownloadManager.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/DownloadManager.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  docs/changelog.md
Labels: <download>

#3863 Issue #3738: update_geckoview.sh: Update command to build sample browser with GeckoView beta. [ci skip]
  automation/taskcluster/action/update_geckoview.sh
Labels: 🛬 needs landing

#3860 Closes #3864: Make text size of minus and plus buttons have the same size on reader view
  components/feature/readerview/src/main/res/layout/mozac_feature_readerview_view.xml
  components/feature/readerview/src/main/res/values/mozac_feature_readerview_strings.xml
  docs/changelog.md
Labels: 🛬 needs landing

#3808 Issue #3637: service-location: Add service to access Mozilla Location Service (MLS).
  .buildconfig.yml
  README.md
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Headers.kt
  components/service/location/.gitignore
  components/service/location/README.md
  components/service/location/build.gradle
  components/service/location/proguard-rules.pro
  components/service/location/src/main/AndroidManifest.xml
  components/service/location/src/main/java/mozilla/components/service/location/MozillaLocationService.kt
  components/service/location/src/test/java/mozilla/components/service/location/MozillaLocationServiceTest.kt
  components/service/location/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  docs/changelog.md
Labels: 🛬 needs landing

#3318 Replaced ViewGroup.forEach with core-ktx
  components/browser/menu/build.gradle
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/edit/EditToolbarTest.kt
  components/feature/customtabs/build.gradle
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/ViewGroup.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/Map.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/MapTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#3818 Fixes #3782 - Add fallback shortcut label
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt
  components/feature/pwa/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#3876 Update Docker image to version 1.20.
  automation/taskcluster/lib/tasks.py
Labels: 🕵️‍♀️ needs review

#3847 Closes #3871: Autocomplete incorrectly fills urls that contains a port number.
  components/support/utils/src/main/java/mozilla/components/support/utils/DomainMatcher.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DomainMatcherTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3878 Public Suffix List update (20190723-175402)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#3819 Closes #2313 - Add related_applications property
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestIconParser.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/manifest/WebAppManifestParserTest.kt
  components/concept/engine/src/test/resources/manifests/spec_typical.json
Labels: <pwa>

#3891 Closes #3887: Memory leak in reader view content message handler
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
Labels: 🛬 needs landing

#3848 fixes #3611, #2991 in fenix and #3839 in a-c - Long press image with link still shows image url
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFeature.kt
Labels: 🛬 needs landing

#3892 Turn Store.broadcastChannel() into Store.channel() and return just a ReceiveChannel.
  components/lib/state/src/main/java/mozilla/components/lib/state/ext/Fragment.kt
  components/lib/state/src/main/java/mozilla/components/lib/state/ext/StoreExtensions.kt
  components/lib/state/src/main/java/mozilla/components/lib/state/ext/View.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/StoreExtensionsKtTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#3902 Fixes #3900 - Catch download IOExceptions
  components/feature/downloads/src/main/AndroidManifest.xml
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt
  components/feature/downloads/src/main/res/drawable/mozac_feature_download_ic_download.xml
  components/feature/downloads/src/main/res/drawable/mozac_feature_download_ic_ongoing_download.xml
  components/feature/downloads/src/main/res/values/colors.xml
  components/feature/downloads/src/main/res/values/strings.xml
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing

#3708 Clean up toolbar feature code
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeature.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarFeature.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarInteractor.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/internal/URLRenderer.kt
Labels: 🛬 needs landing

#3938 MediaService: Introduce first MediaSession and audio focus code.
  buildSrc/src/main/java/Dependencies.kt
  components/feature/media/build.gradle
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/Media.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/MediaState.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaService.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/session/MediaSessionCallback.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/notification/MediaNotificationTest.kt
Labels: 🕵️‍♀️ needs review

#3913 fixes #3912 on ac, fenix related issue #148 - Find in page a11y
  components/feature/findinpage/src/main/res/values/style.xml
Labels: 🛬 needs landing

#3869 Fixes #3868 - Custom tabs style the status bar
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/AbstractWebAppShellActivity.kt
  components/support/ktx/build.gradle
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Activity.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Window.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/WindowTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/CustomTabBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/WebAppBrowserFragment.kt
Labels: 🛬 needs landing

#3945 Closes #3873 - Support custom navigation bar color
  components/browser/session/src/main/java/mozilla/components/browser/session/tab/CustomTabConfig.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabConfigHelper.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabConfigHelperTest.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
  components/feature/pwa/build.gradle
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/AbstractWebAppShellActivity.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Window.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/ColorUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/ColorUtilsTest.kt
  docs/changelog.md
  samples/browser/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#3968 Issue #3935: Process result returned from requestAudioFocus().
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/MediaState.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/focus/AudioFocus.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaService.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/focus/AudioFocusTest.kt
Labels: 🕵️‍♀️ needs review

#3816 Closes #2293 - Open custom tabs when leaving scope
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/manifest/WebAppManifestParserTest.kt
  components/feature/pwa/build.gradle
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/AbstractWebAppShellActivity.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppLauncherActivity.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/Activity.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/Bundle.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/Intent.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/WebAppManifest.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/WebAppActivityFeature.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/WebAppHideToolbarFeature.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessor.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/AbstractWebAppShellActivityTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppLauncherActivityTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppShortcutManagerTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/ActivityKtTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/WebAppManifestKtTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/feature/WebAppActivityFeatureTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/feature/WebAppHideToolbarFeatureTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessorTest.kt
  samples/browser/build.gradle
  samples/browser/src/main/AndroidManifest.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/CustomTabActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/CustomTabBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/IntentReceiverActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/WebAppBrowserFragment.kt
Labels: <pwa>

#3976 Add isTrustedWebActivityIntent
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabConfigHelper.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabConfigHelperTest.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessor.kt
Labels: <customtabs>, <pwa>

#3854 Closes #3487 - Display PWA site controls notification
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/WebAppSiteControlsFeature.kt
  components/feature/pwa/src/main/res/drawable/ic_pwa.xml
  components/feature/pwa/src/main/res/drawable/ic_refresh.xml
  components/feature/pwa/src/main/res/values/strings.xml
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/feature/WebAppSiteControlsFeatureTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Window.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/WindowTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserFragment.kt
Labels: <pwa>, 🕵️‍♀️ needs review
