Repository mozilla-mobile/android-components, pull requests merged in 2019-08, with the labels that each got.

#3971 Issue #3656: Reduce browser icons memory footprint
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/IconMemoryCache.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
Labels: ✏️ needs changes

#3984 Support display: minimal-ui
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppLauncherActivity.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/WebAppManifest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppLauncherActivityTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/WebAppManifestKtTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserActivity.kt
Labels: 🛬 needs landing

#3980 Closes #3711: Additional plugins not loaded when search order specified
  components/browser/search/src/main/java/mozilla/components/browser/search/provider/AssetsSearchEngineProvider.kt
  components/browser/search/src/test/java/mozilla/components/browser/search/provider/AssetsSearchEngineProviderTest.kt
Labels: 🛬 needs landing

#3850 Use manifest background_color for icon background
  components/browser/icons/src/main/java/mozilla/components/browser/icons/Icon.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/IconRequest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/WebAppManifest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/generator/DefaultIconGenerator.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/ColorProcessor.kt
Labels: 🛬 needs landing

#3978 Fixes #3838: Adds selectableItemBackground to HighlightableMenuitem
  components/browser/menu/build.gradle
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuHighlightableItem.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuHighlightableItemTest.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/MenuButton.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/MenuButtonTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/res/drawable/background_with_ripple.xml
Labels: ✏️ needs changes

#3992 Add documentation for the PWA feature [ci skip]
  components/feature/pwa/README.md
Labels: 🕵️‍♀️ needs review

#4048 Updating broken links on the changelog [ci skip]
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4049 Updating the pull request template. Adding a section for breaking changes [ci skip].
  .github/pull_request_template.md
Labels: 🕵️‍♀️ needs review

#4022 Open downloads when download notification tapped
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt
Labels: 🕵️‍♀️ needs review

#4051 Closes #3877: Beta Uplift: Recover when content process gets killed
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4060 Closes #4058: TrackingProtectionIconView#onCreateDrawableState getting called before class properties get initialized.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconView.kt
Labels: 🕵️‍♀️ needs review

#4102 Closes #4079: Manually updating GeckoView nightly 70.0.20190809095611.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptAbuserDetector.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
Labels: 🕵️‍♀️ needs review

#4089 Closes #3923: Create async API for SearchEngineManager
  components/browser/search/src/main/java/mozilla/components/browser/search/SearchEngineManager.kt
  components/browser/search/src/main/java/mozilla/components/browser/search/suggestions/SearchSuggestionClient.kt
  components/browser/search/src/test/java/mozilla/components/browser/search/SearchEngineManagerTest.kt
  components/browser/search/src/test/java/mozilla/components/browser/search/suggestions/SearchSuggestionClientTest.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/AwesomeBarFeatureTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#4104 Issue #4033: Abandon audio focus when media service is shutting down.
  components/feature/media/src/main/java/mozilla/components/feature/media/focus/AudioFocus.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/focus/AudioFocusController.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/focus/AudioFocusControllerV21.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/focus/AudioFocusControllerV26.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaService.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/focus/AudioFocusTest.kt
Labels: 🕵️‍♀️ needs review

#4103 Closes #3797: Do not display site title/url/icon in media notification in private mode.
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
  components/feature/media/src/main/res/values/strings.xml
  components/feature/media/src/test/java/mozilla/components/feature/media/notification/MediaNotificationTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4112 Issue #1200: Correctly order items in bors.toml.
  bors.toml
Labels: 🕵️‍♀️ needs review

#4123 Closes #3921: Adapt tracking protection icons in Custom tab toolbar.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
Labels: 🕵️‍♀️ needs review

#4122 Closes #4069: Update docs for newAccount param
  components/concept/sync/src/main/java/mozilla/components/concept/sync/OAuthAccount.kt
Labels: 🕵️‍♀️ needs review

#4087 For #3439 - Add "report" action to crash notification
  components/lib/crash/src/main/AndroidManifest.xml
  components/lib/crash/src/main/java/mozilla/components/lib/crash/notification/CrashNotification.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SendCrashReportService.kt
  components/lib/crash/src/main/res/values/strings.xml
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SendCrashReportServiceTest.kt
Labels: 🕵️‍♀️ needs review

#4134 Update month chooser strings descriptions [ci skip]
  components/feature/prompts/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#4144 Closes #4121: Use startForegroundService() to start media service.
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaService.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/MediaFeatureTest.kt
Labels: 🛬 needs landing

#4147 Fix parsing of "purpose" field from Gecko
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestIconParser.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/manifest/WebAppManifestParserTest.kt
  components/concept/engine/src/test/resources/manifests/purpose_array.json
Labels: 🕵️‍♀️ needs review

#4143 CCloses #4125: Fragment.consumeFrom(): Temporarily check whether fragment is added.
  components/lib/state/src/main/java/mozilla/components/lib/state/ext/Fragment.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/FragmentKtTest.kt
Labels: 🛬 needs landing

#4145 Closes #3033: Close toolbar menu on app exit
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/MenuButton.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/MenuButtonTest.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarFeature.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  docs/changelog.md
Labels: ✏️ needs changes

#4137 Closes #3861: Add a component for synchronizing Application Services' unit testing dependencies used in Android Components.
  .buildconfig.yml
  README.md
  components/support/test-appservices/README.md
  components/support/test-appservices/build.gradle
  components/support/test-appservices/src/main/AndroidManifest.xml
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4169 Closes #4116: Introduce simplified media state derived from playbackState.
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/media/Media.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/media/MediaTest.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaMap.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4182 MediaStateMachine: Filter media of paused state and batch state updates.
  components/feature/media/src/main/java/mozilla/components/feature/media/state/MediaStateMachine.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/MediaFeatureTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaServiceTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/state/MediaStateMachineTest.kt
Labels: 🕵️‍♀️ needs review

#4170 docs: Update jekyll and dependencies.
  docs/Gemfile
  docs/Gemfile.lock
Labels: 🕵️‍♀️ needs review

#4136 Issue #2295 - Add WebNotification class
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webnotifications/WebNotification.kt
  docs/changelog.md
Labels: <webnotifications>, 🕵️‍♀️ needs review

#4130 Closes #3925: Adding meaningful content descriptions to tracking protection toolbar icon for different states.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconView.kt
  components/browser/toolbar/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#4203 Update Kotlin to 1.3.50 and Coroutines to 1.3.0.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#4204 Add recommended pre-push hook to config folder
  config/pre-push-hook
Labels: 🕵️‍♀️ needs review

#4214 Closes #2682 - Document components versioning.
  docs/contribute/versioning.md
  docs/contributing.md
Labels: 🕵️‍♀️ needs review

#4226 Import strings from android-l10n
  components/browser/errorpages/src/main/res/values-in/strings.xml
  components/browser/errorpages/src/main/res/values-nn-rNO/strings.xml
  components/browser/errorpages/src/main/res/values-tr/strings.xml
  components/browser/toolbar/src/main/res/values-fi/strings.xml
  components/browser/toolbar/src/main/res/values-sv-rSE/strings.xml
  components/browser/toolbar/src/main/res/values-zh-rTW/strings.xml
  components/feature/downloads/src/main/res/values-sv-rSE/strings.xml
  components/feature/downloads/src/main/res/values-tr/strings.xml
  components/feature/downloads/src/main/res/values-zh-rTW/strings.xml
  components/feature/media/src/main/res/values-nb-rNO/strings.xml
  components/feature/media/src/main/res/values-sv-rSE/strings.xml
  components/feature/media/src/main/res/values-tr/strings.xml
  components/feature/media/src/main/res/values-zh-rTW/strings.xml
  components/feature/prompts/src/main/res/values-tr/strings.xml
  components/feature/prompts/src/main/res/values-zh-rTW/strings.xml
  components/feature/readerview/src/main/res/values-vi/strings.xml
  components/feature/readerview/src/main/res/values-zh-rCN/strings.xml
  components/feature/sitepermissions/src/main/res/values-fi/strings.xml
  components/lib/crash/src/main/res/values-fi/strings.xml
  components/lib/crash/src/main/res/values-tr/strings.xml
  components/lib/crash/src/main/res/values-zh-rTW/strings.xml
  components/support/ktx/src/main/res/values-tr/strings.xml
Labels: import-l10n, 🛬 needs landing

#4179 Add property delegates for shared preferences
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/SharedPreferences.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/SharedPreferencesTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#4235 No issue: Updates HighlightableMenuItem to allow startImage
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuHighlightableItem.kt
  components/browser/menu/src/main/res/layout/mozac_browser_menu_highlightable_item.xml
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuHighlightableItemTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/MenuButtonTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🐉 Fenix

#4223 Closes #3359: Document deprecation process.
  docs/contribute/deprecating.md
  docs/contributing.md
Labels: 🕵️‍♀️ needs review

#4251 Closes #4250: Update the tracking protection icon content description XML IDS.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconView.kt
  components/browser/toolbar/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review
