Repository mozilla-mobile/android-components, pull requests merged in 2020-10, with the labels that each got.

#8571 No issue: Update photonInk80 to the correct colour
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing

#8543 Closes issue #8462: Fix intermittent test on DownloadsFeatureTest
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
Labels: 🛬 needs landing

#8553 For #8356 - Null check down event in BrowserGestureDetector
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetector.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetectorTest.kt
Labels: 🛬 needs landing

#8592 Upgrade Glean to v32.4.1
  buildSrc/src/main/java/Dependencies.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8546 Consider implementation and api dependencies when optimizing build tasks (fixes #8540)
  taskcluster/ac_taskgraph/loader/build_config.py
Labels: 🛬 needs landing

#8547 For #8511: Fix CrashHandlerService IntentService deprecation in Android 11
  components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/CrashHandlerService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt
Labels: 🛬 needs landing

#8594 Add a few more configurations to check for dependencies
  taskcluster/ac_taskgraph/loader/build_config.py
Labels: 🛬 needs landing

#8599 Add entry for adding the milestone to issues
  docs/contribute/release_checklist.md
Labels: 🛬 needs landing

#8610 Mergify: Add comment when PR has conflicts.
  .mergify.yml
Labels: 🛬 needs landing

#8588 Closes issue #8587: Add use cases for removing individual and all downloads
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsUseCases.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadUseCasesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8433 Closes #8312:Adds support for ContentDelegate#onExternalResponse
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/browser/state/build.gradle
  components/browser/state/src/main/java/mozilla/components/browser/state/state/content/DownloadState.kt
  components/concept/engine/build.gradle
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8623 Revert Gradle, Android Gradle Plugin and Kotlin upgrade.
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegateTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegateTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegateTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/matcher/UrlMatcher.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/pipeline/IconResourceComparator.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/Utils.kt
  components/browser/storage-memory/src/main/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorage.kt
  components/browser/storage-sync/build.gradle
  components/concept/menu/src/main/java/mozilla/components/concept/menu/ext/MenuCandidate.kt
  components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_unsupported_item.xml
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt
  components/feature/media/src/main/AndroidManifest.xml
  components/feature/push/src/main/java/mozilla/components/feature/push/Connection.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/WebAppSiteControlsFeature.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/AbstractCrashListActivity.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/CrashListAdapter.kt
  components/lib/crash/src/main/res/layout/mozac_lib_crash_activity_crashlist.xml
  components/lib/jexl/src/main/java/mozilla/components/lib/jexl/ast/nodes.kt
  components/lib/jexl/src/main/java/mozilla/components/lib/jexl/lexer/Lexer.kt
  components/service/digitalassetlinks/src/main/java/mozilla/components/service/digitalassetlinks/AndroidAssetFinder.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ExperimentEvaluator.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/Experiments.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/ExperimentEvaluatorTest.kt
  components/service/firefox-accounts/build.gradle
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sharing/AccountSharing.kt
  components/service/sync-logins/build.gradle
  components/support/migration/build.gradle
  components/support/rustlog/build.gradle
  components/tooling/detekt/build.gradle
  components/tooling/glean-gradle-plugin/build.gradle
  components/tooling/lint/build.gradle
  components/tooling/lint/src/main/java/mozilla/components/tooling/lint/AndroidSrcXmlDetector.kt
  components/tooling/lint/src/main/java/mozilla/components/tooling/lint/ImageViewAndroidTintXmlDetector.kt
  docs/changelog.md
  gradle/wrapper/gradle-wrapper.properties
  samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt
  samples/browser/src/main/res/layout/fragment_add_on_settings.xml
  samples/browser/src/main/res/layout/fragment_browser.xml
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashApplication.kt
  samples/firefox-accounts/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#8621 Close #8040: Move ImageLoader to support-base
  components/browser/icons/build.gradle
  components/browser/tabstray/build.gradle
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabsAdapter.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/DefaultTabViewHolderTest.kt
  components/browser/thumbnails/build.gradle
  components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/loader/ThumbnailLoader.kt
  components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/storage/ThumbnailStorage.kt
  components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/utils/ThumbnailDiskCache.kt
  components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/loader/ThumbnailLoaderTest.kt
  components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/storage/ThumbnailStorageTest.kt
  components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/utils/ThumbnailDiskCacheTest.kt
  components/concept/base/build.gradle
  components/concept/base/src/main/java/mozilla/components/concept/base/images/ImageLoader.kt
  components/concept/base/src/main/java/mozilla/components/concept/base/images/ImageRequest.kt
  components/support/images/build.gradle
  docs/changelog.md
  samples/browser/build.gradle
Labels: 🛬 needs landing

#8582 Update JNA to 5.5.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#8620 Closes #8619: Add maximum length for Socorro crash report stack trace
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/support/base/src/main/java/mozilla/components/support/base/ext/Throwable.kt
  components/support/base/src/test/java/mozilla/components/support/base/ext/ThrowableTest.kt
Labels: 🛬 needs landing

#8626 Update changelog release 62.0.0
  docs/changelog.md
Labels: 🛬 needs landing

#8629 Closes #8609: Intermittent test failues in WebExtensionSupportTest
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
Labels: 🛬 needs landing

#8628 Closes #7976: Use different port for article and reader pages
  components/feature/readerview/src/main/assets/extensions/readerview/readerview.js
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewMiddleware.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
  components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionController.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionControllerTest.kt
Labels: 🛬 needs landing

#8627 Update AC version to 63.0.0
  .buildconfig.yml
Labels: 🛬 needs landing

#8434 Closes #8207: Add Delegate and Browser Session State for MediaSession API
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionController.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionControllerTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegateTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/MediaSessionReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/MediaSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/SessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/MediaSessionActionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/mediasession/MediaSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/mediasession/MediaSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8630 Closes issue #8367: Add SHIMMED TrackingCategory
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8633 Closes #8632: Recover from SQLiteBlobTooBigException in crash database
  components/lib/crash/src/main/java/mozilla/components/lib/crash/db/CrashDao.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/CrashListFragment.kt
Labels: 🛬 needs landing

#8647 Closes #8548: Display icons of temporary extensions
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/test/java/AddonManagerTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
Labels: 🛬 needs landing

#8650 For #8527, Closes #8195 - Make 'account' immutable in the FxA manager
  components/feature/accounts/src/test/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeatureTest.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/AccountStorage.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
Labels: 🛬 needs landing

#8663 Introduce log statements in pageStart/pageStop for FNPRMS
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
Labels: 🛬 needs landing

#8437 RFC for determining the region of the user for picking default search engines.
  docs/contributing.md
  docs/rfcs/0006-search-defaults.md
Labels: RFC, 🛬 needs landing

#8646 Bug 1663967 - Ship v16.0.0 of feature-webcompat.
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1567610-dns.google.com-moz-fit-content.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1568908-console.cloud.google.com-scrollbar-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1609991-cracked.com-flex-basis-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1666771-zilow-map-overdraw.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1654906-contentDocument-fix.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#8682 Update CODEOWNERS.
  CODEOWNERS
Labels: 🛬 needs landing

#8685 Closes #8622: Reader page title may contain HTML entities
  components/feature/readerview/src/main/assets/extensions/readerview/readerview.js
Labels: 🛬 needs landing

#8645 Fix Detekt LongParameterList>threshold option deprecated #8644
  config/detekt.yml
Labels: 🛬 needs landing

#8641 Closes #5352: Remove compileOnly dependency on GeckoView in lib-crash
  components/lib/crash/build.gradle
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
Labels: 🛬 needs landing

#8640 For mozilla-mobile/fenix#14557 - Adds API to add click listener to icon view
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/edit/EditToolbarTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8688 Mergify: Add rule for squashing PR
  .mergify.yml
Labels: 🕵️‍♀️ needs review

#8698 Closes #8697: Move Session.loadRequestMetadata to browser state
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/request/LoadRequestMetadata.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/LoadRequestState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
Labels: 🛬 needs landing

#8704 Closes #8669: Fix intermittent test failures in RegionManagerTest.
  components/feature/search/src/main/java/mozilla/components/feature/search/region/RegionManager.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/region/RegionMiddleware.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/region/RegionMiddlewareTest.kt
Labels: 🛬 needs landing (squash)

#8689 CODEOWNERS: Update release engineering section.
  CODEOWNERS
Labels: 🛬 needs landing

#8676 For #8593: Allow extensions to be moved to main browser menu.
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenu.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItem.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/WebExtensionPlaceholderMenuItem.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilderTest.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuTest.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItemTest.kt
  components/feature/webcompat-reporter/src/main/java/mozilla/components/feature/webcompat/reporter/WebCompatReporterFeature.kt
Labels: 🛬 needs landing

#8701 For #8700 - Do not tint TrackingProtectionIconView when animatable
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconView.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconViewTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8712 Set version to 60.0.5.
  .buildconfig.yml
Labels: 🛬 needs landing

#8674 For #8565 - New RepostPrompt that inform if users don't proceeed with reload
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/ConfirmDialogFragment.kt
  components/feature/prompts/src/main/res/values/strings.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SwipeRefreshFeature.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SwipeRefreshFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8695 RegionManager: Initialize shared preferences lazily.
  components/feature/search/src/main/java/mozilla/components/feature/search/region/RegionManager.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/region/RegionManagerTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/region/RegionMiddlewareTest.kt
Labels: 🛬 needs landing

#8696 Closes issue #8425: Allow filename to be optional in the ContentDisposition regex
  components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
Labels: 🛬 needs landing

#8716 Closes #8715: Pass and empty map to loadUrl() instead of null.
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
Labels: 🛬 needs landing

#8711 Closes #8653: Send structured java stack trace in crash reports to Socorro
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
  components/support/base/src/main/java/mozilla/components/support/base/ext/Throwable.kt
  components/support/base/src/test/java/mozilla/components/support/base/ext/ThrowableTest.kt
Labels: 🛬 needs landing

#8720 Closes issue #8705: Update REPLACED_UNSAFE_CONTENT with REPLACED_TRACKING_CONTENT
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
Labels: 🛬 needs landing

#8725 Closes #8724: onPageStart/Stop ignore initial loads of about:blank
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
Labels: 🛬 needs landing

#8717 Update to Gradle 6.1.1, Android Gradle plugin 4.0.1, Kotlin 1.4 and Coroutines 1.3.9.
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegateTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegateTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegateTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/matcher/UrlMatcher.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/pipeline/IconResourceComparator.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/Utils.kt
  components/browser/storage-memory/src/main/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorage.kt
  components/browser/storage-sync/build.gradle
  components/concept/menu/src/main/java/mozilla/components/concept/menu/ext/MenuCandidate.kt
  components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_unsupported_item.xml
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt
  components/feature/media/src/main/AndroidManifest.xml
  components/feature/push/src/main/java/mozilla/components/feature/push/Connection.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/WebAppSiteControlsFeature.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/AbstractCrashListActivity.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/CrashListAdapter.kt
  components/lib/crash/src/main/res/layout/mozac_lib_crash_activity_crashlist.xml
  components/lib/jexl/src/main/java/mozilla/components/lib/jexl/ast/nodes.kt
  components/lib/jexl/src/main/java/mozilla/components/lib/jexl/lexer/Lexer.kt
  components/service/digitalassetlinks/src/main/java/mozilla/components/service/digitalassetlinks/AndroidAssetFinder.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ExperimentEvaluator.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/Experiments.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/ExperimentEvaluatorTest.kt
  components/service/firefox-accounts/build.gradle
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sharing/AccountSharing.kt
  components/service/sync-logins/build.gradle
  components/support/migration/build.gradle
  components/support/rustlog/build.gradle
  components/tooling/detekt/build.gradle
  components/tooling/glean-gradle-plugin/build.gradle
  components/tooling/lint/build.gradle
  components/tooling/lint/src/main/java/mozilla/components/tooling/lint/AndroidSrcXmlDetector.kt
  components/tooling/lint/src/main/java/mozilla/components/tooling/lint/ImageViewAndroidTintXmlDetector.kt
  docs/changelog.md
  gradle/wrapper/gradle-wrapper.properties
  samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt
  samples/browser/src/main/res/layout/fragment_add_on_settings.xml
  samples/browser/src/main/res/layout/fragment_browser.xml
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashApplication.kt
  samples/firefox-accounts/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#8723 Issue #8721: Introduce Fragment.consumeFlow() extension function.
  components/lib/state/src/main/java/mozilla/components/lib/state/ext/Fragment.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/FragmentKtTest.kt
Labels: 🛬 needs landing

#8736 Add version upgrades to changelog.
  docs/changelog.md
Labels: 🛬 needs landing

#8753 Update changelog for 63.0.0 release.
  docs/changelog.md
Labels: 🛬 needs landing

#8249 For #7833: Generate concept-menu items for addons
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/Action.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/webextension/ActionTest.kt
  components/feature/addons/build.gradle
  components/feature/addons/src/main/java/mozilla/components/feature/addons/menu/WebExtensionActionMenuCandidate.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/menu/WebExtensionNestedMenuCandidate.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/AddonManagerTest.kt
  components/feature/addons/src/test/java/AddonTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AddonCollectionProviderTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/menu/WebExtensionActionMenuCandidateTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/menu/WebExtensionNestedMenuCandidateTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragmentTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/ExtensionsTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/PermissionsDialogFragmentTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/UnsupportedAddonsAdapterTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/GlobalAddonDependencyProviderTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/NotificationHandlerServiceTest.kt
Labels: <menu>, <web-extensions>, 🛬 needs landing

#8758 Closes #8757 - Expose CompositorController ClearColor as Setting
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8756 Closes #8710: browser-engine-gecko-nightly: Switch to new Loader API.
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
Labels: 🛬 needs landing

#8765 Issue #8721: Use fragment as default lifecylceowner in consumeFlow
  components/lib/state/src/main/java/mozilla/components/lib/state/ext/Fragment.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/FragmentKtTest.kt
Labels: 🛬 needs landing

#8762 Issue #8702: Add actions for showing/hiding bundled search engines.
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/SearchReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/SearchState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/SearchActionTest.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/middleware/SearchMiddleware.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/storage/SearchMetadataStorage.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/ext/BrowserStoreKtTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
Labels: 🛬 needs landing

#8770 Closes #8769 mark shimmed resources as blocked
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8780 Fragment.consumeFrom(), Fragment.consumeFlow(): Use isDetached instead of isAdded.
  components/lib/state/src/main/java/mozilla/components/lib/state/ext/Fragment.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/FragmentKtTest.kt
Labels: 🛬 needs landing

#8783 Issue #8744: Set search engine type when parsing.
  components/feature/search/src/main/java/mozilla/components/feature/search/storage/BundledSearchEnginesStorage.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/storage/CustomSearchEnginesStorage.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/storage/SearchEngineReader.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/storage/BundledSearchEnginesStorageTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/storage/ParseSearchPluginsTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/storage/SearchEngineReaderTest.kt
Labels: 🛬 needs landing

#8795 Fragment.consumeFrom()/consumeFlow(): Explicitly check for activity and view being available.
  components/lib/state/src/main/java/mozilla/components/lib/state/ext/Fragment.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/FragmentKtTest.kt
Labels: 🛬 needs landing

#8642 Renaming blacklist/whitelist aligned with iOS #7557
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/matcher/Safelist.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/matcher/UrlMatcher.kt
  components/browser/engine-system/src/main/res/raw/domain_blocklist.json
  components/browser/engine-system/src/main/res/raw/domain_safelist.json
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/matcher/SafelistTest.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/matcher/UrlMatcherTest.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/matcher/WhiteListTest.kt
  components/feature/addons/src/test/resources/collection.json
  components/feature/addons/src/test/resources/collection_with_empty_values.json
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
  components/feature/webcompat-reporter/README.md
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/matchPatterns.json
  components/lib/crash/README.md
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  docs/changelog.md
  docs/changelog_archive.md
  docs/contribute/updating_tracking_protection_lists.md
Labels: 🛬 needs landing

#8785 Closes #8784 Create download directory when it doesn't exists
  components/browser/state/src/main/java/mozilla/components/browser/state/state/content/DownloadState.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8801 Closes #8800: Allow notifications from web extensions
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegateTest.kt
  components/browser/engine-gecko-nightly/src/test/java/org/mozilla/geckoview/MockWebNotification.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webnotifications/WebNotification.kt
  components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/WebNotificationFeature.kt
  components/feature/webnotifications/src/test/java/mozilla/components/feature/webnotifications/WebNotificationFeatureTest.kt
Labels: 🛬 needs landing

#8802 Closes #7879 Provide an error message when non translation is found for an add-on field
  components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragment.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/PermissionsDialogFragment.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/UnsupportedAddonsAdapter.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/migration/SupportedAddonsWorkerTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragmentTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/ExtensionsTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/PermissionsDialogFragmentTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonDetailsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonSettingsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/InstalledAddonDetailsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/PermissionsDetailsActivity.kt
Labels: 🛬 needs landing

#8812 (Pre-release) Update changelog for 64.0.0 release.
  docs/changelog.md
Labels: 🛬 needs landing

#8814 Closes #3478: Send user locale with crash reports
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SentryServiceTest.kt
Labels: 🛬 needs landing

#8799 Closes #8751: Added methods to rename top site entries
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/db/PinnedSiteDaoTest.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/PinnedSiteStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesUseCases.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/db/PinnedSiteDao.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/TopSitesUseCasesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing (squash)

#8767 Various debug logging for Send Tab functionality
  components/concept/sync/src/main/java/mozilla/components/concept/sync/Devices.kt
  components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/ConstellationObserverTest.kt
  components/lib/push-firebase/src/main/java/mozilla/components/lib/push/firebase/AbstractFirebasePushService.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
Labels: 🛬 needs landing

#8811 Issue #8744: Update search terminology.
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/SearchReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/SearchState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/SearchActionTest.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/ext/BrowserStore.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/middleware/SearchMiddleware.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/storage/SearchMetadataStorage.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/ext/BrowserStoreKtTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
Labels: 🛬 needs landing

#8826 For #8305 - BrowserToolbarBottomBehavior - browserToolbar null check
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehaviorTest.kt
Labels: 🛬 needs landing

#8555 For #8554 - Migrate permissionFeature to KotlinFlow
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/permission/SystemPermissionRequest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/ext/PermissionRequest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/permission/PermissionRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/permission/PermissionRequestTest.kt
  components/feature/sitepermissions/build.gradle
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsDialogFragment.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsDialogFragmentTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsRulesTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing

#8722 Bug 1672759 - Add notifications whenever PRs about GV updates are busted
  taskcluster/ac_taskgraph/transforms/complete.py
  taskcluster/ci/complete/kind.yml
Labels: 🛬 needs landing

#8829 Close #8823 allow data urls to be downloaded using the new gv download api
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8797 Closes #8752 - Use coverUntilFirstPaint() with PreferredColorScheme
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8845 Closes #8660: Crash when launching PWA with open tab
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessor.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessorTest.kt
Labels: 🛬 needs landing

#8844 Fixes 8796 - Telemetry renewal for expiring migration probes
  components/support/migration/metrics.yaml
Labels: 🛬 needs landing (squash)

#8828 Close #8775: Add logging to push verification
  components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt
Labels: 🛬 needs landing

#8344 For #7725 - Log FxaExceptions to our crash reporters if sending to device fails
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Exceptions.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaDeviceConstellationTest.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/UtilsKtTest.kt
Labels: 🛬 needs landing (squash)

#8849 Fixes #8796 - Telemetry renewal for expiring migration probes
  components/support/migration/metrics.yaml
Labels: 🛬 needs landing

#8850 Set version to 60.0.7.
  .buildconfig.yml
Labels: 🛬 needs landing

#8848 Close #8847 Do not show download dialogs when the fragmentManager is destroyed.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing
