Repository mozilla-mobile/android-components, pull requests merged in 2020-07, with the labels that each got.

#7560 Update to App Services 61.0.7
  buildSrc/src/main/java/Dependencies.kt
Labels: 79ReleaseBlocker, 🕵️‍♀️ needs review

#7593 Closes #7290 - Removes unused isAutofillEnabled param
  components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/GeckoLoginStorageDelegate.kt
  components/service/sync-logins/src/test/java/mozilla/components/service/sync/logins/GeckoLoginStorageDelegateTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7601 Closes #7600: Reset content message handler when selected tab changes
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewMiddleware.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewMiddlewareTest.kt
Labels: 🛬 needs landing

#7492 Closes #7483: Fix telemetry foreground service notification string
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SendCrashTelemetryService.kt
  components/lib/crash/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#7605 Revert "Closes #7483: Fix telemetry foreground service notification string"
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SendCrashTelemetryService.kt
  components/lib/crash/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#7602 Refactor components using SessionManager.getEngineSession().
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/usecases/EngineSessionUseCases.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/content/blocking/TrackingProtectionExceptionStorage.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/TrackingProtectionUseCasesTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#7607 Closes #7606 Consume contentPermissionRequest only when loading new site
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
Labels: 🕵️‍♀️ needs review

#7608 Uplift Resources.getSpanned
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/res/Resources.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/res/ResourcesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7591 For #7592 - Adds Login Exception Storage Feature
  .buildconfig.yml
  components/feature/logins/README.md
  components/feature/logins/build.gradle
  components/feature/logins/proguard-rules.pro
  components/feature/logins/schemas/mozilla.components.feature.logins.exceptions.db.LoginExceptionDatabase/1.json
  components/feature/logins/src/androidTest/java/mozilla/components/feature/logins/LoginExceptionStorageTest.kt
  components/feature/logins/src/androidTest/java/mozilla/components/feature/logins/exceptions/db/LoginExceptionDaoTest.kt
  components/feature/logins/src/main/AndroidManifest.xml
  components/feature/logins/src/main/java/mozilla/components/feature/logins/exceptions/LoginException.kt
  components/feature/logins/src/main/java/mozilla/components/feature/logins/exceptions/LoginExceptionStorage.kt
  components/feature/logins/src/main/java/mozilla/components/feature/logins/exceptions/adapter/LoginExceptionAdapter.kt
  components/feature/logins/src/main/java/mozilla/components/feature/logins/exceptions/db/LoginExceptionDao.kt
  components/feature/logins/src/main/java/mozilla/components/feature/logins/exceptions/db/LoginExceptionDatabase.kt
  components/feature/logins/src/main/java/mozilla/components/feature/logins/exceptions/db/LoginExceptionEntity.kt
  components/feature/logins/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/LoginExceptions.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/LoginDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/PromptDialogFragment.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_prompt_login_prompt.xml
  components/feature/prompts/src/main/res/values/strings.xml
  docs/changelog.md
  taskcluster/ci/test/kind.yml
Labels: 🕵️‍♀️ needs review

#7633 Docs update (20200707-121417) [ci skip]
  docs/api/mozilla.components.support.ktx.android.content.res/get-spanned.md
  docs/api/mozilla.components.support.ktx.android.content.res/index.md
  docs/api/mozilla.components.support.ktx.android.content.res/locale.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/index.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/is-same-origin-as.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/sanitize-u-r-l.md
Labels: 🛬 needs landing

#7635 Update changelog for 49.0.0 release
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#7277 #5178 last used tabs property
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/selector/SelectorsKtTest.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorage.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorageTest.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
Labels: ✏️ needs changes

#7615 Closes #6356: Install built-in extensions using GV extension controller
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/icons/src/main/assets/extensions/browser-icons/manifest.json
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionRuntime.kt
  components/feature/accounts/src/main/assets/extensions/fxawebchannel/manifest.json
  components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FxaWebChannelFeature.kt
  components/feature/accounts/src/test/java/mozilla/components/feature/accounts/FxaWebChannelFeatureTest.kt
  components/feature/addons/src/test/java/AddonManagerTest.kt
  components/feature/p2p/src/main/assets/extensions/p2p/manifest.json
  components/feature/p2p/src/main/java/mozilla/components/feature/p2p/P2PFeature.kt
  components/feature/p2p/src/test/java/mozilla/components/feature/p2p/P2PFeatureTest.kt
  components/feature/readerview/src/main/assets/extensions/readerview/manifest.json
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewMiddleware.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
  components/feature/webcompat-reporter/src/main/java/mozilla/components/feature/webcompat/reporter/WebCompatReporterFeature.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt
  components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionController.kt
  components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionControllerTest.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
  samples/browser/src/geckoNightly/java/org/mozilla/samples/browser/Components.kt
  samples/browser/src/main/assets/extensions/borderify/manifest.json
  samples/browser/src/main/assets/extensions/test/manifest.json
Labels: do not land, 🕵️‍♀️ needs review

#7589 For #7588: Rename search context menu action
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/DefaultSelectionActionDelegate.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ext/DefaultSelectionActionDelegate.kt
  components/feature/contextmenu/src/main/res/values/strings.xml
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/DefaultSelectionActionDelegateTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
Labels: ✏️ needs changes

#7654 GeckoView update (beta) (20200708-141442)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7653 GeckoView update (nightly) (20200708-141157)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7575 Just run release tests on components
  taskcluster/ci/build/kind.yml
Labels: 🤖 automation

#7630 Switch to groovy in buildSrc
  buildSrc/build.gradle
Labels: 🕵️‍♀️ needs review, 🤖 automation

#7650 Issue #7647: Add SessionFeature.release() to allow app to stop rendering engine sessions and release the current one.
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionFeature.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7662 GeckoView update (release) (20200709-140432)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7632 Closes #7626: Add download log entries
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
Labels: 🕵️‍♀️ needs review

#7587 For #7586: Add email & call actions to context menu
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/selection/SelectionActionDelegate.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/DefaultSelectionActionDelegate.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ext/DefaultSelectionActionDelegate.kt
  components/feature/contextmenu/src/main/res/values/strings.xml
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/DefaultSelectionActionDelegateTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt
  components/support/ktx/src/main/res/values/strings.xml
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/ContextTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
Labels: 🕵️‍♀️ needs review

#7668 Closes #7664: Add EngineSession.goToHistoryIndex to jump to a specifi…
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
  docs/changelog.md
Labels: ✏️ needs changes

#7628 For #7627 - Add hasRegionCached() to LocationService
  components/service/location/src/main/java/mozilla/components/service/location/LocationService.kt
  components/service/location/src/main/java/mozilla/components/service/location/MozillaLocationService.kt
  docs/changelog.md
Labels: 79ReleaseBlocker

#7674 GeckoView update (beta) (20200710-140444)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7675 GeckoView update (nightly) (20200710-140440)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7639 Closes #7637: Add allowed redirect URL list for AppLinksInterceptor
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
Labels: 🛬 needs landing

#7623 Issue #7529: Add ContainerState to BrowserState
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContainerReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ContainerState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/ContainerActionTest.kt
  components/feature/containers/build.gradle
  components/feature/containers/src/androidTest/java/mozilla/components/feature/containers/ContainerStorageTest.kt
  components/feature/containers/src/androidTest/java/mozilla/components/feature/containers/db/ContainerDaoTest.kt
  components/feature/containers/src/main/java/mozilla/components/feature/containers/Container.kt
  components/feature/containers/src/main/java/mozilla/components/feature/containers/ContainerStorage.kt
  components/feature/containers/src/main/java/mozilla/components/feature/containers/adapter/ContainerAdapter.kt
  components/feature/containers/src/main/java/mozilla/components/feature/containers/db/ContainerDatabase.kt
  components/feature/containers/src/main/java/mozilla/components/feature/containers/db/ContainerEntity.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#7676 For #7614: Simplify app link query for external application
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing

#7681 Closes #7680: Allow new window onLoadRequest to be intercepted
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
Labels: 🛬 needs landing

#7701 Set version to 51.0.0
  .buildconfig.yml
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#7708 GeckoView update (beta) (20200714-141113)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7439 Closes #7384: Truncated add-on title in AddonsManagerAdapter
  components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
Labels: 🕵️‍♀️ needs review

#7631 Turn on Gradle configure on demand
  gradle.properties
Labels: 🤖 automation

#7693 Update release checklist to include minor releases
  docs/contribute/release_checklist.md
Labels: 🕵️‍♀️ needs review

#7503 For #7337: Prevent text in <ul> tags being read twice by screen readers.
  components/browser/errorpages/src/main/java/mozilla/components/browser/errorpages/ErrorPages.kt
  components/browser/errorpages/src/test/java/mozilla/components/browser/errorpages/ErrorPagesTest.kt
Labels: 🕵️‍♀️ needs review

#7714 Closes #7710: Stop intercepting redirect with subframe load request without user action
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/request/RequestInterceptor.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/request/RequestInterceptorTest.kt
  components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeature.kt
  components/feature/accounts/src/test/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeatureTest.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppInterceptor.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppInterceptorTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/request/SampleRequestInterceptor.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/request/SampleUrlEncodedRequestInterceptor.kt
Labels: 🛬 needs landing

#7713 Issue #7712: Add flag for filtering exact matches from SearchSuggestionProvider and add SearchActionProvider.
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchActionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/AwesomeBarFeatureTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchActionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#7744 GeckoView update (nightly) (20200716-140605)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7740 Remove more properties from Session.
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/SessionExtensions.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SelectionAwareSessionObserverTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuUseCases.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuFeatureTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#7749 Fix Digital Asset Links API URL
  components/service/digitalassetlinks/src/main/java/mozilla/components/service/digitalassetlinks/api/DigitalAssetLinksApi.kt
  components/service/digitalassetlinks/src/test/java/mozilla/components/service/digitalassetlinks/api/DigitalAssetLinksApiTest.kt
Labels: <customtabs>

#7756 GeckoView update (nightly) (20200717-140306)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7755 GeckoView update (beta) (20200717-140307)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7758 Closes #7757: Add blob in default engine supported scheme
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing

#7759 Issue #7753: EngineViewPresenter: Temporarily disable releasing of engine session.
  components/feature/session/src/main/java/mozilla/components/feature/session/engine/EngineViewPresenter.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionFeatureTest.kt
Labels: 🕵️‍♀️ needs review

#7666 Closes #7665: Add support for converting TrackingProtectionPolicy to ContentBlocking.Setting
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7774 GeckoView update (nightly) (20200720-140538)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7746 Issue #7712: SearchActionProvider: Pass in suspending function instead of a Deferred<SearchEngine>
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchActionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchActionProviderTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#7273 For #4637 - Query manifests with share targets
  components/feature/pwa/schemas/mozilla.components.feature.pwa.db.ManifestDatabase/3.json
  components/feature/pwa/src/androidTest/java/mozilla/components/feature/pwa/db/ManifestDatabaseMigrationTest.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ManifestStorage.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/db/ManifestDao.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/db/ManifestDatabase.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/db/ManifestEntity.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ManifestStorageTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7796 GeckoView update (nightly) (20200721-140513)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7799 Closes #7777: Expose l10n strings by default
  l10n.toml
Labels: 🕵️‍♀️ needs review

#7801 Closes #7782: Fix crashes in addon installation dialog
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragment.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragmentTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt
Labels: 🕵️‍♀️ needs review

#7809 Remove ImageLoader.loadIntoView extension function
  components/support/images/src/main/java/mozilla/components/support/images/ext/ImageLoader.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#7794 Public Suffix List update (20200721-140512)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#7819 GeckoView update (nightly) (20200722-140318)
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/docs/metrics.md
Labels: 🛬 needs landing

#7828 GeckoView update (nightly) (20200723-141326)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7786 Close #7079: Decouple BrowserTabsTray from TabsAdapter
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/BrowserTabsTray.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabsAdapter.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabsTrayStyling.kt
  components/browser/tabstray/src/main/res/values/attrs.xml
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/BrowserTabsTrayTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/DefaultTabViewHolderTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabTouchCallbackTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabsAdapterTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/TabsTrayFragment.kt
  samples/browser/src/main/res/layout/fragment_tabstray.xml
Labels: 🕵️‍♀️ needs review

#7804 For #7788 - Cache request to be reused after storage permission is granted
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FilePickerTest.kt
Labels: 🕵️‍♀️ needs review

#7834 Remove deprecated android gradle flag
  components/service/glean/gradle.properties
  components/support/locale/gradle.properties
  gradle.properties
  samples/firefox-accounts/gradle.properties
  samples/sync-logins/gradle.properties
  samples/sync/gradle.properties
Labels: 🛬 needs landing

#7825 Issue #7766: BrowserIcons: Add API for clearing data.
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/IconDiskCache.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#7858 GeckoView update (nightly) (20200727-140336)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7807 Closes #7797: Strip common subdomain before checking if the new URL is in the same domain
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/request/RequestInterceptor.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/request/RequestInterceptorTest.kt
  components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeature.kt
  components/feature/accounts/src/test/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeatureTest.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppInterceptor.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppInterceptorTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/request/SampleRequestInterceptor.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/request/SampleUrlEncodedRequestInterceptor.kt
Labels: 🛬 needs landing

#7883 Update changelog for 52.0.0 release.
  docs/changelog.md
Labels: 🛬 needs landing

#7885 Set version to 53.0.0
  .buildconfig.yml
Labels: 🕵️‍♀️ needs review

#7909 Issue #7876: Remove info logging for SearchEngineMigrationResult.
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
Labels: 🛬 needs landing

#7912 Closes #7893: Prevent crash in QrFragment on devices without camera
  components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt
  components/feature/qr/src/main/res/layout/fragment_layout.xml
  components/feature/qr/src/main/res/values/strings.xml
  components/feature/qr/src/test/java/mozilla/components/feature/qr/QrFragmentTest.kt
Labels: R79

#7915 Make sure device finalization succeeds before proceeding to postAuth
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/State.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/manager/FxaStateMatrixTest.kt
Labels: R79

#7919 Closes #7917 - Update all 3 telemetry options with FHR value in migra…
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecSettingsMigrator.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecSettingsMigrationTest.kt
Labels: R79

#7911 For #7761: Rename Queued Downloads And Persist
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/DownloadStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/DownloadActionTest.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/AndroidDownloadManager.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/AndroidDownloadManagerTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/FetchDownloadManagerTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7927 Public Suffix List update (20200730-140250)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#7936 Closes #7840: Menu is only long clickable if listener is set
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuItemToolbar.kt
  docs/changelog.md
Labels: <menu>

#7776 RFC: Adding a concept-base component for basic interfaces needed by multiple components.
  docs/contributing.md
  docs/rfcs/0003-concept-base-component.md
Labels: RFC

#7940 GeckoView update (beta) (20200731-141012)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing
