Repository mozilla-mobile/android-components, pull requests merged in 2020-08, with the labels that each got.

#7955 Closes #7954 - Ensure all prompt types override onCancel
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/ChoiceDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/ConfirmDialogFragment.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/ChoiceDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/ConfirmDialogFragmentTest.kt
Labels: 🕵️‍♀️ needs review

#7967 GeckoView update (nightly) (20200804-141027)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7562 Closes #6910 - Add custom check run text
  build.gradle
  buildSrc/src/main/java/GithubDetailsTask.kt
  taskcluster/ac_taskgraph/transforms/build.py
  taskcluster/ci/build/kind.yml
  taskcluster/ci/lint/kind.yml
Labels: 🤖 automation

#7962 Closes #7961 - Hide keyboard on menu button clicks
  components/browser/menu/src/main/java/mozilla/components/browser/menu/view/MenuButton.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/view/MenuButton2.kt
Labels: 🕵️‍♀️ needs review

#7982 Docs update (20200805-121434) [ci skip]
  docs/api/mozilla.components.browser.menu.view/-menu-button/dismiss-menu.md
  docs/api/mozilla.components.browser.menu.view/-menu-button/get-orientation.md
  docs/api/mozilla.components.browser.menu.view/-menu-button/index.md
  docs/api/mozilla.components.browser.menu.view/-menu-button/invalidate-browser-menu.md
  docs/api/mozilla.components.browser.menu.view/-menu-button/menu-builder.md
  docs/api/mozilla.components.browser.menu.view/-menu-button/menu-controller.md
  docs/api/mozilla.components.browser.menu.view/-menu-button/on-click.md
  docs/api/mozilla.components.browser.menu.view/-menu-button/on-dismiss.md
  docs/api/mozilla.components.browser.menu.view/-menu-button/on-show.md
  docs/api/mozilla.components.browser.menu.view/-menu-button/set-color-filter.md
  docs/api/mozilla.components.browser.menu.view/-menu-button/set-effect.md
  docs/api/mozilla.components.browser.menu.view/-menu-button/set-highlight.md
  docs/api/mozilla.components.browser.menu2.view/-menu-button2/index.md
  docs/api/mozilla.components.browser.menu2.view/-menu-button2/menu-controller.md
  docs/api/mozilla.components.browser.menu2.view/-menu-button2/on-click.md
  docs/api/mozilla.components.browser.menu2.view/-menu-button2/set-color-filter.md
  docs/api/mozilla.components.browser.menu2.view/-menu-button2/set-effect.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-init-.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/gravity.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/index.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/positive-button-background-color.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/positive-button-radius.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/positive-button-text-color.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/should-width-match-parent.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/index.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/on-download-stopped.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/on-need-to-request-permissions.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/on-permissions-result.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/start.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/stop.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/try-again.md
Labels: 🛬 needs landing

#7986 GeckoView update (nightly) (20200805-140537)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7985 GeckoView update (beta) (20200805-140531)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7999 Add more debuggable information for the Display already acquired exception
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
Labels: 🛬 needs landing

#7977 Remove SimpleBrowserMenuHighlightableItem.itemType
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/SimpleBrowserMenuHighlightableItem.kt
  docs/changelog.md
Labels: ⌨️ code

#7987 Bug 1645844 - Allow the webcompat-reporter to provide a product name to the reporting backend.
  components/feature/webcompat-reporter/README.md
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/background.js
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json
  components/feature/webcompat-reporter/src/main/java/mozilla/components/feature/webcompat/reporter/WebCompatReporterFeature.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#7934 Closes #7933: Add context menu handling for mailto URL
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/main/res/values/strings.xml
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/integration/ContextMenuIntegration.kt
Labels: 🕵️‍♀️ needs review

#8004 For #7992 - Don't show "Download link" for webpages links
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8021 Closes #8020: Log response code when failed to send Socorro crash report
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
Labels: 🕵️‍♀️ needs review

#7870 Closes #7869: Load a non-mobile url when desktop mode is toggled on
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
Labels: 🕵️‍♀️ needs review

#8048 Fix favicon widget border
  components/ui/widgets/src/main/res/drawable/mozac_widget_favicon_background.xml
Labels: 🛬 needs landing

#7838 For #7836: Refine add-ons badge design
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItem.kt
  components/browser/menu/src/main/res/drawable/rounded_corner.xml
  components/browser/menu/src/main/res/layout/mozac_browser_menu_web_extension.xml
  components/browser/menu/src/main/res/values/dimens.xml
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItemTest.kt
Labels: 🛬 needs landing

#7923 Closes #4772: Add support allowing third party apps to download content
  components/feature/downloads/build.gradle
  components/feature/downloads/src/main/AndroidManifest.xml
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ui/DownloadAppChooserDialog.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ui/DownloaderApp.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ui/DownloaderAppAdapter.kt
  components/feature/downloads/src/main/res/layout/mozac_download_app_list_item.xml
  components/feature/downloads/src/main/res/layout/mozac_downloader_chooser_prompt.xml
  components/feature/downloads/src/main/res/values/strings.xml
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/ui/DownloadAppChooserDialogTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/ui/DownloaderAppAdapterTest.kt
  components/support/utils/build.gradle
  components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/BrowsersTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8085 GeckoView update (nightly) (20200810-140944)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#8093 GeckoView update (nightly) (20200811-141018)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#8092 Docs update (20200811-121719) [ci skip]
  docs/api/mozilla.components.feature.app.links/-app-links-interceptor/index.md
  docs/api/mozilla.components.feature.app.links/-app-links-interceptor/on-load-request.md
Labels: 🛬 needs landing

#7842 For #7839 - Stop overriding files with same name from subfolders when downloading
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🕵️‍♀️ needs review

#8094 Issue #7808 Expose cookie purging setting
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8110 Docs update (20200813-121348) [ci skip]
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-high-level/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-high-level/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-addons-exception/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-addons-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-bookmarks-exception/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-bookmarks-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-fxa-exception/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-fxa-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-gecko-exception/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-gecko-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-history-exception/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-history-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-logins-exception/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-logins-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-open-tabs-exception/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-open-tabs-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-pinned-sites-exception/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-pinned-sites-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-search-engine-exception/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-search-engine-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-settings-exception/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-migrate-settings-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-telemetry-identifier-exception/-init-.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/-telemetry-identifier-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator-exception/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/build.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-addons.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-bookmarks.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-fxa.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-gecko.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-history.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-logins.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-open-tabs.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-search-engine.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-settings.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/-builder/migrate-telemetry-identifiers.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/index.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/migrate-async.md
  docs/api/mozilla.components.support.migration/-fennec-migrator/start-migration-if-needed.md
  docs/api/mozilla.components.support.migration/index.md
Labels: 🛬 needs landing

#8112 GeckoView update (nightly) (20200813-140947)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#8118 Update GeckoView (release) to 79.0.20200813192915.
  buildSrc/src/main/java/Gecko.kt
Labels: 🕵️‍♀️ needs review

#8104 Closes issue #7983: Generate a file name when the content provider doesn't provide one.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/net/Uri.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/net/UriTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8133 Public Suffix List update (20200817-140521)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#8126 Closes #8122: Do not redirect to market app if app is already installed
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/pm/PackageManager.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/pm/PackageManagerTest.kt
Labels: 🕵️‍♀️ needs review

#7931 RFC: Introduce a Top Sites Feature
  docs/rfcs/0006-top-sites-feature.md
Labels: RFC

#8139 Docs update (20200818-120916) [ci skip]
  docs/api/index.md
  docs/api/mozilla.components.browser.storage.sync/-a-u-t-o-c-o-m-p-l-e-t-e_-s-o-u-r-c-e_-n-a-m-e.md
  docs/api/mozilla.components.browser.storage.sync/-places-bookmarks-storage/index.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/-init-.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/delete-everything.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/delete-visit.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/delete-visits-between.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/delete-visits-for.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/delete-visits-since.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/get-autocomplete-suggestion.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/get-detailed-visits.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/get-handle.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/get-suggestions.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/get-top-frecent-sites.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/get-visited.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/get-visits-paginated.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/import-from-fennec.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/index.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/logger.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/prune.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/record-observation.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/record-visit.md
  docs/api/mozilla.components.browser.storage.sync/-places-history-storage/sync.md
  docs/api/mozilla.components.browser.storage.sync/-places-storage/-init-.md
  docs/api/mozilla.components.browser.storage.sync/-places-storage/cleanup.md
  docs/api/mozilla.components.browser.storage.sync/-places-storage/crash-reporter.md
  docs/api/mozilla.components.browser.storage.sync/-places-storage/handle-places-exceptions.md
  docs/api/mozilla.components.browser.storage.sync/-places-storage/ignore-url-exceptions.md
  docs/api/mozilla.components.browser.storage.sync/-places-storage/index.md
  docs/api/mozilla.components.browser.storage.sync/-places-storage/logger.md
  docs/api/mozilla.components.browser.storage.sync/-places-storage/run-maintenance.md
  docs/api/mozilla.components.browser.storage.sync/-places-storage/sync-and-handle-exceptions.md
  docs/api/mozilla.components.browser.storage.sync/-places-storage/warm-up.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/-get-app-link-redirect/index.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/-get-app-link-redirect/invoke.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/-open-app-link-redirect/index.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/-open-app-link-redirect/invoke.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/app-link-redirect-include-install.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/app-link-redirect.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/index.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/intercepted-app-link-redirect.md
  docs/api/mozilla.components.feature.app.links/-app-links-use-cases/open-app-link.md
  docs/api/mozilla.components.support.ktx.android.content.pm/index.md
  docs/api/mozilla.components.support.ktx.android.content.pm/is-package-installed.md
  docs/api/mozilla.components.support.ktx.android.net/get-file-extension.md
  docs/api/mozilla.components.support.ktx.android.net/get-file-name.md
  docs/api/mozilla.components.support.ktx.android.net/host-without-common-prefixes.md
  docs/api/mozilla.components.support.ktx.android.net/index.md
  docs/api/mozilla.components.support.ktx.android.net/is-http-or-https.md
  docs/api/mozilla.components.support.ktx.android.net/is-in-scope.md
  docs/api/mozilla.components.support.ktx.android.net/is-under-private-app-directory.md
  docs/api/mozilla.components.support.ktx.android.net/same-origin-as.md
  docs/api/mozilla.components.support.ktx.android.net/same-scheme-and-host-as.md
  docs/api/mozilla.components.support.utils/-web-u-r-l-finder/best-web-u-r-l.md
  docs/api/mozilla.components.support.utils/-web-u-r-l-finder/index.md
  docs/api/mozilla.components.support.utils/-web-u-r-l-finder/is-web-u-r-l.md
  docs/api/package-list
Labels: 🛬 needs landing

#8145 GeckoView update (nightly) (20200818-140725)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#8142 Update AC release version to 55.0.0
  .buildconfig.yml
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8144 Closes #8143: Pass source URL in web notification load icon request
  components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/NativeNotificationBridge.kt
  components/feature/webnotifications/src/test/java/mozilla/components/feature/webnotifications/NativeNotificationBridgeTest.kt
Labels: 🕵️‍♀️ needs review

#8141 Closes #8140: Encode Socorro server URL correctly
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
Labels: 🛬 needs landing

#8117 Close #8067: Add usage documentation on how to setup feature-thumbnails
  components/browser/thumbnails/README.md
Labels: 🕵️‍♀️ needs review

#8116 Close #8115: Add onTabsUpdated to TabsTray.Observer
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabsAdapter.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/ext/TabsAdapter.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabsAdapterTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/ext/TabsAdapterKtTest.kt
  components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/TabsTray.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8155 Docs update (20200819-120618) [ci skip]
  docs/api/index.md
  docs/api/mozilla.components.browser.tabstray.ext/do-on-tabs-updated.md
  docs/api/mozilla.components.browser.tabstray.ext/index.md
  docs/api/mozilla.components.browser.tabstray/-tabs-adapter/index.md
  docs/api/mozilla.components.browser.tabstray/-tabs-adapter/on-tabs-changed.md
  docs/api/mozilla.components.browser.tabstray/-tabs-adapter/on-tabs-inserted.md
  docs/api/mozilla.components.browser.tabstray/-tabs-adapter/on-tabs-moved.md
  docs/api/mozilla.components.browser.tabstray/-tabs-adapter/on-tabs-removed.md
  docs/api/mozilla.components.concept.tabstray/-tabs-tray/-observer/index.md
  docs/api/mozilla.components.concept.tabstray/-tabs-tray/-observer/on-tab-closed.md
  docs/api/mozilla.components.concept.tabstray/-tabs-tray/-observer/on-tab-selected.md
  docs/api/mozilla.components.concept.tabstray/-tabs-tray/-observer/on-tabs-updated.md
  docs/api/mozilla.components.concept.tabstray/-tabs-tray/as-view.md
  docs/api/mozilla.components.concept.tabstray/-tabs-tray/on-tabs-changed.md
  docs/api/mozilla.components.concept.tabstray/-tabs-tray/on-tabs-inserted.md
  docs/api/mozilla.components.concept.tabstray/-tabs-tray/on-tabs-moved.md
  docs/api/mozilla.components.concept.tabstray/-tabs-tray/on-tabs-removed.md
  docs/api/mozilla.components.concept.tabstray/-tabs-tray/update-tabs.md
  docs/api/mozilla.components.feature.tabs.tabstray/-tabs-tray-interactor/index.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/create-crash-report-url.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/id.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/index.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/name.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/report.md
  docs/api/package-list
Labels: 🛬 needs landing

#8055 For #8054 - Unify addons icons design with the one for favicons
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt
  components/feature/addons/build.gradle
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/CustomViewHolder.kt
  components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_unsupported_item.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  components/ui/icons/src/main/res/drawable/mozac_ic_addons_extensions.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_extensions.xml
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🧙‍♂️ Needs UX Feedback

#8152 Closes issue #8042: Intermittent failing test in AbstractFetchDownloadService
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadNotificationTest.kt
Labels: 🛬 needs landing

#8165 Docs update (20200820-120639) [ci skip]
  docs/api/mozilla.components.service.fxa/-firefox-account/-init-.md
  docs/api/mozilla.components.service.fxa/-firefox-account/auth-error-detected.md
  docs/api/mozilla.components.service.fxa/-firefox-account/authorize-o-auth-code-async.md
  docs/api/mozilla.components.service.fxa/-firefox-account/begin-o-auth-flow-async.md
  docs/api/mozilla.components.service.fxa/-firefox-account/begin-pairing-flow-async.md
  docs/api/mozilla.components.service.fxa/-firefox-account/check-authorization-status-async.md
  docs/api/mozilla.components.service.fxa/-firefox-account/close.md
  docs/api/mozilla.components.service.fxa/-firefox-account/complete-o-auth-flow-async.md
  docs/api/mozilla.components.service.fxa/-firefox-account/copy-from-session-token-async.md
  docs/api/mozilla.components.service.fxa/-firefox-account/device-constellation.md
  docs/api/mozilla.components.service.fxa/-firefox-account/disconnect-async.md
  docs/api/mozilla.components.service.fxa/-firefox-account/from-j-s-o-n-string.md
  docs/api/mozilla.components.service.fxa/-firefox-account/get-access-token-async.md
  docs/api/mozilla.components.service.fxa/-firefox-account/get-connection-success-u-r-l.md
  docs/api/mozilla.components.service.fxa/-firefox-account/get-current-device-id.md
  docs/api/mozilla.components.service.fxa/-firefox-account/get-pairing-authority-u-r-l.md
  docs/api/mozilla.components.service.fxa/-firefox-account/get-profile-async.md
  docs/api/mozilla.components.service.fxa/-firefox-account/get-session-token.md
  docs/api/mozilla.components.service.fxa/-firefox-account/get-token-server-endpoint-u-r-l.md
  docs/api/mozilla.components.service.fxa/-firefox-account/index.md
  docs/api/mozilla.components.service.fxa/-firefox-account/is-in-migration-state.md
  docs/api/mozilla.components.service.fxa/-firefox-account/migrate-from-session-token-async.md
  docs/api/mozilla.components.service.fxa/-firefox-account/register-persistence-callback.md
  docs/api/mozilla.components.service.fxa/-firefox-account/retry-migrate-from-session-token-async.md
  docs/api/mozilla.components.service.fxa/-firefox-account/to-j-s-o-n-string.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/-init-.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/ensure-capabilities-async.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/index.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/init-device-async.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/poll-for-commands-async.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/process-raw-event-async.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/refresh-devices-async.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/register-device-observer.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/send-command-to-device-async.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/set-device-name-async.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/set-device-push-subscription-async.md
  docs/api/mozilla.components.service.fxa/-fxa-device-constellation/state.md
  docs/api/mozilla.components.service.fxa/-persist-callback.md
  docs/api/mozilla.components.support.sync.telemetry/-m-a-x_-f-a-i-l-u-r-e_-r-e-a-s-o-n_-l-e-n-g-t-h.md
  docs/api/mozilla.components.support.sync.telemetry/-sync-telemetry/index.md
  docs/api/mozilla.components.support.sync.telemetry/-sync-telemetry/process-bookmarks-ping.md
  docs/api/mozilla.components.support.sync.telemetry/-sync-telemetry/process-fxa-telemetry.md
  docs/api/mozilla.components.support.sync.telemetry/-sync-telemetry/process-history-ping.md
  docs/api/mozilla.components.support.sync.telemetry/-sync-telemetry/process-logins-ping.md
  docs/api/mozilla.components.support.sync.telemetry/-sync-telemetry/process-sync-telemetry.md
Labels: 🛬 needs landing

#8173 Un-break the report site issue feature by removing no-longer-needed c…
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/background.js
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/browserInfo.js
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/browserInfo.json
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json
Labels: 🕵️‍♀️ needs review

#8204 Public Suffix List update (20200824-140606)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#8203 Closes issue #8202: Increase downloadJobState.currentBytesCopied in copyInChunks.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8218 Dismiss previous download dialogs when navigating away
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
Labels: 🕵️‍♀️ needs review

#8205 Fix failing toolbar menu test
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
Labels: 🕵️‍♀️ needs review

#8137 Closes #7204: Allow to substitute GeckoView in all projects.
  build.gradle
  samples/browser/build.gradle
Labels: 🕵️‍♀️ needs review

#7281 Closes #5250 - Add monochrome purpose support
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/WebAppManifest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/parser/WebAppManifestIconParser.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/manifest/WebAppManifestParserTest.kt
  components/concept/engine/src/test/resources/manifests/purpose_array.json
  components/concept/engine/src/test/resources/manifests/unusual.json
  components/feature/pwa/build.gradle
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/SiteControlsBuilder.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/WebAppSiteControlsFeature.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/SessionKtTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/WebAppManifestKtTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/feature/WebAppSiteControlsFeatureTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserFragment.kt
Labels: 🛬 needs landing

#8224 For #8223: Fix compound drawable position for RTL.
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuImageSwitch.kt
Labels: 🛬 needs landing

#8213 Avoid double layout in WidgetSiteItemView
  components/ui/widgets/src/main/res/layout/mozac_widget_site_item.xml
Labels: 🛬 needs landing

#8227 Update changelog for AC release 56.0.0
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8221 Merge day!
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko/src/androidTest/java/mozilla/components/browser/engine/gecko/fetch/geckoview/GeckoViewFetchTestCases.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/profiler/Profiler.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
Labels: 🕵️‍♀️ needs review

#8229 Update AC version to 57.0.0
  .buildconfig.yml
Labels: 🛬 needs landing

#8149 For mozilla-mobile/fenix#9056: Search with custom tab
  components/feature/search/src/main/java/mozilla/components/feature/search/BrowserStoreSearchAdapter.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/SearchFeature.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/BrowserStoreSeachAdapterTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/SearchFeatureTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: <search>, 🕵️‍♀️ needs review

#8233 Close #8232: Remove firebase-core dependency from lib-push-firebase
  buildSrc/src/main/java/Dependencies.kt
  components/lib/push-firebase/build.gradle
  docs/changelog.md
Labels: 🛬 needs landing

#8198 For #7134 - Dismiss the current select login prompt request in LoginPicker
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/autofill/GeckoLoginDelegateWrapper.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/LoginPicker.kt
  components/feature/prompts/src/main/res/layout/login_selection_list_item.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_login_multiselect_view.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
Labels: 🕵️‍♀️ needs review

#8239 Update GeckoView (Beta) to 81.0.20200825191644.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
Labels: 🛬 needs landing

#8243 Closes #8242: Keep latest breadcrumbs
  components/lib/crash/src/main/java/mozilla/components/lib/crash/BreadcrumbPriorityQueue.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/ExceptionHandler.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/BreadcrumbPriorityQueueTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
  components/support/base/src/main/java/mozilla/components/support/base/crash/Breadcrumb.kt
Labels: 🕵️‍♀️ needs review

#7795 Issue #6429: Add container page action icon in the browser toolbar
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ContainerToolbarAction.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ContainerToolbarFeature.kt
  components/feature/toolbar/src/main/res/layout/mozac_feature_toolbar_container_action_layout.xml
  components/feature/toolbar/src/main/res/values/colors.xml
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ContainerToolbarActionTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ContainerToolbarFeatureTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#7705 For #7700 - Use the website favicon in save login dialog
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/SaveLoginDialogFragment.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_prompt_save_login_prompt.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/SaveLoginDialogFragmentTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8257 Update GeckoView Nightly to 82.0.20200826032437.
  buildSrc/src/main/java/Gecko.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webnotifications/WebNotification.kt
  components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/NativeNotificationBridge.kt
  components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/WebNotificationFeature.kt
Labels: 🕵️‍♀️ needs review

#8262 GeckoView update (nightly) (20200827-140422)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#8266 Closes #8264: Pass copy of breadcrumbs to crash reporting services
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/ExceptionHandler.kt
Labels: 🕵️‍♀️ needs review

#8186 For #8185 - Add a new VerticalSwipeRefreshLayout
  components/ui/widgets/build.gradle
  components/ui/widgets/src/main/java/mozilla/components/ui/widgets/VerticalSwipeRefreshLayout.kt
  components/ui/widgets/src/test/java/mozilla/components/ui/widgets/TestUtils.kt
  components/ui/widgets/src/test/java/mozilla/components/ui/widgets/VerticalSwipeRefreshLayoutTest.kt
  components/ui/widgets/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8282 Add download ids to log statements
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
Labels: 🛬 needs landing

#8274 Closes #8271: Fix DownloadMiddleware intermittent test
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt
Labels: 🕵️‍♀️ needs review

#8280 Public Suffix List update (20200828-140553)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#8244 Closes #8240: Only dismiss prompts that are not already dismissed
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8250 Close #7476: Persists lastAccess to SnapshotSerializer
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineMiddleware.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/middleware/LastAccessMiddleware.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/BrowserStateSerializer.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/SnapshotSerializer.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/middleware/LastAccessMiddlewareTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/storage/SnapshotSerializerTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/LastAccessReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/LastAccessActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/selector/SelectorsKtTest.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
  docs/changelog.md
Labels: do not land

#8293 Closes #8292: DownloadMiddleware uses context.dispatch on wrong thread
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
Labels: 🛬 needs landing

#8295 GeckoView update (nightly) (20200831-140310)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#8294 GeckoView update (beta) (20200831-140310)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#8275 Closes #8273: Set timestamp of crash reports to when crash occurred
  components/lib/crash/src/main/java/mozilla/components/lib/crash/Crash.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/ExceptionHandler.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/NativeCodeCrashTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/UncaughtExceptionCrashTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/notification/CrashNotificationTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/prompt/CrashReporterActivityTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/GleanCrashReporterServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SendCrashReportServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SendCrashTelemetryServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SentryServiceTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review
