Repository mozilla-mobile/android-components, pull requests merged in 2020-04, with the labels that each got.

#6490 Closes #6287: Add Not yet available string
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
Labels: 🛬 needs landing

#6483 Make GeckoViewFetchTestCases pass in automation
  components/browser/engine-gecko-nightly/src/androidTest/java/mozilla/components/browser/engine/gecko/fetch/geckoview/GeckoViewFetchTestCases.kt
  components/tooling/fetch-tests/src/main/java/mozilla/components/tooling/fetch/tests/FetchTestCases.kt
Labels: 🛬 needs landing

#6401 For #6399: Add method to find session by url
  components/browser/state/src/main/java/mozilla/components/browser/state/selector/Selectors.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/selector/SelectorsKtTest.kt
Labels: 🕵️‍♀️ needs review

#6457 For #3182 - Separate behaviours depending on user's MotionEvents
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/NestedWebView.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/toolbar/build.gradle
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehaviorTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SwipeRefreshFeature.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6405 Closes #3832: Add EXTRA_HEADERS support for custom tab
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProviderTest.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabIntentProcessor.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabIntentProcessorTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/intent/TrustedWebActivityIntentProcessorTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/SafeBundle.kt
  config/detekt-baseline.xml
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6515 For #6510 - Allow a different LayoutManager for TabsTray
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/BrowserTabsTray.kt
  docs/changelog.md
Labels: ✏️ needs changes

#6540 Docs update (20200406-120803) [ci skip]
  docs/api/mozilla.components.browser.tabstray/-tab-view-holder/bind.md
Labels: 🛬 needs landing

#6458 Closes #6453: Limit the number of notifications to stay under the android limit.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ext/Intent.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing

#6541 GeckoView update (nightly) (20200406-140518)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6518 For #6517 - Always try to set a locale in updateResources
  components/support/locale/src/main/java/mozilla/components/support/locale/LocaleManager.kt
  components/support/locale/src/test/java/mozilla/components/support/locale/LocaleManagerTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6505 Add codeowners for lib-nearby
  CODEOWNERS
Labels: 🛬 needs landing

#6551 Closes #6550: Update Flank templates to use single and same device
  automation/taskcluster/androidTest/flank-arm.yml
  automation/taskcluster/androidTest/flank-x86.yml
Labels: 🤖 automation

#6549 For #6548: Force expand toolbar if touch unhandled
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt
Labels: 🕵️‍♀️ needs review

#6568 Close #6567: Return result of block in runWithSessionIdOrSelected
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FxaWebChannelFeature.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6557 For #6556 - Add customTabSessionId param to PictureInPictureFeature
  components/feature/session/src/main/java/mozilla/components/feature/session/PictureInPictureFeature.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/PictureInPictureFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6546 For #6545 - Don't assume CardView for tabstray
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  components/browser/tabstray/src/main/res/layout/mozac_browser_tabstray_item.xml
Labels: 🛬 needs landing

#6504 For #6501 - Increment google_materials dependency to 1.1.0.
  buildSrc/src/main/java/Dependencies.kt
  components/feature/session/build.gradle
  docs/changelog.md
  samples/browser/build.gradle
Labels: dependencies, 🛬 needs landing

#6573 Removed checkboxes from unused PR template options
  .github/pull_request_template.md
Labels: 🛬 needs landing

#6581 Public Suffix List update (20200408-140624)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#6583 GeckoView update (beta) (20200408-140804)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6432 Do not pause or display media notification when all media is muted.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/MediaObserver.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/Media.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/MediaReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/MediaState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/MediaActionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/media/Media.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/media/MediaTest.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/MediaState.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/middleware/MediaMiddleware.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/middleware/sideeffects/MediaAggregateUpdater.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/MockMediaElement.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/middleware/MediaMiddlewareTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/middleware/sideeffects/MediaAggregateUpdaterTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6566 For #6564 - Only display URL hostname for tabstray
  components/browser/tabstray/build.gradle
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabViewHolderTest.kt
  docs/changelog.md
Labels: ✏️ needs changes

#6594 Public Suffix List update (20200409-140700)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#6569 Close #5913: Remove deprecated WebPushHandler.onSubscriptionChanged API
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webpush/WebPush.kt
  components/feature/push/README.md
Labels: 🕵️‍♀️ needs review

#6602 Add api for customizing the style of the AddonPermissionsAdapter
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/CustomViewHolder.kt
  components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_permission_item.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_section_item.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  components/ui/icons/src/main/res/drawable/mozac_ic_new.xml
Labels: 🛬 needs landing

#6604 Closes #6603 use the created time when creating a download notification
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt
Labels: 🕵️‍♀️ needs review

#6626 GeckoView update (nightly) (20200413-140631)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6586 For #6585 - Cancel and dismiss on negative button in LoginDialogFragment
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/LoginDialogFragment.kt
Labels: 🛬 needs landing

#5386 Closes #5371 - Introduce 'sync' ping, add 'syncUuid' to all sync-related pings
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt
  components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/SyncableLoginsStorage.kt
  components/support/sync-telemetry/docs/metrics.md
  components/support/sync-telemetry/metrics.yaml
  components/support/sync-telemetry/pings.yaml
  components/support/sync-telemetry/src/main/java/mozilla/components/support/sync/telemetry/SyncTelemetry.kt
  components/support/sync-telemetry/src/test/java/mozilla/components/support/sync/telemetry/SyncTelemetryTest.kt
Labels: E5, 🕵️‍♀️ needs review

#6628 Closes #6627: Add default local property to Addon
  components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AddonCollectionProvider.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/PermissionsDialogFragment.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/UnsupportedAddonsAdapter.kt
  components/feature/addons/src/test/java/AddonCollectionProviderTest.kt
  components/feature/addons/src/test/java/AddonManagerTest.kt
  components/feature/addons/src/test/java/AddonTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/migration/SupportedAddonsWorkerTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/ExtensionsTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/PermissionsDialogFragmentTest.kt
  components/feature/addons/src/test/resources/collection.json
  components/feature/addons/src/test/resources/collection_with_empty_values.json
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonDetailsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonSettingsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/InstalledAddonDetailsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/PermissionsDetailsActivity.kt
Labels: 🛬 needs landing

#6611 For #6610 - Don't assume iconView within the tabstray
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6631 Close #5866: Pass Uri to handleNewWindowRequestError when failed to open a new window request in custom tab
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabWindowFeatureTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6298 For #6303 - Change logic for updating vs creating logins
  buildSrc/src/main/java/Dependencies.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/LoginsStorage.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/LoginDialogFragment.kt
  components/feature/prompts/src/main/res/color/button_state_list.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_prompt_login_prompt.xml
  components/service/sync-logins/build.gradle
  components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/DefaultLoginValidationDelegate.kt
  components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/GeckoLoginStorageDelegate.kt
  components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/SyncableLoginsStorage.kt
  components/service/sync-logins/src/test/java/mozilla/components/service/sync/logins/DefaultLoginValidationDelegateTest.kt
  components/service/sync-logins/src/test/java/mozilla/components/service/sync/logins/GeckoLoginStorageDelegateTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6647 Closes #6646 - Use app namespace for save login button tint
  components/feature/prompts/src/main/res/layout/mozac_feature_prompt_login_prompt.xml
Labels: 🕵️‍♀️ needs review

#6661 Closes #6659: Upgrade to GV Nightly 77.0.20200415092524
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
Labels: 🛬 needs landing

#6649 Close #6648: After AUDIOFOCUS_LOSS_TRANSIENT only resume playing if media was playing before loss
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/MediaState.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/focus/AudioFocus.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/focus/AudioFocusTest.kt
Labels: 🛬 needs landing

#6655 Fixes #6654: Vertically aligns users count with rating
  components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
Labels: 🛬 needs landing

#6693 Closes #6685 enable previously unsupported add-ons when available
  components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt
  components/feature/addons/src/test/java/AddonManagerTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/migration/SupportedAddonsWorkerTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6697 Docs update (20200417-120813) [ci skip]
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/index.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/set-visibility.md
  docs/api/mozilla.components.feature.addons.migration/-default-supported-addons-checker/index.md
  docs/api/mozilla.components.feature.addons.migration/-default-supported-addons-checker/register-for-checks.md
  docs/api/mozilla.components.feature.addons.migration/-default-supported-addons-checker/unregister-for-checks.md
  docs/api/mozilla.components.feature.addons.migration/-supported-addons-checker/-frequency/index.md
  docs/api/mozilla.components.feature.addons.migration/-supported-addons-checker/-frequency/repeat-interval-time-unit.md
  docs/api/mozilla.components.feature.addons.migration/-supported-addons-checker/-frequency/repeat-interval.md
  docs/api/mozilla.components.feature.addons.migration/-supported-addons-checker/index.md
  docs/api/mozilla.components.feature.addons.migration/-supported-addons-checker/register-for-checks.md
  docs/api/mozilla.components.feature.addons.migration/-supported-addons-checker/unregister-for-checks.md
  docs/api/mozilla.components.feature.addons/-addon-manager-exception/index.md
  docs/api/mozilla.components.feature.addons/-addon-manager/-b-l-o-c-k-e-d_-p-e-r-m-i-s-s-i-o-n-s.md
  docs/api/mozilla.components.feature.addons/-addon-manager/disable-addon.md
  docs/api/mozilla.components.feature.addons/-addon-manager/enable-addon.md
  docs/api/mozilla.components.feature.addons/-addon-manager/get-addons.md
  docs/api/mozilla.components.feature.addons/-addon-manager/index.md
  docs/api/mozilla.components.feature.addons/-addon-manager/install-addon.md
  docs/api/mozilla.components.feature.addons/-addon-manager/uninstall-addon.md
  docs/api/mozilla.components.feature.addons/-addon-manager/update-addon.md
Labels: 🛬 needs landing

#6692 Close #6691: Add open in external app context menu support for video and audio
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
Labels: 🕵️‍♀️ needs review

#6701 Bug 1631014 - Do no trigger a new set of jobs when PR is edited
  .taskcluster.yml
Labels: 🛬 needs landing

#6542 README: Replace snapshots with nightly builds.
  README.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#6714 GeckoView update (beta) (20200420-140822)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6713 GeckoView update (nightly) (20200420-140718)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6663 Closes #6228: Expose allowedInPrivateBrowsing control
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenu.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/WebExtensionReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/WebExtensionState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/WebExtensionActionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionDelegate.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionRuntime.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/WebExtensionToolbarFeature.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/WebExtensionToolbarFeatureTest.kt
  components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/InstalledAddonDetailsActivity.kt
  samples/browser/src/main/res/layout/activity_installed_add_on_details.xml
Labels: 🕵️‍♀️ needs review

#6570 Closes #6565: Handle deny & don't ask again in SitePermissionsFeature.
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsRulesTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing

#6722 Close #6720: Update current URL in onLocationChange
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
Labels: 🛬 needs landing

#6736 Docs update (20200422-120704) [ci skip]
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/-dialog-config/index.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/-dialog-config/should-preselect-do-not-ask-again.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/-init-.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/-prompts-styling/gravity.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/-prompts-styling/index.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/-prompts-styling/positive-button-background-color.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/-prompts-styling/positive-button-text-color.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/-prompts-styling/should-width-match-parent.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/index.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/on-need-to-request-permissions.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/on-permissions-result.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/on-should-show-request-permission-rationale.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/prompts-styling.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/site-permissions-rules.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/start.md
  docs/api/mozilla.components.feature.sitepermissions/-site-permissions-feature/stop.md
Labels: 🛬 needs landing

#6742 Closes #6702: Upgrade to GV Nightly 77.0.20200422093542
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6690 For mozilla-mobile/fenix#9413 - Workaround Android 8 to update layoutDirection on activity recreation
  components/support/locale/src/main/java/mozilla/components/support/locale/LocaleAwareAppCompatActivity.kt
  components/support/locale/src/test/java/mozilla/components/support/locale/LocaleAwareAppCompatActivityTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6704 Closes #6703 - Use BlendModeCompat Modulate instead of Multiply
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/BasicColorAdapter.kt
Labels: 🛬 needs landing

#6745 Fixes #6744: Import WebCompat v10.1.0 sources
  components/feature/webcompat/src/main/assets/extensions/webcompat/about-compat/aboutCompat.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/about-compat/aboutCompat.html
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/picture_in_picture_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1526977-sreedharscce.in-login-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1574973-patch.com-dropdown-menu-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1575011-holiday-weather.com-scrolling-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1631960-websube.ckbogazici.com.tr-table-row-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1632019-everyman.co-gallery-width-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1625224-sixt-neuwagen.de-window-netscape-shim.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1629926-mail.google.com-hangouts-mic-fix.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/intervention_helpers.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#6753 Docs update (20200423-121310) [ci skip]
  docs/api/mozilla.components.support.locale/-locale-aware-app-compat-activity/attach-base-context.md
  docs/api/mozilla.components.support.locale/-locale-aware-app-compat-activity/index.md
  docs/api/mozilla.components.support.locale/-locale-aware-app-compat-activity/on-create.md
  docs/api/mozilla.components.support.locale/-locale-aware-app-compat-activity/set-layout-direction-if-needed.md
Labels: 🛬 needs landing

#6755 Closes #6754: Intent.asForegroundServicePendingIntent: Set PendingIntent.FLAG_UPDATE_CURRENT by default.
  components/support/utils/src/main/java/mozilla/components/support/utils/intents.kt
Labels: 🕵️‍♀️ needs review

#6760 Docs update (20200424-120843) [ci skip]
  docs/api/mozilla.components.browser.tabstray/-browser-tabs-tray/as-view.md
  docs/api/mozilla.components.browser.toolbar/-async-filter-listener/coroutine-context.md
  docs/api/mozilla.components.browser.toolbar/-async-filter-listener/index.md
  docs/api/mozilla.components.browser.toolbar/-async-filter-listener/invoke.md
  docs/api/mozilla.components.browser.toolbar/-browser-toolbar/-button/index.md
  docs/api/mozilla.components.browser.toolbar/-browser-toolbar/-button/padding.md
  docs/api/mozilla.components.browser.toolbar/-browser-toolbar/-toggle-button/index.md
  docs/api/mozilla.components.browser.toolbar/-browser-toolbar/-toggle-button/padding.md
  docs/api/mozilla.components.browser.toolbar/-browser-toolbar/-two-state-button/bind.md
  docs/api/mozilla.components.browser.toolbar/-browser-toolbar/-two-state-button/enabled.md
  docs/api/mozilla.components.browser.toolbar/-browser-toolbar/-two-state-button/index.md
  docs/api/mozilla.components.browser.toolbar/-browser-toolbar/display-mode.md
  docs/api/mozilla.components.support.utils/as-foreground-service-pending-intent.md
  docs/api/mozilla.components.support.utils/index.md
Labels: 🛬 needs landing

#6746 Close #6421: Download try again should not crash when download does not exist
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/FetchDownloadManagerTest.kt
Labels: 🛬 needs landing

#6765 Closes #6764 Clear notifications and download jobs when onTaskRemoved or onDestroy are called.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6726 Closes #6481: Introduce api to partially update the AddonsManagerAdapter
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterDelegate.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt
Labels: 🕵️‍♀️ needs review

#6738 Issue #1705: Allow CrashReporterService to return a unique identifier for reported crashes.
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/CrashReporterService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/GleanCrashReporterService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/ExceptionHandlerTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SendCrashReportServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SendCrashTelemetryServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SentryServiceTest.kt
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashApplication.kt
Labels: 🛬 needs landing

#6780 GeckoView update (nightly) (20200427-140732)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6636 A-S 0.58.1 update; Support for v34 (history) and v23 (bookmarks) fennec db migrations.
  buildSrc/src/main/java/Dependencies.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorageTest.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/browser/storage-sync/src/test/resources/databases/bookmarks-v23.db
  components/browser/storage-sync/src/test/resources/databases/history-v34.db
Labels: 🛬 needs landing

#6779 MozillaSocorroService: Use internal logger instance.
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
Labels: 🛬 needs landing

#6785 Fix component name in changelog
  docs/changelog.md
Labels: 🛬 needs landing

#6787 Closes #6783: Engine session state is not restored
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/SnapshotSerializer.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/storage/SnapshotSerializerTest.kt
Labels: 🛬 needs landing

#6777 Issue #1705: Create separate interface for crash telemetry services.
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/CrashTelemetryService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/GleanCrashReporterService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/GleanCrashReporterServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SendCrashTelemetryServiceTest.kt
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashApplication.kt
Labels: 🕵️‍♀️ needs review

#6778 Docs update (20200427-121009) [ci skip]
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter-delegate/index.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter-delegate/on-not-yet-supported-section-clicked.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/-style/addon-background-icon-color.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/-style/addon-name-text-color.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/-style/addon-summary-text-color.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/-style/index.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/-style/sections-text-color.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/-style/sections-type-face.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/get-item-count.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/get-item-view-type.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/index.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/on-bind-view-holder.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/on-create-view-holder.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/update-addon.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/update-addons.md
  docs/api/mozilla.components.feature.addons.ui/index.md
  docs/api/mozilla.components.lib.crash.service/-crash-reporter-service/index.md
  docs/api/mozilla.components.lib.crash.service/-crash-reporter-service/report.md
  docs/api/mozilla.components.lib.crash.service/-glean-crash-reporter-service/index.md
  docs/api/mozilla.components.lib.crash.service/-glean-crash-reporter-service/report.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/index.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/report.md
  docs/api/mozilla.components.lib.crash.service/-sentry-service/index.md
  docs/api/mozilla.components.lib.crash.service/-sentry-service/report.md
Labels: 🛬 needs landing

#6715 Issue #6331: Add isDefault bool to TopSiteEntity and APIs for flagging default top sites
  components/feature/top-sites/schemas/mozilla.components.feature.top.sites.db.TopSiteDatabase/2.json
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/TopSiteStorageTest.kt
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/db/TopSiteDaoTest.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSite.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSiteStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/adapter/TopSiteAdapter.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/db/TopSiteDatabase.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/db/TopSiteEntity.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecMigratorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6808 GeckoView update (nightly) (20200429-140741)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6784 Issue #5680: Deprecate URLStringUtils.isURLLikeStrict.
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/URLStringUtils.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/WebURLFinder.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/URLStringUtilsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6803 Issue #6331: Update changelog to mention the new top site schema is a breaking change
  docs/changelog.md
Labels: 🛬 needs landing

#6826 Docs update (20200430-120851) [ci skip]
  docs/api/mozilla.components.feature.push/-auto-push-feature/-init-.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/-observer/index.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/-observer/on-message-received.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/-observer/on-subscription-changed.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/index.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/initialize.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/on-error.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/on-message-received.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/on-new-token.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/renew-registration.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/shutdown.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/subscribe.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/unsubscribe.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription-changed/channel-id.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription-changed/index.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription-changed/scope.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/app-server-key.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/auth-key.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/endpoint.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/index.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/public-key.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/scope.md
  docs/api/mozilla.components.feature.push/-protocol/-h-t-t-p-s.md
  docs/api/mozilla.components.feature.push/-protocol/-h-t-t-p.md
  docs/api/mozilla.components.feature.push/-protocol/index.md
  docs/api/mozilla.components.feature.push/-push-config/index.md
  docs/api/mozilla.components.feature.push/-push-config/protocol.md
  docs/api/mozilla.components.feature.push/-push-config/sender-id.md
  docs/api/mozilla.components.feature.push/-push-config/server-host.md
  docs/api/mozilla.components.feature.push/-push-config/service-type.md
  docs/api/mozilla.components.feature.push/-service-type/-a-d-m.md
  docs/api/mozilla.components.feature.push/-service-type/-f-c-m.md
  docs/api/mozilla.components.feature.push/-service-type/index.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/index.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/is-email.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/is-geo-location.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/is-phone.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/is-same-origin-as.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/is-url-strict.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/sha1.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/to-date.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/to-normalized-url.md
  docs/api/mozilla.components.support.ktx.kotlin/kotlin.-string/try-get-host-from-url.md
  docs/api/mozilla.components.support.utils/-u-r-l-string-utils/index.md
  docs/api/mozilla.components.support.utils/-u-r-l-string-utils/is-search-term.md
  docs/api/mozilla.components.support.utils/-u-r-l-string-utils/is-u-r-l-like-strict.md
  docs/api/mozilla.components.support.utils/-u-r-l-string-utils/is-u-r-l-like.md
  docs/api/mozilla.components.support.utils/-u-r-l-string-utils/to-display-url.md
  docs/api/mozilla.components.support.utils/-u-r-l-string-utils/to-normalized-u-r-l.md
  docs/api/mozilla.components.support.utils/-web-u-r-l-finder/is-web-u-r-l.md
Labels: 🛬 needs landing

#6821 Closes #6820 Ignore JobCancellationExceptions in add-ons workers
  components/feature/addons/src/main/java/mozilla/components/feature/addons/worker/Extensions.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/worker/ExtensionsTest.kt
Labels: 🛬 needs landing

#6829 GeckoView update (nightly) (20200430-140934)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6839 Issue #6838: Fix top sites migration that used isDefault instead of is_default
  components/feature/top-sites/schemas/mozilla.components.feature.top.sites.db.TopSiteDatabase/3.json
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/TopSiteStorageTest.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/db/TopSiteDatabase.kt
Labels: 🛬 needs landing
