Repository mozilla-mobile/android-components, pull requests merged in 2020-11, with the labels that each got.

#8817 Close #8776: Add rate-limit override to Push features
  components/feature/accounts-push/build.gradle
  components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/AccountObserverTest.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/ConstellationObserverTest.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/FxaPushSupportFeatureTest.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/VerificationDelegateTest.kt
  components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/AutoPushFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8832 For #8831 - Adds ability to remove (and restore) an arbitrary list of…
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/middleware/TabsRemovedMiddleware.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/undo/UndoMiddleware.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/middleware/TabsRemovedMiddlewareTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/undo/UndoMiddlewareTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
  components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/ThumbnailsMiddleware.kt
  components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/ThumbnailsMiddlewareTest.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/middleware/MediaMiddleware.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/middleware/MediaMiddlewareTest.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddleware.kt
  components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddlewareTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8876 Revert "Closes #8660: Crash when launching PWA with open tab"
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessor.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessorTest.kt
Labels: 🛬 needs landing

#8858 Close #8857 call stopForeground when all downloads are completed
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8882 Update changelog for 65.0.0 release.
  docs/changelog.md
Labels: 🛬 needs landing

#8887 Closes #8868: Prevent white flash for reader pages with dark theme
  components/feature/readerview/src/main/assets/extensions/readerview/readerview-background.js
  components/feature/readerview/src/main/assets/extensions/readerview/readerview.html
  components/feature/readerview/src/main/assets/extensions/readerview/readerview.js
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#8774 Closes #8745 Remove OneTimeFxaPushReset from FxaPushSupportFeature
  components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/OneTimeFxaPushResetTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8885 Set version to 66.0.0.
  .buildconfig.yml
Labels: 🛬 needs landing

#8890 Issue #8744: CustomSearchEnginesStorage: Use filesystem safe file names.
  components/feature/search/src/main/java/mozilla/components/feature/search/storage/CustomSearchEnginesStorage.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
Labels: 🛬 needs landing

#8895 Closes #8867: Correctly handle PageAction enabled state
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenu.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilderTest.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuTest.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/WebExtensionToolbarFeature.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/WebExtensionToolbarFeatureTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#8898 Closes #8660: Release engine view on stop
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionFeature.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/engine/EngineViewPresenter.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionFeatureTest.kt
Labels: 🛬 needs landing

#8901 Issue #8744: Add additional search use cases.
  components/feature/intent/src/test/java/mozilla/components/feature/intent/processing/TabIntentProcessorTest.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/SearchUseCases.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/ext/SearchEngine.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/storage/SearchEngineWriter.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/SearchUseCasesTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/ext/SearchEngineKtTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/storage/SearchEngineWriterTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#8914 Issue #7247: Deprecate SelectionAwareSessionObserver
  components/browser/session/src/main/java/mozilla/components/browser/session/SelectionAwareSessionObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SelectionAwareSessionObserverTest.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/CoordinateScrollingFeature.kt
  docs/changelog.md
  samples/browser/build.gradle
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#8906 Close #8904 Use the gecko fetch client when resuming a download
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8923 Remove SessionManager from SitePermissionsFeature.
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsRulesTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing

#8878 For #8877 - Pass crashReporter when instantiating FirefoxAccount fromJSONString
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/AccountStorage.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt
  samples/firefox-accounts/src/main/java/org/mozilla/samples/fxa/MainActivity.kt
Labels: 🛬 needs landing (squash)

#8922 For #8911: await for threading to complete in LazyComponent test.
  components/support/base/src/test/java/mozilla/components/support/base/utils/LazyComponentTest.kt
Labels: 🛬 needs landing

#8910 Bug 1663978 - v17.0.0 site interventions
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/matchPatterns.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1577297-kitkat.com.au-slider-width-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#8936 Closes #8867: Correctly handle PageAction enabled state
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenu.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilderTest.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/Action.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/WebExtensionToolbarFeature.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/WebExtensionToolbarFeatureTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#8916 Issue #8791: SearchMiddleware: Add mechanism for migrating legacy data from app
  components/browser/search/src/main/java/mozilla/components/browser/search/SearchEngine.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/ext/SearchEngine.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/middleware/SearchMiddleware.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
Labels: 🛬 needs landing

#8261 Adds Nimbus component
  .buildconfig.yml
  README.md
  buildSrc/src/main/java/Dependencies.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/service/nimbus/.gitignore
  components/service/nimbus/README.md
  components/service/nimbus/build.gradle
  components/service/nimbus/proguard-rules-consumer.pro
  components/service/nimbus/proguard-rules.pro
  components/service/nimbus/src/debug/res/values/endpoints.xml
  components/service/nimbus/src/main/AndroidManifest.xml
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
  components/service/nimbus/src/release/res/values/endpoints.xml
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/NimbusTest.kt
  components/service/nimbus/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/service/nimbus/src/test/resources/robolectric.properties
  components/support/locale/src/main/java/mozilla/components/support/locale/Extensions.kt
  samples/glean/README.md
  samples/glean/build.gradle
  samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/MainActivity.kt
Labels: 🛬 needs landing

#8951 Closes #8950 - Glean sample app crashing on Firebase
  components/service/nimbus/src/debug/res/values/endpoints.xml
Labels: 🛬 needs landing

#8945 Make bot owner of automatically updated files
  CODEOWNERS
Labels: 🛬 needs landing

#8957 Update codeowner for browser-menu2
  CODEOWNERS
Labels: 🛬 needs landing

#8948 [doc only]Update Nimbus README.md
  components/service/nimbus/README.md
  docs/changelog.md
Labels: 🛬 needs landing (squash)

#8959 Uplift: Close #8904 Use the gecko fetch client when resuming a download
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing

#8952 (63.0.x) Update to GeckoView 83 (first RC).
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/docs/metrics.md
  components/browser/engine-gecko/docs/metrics.md
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionController.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionException.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionControllerTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegateTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
Labels: 🛬 needs landing

#8960 Set version to 63.0.8.
  .buildconfig.yml
Labels: 🛬 needs landing

#8962 Remove workaround for bug 1675644
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
Labels: 🛬 needs landing

#8964 Pre-release: Update changelog for 66.0.0 release.
  docs/changelog.md
Labels: 🛬 needs landing

#8944 Closes #8943 refactor SwipeRefreshFeature to not use EngineSession.Observer
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SwipeRefreshFeature.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SwipeRefreshFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8966 Fixes #8815 Expose global opt out for first inclusion with Fenix
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/NimbusTest.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/MainActivity.kt
Labels: 🛬 needs landing

#8978 Uplift: For fenix#16232 - Make sure we cancel any in-progress auth
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/State.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/manager/StateKtTest.kt
Labels: 🛬 needs landing

#8974 Fix context activity leak in CrashDatabase
  components/lib/crash/src/main/java/mozilla/components/lib/crash/db/CrashDatabase.kt
Labels: 🛬 needs landing

#8975 TabsUseCases: Open new tabs with "about:blank" by default.
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/WindowFeature.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/WindowFeatureTest.kt
Labels: 🛬 needs landing

#8986 Mergify: Automatically approve uplift PRs bumping Gecko and release version
  .mergify.yml
Labels: 🕵️‍♀️ needs review

#8988 For #8987 - Better handling of ACTION_DOWN in NestedGeckoView
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
Labels: 🛬 needs landing

#8968 Closes #8967 prevent handling invalid requests in FilePicker
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FilePickerTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8954 Close #8953: Scroll to the selected choice prompt if one exists
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/ChoiceDialogFragment.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/ChoiceDialogFragmentTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8865 Closes #8864: Allow migrating FxA with custom servers configured (for Fenix China)
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecFxaMigration.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecFxaMigrationTest.kt
  components/support/migration/src/test/resources/fxa/china-sync-config-idp-token.json
Labels: 🛬 needs landing

#8995 Set version to 68.0.0
  .buildconfig.yml
Labels: 🛬 needs landing

#8992 Closes #8991: Handle PackageItemInfo.packageName NullPointerException
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8973 Closes #8464 ensure prompts are not completed before confirming
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8805 Closes #8743, closes #8886: Use MediaSesssion API in Media Notification
  components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/MediaSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/mediasession/MediaSession.kt
  components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/Tab.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/MediaSessionFeature.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/MediaSessionState.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeature.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/AbstractMediaSessionService.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/MediaSessionFeatureTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeatureTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/notification/MediaNotificationTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaSessionServiceDelegateTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/TabSessionState.kt
  samples/browser/src/main/AndroidManifest.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/media/MediaSessionService.kt
Labels: 🛬 needs landing

#9010 Closes #8999: Integrate new media code into sample browser
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#9008 Closes #8899: Integrate Audio Focus with Media Session API
  components/feature/media/src/main/java/mozilla/components/feature/media/focus/AudioFocus.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaServiceDelegate.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/focus/AudioFocusTest.kt
Labels: 🛬 needs landing

#9013 Close #9011: Unsubscribe before subscribing to fix FxA push
  components/feature/accounts-push/build.gradle
  components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt
  components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/ext/String.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/ConstellationObserverTest.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/ext/StringKtTest.kt
Labels: 🛬 needs landing

#9014 SearchMiddleware: Add additional tests.
  components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
Labels: 🛬 needs landing

#9018 Update Taskcluster and Mergify badge in README
  README.md
Labels: 🛬 needs landing

#9019 Closes #9017: Memory leak in consumeFlow
  components/lib/state/src/main/java/mozilla/components/lib/state/Store.kt
  components/lib/state/src/main/java/mozilla/components/lib/state/ext/StoreExtensions.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/StoreExtensionsKtTest.kt
Labels: 🛬 needs landing

#9007 Mergify: Delete head branch after merging PR matching "release automation" rule
  .mergify.yml
Labels: 🛬 needs landing

#9023 Closes #9022: Memory leak in BrowserThumbnails.requestScreenshot
  components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/BrowserThumbnails.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt
Labels: 🛬 needs landing

#9024 SDK-118 Force the app to specify a server URL
  components/service/nimbus/src/debug/res/values/endpoints.xml
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
  components/service/nimbus/src/release/res/values/endpoints.xml
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/NimbusTest.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt
  samples/glean/src/main/res/values/enpoints.xml
Labels: 🛬 needs landing (squash)

#9029 For #9028 - Adds return id to createCollection
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/TabCollectionStorage.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9027 Introduce helper BrowserState.findActiveMediaTab().
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/SessionState.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
Labels: 🛬 needs landing

#9045 For #9043 - Stop leaking the old MotionEvent handled state
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt
Labels: 🛬 needs landing

#9044 For #9042 - Dismiss pull to refresh if beforeunload prompt is cancelled
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
Labels: 🛬 needs landing

#9037 MediaSessionFeatureTest: Add license header
  components/feature/media/src/test/java/mozilla/components/feature/media/MediaSessionFeatureTest.kt
Labels: 🛬 needs landing

#9051 Fixes #9003 - Adds license header
  components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaSessionServiceDelegateTest.kt
Labels: 🛬 needs landing

#9061 Closes #9056: consumeFlow leaks fragment if removed before flow created
  components/lib/state/src/main/java/mozilla/components/lib/state/ext/Fragment.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/ext/FragmentKtTest.kt
Labels: 🛬 needs landing

#9068 TrimMemoryMiddleware: Log whenever we suspend tabs to trim memory.
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/middleware/TrimMemoryMiddleware.kt
Labels: 🛬 needs landing

#9032 Workflow to update GeckoView Beta
  .github/workflows/update-geckoview.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#9036 Closes #9354 improve resume downloads in slow networks
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9071 Issue #9011: Submit exception on subscribe error
  components/concept/push/src/main/java/mozilla/components/concept/push/exceptions/SubscriptionException.kt
  components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/ConstellationObserverTest.kt
Labels: 🛬 needs landing
