Repository mozilla-mobile/android-components, pull requests merged in 2020-02, with the labels that each got.

#5709 F7832 fix logins storage exception
  components/concept/storage/src/main/java/mozilla/components/concept/storage/LoginsStorage.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/LoginDialogFragment.kt
Labels: 🕵️‍♀️ needs review

#5780 Public Suffix List update (20200202-140706)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#5781 GeckoView update (beta) (20200202-140707)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5790 GeckoView update (beta) (20200203-141535)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5791 GeckoView update (nightly) (20200203-141523)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5798 Docs update (20200204-121316) [ci skip]
  docs/api/mozilla.components.concept.engine.webextension/-metadata/-init-.md
  docs/api/mozilla.components.concept.engine.webextension/-metadata/index.md
  docs/api/mozilla.components.concept.engine.webextension/-metadata/open-options-page-in-tab.md
  docs/api/mozilla.components.lib.state/-store-exception/e.md
  docs/api/mozilla.components.lib.state/-store-exception/index.md
  docs/api/mozilla.components.lib.state/-store-exception/msg.md
  docs/api/mozilla.components.lib.state/-store/-subscription/-binding/index.md
  docs/api/mozilla.components.lib.state/-store/-subscription/-binding/unbind.md
  docs/api/mozilla.components.lib.state/-store/-subscription/index.md
  docs/api/mozilla.components.lib.state/-store/-subscription/pause.md
  docs/api/mozilla.components.lib.state/-store/-subscription/resume.md
  docs/api/mozilla.components.lib.state/-store/-subscription/unsubscribe.md
  docs/api/mozilla.components.lib.state/-store/dispatch.md
  docs/api/mozilla.components.lib.state/-store/observe-manually.md
Labels: 🛬 needs landing

#5676 Fix #5603 - Implement notification for when the migration is complete.
  components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt
  components/support/migration/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#5797 Closes #5744: Replace 'in memory' session store parser with stream parser.
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecSessionMigration.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/session/InMemorySessionStoreParser.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/session/StreamingSessionStoreParser.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/CompareSessionParsersTest.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecSessionMigrationTest.kt
  components/support/migration/src/test/resources/sessions/large/sessionstore.js
Labels: 🛬 needs landing

#5796 For #5342 - Synchronize dataprotect Cipher functions
  components/lib/dataprotect/src/main/java/mozilla/components/lib/dataprotect/Keystore.kt
Labels: 🛬 needs landing

#5819 Issue #5818: Try to migrate default search engine.
  components/support/migration/build.gradle
  components/support/migration/docs/metrics.md
  components/support/migration/metrics.yaml
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/MigrationResultsStore.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/SearchEngineMigration.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/TelemetryHelpers.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/SearchEngineMigrationTest.kt
Labels: 🕵️‍♀️ needs review

#5773 For #5771: Changes description for a suggestion that represents an opened tab
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt
  components/feature/awesomebar/src/main/res/values/strings.xml
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/AwesomeBarFeatureTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProviderTest.kt
  docs/changelog.md
  l10n.toml
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#5833 GeckoView update (nightly) (20200206-140531)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5858 Add disabled section in AddonsManagerAdapter
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
Labels: 🕵️‍♀️ needs review

#5853 Closes #4466, #5278: Migration: Filter about:home tabs and rewrite about:reader URLs.
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecSessionMigration.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecSessionMigrationTest.kt
  components/support/migration/src/test/resources/sessions/about-urls/sessionstore.js
  components/support/migration/src/test/resources/sessions/only-about-home/sessionstore.js
Labels: 🛬 needs landing

#5863 GeckoView update (nightly) (20200209-140650)
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/docs/metrics.md
Labels: 🛬 needs landing

#5862 Docs update (20200209-120707) [ci skip]
  docs/api/mozilla.components.browser.errorpages/-error-pages/create-error-page.md
  docs/api/mozilla.components.browser.errorpages/-error-pages/create-url-encoded-error-page.md
  docs/api/mozilla.components.browser.errorpages/-error-pages/index.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-c-o-n-n-e-c-t-i-o-n_-r-e-f-u-s-e-d.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-c-o-n-t-e-n-t_-c-r-a-s-h-e-d.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-c-o-r-r-u-p-t-e-d_-c-o-n-t-e-n-t.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-f-i-l-e_-a-c-c-e-s-s_-d-e-n-i-e-d.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-f-i-l-e_-n-o-t_-f-o-u-n-d.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-i-n-v-a-l-i-d_-c-o-n-t-e-n-t_-e-n-c-o-d-i-n-g.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-m-a-l-f-o-r-m-e-d_-u-r-i.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-n-e-t_-i-n-t-e-r-r-u-p-t.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-n-e-t_-r-e-s-e-t.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-n-e-t_-t-i-m-e-o-u-t.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-n-o_-i-n-t-e-r-n-e-t.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-o-f-f-l-i-n-e.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-p-o-r-t_-b-l-o-c-k-e-d.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-p-r-o-x-y_-c-o-n-n-e-c-t-i-o-n_-r-e-f-u-s-e-d.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-r-e-d-i-r-e-c-t_-l-o-o-p.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-s-a-f-e-b-r-o-w-s-i-n-g_-h-a-r-m-f-u-l_-u-r-i.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-s-a-f-e-b-r-o-w-s-i-n-g_-m-a-l-w-a-r-e_-u-r-i.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-s-a-f-e-b-r-o-w-s-i-n-g_-p-h-i-s-h-i-n-g_-u-r-i.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-s-a-f-e-b-r-o-w-s-i-n-g_-u-n-w-a-n-t-e-d_-u-r-i.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-s-e-c-u-r-i-t-y_-b-a-d_-c-e-r-t.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-s-e-c-u-r-i-t-y_-s-s-l.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-u-n-k-n-o-w-n_-h-o-s-t.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-u-n-k-n-o-w-n_-p-r-o-t-o-c-o-l.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-u-n-k-n-o-w-n_-p-r-o-x-y_-h-o-s-t.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-u-n-k-n-o-w-n_-s-o-c-k-e-t_-t-y-p-e.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-e-r-r-o-r_-u-n-s-a-f-e_-c-o-n-t-e-n-t_-t-y-p-e.md
  docs/api/mozilla.components.browser.errorpages/-error-type/-u-n-k-n-o-w-n.md
  docs/api/mozilla.components.browser.errorpages/-error-type/image-name-res.md
  docs/api/mozilla.components.browser.errorpages/-error-type/index.md
  docs/api/mozilla.components.browser.errorpages/-error-type/message-res.md
  docs/api/mozilla.components.browser.errorpages/-error-type/refresh-button-res.md
  docs/api/mozilla.components.browser.errorpages/-error-type/title-res.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/get-item-count.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/get-item-view-type.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/index.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/on-bind-view-holder.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/on-create-view-holder.md
  docs/api/mozilla.components.feature.addons/-addon-manager-exception/index.md
  docs/api/mozilla.components.feature.addons/-addon-manager/disable-addon.md
  docs/api/mozilla.components.feature.addons/-addon-manager/enable-addon.md
  docs/api/mozilla.components.feature.addons/-addon-manager/install-addon.md
  docs/api/mozilla.components.feature.addons/-addon-manager/uninstall-addon.md
  docs/api/mozilla.components.feature.addons/-addon-manager/update-addon.md
  docs/api/mozilla.components.feature.addons/-addon/filter-translations.md
  docs/api/mozilla.components.feature.addons/-addon/index.md
  docs/api/mozilla.components.feature.addons/-addon/localize-permissions.md
  docs/api/mozilla.components.feature.addons/-addon/permission-to-translation.md
  docs/api/mozilla.components.service.experiments/-experiments-internal-a-p-i/index.md
  docs/api/mozilla.components.service.experiments/-experiments-internal-a-p-i/initialize.md
  docs/api/mozilla.components.service.experiments/-experiments-internal-a-p-i/with-experiment.md
  docs/api/mozilla.components.service.experiments/-experiments.md
Labels: 🛬 needs landing

#5847 No issue: land context menu search strings
  components/feature/contextmenu/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5871 GeckoView update (nightly) (20200210-140525)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5824 Navigate to home screen after PWA is installed
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt
Labels: 🛬 needs landing

#5774 Fix for #5605 - Set content intent for the migration notifications
  components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
Labels: 🕵️‍♀️ needs review

#5872 Annotate breaking API on Awesomebar changes [ci skip]
  docs/changelog.md
Labels: 🛬 needs landing

#5850 Closes #5692: NotImplementedError: Octet length not supported
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecLoginsMigration.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecLoginsMigrationTest.kt
Labels: 🕵️‍♀️ needs review

#5881 Add Enabled and Disabled strings for add-ons settings
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/InstalledAddonDetailsActivity.kt
Labels: 🛬 needs landing

#5870 Closes #5868: Correctly handle null title when migrating open tabs.
  components/support/migration/src/main/java/mozilla/components/support/migration/session/InMemorySessionStoreParser.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/session/StreamingSessionStoreParser.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecSessionMigrationTest.kt
  components/support/migration/src/test/resources/sessions/null-title/sessionstore.js
Labels: 🕵️‍♀️ needs review

#5835 Closes #4779 - Fix `ExperimentsDebugActivity` command to change server
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ExperimentsUpdater.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/debug/ExperimentsDebugActivity.kt
Labels: <experiments>

#5767 Closes #5766: AppLinksFeature should ignore file scheme.
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🕵️‍♀️ needs review

#5927 Issue #5886: Add ability to dismiss "migration completed" notification.
  components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt
Labels: 🕵️‍♀️ needs review

#5936 Docs update (20200214-120828) [ci skip]
  docs/api/mozilla.components.concept.engine.webpush/-web-push-handler/index.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-handler/on-subscription-changed.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-subscription/app-server-key.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-subscription/auth-secret.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-subscription/endpoint.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-subscription/equals.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-subscription/hash-code.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-subscription/index.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-subscription/public-key.md
  docs/api/mozilla.components.concept.engine.webpush/-web-push-subscription/scope.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/get-item-count.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/get-item-view-type.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/on-bind-view-holder.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/-init-.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/add-button.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/index.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/rating-accessible-view.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/user-count-view.md
  docs/api/mozilla.components.feature.awesomebar.provider/-search-suggestion-provider/-init-.md
  docs/api/mozilla.components.feature.awesomebar.provider/-search-suggestion-provider/-mode/-m-u-l-t-i-p-l-e_-s-u-g-g-e-s-t-i-o-n-s.md
  docs/api/mozilla.components.feature.awesomebar.provider/-search-suggestion-provider/-mode/-s-i-n-g-l-e_-s-u-g-g-e-s-t-i-o-n.md
  docs/api/mozilla.components.feature.awesomebar.provider/-search-suggestion-provider/-mode/index.md
  docs/api/mozilla.components.feature.awesomebar.provider/-search-suggestion-provider/index.md
  docs/api/mozilla.components.feature.awesomebar.provider/-search-suggestion-provider/on-input-changed.md
  docs/api/mozilla.components.feature.awesomebar.provider/-search-suggestion-provider/should-clear-suggestions.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/index.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/sign-in-with-shareable-account-async.md
  docs/api/mozilla.components.support.migration/-abstract-migration-service/dismiss-notification.md
  docs/api/mozilla.components.support.migration/-abstract-migration-service/index.md
  docs/api/mozilla.components.support.migration/-abstract-migration-service/migration-activity.md
  docs/api/mozilla.components.support.migration/-abstract-migration-service/migrator.md
  docs/api/mozilla.components.support.migration/-abstract-migration-service/on-bind.md
  docs/api/mozilla.components.support.migration/-abstract-migration-service/on-create.md
  docs/api/mozilla.components.support.migration/-abstract-migration-service/on-destroy.md
  docs/api/mozilla.components.support.migration/-abstract-migration-service/store.md
Labels: 🛬 needs landing

#5942 GeckoView update (nightly) (20200214-140624)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5941 GeckoView update (beta) (20200214-140502)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5945 Bors: Enable CODEOWNERS support.
  bors.toml
Labels: 🛬 needs landing

#5669 F5695 add search to context menu
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegateTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/test/ReflectionUtils.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegateTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Engine.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/search/SearchRequest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/selection/SelectionActionDelegate.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineViewTest.kt
  components/feature/contextmenu/build.gradle
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/DefaultSelectionActionDelegate.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ext/DefaultSelectionActionDelegate.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/DefaultSelectionActionDelegateTest.kt
  components/feature/search/build.gradle
  components/feature/search/src/main/java/mozilla/components/feature/search/BrowserStoreSearchAdapter.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/SearchAdapter.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/SearchFeature.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/SearchFeatureTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SwipeRefreshFeatureTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/behavior/EngineViewBottomBehaviorTest.kt
  components/support/test/src/main/java/mozilla/components/support/test/Mock.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/ext/Pair.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/ext/PairKtTest.kt
  docs/changelog.md
  samples/browser/src/geckoNightly/java/org/mozilla/samples/browser/Components.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/TabsTrayFragment.kt
Labels: <contextmenu>, <search>

#5935 Issue #5886: Automatically cancel 'migration completed' notification after user clicks it.
  components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt
Labels: 🕵️‍♀️ needs review

#5976 Improve add-ons update flow.
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/DefaultAddonUpdaterTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/UpdateStatusStorageTest.kt
  samples/browser/src/geckoNightly/java/org/mozilla/samples/browser/Components.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonDetailsActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/InstalledAddonDetailsActivity.kt
Labels: 🕵️‍♀️ needs review

#5981 Closes 5861: A few messages reference "computer"
  components/browser/errorpages/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5971 Closes #5966: Migrate browser-icons to use browser-state.
  components/browser/icons/build.gradle
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/IconMessageHandler.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/extension/IconSessionObserver.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/extension/IconMessageHandlerTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/extension/IconSessionObserverTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#5993 Public Suffix List update (20200219-140729)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#5995 GeckoView update (nightly) (20200219-140737)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5994 GeckoView update (beta) (20200219-140730)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5987 Closes #5911: Update test coverage for feature-addons/ui
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/ExtensionsTest.kt
Labels: 🕵️‍♀️ needs review

#6002 GeckoView update (nightly) (20200220-140714)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5591 Closes #5884 - Let PWA site controls be customized
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/SiteControlsBuilder.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/WebAppSiteControlsFeature.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/feature/WebAppSiteControlsFeatureTest.kt
Labels: 🛬 needs landing

#6007 Closes #6004: Show web ext badge in browser menu item
  components/browser/menu/src/main/res/layout/mozac_browser_menu_web_extension.xml
Labels: 🛬 needs landing

#4946 For #4907 - RTL url no margin set
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_edittoolbar.xml
  components/browser/toolbar/src/main/res/values/dimens.xml
Labels: 🛬 needs landing

#6014 Closes issue #6006: Fix null pointer exception when trying to update an add-on without a new update available
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
Labels: 🕵️‍♀️ needs review

#5988 Closes #5926: Launch third party app if protocol is not supported by engine.
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6028 Add breaking customTabId rename in change log [skip ci]
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6026 Closes #6025: Disable remove actions while uninstalling in UnsupportedAddonsAdapter
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/UnsupportedAddonsAdapter.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/UnsupportedAddonsAdapterTest.kt
Labels: 🛬 needs landing

#6000 Closes #5965: Migrate concept-tabstray and browser-tabstray to use browser-state.
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  components/browser/tabstray/build.gradle
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/BrowserTabsTray.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabTouchCallback.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabsAdapter.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/BrowserTabsTrayTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabTouchCallbackTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabViewHolderTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabsAdapterTest.kt
  components/concept/tabstray/build.gradle
  components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/Tab.kt
  components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/Tabs.kt
  components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/TabsTray.kt
  components/feature/tabs/build.gradle
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/BrowserState.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/TabSessionState.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsFeature.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsTrayInteractor.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenter.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsFeatureTest.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsTrayInteractorTest.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenterTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/TabsTrayFragment.kt
Labels: 🕵️‍♀️ needs review

#6034 Closes #6011: Integrate DebuggerDelegate to support temporary extensions
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/WebExtensionReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/WebExtensionActionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionDelegate.kt
  components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
Labels: 🛬 needs landing

#6037 For Fenix #5696 - Add share to selection action delegate
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/DefaultSelectionActionDelegate.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ext/DefaultSelectionActionDelegate.kt
  components/feature/contextmenu/src/main/res/values/strings.xml
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/DefaultSelectionActionDelegateTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
Labels: 🕵️‍♀️ needs review

#6051 For Fenix #8524 - Use SwitchCompat for BrowserMenuImageSwitch
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuImageSwitch.kt
  components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_switch.xml
Labels: 🛬 needs landing

#6005 Closes #5975: Make StreamingSessionStoreParser less strict.
  components/support/migration/src/main/java/mozilla/components/support/migration/session/StreamingSessionStoreParser.kt
Labels: 🛬 needs landing

#6055 For Fenix #8706: Add padding to web-ext menu item badge text
  components/browser/menu/src/main/res/layout/mozac_browser_menu_web_extension.xml
Labels: 🕵️‍♀️ needs review

#6063 Support appServerKey and complete callbacks for push subscription failures
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webpush/WebPushDelegate.kt
  components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt
  components/feature/push/src/main/java/mozilla/components/feature/push/Connection.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/AutoPushFeatureTest.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/ConnectionKtTest.kt
Labels: 🕵️‍♀️ needs review

#6071 Closes #6070: Mark badgeView invisible if it's null
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItem.kt
  components/browser/menu/src/main/res/layout/mozac_browser_menu_web_extension.xml
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItemTest.kt
Labels: 🕵️‍♀️ needs review

#6059 #6084 #5531 - Implement onLoginFetch in non-blocking way
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/autofill/GeckoLoginDelegateWrapper.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/autofill/GeckoLoginDelegateWrapper.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/LoginsStorage.kt
  components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/GeckoLoginStorageDelegate.kt
Labels: 🕵️‍♀️ needs review

#6078 Submit caught exceptions while updating add-ons to the crashReporter
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/GlobalAddonDependencyProvider.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/AddonUpdaterWorkerTest.kt
Labels: 🕵️‍♀️ needs review

#6072 Bug 1615248 - add beetmover jobs in the nightly graphs
  taskcluster/ac_taskgraph/transforms/beetmover.py
  taskcluster/ac_taskgraph/transforms/build.py
  taskcluster/ci/beetmover/kind.yml
Labels: 🕵️‍♀️ needs review

#6077 Closes #6058: Replace IntentService with JobIntentService for crash handler
  components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/CrashHandlerService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt
Labels: 🛬 needs landing

#6096 Docs update (20200227-120835) [ci skip]
  docs/api/alltypes/index.md
  docs/api/index.md
  docs/api/mozilla.components.browser.engine.gecko.autofill/-gecko-login-delegate-wrapper/index.md
  docs/api/mozilla.components.browser.engine.gecko.autofill/-gecko-login-delegate-wrapper/on-login-fetch.md
  docs/api/mozilla.components.browser.engine.gecko.autofill/-gecko-login-delegate-wrapper/on-login-save.md
  docs/api/mozilla.components.browser.engine.gecko.autofill/-gecko-login-delegate-wrapper/on-login-used.md
  docs/api/mozilla.components.browser.menu.facts/-browser-menu-facts/-init-.md
  docs/api/mozilla.components.browser.menu.facts/-browser-menu-facts/-items/-w-e-b_-e-x-t-e-n-s-i-o-n_-m-e-n-u_-i-t-e-m.md
  docs/api/mozilla.components.browser.menu.facts/-browser-menu-facts/-items/index.md
  docs/api/mozilla.components.browser.menu.facts/-browser-menu-facts/index.md
  docs/api/mozilla.components.browser.menu.facts/index.md
  docs/api/mozilla.components.browser.menu/-web-extension-browser-menu/index.md
  docs/api/mozilla.components.browser.menu/-web-extension-browser-menu/show.md
  docs/api/mozilla.components.concept.storage/-login-storage-delegate/index.md
  docs/api/mozilla.components.concept.storage/-login-storage-delegate/on-login-fetch.md
  docs/api/mozilla.components.concept.storage/-login-storage-delegate/on-login-save.md
  docs/api/mozilla.components.concept.storage/-login-storage-delegate/on-login-used.md
  docs/api/mozilla.components.concept.storage/-login-validation-delegate/-result/-can-be-updated.md
  docs/api/mozilla.components.concept.storage/-login-validation-delegate/-result/-error/-empty-password.md
  docs/api/mozilla.components.concept.storage/-login-validation-delegate/-result/-error/-gecko-error/exception.md
  docs/api/mozilla.components.concept.storage/-login-validation-delegate/-result/-error/-gecko-error/index.md
  docs/api/mozilla.components.concept.storage/-login-validation-delegate/-result/-error/index.md
  docs/api/mozilla.components.concept.storage/-login-validation-delegate/validate-can-persist.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/-frequency/index.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/-frequency/repeat-interval-time-unit.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/-frequency/repeat-interval.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/-status/-error/exception.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/-status/-error/index.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/-status/-error/message.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/-status/-no-update-available.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/-status/-not-installed.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/-status/-successfully-updated.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/-status/index.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/index.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/on-update-permission-request.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/register-for-future-updates.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/unregister-for-future-updates.md
  docs/api/mozilla.components.feature.addons.update/-addon-updater/update.md
  docs/api/mozilla.components.feature.addons.update/-default-addon-updater/index.md
  docs/api/mozilla.components.feature.addons.update/-default-addon-updater/on-update-permission-request.md
  docs/api/mozilla.components.feature.addons.update/-default-addon-updater/register-for-future-updates.md
  docs/api/mozilla.components.feature.addons.update/-default-addon-updater/unregister-for-future-updates.md
  docs/api/mozilla.components.feature.addons.update/-default-addon-updater/update.md
  docs/api/mozilla.components.lib.crash.handler/-crash-handler-service/index.md
  docs/api/mozilla.components.lib.crash.handler/-crash-handler-service/on-handle-intent.md
  docs/api/mozilla.components.lib.crash.handler/-crash-handler-service/on-handle-work.md
  docs/api/mozilla.components.lib.crash.handler/-crash-handler-service/on-start-command.md
  docs/api/mozilla.components.lib.crash.handler/index.md
  docs/api/mozilla.components.service.sync.logins/-gecko-login-storage-delegate/get-persistence-operation.md
  docs/api/mozilla.components.service.sync.logins/-gecko-login-storage-delegate/index.md
  docs/api/mozilla.components.service.sync.logins/-gecko-login-storage-delegate/on-login-fetch.md
  docs/api/mozilla.components.service.sync.logins/-gecko-login-storage-delegate/on-login-save.md
  docs/api/mozilla.components.service.sync.logins/-gecko-login-storage-delegate/on-login-used.md
  docs/api/mozilla.components.service.sync.logins/-operation/-c-r-e-a-t-e.md
  docs/api/mozilla.components.service.sync.logins/-operation/-u-p-d-a-t-e.md
  docs/api/mozilla.components.service.sync.logins/-operation/index.md
  docs/api/mozilla.components.service.sync.logins/mozilla.appservices.logins.-server-password/merge-with-login.md
  docs/api/mozilla.components.service.sync.logins/mozilla.appservices.logins.-server-password/to-login.md
  docs/api/mozilla.components.service.sync.logins/to-server-password.md
  docs/api/package-list
Labels: 🛬 needs landing

#6098 GeckoView update (nightly) (20200227-140615)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6103 For #6102 - Use app:srcCompat instead of android:src
  components/browser/menu/src/main/res/layout/mozac_browser_menu_web_extension.xml
  components/browser/tabstray/src/main/res/layout/mozac_browser_tabstray_item.xml
  components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml
  components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_edittoolbar.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_fragment_dialog_addon_permissions.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_section_unsupported_section_item.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_unsupported_item.xml
  components/feature/downloads/src/main/res/layout/mozac_downloads_prompt.xml
  components/feature/findinpage/src/main/res/layout/mozac_feature_findinpage_view.xml
  components/feature/qr/src/main/res/layout/fragment_layout.xml
  components/ui/tabcounter/src/main/res/layout/mozac_ui_tabcounter_layout.xml
  samples/browser/src/main/res/layout/activity_add_on_details.xml
Labels: 🕵️‍♀️ needs review
