Repository mozilla-mobile/android-components, pull requests merged in 2020-09, with the labels that each got.

#8215 Update search engines
  components/browser/search/src/main/assets/search/list.json
  components/browser/search/src/test/java/mozilla/components/browser/search/provider/AssetsSearchEngineProviderTest.kt
Labels: 🛬 needs landing

#8317 GeckoView update (nightly) (20200902-140616)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#8299 Closes #8297: Always show Copy link in context menu
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
Labels: 🕵️‍♀️ needs review

#8342 GeckoView update (release) (20200906-140727)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#8341 GeckoView update (nightly) (20200906-140724)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#8334 Incorrect getTopFrecuentSites parameter - For https://github.com/mozilla-mobile/fenix/issues/14724
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt
Labels: 🕵️‍♀️ needs review

#8191 Closes issue #8190 ArithmeticException: divide by zero in Download notification
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadNotificationTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8353 GeckoView update (nightly) (20200908-140443)
  buildSrc/src/main/java/Gecko.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#8254 Closes #8253 - Adds RecentlyClosedTabStorage
  .buildconfig.yml
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/AtomicFile.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/BrowserStateSerializer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/RecentlyClosedReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ClosedTabSessionState.kt
  components/feature/recentlyclosed/README.md
  components/feature/recentlyclosed/build.gradle
  components/feature/recentlyclosed/proguard-rules.pro
  components/feature/recentlyclosed/schemas/mozilla.components.feature.recentlyclosed.db.RecentlyClosedTabsDatabase/1.json
  components/feature/recentlyclosed/src/androidTest/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorageTest.kt
  components/feature/recentlyclosed/src/androidTest/java/mozilla/components/feature/recentlyclosed/db/RecentlyClosedTabDaoTest.kt
  components/feature/recentlyclosed/src/main/AndroidManifest.xml
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddleware.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorage.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/db/RecentlyClosedTabDao.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/db/RecentlyClosedTabEntity.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/db/RecentlyClosedTabsDatabase.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/ext/ClosedTab.kt
  components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddlewareTest.kt
  components/feature/recentlyclosed/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/feature/recentlyclosed/src/test/resources/robolectric.properties
  docs/changelog.md
  taskcluster/ci/test/kind.yml
Labels: 🕵️‍♀️ needs review

#8366 Temporarily stop building lib-jexl, service-pocket and service-telemetry
  .buildconfig.yml
Labels: 🛬 needs landing

#8371 Public Suffix List update (20200910-140542)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#8357 For #8356 - Speculative fix for BrowserGestureDetector IAE
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetector.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetectorTest.kt
Labels: 🕵️‍♀️ needs review

#8358 SessionStorage: Write state as stream to disk instead of building model in memory first.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionState.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionStateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionState.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionStateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionState.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionStateTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSessionState.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionStateTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/AtomicFile.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/BrowserStateSerializer.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/SessionStorage.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/SnapshotSerializer.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/ext/AtomicFileKtTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/storage/SessionStorageTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/storage/SnapshotSerializerTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSessionState.kt
  components/feature/recentlyclosed/src/androidTest/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorageTest.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorage.kt
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/TabCollectionStorageTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/util/AtomicFile.kt
Labels: 🕵️‍♀️ needs review

#8049 For #6099 - Convert config to yaml
  .config.yml
  buildSrc/src/main/java/Config.kt
  components/browser/state/build.gradle
  docs/changelog.md
  settings.gradle
  taskcluster/ci/toolchain/android.yml
Labels: 🏗️ build

#8231 Close #7822: Remove deprecated BrowserTabsTray
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/BrowserTabsTray.kt
  components/browser/tabstray/src/main/res/values/attrs.xml
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/BrowserTabsTrayTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8391 Closes #8390 - Do not add singular private tabs to recently closed st…
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddleware.kt
  components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddlewareTest.kt
Labels: 🕵️‍♀️ needs review

#8377 Close #8354: Do not restart FAILED downloads
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8157 For #8156: Add indicator to synced tabs suggestion in awesomebar
  components/concept/awesomebar/src/main/java/mozilla/components/concept/awesomebar/AwesomeBar.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/SyncedTabsStorageSuggestionProvider.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/SyncedTabsStorageSuggestionProviderTest.kt
  docs/changelog.md
Labels: ✏️ needs changes

#8409 Correct restore download log entry from restarted to restored
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt
Labels: 🛬 needs landing

#8403 Closes #8402 - Dismiss Select Login Prompt on Refresh
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
Labels: 🕵️‍♀️ needs review

#8419 Issue #8417: SessionStorage: Remove invalid selected tab id before saving state to disk.
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/SessionStorage.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/storage/SessionStorageTest.kt
Labels: 🛬 needs landing

#8422 Update changelog for 59.0.0 release.
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8388 Closes #8323: Add-on permission dialog does not prompt for host permissions
  components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/PermissionsDialogFragment.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/AddonTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/PermissionsDetailsActivity.kt
Labels: 🛬 needs landing

#8424 Set version to 60.0.0.
  .buildconfig.yml
Labels: 🕵️‍♀️ needs review

#8394 For #8393: Remove possible trailing slash from displayed url.
  components/support/utils/src/main/java/mozilla/components/support/utils/URLStringUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/URLStringUtilsTest.kt
Labels: 🛬 needs landing

#8420 Issue #7719: Remove default headers for "User-Agent" and "Connection".
  components/browser/engine-gecko-beta/src/androidTest/java/mozilla/components/browser/engine/gecko/fetch/geckoview/GeckoViewFetchTestCases.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko-nightly/src/androidTest/java/mozilla/components/browser/engine/gecko/fetch/geckoview/GeckoViewFetchTestCases.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko/src/androidTest/java/mozilla/components/browser/engine/gecko/fetch/geckoview/GeckoViewFetchTestCases.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Client.kt
  components/concept/fetch/src/test/java/mozilla/components/concept/fetch/ClientTest.kt
  components/lib/fetch-httpurlconnection/src/main/java/mozilla/components/lib/fetch/httpurlconnection/HttpURLConnectionClient.kt
  components/lib/fetch-okhttp/src/main/java/mozilla/components/lib/fetch/okhttp/OkHttpClient.kt
  components/tooling/fetch-tests/src/main/java/mozilla/components/tooling/fetch/tests/FetchTestCases.kt
Labels: 🕵️‍♀️ needs review

#8432 Closes #8431: Notify all new observers about change on enableTrackingProtection
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/support/base/src/main/java/mozilla/components/support/base/observer/ObserverRegistry.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7855 RFC: Migrate feature-sitepermissions to be compatible with the new GeckoView permission API [ci skip]
  docs/contributing.md
  docs/rfcs/0005-migrate-sitepermission-ac-store-geckoview-store.md
Labels: RFC

#8407 Closes #8406: Create separate usecases for removing all normal/private tabs.
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#8381 Update application-services to version 63.0.0
  buildSrc/src/main/java/Dependencies.kt
  components/concept/sync/src/main/java/mozilla/components/concept/sync/OAuthAccount.kt
  components/feature/accounts/src/test/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeatureTest.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
Labels: 🕵️‍♀️ needs review

#8447 Closes #7719: Remove all default headers from GeckoViewFetchClient.
  components/browser/engine-gecko-beta/src/androidTest/java/mozilla/components/browser/engine/gecko/fetch/geckoview/GeckoViewFetchTestCases.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko-nightly/src/androidTest/java/mozilla/components/browser/engine/gecko/fetch/geckoview/GeckoViewFetchTestCases.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko/src/androidTest/java/mozilla/components/browser/engine/gecko/fetch/geckoview/GeckoViewFetchTestCases.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Client.kt
  components/concept/fetch/src/test/java/mozilla/components/concept/fetch/ClientTest.kt
  components/lib/fetch-httpurlconnection/src/main/java/mozilla/components/lib/fetch/httpurlconnection/HttpURLConnectionClient.kt
  components/lib/fetch-okhttp/src/main/java/mozilla/components/lib/fetch/okhttp/OkHttpClient.kt
  components/tooling/fetch-tests/src/main/java/mozilla/components/tooling/fetch/tests/FetchTestCases.kt
Labels: 🕵️‍♀️ needs review

#8436 Upgrade Glean
  buildSrc/src/main/java/Dependencies.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8454 Scripts for updating GeckoView/PSL: Always open PR for changes.
  automation/taskcluster/action/update_geckoview.sh
  automation/taskcluster/action/update_publicsuffixlist.sh
Labels: 🛬 needs landing

#8449 Issue #3265: Add support for "undo" functionality.
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/undo/UndoMiddleware.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/undo/UndoMiddlewareTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/UndoReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/UndoHistoryState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/recover/RecoverableTab.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/TabsTrayFragment.kt
Labels: 🛬 needs landing

#8467 Move changelog entry for webcompat-reporter to 61
  docs/changelog.md
Labels: 🛬 needs landing

#8427 Issue #8426: Strip https/http and WWW prefixes when comparing top sites for duplicates
  components/feature/top-sites/build.gradle
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/ext/TopSite.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/DefaultTopSitesStorageTest.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/ext/TopSiteKtTest.kt
Labels: 🛬 needs landing

#8457 Closes issue #8456: Don't process add request for downloads already added
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8468 Closes #8401: Send App build ID to Socorro crash reports
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
Labels: 🛬 needs landing

#8465 Mergify: Use smart strict merge.
  .mergify.yml
Labels: 🛬 needs landing

#8476 Closes issue #8267: Devtools permission had wrong translation.
  components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  components/feature/addons/src/test/java/AddonTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8494 Closes #8493 - Add private param to RecoverableTab
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/recover/RecoverableTab.kt
Labels: 🛬 needs landing

#8490 Closes #8489 - Removes tab collection storage get limit
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/TabCollectionStorageTest.kt
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/db/TabCollectionDaoTest.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/TabCollectionStorage.kt
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/db/TabCollectionDao.kt
Labels: 🛬 needs landing

#8502 Closes #8401: Update VersionCode to ApplicationBuildID in Socorro crash reports
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
Labels: 🛬 needs landing

#8506 Improve download flow
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/content/DownloadState.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  components/feature/downloads/schemas/mozilla.components.feature.downloads.db.DownloadsDatabase/2.json
  components/feature/downloads/src/androidTest/java/mozilla/components/feature/downloads/OnDeviceDownloadStorageTest.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/db/DownloadEntity.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/db/DownloadsDatabase.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/db/DownloadEntityTest.kt
Labels: 🛬 needs landing

#8507 Removed unwanted try catch.
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
Labels: 🛬 needs landing

#8534 No issue: Add photonViolet70 to photon colours
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing

#8532 Close #8531: Use synchronized block in PushConnection init check
  components/feature/push/src/main/java/mozilla/components/feature/push/Connection.kt
Labels: 🛬 needs landing

#8451 For #8298: Limit title length in HitResult.
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
Labels: 🛬 needs landing

#8539 Issue #8471: Disable testAddingAllDefaultSites()
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/PinnedSitesStorageTest.kt
Labels: 🛬 needs landing

#8545 Closes #8488: Treat temporarily installed add-ons as supported
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  components/feature/addons/src/test/java/AddonManagerTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#8549 Pre-release: Update changelog for 61.0.0 release.
  docs/changelog.md
Labels: 🛬 needs landing

#8550 Post-release: Set version to 62.0.0.
  .buildconfig.yml
  docs/changelog.md
Labels: 🛬 needs landing

#8544 Close #8471: Use transaction annotation for addAllPinnedSites
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/PinnedSitesStorageTest.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/PinnedSiteStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/db/PinnedSiteDao.kt
Labels: 🛬 needs landing

#8416 For #8415 - Speculative RecentlyClosedMiddlewareTest fix
  components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddlewareTest.kt
Labels: 🛬 needs landing

#8561 Closes #8529: Dispatch a generic InitAction from BrowserStore
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/middleware/TabsRemovedMiddlewareTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/middleware/TrimMemoryMiddlewareTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/store/BrowserStore.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/store/BrowserStoreTest.kt
  components/feature/accounts/src/test/java/mozilla/components/feature/accounts/FxaWebChannelFeatureTest.kt
  components/feature/addons/src/test/java/AddonManagerTest.kt
  components/feature/containers/src/main/java/mozilla/components/feature/containers/ContainerMiddleware.kt
  components/feature/containers/src/main/java/mozilla/components/feature/containers/ContainerStorage.kt
  components/feature/containers/src/test/java/mozilla/components/feature/containers/ContainerMiddlewareTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/middleware/sideeffects/MediaAggregateUpdaterTest.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
  components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddlewareTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/WindowFeatureTest.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
Labels: 🛬 needs landing

#8559 No issue: Update PR template to remove bors instructions
  .github/pull_request_template.md
  docs/contribute/release_checklist.md
Labels: 🛬 needs landing

#8573 Issue #8076: Set add-on collection page size to max and allow sorting
  components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AddonCollectionProvider.kt
  components/feature/addons/src/test/java/AddonCollectionProviderTest.kt
  docs/changelog.md
Labels: 🛬 needs landing
