Repository mozilla-mobile/android-components, pull requests merged in 2020-05, with the labels that each got.

#6828 Issue #1705 - lib-crash: Add database storage for crashes.
  components/lib/crash/build.gradle
  components/lib/crash/schemas/mozilla.components.lib.crash.db.CrashDatabase/1.json
  components/lib/crash/src/main/java/mozilla/components/lib/crash/db/CrashDao.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/db/CrashDatabase.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/db/CrashEntity.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/db/CrashWithReports.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/db/ReportEntity.kt
  components/support/base/src/main/java/mozilla/components/support/base/ext/Throwable.kt
  components/support/base/src/main/java/mozilla/components/support/base/log/sink/AndroidLogSink.kt
Labels: 🕵️‍♀️ needs review

#6559 For #6558: Adds a menu with simple highlightable items
  components/browser/menu/src/main/java/mozilla/components/browser/menu/ext/View.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/SimpleBrowserMenuHighlightableItem.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/SimpleBrowserMenuHighlightableItemTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6817 Closes #6797 Remove !! operator usages from AbstractFetchDownloadService
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
Labels: 🛬 needs landing

#6861 GeckoView update (nightly) (20200504-140827)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6857 Closes #6856 Add Fingerprinters to the recommended Tracking protection policy
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6814 Close #6811: Add breadcrumbs for caught exceptions
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/CrashReporterService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/ExceptionHandlerTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SendCrashReportServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SentryServiceTest.kt
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashApplication.kt
Labels: 🛬 needs landing

#6852 Closes #6851 improve social trackers categorization
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6873 Merge day!
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko/src/androidTest/java/mozilla/components/browser/engine/gecko/fetch/geckoview/GeckoViewFetchTestCases.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoResult.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
Labels: 🕵️‍♀️ needs review

#6865 Close #6535: Add breadcrumbs to CrashReporting interface
  components/lib/crash/src/main/java/mozilla/components/lib/crash/BreadcrumbPriorityQueue.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/Crash.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/CrashReporterService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/BreadcrumbPriorityQueueTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/BreadcrumbTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/ExceptionHandlerTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SendCrashReportServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SentryServiceTest.kt
  components/support/base/build.gradle
  components/support/base/src/main/java/mozilla/components/support/base/crash/Breadcrumb.kt
  components/support/base/src/main/java/mozilla/components/support/base/crash/CrashReporting.kt
  docs/changelog.md
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashActivity.kt
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashApplication.kt
Labels: 🛬 needs landing

#6882 Update changelog to reflect breaking APIs
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6886 Update GeckoView Nightly version to 78.0.20200505094621.
  buildSrc/src/main/java/Gecko.kt
Labels: 🕵️‍♀️ needs review

#6885 Issue #6884: SessionManager.onTrimMemory(): Do not remove engine session state from sessions.
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
Labels: 🕵️‍♀️ needs review

#6877 Close #6876: Only use fallback if user preference is to not launch in third party app
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
Labels: 🛬 needs landing

#6531 For #6499 - Add min/max width support for BrowserMenu
  components/browser/menu/README.md
  components/browser/menu/src/main/java/mozilla/components/browser/menu/view/DynamicWidthRecyclerView.kt
  components/browser/menu/src/main/res/layout/mozac_browser_menu.xml
  components/browser/menu/src/main/res/values/attrs.xml
  components/browser/menu/src/main/res/values/dimens.xml
  components/browser/menu/src/test/java/mozilla/components/browser/menu/view/DynamicWidthRecyclerViewTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6894 Closes #6892: Improve stuck download notifications
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
Labels: 🛬 needs landing

#6901 Close #6812: Submit breadcrumbs to Socorro crash reports
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/BreadcrumbTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
  components/support/base/src/main/java/mozilla/components/support/base/crash/Breadcrumb.kt
Labels: 🛬 needs landing

#6913 GeckoView update (beta) (20200508-140814)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6871 Add crash database to CrashReporter and add UI for showing past crashes.
  components/lib/crash/build.gradle
  components/lib/crash/schemas/mozilla.components.lib.crash.db.CrashDatabase/1.json
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/db/CrashDao.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/db/ReportEntity.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/ExceptionHandler.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/CrashReporterService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/AbstractCrashListActivity.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/CrashListAdapter.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/CrashListFragment.kt
  components/lib/crash/src/main/res/layout/mozac_lib_crash_activity_crashlist.xml
  components/lib/crash/src/main/res/layout/mozac_lib_crash_crashlist.xml
  components/lib/crash/src/main/res/layout/mozac_lib_crash_crashreporter.xml
  components/lib/crash/src/main/res/layout/mozac_lib_crash_item_crash.xml
  components/lib/crash/src/main/res/values/strings.xml
  components/lib/crash/src/test/java/mozilla/components/lib/crash/BreadcrumbTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/ExceptionHandlerTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/prompt/CrashReporterActivityTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SendCrashReportServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SendCrashTelemetryServiceTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SentryServiceTest.kt
  samples/crash/src/main/AndroidManifest.xml
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashActivity.kt
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashApplication.kt
  samples/crash/src/main/java/org/mozilla/samples/crash/CrashListActivity.kt
  samples/crash/src/main/res/layout/activity_crash.xml
  samples/crash/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#6941 GeckoView update (nightly) (20200511-140826)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6940 GeckoView update (beta) (20200511-140812)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6937 Docs update (20200511-120613) [ci skip]
  docs/api/alltypes/index.md
  docs/api/index.md
  docs/api/mozilla.components.lib.crash.service/-crash-reporter-service/create-crash-report-url.md
  docs/api/mozilla.components.lib.crash.service/-crash-reporter-service/id.md
  docs/api/mozilla.components.lib.crash.service/-crash-reporter-service/index.md
  docs/api/mozilla.components.lib.crash.service/-crash-reporter-service/name.md
  docs/api/mozilla.components.lib.crash.service/-crash-reporter-service/report.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/create-crash-report-url.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/id.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/index.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/name.md
  docs/api/mozilla.components.lib.crash.service/-mozilla-socorro-service/report.md
  docs/api/mozilla.components.lib.crash.service/-sentry-service/create-crash-report-url.md
  docs/api/mozilla.components.lib.crash.service/-sentry-service/id.md
  docs/api/mozilla.components.lib.crash.service/-sentry-service/index.md
  docs/api/mozilla.components.lib.crash.service/-sentry-service/name.md
  docs/api/mozilla.components.lib.crash.service/-sentry-service/report.md
  docs/api/mozilla.components.lib.crash.ui/-abstract-crash-list-activity/-init-.md
  docs/api/mozilla.components.lib.crash.ui/-abstract-crash-list-activity/crash-reporter.md
  docs/api/mozilla.components.lib.crash.ui/-abstract-crash-list-activity/index.md
  docs/api/mozilla.components.lib.crash.ui/-abstract-crash-list-activity/on-crash-service-selected.md
  docs/api/mozilla.components.lib.crash.ui/-abstract-crash-list-activity/on-create.md
  docs/api/mozilla.components.lib.crash.ui/index.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/-init-.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/-prompt-configuration/index.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/-prompt/-a-l-w-a-y-s.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/-prompt/-n-e-v-e-r.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/-prompt/-o-n-l-y_-n-a-t-i-v-e_-c-r-a-s-h.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/-prompt/index.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/enabled.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/index.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/install.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/record-crash-breadcrumb.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/submit-caught-exception.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/submit-crash-telemetry.md
  docs/api/mozilla.components.lib.crash/-crash-reporter/submit-report.md
  docs/api/package-list
Labels: 🛬 needs landing

#6666 For #2930 - Different BrowserToolbar behaviors depending on gestures
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetector.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetectorTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehaviorTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/TestUtils.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6950 Docs update (20200512-120756) [ci skip]
  docs/api/alltypes/index.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/-init-.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/-prompts-styling/-init-.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/-prompts-styling/confirm-button-background-color.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/-prompts-styling/confirm-button-radius.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/-prompts-styling/confirm-button-text-color.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/-prompts-styling/gravity.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/-prompts-styling/index.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/-prompts-styling/should-width-match-parent.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/index.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/new-instance.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/on-confirm-button-clicked.md
  docs/api/mozilla.components.feature.addons.ui/-addon-installation-dialog-fragment/on-create-dialog.md
  docs/api/mozilla.components.feature.addons.ui/index.md
Labels: 🛬 needs landing

#6880 Revert to previous tabs tray layout
  components/browser/tabstray/src/main/res/layout/mozac_browser_tabstray_item.xml
Labels: 🕵️‍♀️ needs review

#6908 🎲 For #6907 - Dispatches tabsTray update when MediaState changes.
  components/browser/tabstray/build.gradle
  components/concept/tabstray/build.gradle
  components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/Tab.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/BrowserState.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/TabSessionState.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenter.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/ext/TabSessionStateTest.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenterTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6968 README: Add link to Matrix explanation
  README.md
Labels: 🛬 needs landing

#6946 Close #6903: Caught exception with no stack trace will be reported as UnexpectedlyMissingStacktrace
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
Labels: 🕵️‍♀️ needs review

#6970 GeckoView update (nightly) (20200513-141104)
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/docs/metrics.md
Labels: 🛬 needs landing

#6956 Close #6953: Report native fatal crash to Sentry as level FATAL
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/SentryServiceTest.kt
Labels: 🕵️‍♀️ needs review

#6972 Fixed #6914 CrashReporter: Log correct variable
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
Labels: 🛬 needs landing

#6962 Close #6957: Allow nullable encoding param in push messages
  components/concept/push/src/main/java/mozilla/components/concept/push/PushProcessor.kt
  components/concept/push/src/main/java/mozilla/components/concept/push/PushService.kt
  components/lib/push-amazon/src/main/java/mozilla/components/lib/push/amazon/AbstractAmazonPushService.kt
  components/lib/push-amazon/src/test/java/mozilla/components/lib/push/amazon/AbstractAmazonPushServiceTest.kt
  components/lib/push-firebase/src/main/java/mozilla/components/lib/push/firebase/AbstractFirebasePushService.kt
  components/lib/push-firebase/src/test/java/mozilla/components/lib/push/firebase/AbstractFirebasePushServiceTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6979 For #6978 - Catch reflection exceptions in BrowserGestureDetector
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetector.kt
Labels: 🕵️‍♀️ needs review

#6982 Makes updateUrl on EditToolbar public
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
Labels: 🛬 needs landing

#6987 Docs update (20200515-120614) [ci skip]
  docs/api/alltypes/index.md
  docs/api/mozilla.components.browser.toolbar.edit/-edit-toolbar/index.md
  docs/api/mozilla.components.browser.toolbar.edit/-edit-toolbar/update-url.md
  docs/api/mozilla.components.concept.fetch/-request/index.md
  docs/api/mozilla.components.concept.fetch/index.md
  docs/api/mozilla.components.concept.fetch/is-blob-uri.md
  docs/api/mozilla.components.feature.qr.views/-custom-view-finder/-init-.md
  docs/api/mozilla.components.feature.qr.views/-custom-view-finder/index.md
  docs/api/mozilla.components.feature.qr.views/-custom-view-finder/on-configuration-changed.md
  docs/api/mozilla.components.feature.qr.views/-custom-view-finder/on-draw.md
  docs/api/mozilla.components.feature.qr.views/-custom-view-finder/on-layout.md
  docs/api/mozilla.components.feature.qr.views/-custom-view-finder/on-size-changed.md
  docs/api/mozilla.components.feature.qr.views/-custom-view-finder/set-message.md
  docs/api/mozilla.components.feature.qr.views/-custom-view-finder/set-view-finder-color.md
  docs/api/mozilla.components.feature.qr.views/index.md
  docs/api/mozilla.components.feature.qr/-on-scan-result.md
  docs/api/mozilla.components.feature.qr/-qr-feature/-init-.md
  docs/api/mozilla.components.feature.qr/-qr-feature/index.md
  docs/api/mozilla.components.feature.qr/-qr-feature/on-back-pressed.md
  docs/api/mozilla.components.feature.qr/-qr-feature/on-need-to-request-permissions.md
  docs/api/mozilla.components.feature.qr/-qr-feature/on-permissions-result.md
  docs/api/mozilla.components.feature.qr/-qr-feature/scan.md
  docs/api/mozilla.components.feature.qr/-qr-feature/start.md
  docs/api/mozilla.components.feature.qr/-qr-feature/stop.md
  docs/api/mozilla.components.feature.qr/-qr-fragment/-on-scan-complete-listener/index.md
  docs/api/mozilla.components.feature.qr/-qr-fragment/-on-scan-complete-listener/on-scan-complete.md
  docs/api/mozilla.components.feature.qr/-qr-fragment/index.md
  docs/api/mozilla.components.feature.qr/-qr-fragment/new-instance.md
  docs/api/mozilla.components.feature.qr/-qr-fragment/on-create-view.md
  docs/api/mozilla.components.feature.qr/-qr-fragment/on-pause.md
  docs/api/mozilla.components.feature.qr/-qr-fragment/on-resume.md
  docs/api/mozilla.components.feature.qr/-qr-fragment/on-view-created.md
  docs/api/mozilla.components.support.ktx.android.util/index.md
  docs/api/mozilla.components.support.ktx.android.util/kotlin.-float/dp-to-px.md
  docs/api/mozilla.components.support.ktx.android.util/kotlin.-float/index.md
  docs/api/mozilla.components.support.ktx.android.util/kotlin.-float/sp-to-px.md
  docs/api/package-list
Labels: 🛬 needs landing

#6989 GeckoView update (nightly) (20200515-140928)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6988 GeckoView update (beta) (20200515-140932)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6998 Closes #6942: Update tracking protection lists
  components/browser/engine-system/src/main/res/raw/domain_blacklist.json
  components/browser/engine-system/src/main/res/raw/domain_whitelist.json
Labels: 🛬 needs landing

#6997 For #6996: Apply proper window flags to LoginDialogFragment
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/LoginDialogFragment.kt
  components/feature/prompts/src/main/res/values/styles.xml
Labels: 🛬 needs landing

#6994 Issue #6938: CrashReporter.getCrashReporterServiceById(): Handle missing crash reporter services.
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/CrashListAdapter.kt
Labels: 🕵️‍♀️ needs review

#7008 Add maven central repository.
  build.gradle
  taskcluster/ac_taskgraph/job.py
  taskcluster/scripts/toolchain/android-gradle-dependencies.sh
  taskcluster/scripts/toolchain/android-gradle-dependencies/after.sh
Labels: 🕵️‍♀️ needs review

#6923 No issue: Update Flank to v20.05.0 (stable)
  taskcluster/docker/ui-tests/Dockerfile
Labels: 🛬 needs landing, 🤖 automation

#7015 Bug 1620585 - remove snapshots logic from AC
  automation/taskcluster/rename_snapshot_artifacts.py
  components/tooling/glean-gradle-plugin/build.gradle
  publish.gradle
  taskcluster/ac_taskgraph/build_config.py
  taskcluster/ac_taskgraph/loader/build_config.py
  taskcluster/ac_taskgraph/target_tasks.py
  taskcluster/ac_taskgraph/transforms/beetmover.py
  taskcluster/ac_taskgraph/transforms/build.py
  taskcluster/ci/beetmover/kind.yml
  taskcluster/ci/build/kind.yml
  taskcluster/ci/post-signing/kind.yml
  taskcluster/ci/signing/kind.yml
Labels: 🛬 needs landing

#7014 Closes #7013 fix mozac_browser_engine_system_auth_message description comment
  components/browser/engine-system/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#6216 For #6215 - Expose media height and width
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/MediaObserver.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/Media.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/MediaReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/MediaState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/MediaActionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/media/Media.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/media/MediaTest.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/MediaState.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaFullscreenOrientationFeature.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/middleware/MediaMiddleware.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/middleware/sideeffects/MediaAggregateUpdater.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/MockMediaElement.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/ext/MediaStateKtTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/fullscreen/MediaFullscreenOrientationFeatureTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/middleware/sideeffects/MediaAggregateUpdaterTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#7020 GeckoView update (nightly) (20200519-140919)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6999 Use helper to change state of tab in BrowserStore
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/CustomTabListReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/EngineStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ReaderStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TrackingProtectionStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/WebExtensionReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/SessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
Labels: 🛬 needs landing

#7028 Issue #5217: Skip check to open about/data/js URLs in external apps
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing

#6927 Upgrade Application Services to v0.59.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#7060 GeckoView update (beta) (20200521-140756)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7059 GeckoView update (nightly) (20200521-140727)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6975 Update lifecycle version
  buildSrc/src/main/java/Dependencies.kt
  components/browser/session/build.gradle
  components/feature/accounts-push/build.gradle
  components/feature/accounts/build.gradle
  components/feature/prompts/build.gradle
  components/feature/push/build.gradle
  components/feature/share/build.gradle
  components/feature/sitepermissions/build.gradle
  components/feature/syncedtabs/build.gradle
  components/feature/tab-collections/build.gradle
  components/feature/top-sites/build.gradle
  components/lib/state/build.gradle
  components/service/glean/build.gradle
  components/support/android-test/build.gradle
  components/support/webextensions/build.gradle
Labels: 🕵️‍♀️ needs review

#6918 Issue #2754: Adds ThumbnailDiskCache for storing and restoring thumbnails
  components/browser/thumbnails/build.gradle
  components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/utils/ThumbnailDiskCache.kt
  components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/utils/ThumbnailDiskCacheTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#7070 Closes #6917: Remove unused manual disabling of tracking protection
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
Labels: 🛬 needs landing

#7075 Public Suffix List update (20200522-140625)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#7056 Fixes #7041: Adds an attribute to change login prompt editText cursor color
  components/feature/prompts/src/main/res/layout/mozac_feature_prompt_login_prompt.xml
  components/feature/prompts/src/main/res/values/attrs.xml
  components/feature/prompts/src/main/res/values/styles.xml
  docs/changelog.md
Labels: 🛬 needs landing

#7045 Issue #7012: Add share option to crash list.
  components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/CrashListAdapter.kt
  components/lib/crash/src/main/res/layout/mozac_lib_crash_item_crash.xml
  components/lib/crash/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#7039 Issue #7037: CrashReporter: Log ids and URLs of crash reports when submitting crash reports.
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
Labels: 🕵️‍♀️ needs review

#7099 GeckoView update (nightly) (20200525-140510)
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/docs/metrics.md
Labels: 🛬 needs landing

#6995 For #6687: Add crash reporting information for ClassCastException in PromptFeature
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
Labels: 🕵️‍♀️ needs review

#6959 Add menu2 recycler view adapter
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/CompoundMenuCandidateViewHolders.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/DecorativeTextMenuCandidateViewHolder.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/DividerMenuCandidateViewHolder.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/LastItemViewHolder.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/MenuCandidateListAdapter.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/MenuCandidateViewHolder.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/RowMenuCandidateViewHolder.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/SmallMenuCandidateViewHolder.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/TextMenuCandidateViewHolder.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/icons/DrawableMenuIconViewHolders.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/icons/MenuIconAdapter.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/icons/MenuIconViewHolder.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/adapter/icons/TextMenuIconViewHolder.kt
  components/browser/menu2/src/main/java/mozilla/components/browser/menu2/ext/View.kt
  components/browser/menu2/src/main/res/anim/menu_enter_bottom.xml
  components/browser/menu2/src/main/res/anim/menu_enter_top.xml
  components/browser/menu2/src/main/res/anim/menu_exit.xml
  components/browser/menu2/src/main/res/drawable/mozac_browser_menu2_indicator.xml
  components/browser/menu2/src/main/res/drawable/mozac_browser_menu2_notification.xml
  components/browser/menu2/src/main/res/drawable/mozac_browser_menu2_notification_icon.xml
  components/browser/menu2/src/main/res/layout/mozac_browser_menu2_candidate_compound_checkbox.xml
  components/browser/menu2/src/main/res/layout/mozac_browser_menu2_candidate_compound_switch.xml
  components/browser/menu2/src/main/res/layout/mozac_browser_menu2_candidate_decorative_text.xml
  components/browser/menu2/src/main/res/layout/mozac_browser_menu2_candidate_divider.xml
  components/browser/menu2/src/main/res/layout/mozac_browser_menu2_candidate_row.xml
  components/browser/menu2/src/main/res/layout/mozac_browser_menu2_candidate_row_small_icon.xml
  components/browser/menu2/src/main/res/layout/mozac_browser_menu2_candidate_text.xml
  components/browser/menu2/src/main/res/layout/mozac_browser_menu2_icon_button.xml
  components/browser/menu2/src/main/res/layout/mozac_browser_menu2_icon_drawable.xml
  components/browser/menu2/src/main/res/layout/mozac_browser_menu2_icon_notification_dot.xml
  components/browser/menu2/src/main/res/layout/mozac_browser_menu2_icon_text.xml
  components/browser/menu2/src/main/res/values-ldrtl/dimens.xml
  components/browser/menu2/src/main/res/values/dimens.xml
  components/browser/menu2/src/main/res/values/strings.xml
  components/browser/menu2/src/main/res/values/style.xml
  components/browser/menu2/src/test/java/mozilla/components/browser/menu2/adapter/CompoundMenuCandidateViewHolderTest.kt
  components/browser/menu2/src/test/java/mozilla/components/browser/menu2/adapter/DecorativeTextMenuCandidateViewHolderTest.kt
  components/browser/menu2/src/test/java/mozilla/components/browser/menu2/adapter/DividerMenuCandidateViewHolderTest.kt
  components/browser/menu2/src/test/java/mozilla/components/browser/menu2/adapter/MenuCandidateListAdapterTest.kt
  components/browser/menu2/src/test/java/mozilla/components/browser/menu2/adapter/RowMenuCandidateViewHolderTest.kt
  components/browser/menu2/src/test/java/mozilla/components/browser/menu2/adapter/SmallMenuCandidateViewHolderTest.kt
  components/browser/menu2/src/test/java/mozilla/components/browser/menu2/adapter/TextMenuCandidateViewHolderTest.kt
  components/browser/menu2/src/test/java/mozilla/components/browser/menu2/adapter/icons/DrawableMenuIconViewHoldersTest.kt
  components/browser/menu2/src/test/java/mozilla/components/browser/menu2/adapter/icons/MenuIconAdapterTest.kt
  components/browser/menu2/src/test/java/mozilla/components/browser/menu2/adapter/icons/TextMenuIconViewHolderTest.kt
  components/browser/menu2/src/test/java/mozilla/components/browser/menu2/ext/ViewTest.kt
  components/browser/menu2/src/test/resources/robolectric.properties
  components/concept/menu/src/main/java/mozilla/components/concept/menu/candidate/MenuCandidate.kt
  components/concept/menu/src/main/java/mozilla/components/concept/menu/candidate/MenuIcon.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7061 Closes #7047: Add handling for onSubframeLoadRequest for GeckoEngineSession
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing

#7078 Closes #7062: Add nested menu UI for web extensions actions
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/AbstractParentBrowserMenuItem.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BackPressMenuItem.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/ParentBrowserMenuItem.kt
  components/browser/menu/src/main/res/values/strings.xml
  components/browser/menu/src/test/java/mozilla/components/browser/menu/BrowserMenuTest.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilderTest.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/AbstractParentBrowserMenuItemTest.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/ParentBrowserMenuItemTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#7058 For #7043 - onSelectionChanged won't trigger autocomplete suggestions
  components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
Labels: <autocomplete>

#7112 Public Suffix List update (20200526-140442)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#7100 Issue #7011: Correctly evaluate memory trimming levels.
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
Labels: 🕵️‍♀️ needs review

#7124 Docs update (20200527-120845) [ci skip]
  docs/api/mozilla.components.browser.menu.item/-browser-menu-item-toolbar/bind.md
  docs/api/mozilla.components.browser.menu.item/-browser-menu-item-toolbar/get-layout-resource.md
  docs/api/mozilla.components.browser.menu.item/-browser-menu-item-toolbar/index.md
  docs/api/mozilla.components.browser.menu.item/-browser-menu-item-toolbar/interactive-count.md
  docs/api/mozilla.components.browser.menu.item/-browser-menu-item-toolbar/visible.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-c-a-n-c-e-l.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-d-i-s-m-i-s-s.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-o-p-e-n.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-p-a-u-s-e.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-r-e-s-u-m-e.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-a-c-t-i-o-n_-t-r-y_-a-g-a-i-n.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-c-o-m-p-a-t_-d-e-f-a-u-l-t_-f-o-r-e-g-r-o-u-n-d_-i-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/-a-c-t-i-v-e.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/-c-a-n-c-e-l-l-e-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/-c-o-m-p-l-e-t-e-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/-f-a-i-l-e-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/-p-a-u-s-e-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-download-job-status/index.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-e-x-t-r-a_-d-o-w-n-l-o-a-d.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/-e-x-t-r-a_-d-o-w-n-l-o-a-d_-s-t-a-t-u-s.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/http-client.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/index.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/on-bind.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/on-create.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/on-destroy.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/on-start-command.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/on-task-removed.md
  docs/api/mozilla.components.feature.downloads/-abstract-fetch-download-service/open-file.md
  docs/api/mozilla.components.ui.autocomplete/-inline-autocomplete-edit-text/-i-n-p-u-t_-m-e-t-h-o-d_-a-m-a-z-o-n_-e-c-h-o_-s-h-o-w.md
  docs/api/mozilla.components.ui.autocomplete/-inline-autocomplete-edit-text/-i-n-p-u-t_-m-e-t-h-o-d_-s-o-n-y.md
  docs/api/mozilla.components.ui.autocomplete/-inline-autocomplete-edit-text/apply-autocomplete-result.md
  docs/api/mozilla.components.ui.autocomplete/-inline-autocomplete-edit-text/dispatch-key-event-pre-ime.md
  docs/api/mozilla.components.ui.autocomplete/-inline-autocomplete-edit-text/no-autocomplete-result.md
  docs/api/mozilla.components.ui.autocomplete/-inline-autocomplete-edit-text/on-create-input-connection.md
  docs/api/mozilla.components.ui.autocomplete/-inline-autocomplete-edit-text/on-key-pre-ime.md
  docs/api/mozilla.components.ui.autocomplete/-inline-autocomplete-edit-text/on-selection-changed.md
  docs/api/mozilla.components.ui.autocomplete/-inline-autocomplete-edit-text/on-text-context-menu-item.md
  docs/api/mozilla.components.ui.autocomplete/-inline-autocomplete-edit-text/on-touch-event.md
  docs/api/mozilla.components.ui.autocomplete/-inline-autocomplete-edit-text/on-window-focus-changed.md
Labels: 🛬 needs landing

#7125 Public Suffix List update (20200527-140953)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#7133 For #7132 - Update to new Autocomplete API
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/autofill/GeckoLoginDelegateWrapper.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
Labels: 🛬 needs landing

#7128 Closes #7113: Implement the before unload prompt
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/res/values/strings.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#7147 Closes #7145: Switch sample-browser to browser-storage-sync
  samples/browser/build.gradle
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt
Labels: 🕵️‍♀️ needs review

#7137 Closes #7129: Stop sending caught exceptions to Socorro
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
Labels: 🕵️‍♀️ needs review

#7154 Add blog posting about engine dependent feature flags.
  docs/_posts/2020-05-28-engine-version-feature-flags.md
Labels: 🛬 needs landing

#7156 Public Suffix List update (20200528-140449)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#7111 For #7110: Dismiss menu popup window when anchor is detached from window.
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/BrowserMenuTest.kt
Labels: 🕵️‍♀️ needs review

#7106 Import MVP-version of the "Report Site Issue" feature ported from Desktop.
  .buildconfig.yml
  README.md
  components/feature/webcompat-reporter/README.md
  components/feature/webcompat-reporter/build.gradle
  components/feature/webcompat-reporter/proguard-rules.pro
  components/feature/webcompat-reporter/src/main/AndroidManifest.xml
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/.eslintrc.js
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/background.js
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/aboutConfigPrefs.js
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/aboutConfigPrefs.json
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/browserInfo.js
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/browserInfo.json
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/icons/lightbulb.svg
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json
  components/feature/webcompat-reporter/src/main/java/mozilla/components/feature/webcompat/reporter/WebCompatReporterFeature.kt
  samples/browser/build.gradle
  samples/browser/src/geckoBeta/java/org/mozilla/samples/browser/Components.kt
  samples/browser/src/geckoNightly/java/org/mozilla/samples/browser/Components.kt
  samples/browser/src/geckoRelease/java/org/mozilla/samples/browser/Components.kt
  taskcluster/ci/build/kind.yml
  taskcluster/ci/config.yml
Labels: 🕵️‍♀️ needs review

#7152 Closes #7150: Media notification: Set flag to replace existing pending intent.
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaServiceDelegateTest.kt
Labels: 🕵️‍♀️ needs review

#7102 Make sure the bottom toolbar is never stuck invisible
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehaviorTest.kt
Labels: 🕵️‍♀️ needs review

#7172 Close #7164: Add getSubscription to AutoPushFeature if one exists
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webpush/GeckoWebPushDelegateTest.kt
  components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt
  components/feature/push/src/main/java/mozilla/components/feature/push/Connection.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/AutoPushFeatureTest.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/RustPushConnectionTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review
