Repository mozilla-mobile/android-components, pull requests merged in 2020-06, with the labels that each got.

#7197 Docs update (20200601-120842) [ci skip]
  docs/api/alltypes/index.md
  docs/api/index.md
  docs/api/mozilla.components.browser.menu.item/-parent-browser-menu-item/as-candidate.md
  docs/api/mozilla.components.browser.toolbar.behavior/-browser-toolbar-bottom-behavior/force-expand.md
  docs/api/mozilla.components.browser.toolbar.behavior/-browser-toolbar-bottom-behavior/layout-depends-on.md
  docs/api/mozilla.components.browser.toolbar.behavior/-browser-toolbar-bottom-behavior/on-intercept-touch-event.md
  docs/api/mozilla.components.browser.toolbar.behavior/-browser-toolbar-bottom-behavior/on-start-nested-scroll.md
  docs/api/mozilla.components.browser.toolbar.behavior/-browser-toolbar-bottom-behavior/on-stop-nested-scroll.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/-observer/index.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/-observer/on-message-received.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/-observer/on-subscription-changed.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/get-subscription.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/index.md
  docs/api/mozilla.components.feature.push/-auto-push-feature/renew-registration.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription-changed/channel-id.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription-changed/index.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription-changed/scope.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/app-server-key.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/auth-key.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/endpoint.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/index.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/public-key.md
  docs/api/mozilla.components.feature.push/-auto-push-subscription/scope.md
  docs/api/mozilla.components.feature.push/-decrypted-message/equals.md
  docs/api/mozilla.components.feature.push/-decrypted-message/hash-code.md
  docs/api/mozilla.components.feature.push/-decrypted-message/index.md
  docs/api/mozilla.components.feature.push/-decrypted-message/message.md
  docs/api/mozilla.components.feature.push/-decrypted-message/scope.md
  docs/api/mozilla.components.feature.push/-protocol/-h-t-t-p-s.md
  docs/api/mozilla.components.feature.push/-protocol/-h-t-t-p.md
  docs/api/mozilla.components.feature.push/-protocol/index.md
  docs/api/mozilla.components.feature.push/-push-config/index.md
  docs/api/mozilla.components.feature.push/-push-config/protocol.md
  docs/api/mozilla.components.feature.push/-push-config/sender-id.md
  docs/api/mozilla.components.feature.push/-push-config/server-host.md
  docs/api/mozilla.components.feature.push/-push-config/service-type.md
  docs/api/mozilla.components.feature.push/-push-connection/contains-subscription.md
  docs/api/mozilla.components.feature.push/-push-connection/decrypt-message.md
  docs/api/mozilla.components.feature.push/-push-connection/index.md
  docs/api/mozilla.components.feature.push/-push-connection/is-initialized.md
  docs/api/mozilla.components.feature.push/-push-connection/update-token.md
  docs/api/mozilla.components.feature.push/-push-connection/verify-connection.md
  docs/api/mozilla.components.feature.push/-service-type/-a-d-m.md
  docs/api/mozilla.components.feature.push/-service-type/-f-c-m.md
  docs/api/mozilla.components.feature.push/-service-type/index.md
  docs/api/mozilla.components.feature.session/-thumbnails-feature/-init-.md
  docs/api/mozilla.components.feature.session/-thumbnails-feature/index.md
  docs/api/mozilla.components.feature.session/-thumbnails-feature/start.md
  docs/api/mozilla.components.feature.session/-thumbnails-feature/stop.md
  docs/api/mozilla.components.feature.session/index.md
  docs/api/mozilla.components.feature.tabs.tabstray/-tabs-feature/-init-.md
  docs/api/mozilla.components.feature.tabs.tabstray/-tabs-feature/index.md
  docs/api/mozilla.components.feature.tabs.tabstray/-tabs-tray-presenter/-init-.md
  docs/api/mozilla.components.feature.tabs.tabstray/-tabs-tray-presenter/index.md
  docs/api/mozilla.components.feature.webcompat.reporter/-web-compat-reporter-feature/index.md
  docs/api/mozilla.components.feature.webcompat.reporter/-web-compat-reporter-feature/install.md
  docs/api/mozilla.components.feature.webcompat.reporter/index.md
  docs/api/mozilla.components.support.base.feature/-lifecycle-aware-feature/index.md
  docs/api/package-list
Labels: 🛬 needs landing

#7201 Closes #6855: Do not use unsupportedAddon as global value
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
Labels: 🕵️‍♀️ needs review

#7083 Use private keyboard for find in page in private mode
  components/feature/findinpage/src/main/java/mozilla/components/feature/findinpage/internal/FindInPagePresenter.kt
  components/feature/findinpage/src/main/java/mozilla/components/feature/findinpage/view/FindInPageBar.kt
  components/feature/findinpage/src/main/java/mozilla/components/feature/findinpage/view/FindInPageView.kt
  components/feature/findinpage/src/test/java/mozilla/components/feature/findinpage/internal/FindInPagePresenterTest.kt
  components/feature/findinpage/src/test/java/mozilla/components/feature/findinpage/view/FindInPageBarTest.kt
Labels: 🛬 needs landing

#7140 Add getNormalOrPrivateTabs function to BrowserState
  components/browser/state/src/main/java/mozilla/components/browser/state/selector/Selectors.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/selector/SelectorsKtTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#7213 Merge day!
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/docs/metrics.md
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/autofill/GeckoLoginDelegateWrapper.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/media/GeckoMediaTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
Labels: 🛬 needs landing

#7182 Closes #7181 - Do not crash on nonimplemented select login prompt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
Labels: 🛬 needs landing

#7206 Closes #7131: Stop delegating uncaught exceptions to default exception handler
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/ExceptionHandler.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/ExceptionHandlerTest.kt
Labels: 🕵️‍♀️ needs review

#7209 Update Glean to include new upload mechanism (& gzip)
  buildSrc/src/main/java/Dependencies.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/net/ConceptFetchHttpUploader.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/net/ConceptFetchHttpUploaderTest.kt
  docs/changelog.md
Labels: ✏️ needs changes

#7226 GeckoView update (nightly) (20200603-140700)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7225 GeckoView update (release) (20200603-140708)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7224 GeckoView update (beta) (20200603-140649)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7221 Closes #7220: Add expiry to browser package names discovery
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing

#7231 Closes #7230: Add downloads to the system download database for devices older than Q
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#7232 Closes #7229: Remove browserPackageNames in AppLinksUseCases
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🕵️‍♀️ needs review

#7169 Closes #7168 - Expose new GeckoRuntimeSetting setLoginAutofillEnabled…
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7280 Closes #7279: Do not pass non-http(s) url to addCompletedDownload
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ext/Context.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing

#7260 Closes #7256 - Updates save login dialog strings
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/LoginDialogFragment.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_prompt_login_prompt.xml
  components/feature/prompts/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#7287 Closes #7286 - Hide the keyboard when the find in page bar is unfocused
  components/feature/findinpage/src/main/java/mozilla/components/feature/findinpage/view/FindInPageBar.kt
  components/feature/findinpage/src/test/java/mozilla/components/feature/findinpage/view/FindInPageBarTest.kt
Labels: 🛬 needs landing

#7239 Close #7236: Fix last verification check in AutoPushFeature
  components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/AutoPushFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7274 Closes #7271 Mark downloads as failed when exception occur when fetching
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing

#7309 Closes #7308: Update the store queuedDownloads when mutate the download state.
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/DownloadStateReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/DownloadActionTest.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing

#7251 Move PIP to BrowserState, use for toolbar visibility
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/WebAppHideToolbarFeature.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/feature/WebAppHideToolbarFeatureTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/PictureInPictureFeature.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/PictureInPictureFeatureTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/net/Uri.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/net/UriTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#7356 Issue #7313: Use ThumbnailLoader for the TabViewHolder
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/tabstray/build.gradle
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabsAdapter.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/thumbnail/TabThumbnailView.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/DefaultTabViewHolderTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabTouchCallbackTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabsAdapterTest.kt
  components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/thumbnail/TabThumbnailViewTest.kt
  components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/loader/ThumbnailLoader.kt
  components/browser/thumbnails/src/main/res/values/tags.xml
  components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/loader/ThumbnailLoaderTest.kt
  components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/Tab.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenter.kt
  components/support/images/build.gradle
  components/support/images/src/main/java/mozilla/components/support/images/CancelOnDetach.kt
  components/support/images/src/main/java/mozilla/components/support/images/loader/ImageLoader.kt
  components/support/images/src/test/java/mozilla/components/support/images/CancelOnDetachTest.kt
  docs/changelog.md
  samples/browser/build.gradle
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#7357 Close #7297: Add support for source URL to WebNotification
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegate.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegate.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegate.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webnotifications/WebNotification.kt
  components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/NativeNotificationBridge.kt
  components/feature/webnotifications/src/test/java/mozilla/components/feature/webnotifications/NativeNotificationBridgeTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7379 Close #7372: Select regular tab ID first if it exists for PromptFeature
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7360 Closes #7359: Register WebCompat add-on with ID matching manifest
  components/feature/webcompat/src/main/java/mozilla/components/feature/webcompat/WebCompatFeature.kt
Labels: 🛬 needs landing

#7330 Combine ktlint and detekt ci jobs
  taskcluster/ci/lint/kind.yml
Labels: 🛬 needs landing

#7400 Closes issue #7398: Avoid passing negative values to the download contentLength
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
Labels: 🛬 needs landing

#7377 For #7376 - Update canClearSelection to check if text is empty
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko-beta/src/test/java/org/mozilla/geckoview/MockSelection.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko-nightly/src/test/java/org/mozilla/geckoview/MockSelection.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko/src/test/java/org/mozilla/geckoview/MockSelection.kt
Labels: 🕵️‍♀️ needs review

#7396 For #7392 - Material design sanity checks for BrowserMenu min/max width
  components/browser/menu/src/main/java/mozilla/components/browser/menu/view/DynamicWidthRecyclerView.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/view/DynamicWidthRecyclerViewTest.kt
  docs/changelog.md
Labels: 🐉 Fenix

#7404 Docs update (20200616-121031) [ci skip]
  docs/api/mozilla.components.browser.menu.view/-dynamic-width-recycler-view/index.md
  docs/api/mozilla.components.browser.menu.view/-dynamic-width-recycler-view/on-measure.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/-init-.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/content-length.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/content-type.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/destination-directory.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/file-name.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/file-path.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/id.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/index.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/referrer-url.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/session-id.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/skip-confirmation.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/url.md
  docs/api/mozilla.components.browser.state.state.content/-download-state/user-agent.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/gravity.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/index.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/positive-button-background-color.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/positive-button-radius.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/positive-button-text-color.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/-prompts-styling/should-width-match-parent.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/on-permissions-result.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/stop.md
  docs/api/mozilla.components.feature.downloads/-downloads-feature/try-again.md
Labels: 🛬 needs landing

#7052 For #7046 - Rewrite room queries
  components/feature/share/build.gradle
  components/feature/share/src/androidTest/java/mozilla/components/feature/share/RecentAppsDaoTest.kt
  components/feature/share/src/main/java/mozilla/components/feature/share/RecentAppsStorage.kt
  components/feature/share/src/main/java/mozilla/components/feature/share/db/RecentAppEntity.kt
  components/feature/share/src/main/java/mozilla/components/feature/share/db/RecentAppsDao.kt
  components/feature/share/src/test/java/mozilla/components/feature/share/RecentAppStorageTest.kt
  taskcluster/ci/test/kind.yml
Labels: ✏️ needs changes

#7329 Closes #7327: Crash and telemetry send service should be on separate process
  components/lib/crash/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#7433 Docs update (20200618-121101) [ci skip]
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/account-migration-in-flight.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/account-needs-reauth.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/account-profile.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/authenticated-account.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/begin-authentication-async.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/close.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/create-account.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/finish-authentication-async.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/index.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/init-async.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/is-sync-active.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/logout-async.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/register-for-account-events.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/register-for-sync-events.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/set-sync-config-async.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/shareable-accounts.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/sign-in-with-shareable-account-async.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/supported-sync-engines.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/sync-now-async.md
  docs/api/mozilla.components.service.fxa.manager/-fxa-account-manager/update-profile-async.md
  docs/api/mozilla.components.service.fxa.manager/-s-c-o-p-e_-p-r-o-f-i-l-e.md
  docs/api/mozilla.components.service.fxa.manager/-s-c-o-p-e_-s-e-s-s-i-o-n.md
  docs/api/mozilla.components.service.fxa.manager/-s-c-o-p-e_-s-y-n-c.md
  docs/api/mozilla.components.service.fxa.manager/-sign-in-with-shareable-account-result/-failure.md
  docs/api/mozilla.components.service.fxa.manager/-sign-in-with-shareable-account-result/-success.md
  docs/api/mozilla.components.service.fxa.manager/-sign-in-with-shareable-account-result/-will-retry.md
  docs/api/mozilla.components.service.fxa.manager/-sign-in-with-shareable-account-result/index.md
Labels: 🛬 needs landing

#7432 For #7422 - Handles case where synced devices exist but have no open tabs
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/RemoteTabsStorage.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/SyncedTabsStorageSuggestionProvider.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsProvider.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorage.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/view/SyncedTabsView.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/SyncedTabsStorageSuggestionProviderTest.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/controller/DefaultControllerTest.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorageTest.kt
Labels: <sync-tabs>

#7355 Fixes #7354: Changes the add-ons icon from toolbar menu
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt
  components/ui/icons/src/main/res/drawable/mozac_ic_addons_extensions.xml
Labels: 🛬 needs landing

#7419 For mozilla-mobile/fenix#11645: Update ic_device_mobile.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_device_mobile.xml
Labels: 🕵️‍♀️ needs review

#7437 Upgrade Application Services to v61.0.4
  buildSrc/src/main/java/Dependencies.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt
Labels: 🛬 needs landing

#7442 Issue #7441: Remove unused ThumbnailsUseCase
  components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/ThumbnailsUseCases.kt
  components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/ThumbnailsUseCasesTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsFeature.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenter.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsFeatureTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/TabsTrayFragment.kt
Labels: 🛬 needs landing

#7471 Closes #7470 - Uplift private notification service
  components/feature/privatemode/build.gradle
  components/feature/privatemode/src/main/java/mozilla/components/feature/privatemode/notification/AbstractPrivateNotificationService.kt
  components/feature/privatemode/src/main/java/mozilla/components/feature/privatemode/notification/PrivateNotificationFeature.kt
  components/feature/privatemode/src/main/res/values/strings.xml
  components/feature/privatemode/src/test/java/mozilla/components/feature/privatemode/notification/AbstractPrivateNotificationServiceTest.kt
  components/feature/privatemode/src/test/java/mozilla/components/feature/privatemode/notification/PrivateNotificationFeatureTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/notification/Notification.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7514 For #7468 - Don't set notification style on Huawei devices on lollipop
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
Labels: 🛬 needs landing

#7499 Close #7495: Wait for firstContentfulPaint in BrowserThumbnail
  components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/BrowserThumbnails.kt
  components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/BrowserThumbnailsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#7515 For #7181 - Add no-op fix for beta onLoginSelect crash
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
Labels: 🕵️‍♀️ needs review

#7522 Closes #7161: Check site permissions before showing web notification
  components/feature/webnotifications/build.gradle
  components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/WebNotificationFeature.kt
  components/feature/webnotifications/src/test/java/mozilla/components/feature/webnotifications/WebNotificationFeatureTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#7513 For #7512 - Set parent session as selected session in NewTabSearchUse…
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
  components/feature/search/build.gradle
  components/feature/search/src/main/java/mozilla/components/feature/search/SearchUseCases.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/SearchUseCasesTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🕵️‍♀️ needs review

#7240 Issue #468: Define initial set of design axioms.
  docs/contribute/design_axioms.md
  docs/contributing.md
Labels: 🕵️‍♀️ needs review

#7544 AddonMigration: Update fallback list with M3 add-ons
  components/support/migration/src/main/java/mozilla/components/support/migration/AddonMigration.kt
Labels: 🛬 needs landing

#7572 Docs update (20200630-121300) [ci skip]
  docs/api/mozilla.components.browser.engine.gecko.autofill/-gecko-login-delegate-wrapper/index.md
  docs/api/mozilla.components.browser.engine.gecko.autofill/-gecko-login-delegate-wrapper/on-login-save.md
  docs/api/mozilla.components.browser.engine.gecko.autofill/-gecko-login-delegate-wrapper/on-login-used.md
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-port/disconnect.md
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-port/index.md
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-port/name.md
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-port/post-message.md
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-port/sender-url.md
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-web-extension/get-metadata.md
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-web-extension/has-tab-handler.md
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-web-extension/is-allowed-in-private-browsing.md
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-web-extension/is-enabled.md
  docs/api/mozilla.components.browser.engine.gecko.webextension/-gecko-web-extension/register-tab-handler.md
  docs/api/mozilla.components.support.migration/-addon-migration-exception/failure.md
  docs/api/mozilla.components.support.migration/-addon-migration-exception/index.md
  docs/api/mozilla.components.support.migration/-addon-migration-result/-failure.md
  docs/api/mozilla.components.support.migration/-addon-migration-result/-success/-addons-migrated/index.md
  docs/api/mozilla.components.support.migration/-addon-migration-result/-success/-addons-migrated/migrated-addons.md
  docs/api/mozilla.components.support.migration/-addon-migration-result/-success/-addons-migrated/to-string.md
  docs/api/mozilla.components.support.migration/-addon-migration-result/-success/-no-addons.md
  docs/api/mozilla.components.support.migration/-addon-migration-result/-success/index.md
  docs/api/mozilla.components.support.migration/-addon-migration-result/index.md
Labels: 🛬 needs landing

#7573 GeckoView update (beta) (20200630-140251)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#7561 Make gradle tasks in plugins lazy
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/GVVersionVerifierPlugin.kt
  buildSrc/src/main/java/Gecko.kt
  buildSrc/src/main/java/GitHubClient.kt
  buildSrc/src/main/java/GitHubPlugin.kt
  buildSrc/src/main/java/plugins/PublicSuffixListPlugin.kt
Labels: 🛬 needs landing

#7574 For mozilla-mobile/fenix#12137: Update sync icon
  components/ui/icons/src/main/res/drawable/mozac_ic_sync.xml
Labels: 🛬 needs landing
