Repository mozilla-mobile/android-components, pull requests merged in 2020-03, with the labels that each got.

#6136 For #6102 - When tinting ImageViews, use AppCompatImageView and app:tint
  components/feature/addons/src/main/res/layout/mozac_feature_addons_fragment_dialog_addon_permissions.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_section_unsupported_section_item.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_unsupported_item.xml
  components/feature/downloads/src/main/res/layout/mozac_downloads_prompt.xml
  components/feature/findinpage/src/main/res/values/style.xml
  components/feature/sitepermissions/src/main/res/layout/mozac_site_permissions_prompt.xml
  samples/browser/src/main/res/layout/activity_add_on_details.xml
Labels: 🛬 needs landing

#6100 Bug 1615248 - add same cron entries for nightlies as we do for snapsh…
  .cron.yml
Labels: 🕵️‍♀️ needs review

#6112 For #6102 : Add lint checks for using app namespace for vector drawables
  components/tooling/lint/src/main/java/mozilla/components/tooling/lint/AndroidSrcXmlDetector.kt
  components/tooling/lint/src/main/java/mozilla/components/tooling/lint/ImageViewAndroidTintXmlDetector.kt
  components/tooling/lint/src/main/java/mozilla/components/tooling/lint/LintIssueRegistry.kt
  components/tooling/lint/src/main/java/mozilla/components/tooling/lint/LintLogChecks.kt
  components/tooling/lint/src/main/java/mozilla/components/tooling/lint/TextViewAndroidSrcXmlDetector.kt
  components/tooling/lint/src/test/java/mozilla/components/tooling/lint/AndroidSrcXmlDetectorTest.kt
  components/tooling/lint/src/test/java/mozilla/components/tooling/lint/ImageViewAndroidTintXmlDetectorTest.kt
  components/tooling/lint/src/test/java/mozilla/components/tooling/lint/TextViewAndroidSrcXmlDetectorTest.kt
  samples/browser/src/main/res/layout/overlay_add_on_progress.xml
  samples/toolbar/src/main/res/layout/focus_blocking_switch.xml
Labels: 🛬 needs landing

#6138 For #6137: Set BrowserMenuCategory padding same as other items in menu
  components/browser/menu/src/main/res/values/dimens.xml
Labels: 🛬 needs landing

#6068 Closes #4562: Migrate feature-awesomebar to use browser-state.
  components/feature/accounts/build.gradle
  components/feature/awesomebar/build.gradle
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProviderTest.kt
  components/feature/contextmenu/build.gradle
  components/feature/tabs/build.gradle
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#6156 Closes #6117: Disable TypographyEllipsis lint check.
  build.gradle
Labels: 🕵️‍♀️ needs review

#6159 Issue #6097: Remove IntentProcessor.matches().
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabIntentProcessor.kt
  components/feature/intent/src/main/java/mozilla/components/feature/intent/processing/IntentProcessor.kt
  components/feature/intent/src/main/java/mozilla/components/feature/intent/processing/TabIntentProcessor.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/intent/TrustedWebActivityIntentProcessor.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessor.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/intent/TrustedWebActivityIntentProcessorTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessorTest.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/MigrationIntentProcessor.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/MigrationIntentProcessorTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/IntentReceiverActivity.kt
Labels: 🕵️‍♀️ needs review

#6127 Closes #6147: Launch intent in third party app if URL scheme is not supported by engine
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  config/detekt-baseline.xml
Labels: 🕵️‍♀️ needs review

#6080 Closes #6079: Add strictSocialTrackingProtection on SessionTypes PrivateOnly and RegularOnly
  components/concept/engine/build.gradle
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6141 Feature/#6140 add toolbar menu dismiss setter
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/MenuButton.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/MenuButtonTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6166 Closes issue #5616: When present use sitePermissionsRules for new sitePermissions exceptions
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsRules.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsRulesTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6153 Closes #6145: Do not invoke close callback on start
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsFeature.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenter.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsFeatureTest.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenterTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/TabsTrayFragment.kt
Labels: 🕵️‍♀️ needs review

#6170 On memory pressure close engine sessions and keep state for restoring later.
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/browser/state/build.gradle
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/SystemReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/SystemActionTest.kt
  components/support/base/src/main/java/mozilla/components/support/base/memory/MemoryConsumer.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt
Labels: 🕵️‍♀️ needs review

#6179 GeckoView update (nightly) (20200305-140730)
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/docs/metrics.md
Labels: 🛬 needs landing

#6181 Closes #6180: Update browser-engine-gecko to GeckoView 74 RC2.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko/docs/metrics.md
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/autofill/GeckoLoginDelegateWrapper.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequestTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/test/ReflectionUtils.kt
Labels: 🕵️‍♀️ needs review

#6183 Closes #6163: Update the tracking protection lists in SystemEngine
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/matcher/UrlMatcher.kt
  components/browser/engine-system/src/main/res/raw/domain_blacklist.json
  components/browser/engine-system/src/main/res/raw/domain_overrides.json
  components/browser/engine-system/src/main/res/raw/domain_whitelist.json
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/matcher/UrlMatcherTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6191 GeckoView update (nightly) (20200306-140621)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6123 Closes #5434: Notify user when previously unsupported addons become available
  components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/migration/DefaultSupportedAddonCheckerTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/migration/SupportedAddonsWorkerTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt
Labels: 🕵️‍♀️ needs review

#6139 For #6202 - Fix autocomplete not being generated on first key press
  components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
Labels: 🕵️‍♀️ needs review

#6190 For #6189 - Update Logins Dialog to match Specs
  components/feature/prompts/src/main/res/layout/mozac_feature_prompt_login_prompt.xml
Labels: 🛬 needs landing

#6222 Closes #6221: Allow applications to specify release channel for Socorro
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
Labels: 🛬 needs landing

#6234 Improve descriptions on add-on strings
  components/feature/addons/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#6195 Closes #6149: Notify push observers for onSubscriptionChange events
  buildSrc/src/main/java/Dependencies.kt
  components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt
  components/feature/push/src/main/java/mozilla/components/feature/push/Connection.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/AutoPushFeatureTest.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/ConnectionKtTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6260 Issue #6255: Do not attempt to update unsupported add-ons
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/webextension/WebExtensionTest.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/test/java/AddonManagerTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/DefaultAddonUpdaterTest.kt
Labels: 🛬 needs landing

#6262 Closes #9150: Do not prompt users for invalid add-on permissions.
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/DefaultAddonUpdaterTest.kt
Labels: 🕵️‍♀️ needs review

#6275 GeckoView update (beta) (20200316-140843)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6264 Closes #6263 Sanitize the exceptions sent by the SupportedAddonsChecker
  components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/migration/SupportedAddonsWorkerTest.kt
Labels: 🕵️‍♀️ needs review

#6273 Public Suffix List update (20200316-140834)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#6274 GeckoView update (nightly) (20200316-140834)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6277 Fix addons_updater_notification_content_singular string
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/DefaultAddonUpdaterTest.kt
Labels: 🛬 needs landing

#6293 GeckoView update (nightly) (20200317-140920)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6285 Update Kotlin version to 1.3.7.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#6312 GeckoView update (nightly) (20200318-140448)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6320 GeckoView update (nightly) (20200319-140511)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6203 Closes #6092: Add download link in context menu.
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/main/res/values/strings.xml
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
Labels: 🕵️‍♀️ needs review

#6309 Bugfix/#6308 optional highlight propagation
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenuHighlight.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/ext/BrowserMenuItem.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/ext/BrowserMenuItemTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6323 Closes #6322: Clear the site permission cache after updating or removing
  components/concept/engine/src/main/java/mozilla/components/concept/engine/DataCleanable.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Engine.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsStorage.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsStorageTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6349 GeckoView update (beta) (20200323-140733)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6348 GeckoView update (nightly) (20200323-140719)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6347 Public Suffix List update (20200323-140836)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#6345 Docs update (20200323-121026) [ci skip]
  docs/api/mozilla.components.browser.menu.item/-browser-menu-highlightable-item/-highlight/index.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-classic-highlight/-init-.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-classic-highlight/background-resource.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-classic-highlight/can-propagate.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-classic-highlight/color-resource.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-classic-highlight/end-image-resource.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-classic-highlight/index.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-classic-highlight/label.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-classic-highlight/start-image-resource.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-high-priority/-init-.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-high-priority/background-tint.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-high-priority/can-propagate.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-high-priority/end-image-resource.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-high-priority/index.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-high-priority/label.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-low-priority/-init-.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-low-priority/can-propagate.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-low-priority/index.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-low-priority/label.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/-low-priority/notification-tint.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/can-propagate.md
  docs/api/mozilla.components.browser.menu/-browser-menu-highlight/index.md
  docs/api/mozilla.components.browser.menu/-highlightable-menu-item/highlight.md
  docs/api/mozilla.components.browser.menu/-highlightable-menu-item/index.md
  docs/api/mozilla.components.browser.menu/-highlightable-menu-item/is-highlighted.md
Labels: 🛬 needs landing

#6346 Closes #6344: Use activityName instead of packageName as primary key.
  components/feature/share/schemas/mozilla.components.feature.share.db.RecentAppsDatabase/2.json
  components/feature/share/src/main/java/mozilla/components/feature/share/RecentApp.kt
  components/feature/share/src/main/java/mozilla/components/feature/share/RecentAppsStorage.kt
  components/feature/share/src/main/java/mozilla/components/feature/share/adapter/RecentAppAdapter.kt
  components/feature/share/src/main/java/mozilla/components/feature/share/db/RecentAppEntity.kt
  components/feature/share/src/main/java/mozilla/components/feature/share/db/RecentAppsDao.kt
  components/feature/share/src/main/java/mozilla/components/feature/share/db/RecentAppsDatabase.kt
  components/feature/share/src/test/java/mozilla/components/feature/share/RecentAppStorageTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6355 For #2985: Expose base URL for web extension pages
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
Labels: 🕵️‍♀️ needs review

#6301 Closes #6299: Auto reject any media site permission when a system permission is not allowed first
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6363 Update Kotlin to 1.3.71.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#6339 Closes #6278: Expose information about the last attempt to update an add-on
  components/feature/addons/build.gradle
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/db/UpdateAttemptDao.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/db/UpdateAttemptEntity.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/db/UpdateAttemptsDatabase.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/ExtensionsTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/AddonUpdaterWorkerTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/DefaultAddonUpdaterTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/UpdateAttemptStorageTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/UpdateStatusStorageTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/db/UpdateAttemptEntityTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonDetailsActivity.kt
Labels: 🛬 needs landing

#6373 Closes #6372: Ignore JobCancellationException for add-on workers
  components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/worker/Extensions.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/worker/ExtensionsTest.kt
Labels: 🛬 needs landing

#6383 GeckoView update (nightly) (20200325-140815)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6382 GeckoView update (beta) (20200325-140640)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6376 Closes #6369. Add ThrowProperty to support-test
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt
  components/support/test/src/main/java/mozilla/components/support/test/ThrowProperty.kt
  components/support/test/src/test/java/mozilla/components/support/test/ThrowPropertyTest.kt
Labels: ✏️ needs changes

#6306 Closes #6194: Re-subscribe for push on subscription change events
  components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/AccountObserverTest.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/AutoPushObserverTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6395 Closes #6354 - Take Lazy references to storage in FennecMigrator
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecMigratorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6396 Closes #6394 - Add warm-up API to places and logins storage layers
  components/browser/storage-memory/src/main/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/RemoteTabsStorage.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/Storage.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/HistoryDelegateTest.kt
  components/service/sync-logins/build.gradle
  components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/SyncableLoginsStorage.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/Performance.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6403 GeckoView update (beta) (20200326-140654)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6404 GeckoView update (nightly) (20200326-140657)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6393 Closes #6317: Prevent inserting duplicate record into content resolver
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
Labels: 🛬 needs landing

#6406 Add api for customizing the ui of the AddonPermissionsAdapter and AddonsManagerAdapter
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonPermissionsAdapter.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
  components/feature/addons/src/main/res/layout/mozac_feature_addons_permission_item.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsPermissionsAdapterTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6425 Public Suffix List update (20200327-140449)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#6385 For #6384: Use uri as format argument in error pages description string
  components/browser/errorpages/src/main/java/mozilla/components/browser/errorpages/ErrorPages.kt
  components/browser/errorpages/src/test/java/mozilla/components/browser/errorpages/ErrorPagesTest.kt
Labels: 🕵️‍♀️ needs review

#6361 Closes #6352: Add contextId to BrowserState
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngine.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineTest.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/LegacySessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/SessionExtensions.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/storage/SnapshotSerializer.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerMigrationTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionManagerTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/ext/SessionExtensionsTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/storage/SessionStorageTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/storage/SnapshotSerializerTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/SessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Engine.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineTest.kt
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/TabCollectionStorageTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
Labels: 🕵️‍♀️ needs review

#6443 Closes #6441: Add contextId support to ContextMenuCandidate
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
Labels: 🕵️‍♀️ needs review

#6454 Improve Exception.shouldReport on add-on workers
  components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/worker/Extensions.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/worker/ExtensionsTest.kt
Labels: 🛬 needs landing

#6122 Fixes #6094: Check if we are able to open url
  components/feature/customtabs/build.gradle
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabWindowFeatureTest.kt
  docs/changelog.md
  samples/browser/build.gradle
  samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserFragment.kt
Labels: 🕵️‍♀️ needs review

#6431 For #6048: Adds forceExpand to BottomBrowserToolbarBehavior
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehaviorTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6428 Closes #6297: GeckoEngineView: Detach SelectionActionDelegate if session is no longer rendered.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#6465 Docs update (20200331-120751) [ci skip]
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/can-clear-selection.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/can-scroll-vertically-down.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/can-scroll-vertically-up.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/capture-thumbnail.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/clear-selection.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/index.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/on-detached-from-window.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/release.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/render.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/selection-action-delegate.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/set-dynamic-toolbar-max-height.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-view/set-vertical-clipping.md
  docs/api/mozilla.components.browser.toolbar.behavior/-browser-toolbar-bottom-behavior/force-expand.md
  docs/api/mozilla.components.browser.toolbar.behavior/-browser-toolbar-bottom-behavior/index.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-error-response/-content/data.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-error-response/-content/encoding.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-error-response/-content/index.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-error-response/-content/mime-type.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-error-response/-content/url.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-error-response/-uri/index.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-error-response/-uri/uri.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-error-response/index.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-interception-response/-app-intent/app-intent.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-interception-response/-app-intent/index.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-interception-response/-app-intent/url.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-interception-response/-content/data.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-interception-response/-content/encoding.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-interception-response/-content/index.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-interception-response/-content/mime-type.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-interception-response/-url/index.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-interception-response/-url/url.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/-interception-response/index.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/index.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/intercepts-app-initiated-requests.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/on-error-request.md
  docs/api/mozilla.components.concept.engine.request/-request-interceptor/on-load-request.md
  docs/api/mozilla.components.feature.app.links/-app-links-interceptor/index.md
  docs/api/mozilla.components.feature.customtabs/-custom-tab-window-feature/-init-.md
  docs/api/mozilla.components.feature.customtabs/-custom-tab-window-feature/index.md
  docs/api/mozilla.components.feature.customtabs/-custom-tab-window-feature/start.md
  docs/api/mozilla.components.feature.customtabs/-custom-tab-window-feature/stop.md
  docs/api/mozilla.components.feature.customtabs/-s-h-o-r-t-c-u-t_-c-a-t-e-g-o-r-y.md
Labels: 🛬 needs landing

#6471 Public Suffix List update (20200331-140704)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#6473 GeckoView update (nightly) (20200331-140657)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6472 GeckoView update (beta) (20200331-140652)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#6360 Closes issue #6388: Add remove functionality to the RecentAppsStorage
  components/feature/share/src/main/java/mozilla/components/feature/share/RecentAppsStorage.kt
  components/feature/share/src/main/java/mozilla/components/feature/share/db/RecentAppsDao.kt
  components/feature/share/src/test/java/mozilla/components/feature/share/RecentAppStorageTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#6371 Closes #6366: Improve service-experiments (Mako) startup performance
  components/service/experiments/src/main/java/mozilla/components/service/experiments/Experiments.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/ExperimentsTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/debug/ExperimentsDebugActivityTest.kt
Labels: 🕵️‍♀️ needs review

#5288 Add peer-to-peer communication
  .buildconfig.yml
  README.md
  components/feature/p2p/README.md
  components/feature/p2p/build.gradle
  components/feature/p2p/docs/feature-p2p-block-diagram.png
  components/feature/p2p/proguard-rules.pro
  components/feature/p2p/src/main/AndroidManifest.xml
  components/feature/p2p/src/main/assets/extensions/p2p/manifest.json
  components/feature/p2p/src/main/assets/extensions/p2p/p2p.js
  components/feature/p2p/src/main/java/mozilla/components/feature/p2p/P2PFeature.kt
  components/feature/p2p/src/main/java/mozilla/components/feature/p2p/internal/P2PInteractor.kt
  components/feature/p2p/src/main/java/mozilla/components/feature/p2p/internal/P2PPresenter.kt
  components/feature/p2p/src/main/java/mozilla/components/feature/p2p/view/P2PBar.kt
  components/feature/p2p/src/main/java/mozilla/components/feature/p2p/view/P2PView.kt
  components/feature/p2p/src/main/res/layout/mozac_feature_p2p_view.xml
  components/feature/p2p/src/main/res/values/mozac_feature_p2p_strings.xml
  components/feature/p2p/src/main/res/values/style.xml
  components/feature/p2p/src/test/java/mozilla/components/feature/p2p/P2PFeatureTest.kt
  components/feature/p2p/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/lib/nearby/src/main/java/mozilla/components/lib/nearby/NearbyConnection.kt
  components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionController.kt
  docs/changelog.md
  samples/browser/build.gradle
  samples/browser/src/main/AndroidManifest.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/integration/P2PIntegration.kt
  samples/browser/src/main/res/layout/fragment_browser.xml
Labels: 🛬 needs landing
