Repository mozilla-mobile/android-components, pull requests merged in 2020-01, with the labels that each got.

#5459 Closes #5148: Add notify and cancel extension functions to NotificationManagerCompat
  components/support/base/src/main/java/mozilla/components/support/base/ids/SharedIdsHelper.kt
Labels: 🕵️‍♀️ needs review

#5384 Issue #5376: Simpler method for determining whether a string is a search query
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/URLStringUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/URLStringUtilsTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#5472 GeckoView update (nightly) (20200106-140647)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5322 Closes issue #5143 Adds support for while updating an Addon it requires new permissions.
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionDelegate.kt
  components/feature/addons/build.gradle
  components/feature/addons/src/main/AndroidManifest.xml
  components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/GlobalAddonDependencyProvider.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/AddonUpdaterWorkerTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/DefaultAddonUpdaterTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/GlobalAddonDependencyProviderTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/GlobalAddonManagerProviderTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/NotificationHandlerServiceTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/UpdateStatusStorageTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/notification/Notification.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/notification/NotificationTest.kt
  components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt
Labels: 🕵️‍♀️ needs review

#5477 Remove accidental suffix from search engine
  components/browser/search/src/main/assets/searchplugins/ecosia.xml
Labels: 🛬 needs landing

#5486 Public Suffix List update (20200107-141143)
  components/lib/publicsuffixlist/src/main/assets/publicsuffixes
Labels: 🛬 needs landing

#5307 Issue #4872: Add lib-state based store for observing migration state.
  components/support/migration/build.gradle
  components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/state/MigrationAction.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/state/MigrationReducer.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/state/MigrationState.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/state/MigrationStore.kt
Labels: 🕵️‍♀️ needs review

#5523 GeckoView update (beta) (20200109-140758)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5507 Closes #5505: Fix Awesomebar text length calculation
  components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
  components/ui/autocomplete/src/test/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditTextTest.kt
Labels: 🛬 needs landing

#5511 Closes #5508: fix Intermittent test failure in CrashReporter
  components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/ExceptionHandlerTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/prompt/CrashReporterActivityTest.kt
Labels: 🛬 needs landing

#5484 Closes #3960 Support for bypassing SSL certificates
  components/browser/errorpages/src/main/java/mozilla/components/browser/errorpages/ErrorPages.kt
  components/browser/errorpages/src/main/res/raw/error_pages.html
  components/browser/errorpages/src/main/res/raw/error_style.css
  components/browser/errorpages/src/main/res/values/strings.xml
  components/browser/errorpages/src/test/java/mozilla/components/browser/errorpages/ErrorPagesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#5521 Closes #5042: Save state of migration immediately after every migration run.
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
Labels: 🕵️‍♀️ needs review

#5552 GeckoView update (beta) (20200113-140806)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5517 Closes #5345: Migration service: Use lowest priority and set category.
  components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt
Labels: 🕵️‍♀️ needs review

#5540 Move addon permissions dialog to feature addons
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/PermissionsDialogFragment.kt
  components/feature/addons/src/main/res/layout/mozac_feature_addons_fragment_dialog_addon_permissions.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/ExtensionsTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/PermissionsDialogFragmentTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt
Labels: 🕵️‍♀️ needs review

#5554 Issue #5141: Update strings of migration notification.
  components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt
  components/support/migration/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#5565 Adds description the variable in an SSL bypass string
  components/browser/errorpages/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5534 Make height of screen form elements adjustable to the content length
  components/feature/prompts/src/main/res/layout/mozac_feature_multiple_choice_item.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_single_choice_item.xml
Labels: 🛬 needs landing

#5566 Closes #5564: Fix typo on add-ons strings xml file
  components/feature/addons/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#5581 FennecMigrator: Notify Glean about whether telemetry should be collected after migrating Fennec setting.
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
Labels: 🕵️‍♀️ needs review

#5610 Closes #5583: Use Firefox logo in migration notification.
  components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt
  components/support/migration/src/main/res/drawable/mozac_support_migration_notification_icon.xml
Labels: 🕵️‍♀️ needs review

#5611 Closes #5488: Rebind the add-ons recyclerView in onStart
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt
Labels: 🕵️‍♀️ needs review

#5643 Issue #5509: Provide state in completed migration UI callback
  components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationProgressActivity.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/MigrationObserverTest.kt
Labels: 🛬 needs landing

#5624 L10n fixes for SSL bypass
  components/browser/errorpages/build.gradle
  components/browser/errorpages/src/main/java/mozilla/components/browser/errorpages/ErrorPages.kt
  components/browser/errorpages/src/main/res/values/strings.xml
  components/browser/errorpages/src/test/java/mozilla/components/browser/errorpages/ErrorPagesTest.kt
Labels: 🛬 needs landing

#5636 No issue: Make LoginDialogFragment dismiss on negative button click
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/LoginDialogFragment.kt
Labels: 🛬 needs landing

#5638 Closes #5637: Fix crash in sample browser when launching MarketplaceIntent
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing

#5645 Closes #5644: Update MigrationStore from FennecMigrator after every migration step.
  components/support/migration/src/main/java/mozilla/components/support/migration/AbstractMigrationService.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/FennecMigrator.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/state/MigrationAction.kt
  components/support/migration/src/main/java/mozilla/components/support/migration/state/MigrationReducer.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecMigratorTest.kt
Labels: 🕵️‍♀️ needs review

#5590 Always use web app manifest if possible
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/Session.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/WebAppManifest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppShortcutManagerTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppUseCasesTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/SessionKtTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/WebAppManifestKtTest.kt
Labels: 🕵️‍♀️ needs review

#5629 Closes #5627: Catch RecordNotFoundError exception in Push
  components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/AutoPushFeatureKtTest.kt
Labels: 🕵️‍♀️ needs review

#5642 Closes #5632 #4699 Improve tracking protection use cases to delete individual exceptions.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/content/blocking/GeckoTrackingProtectionException.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/content/blocking/GeckoTrackingProtectionException.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/content/blocking/GeckoTrackingProtectionException.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/content/blocking/TrackingProtectionException.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/content/blocking/TrackingProtectionExceptionStorage.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/TrackingProtectionUseCasesTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review

#5575 Closes #5097: Add web domain for autofill in authentication dialog
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AutofillEditText.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_prompt_auth_prompt.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragmentTest.kt
Labels: 🕵️‍♀️ needs review

#5657 GeckoView update (nightly) (20200121-140638)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5652 Add missing 'addons' labeled_string to migration ping
  components/support/migration/docs/metrics.md
  components/support/migration/metrics.yaml
Labels: 🛬 needs landing

#5675 GeckoView update (nightly) (20200122-140750)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5660 Closes #5572: Update BrowserAction to allow opening a popup
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/WebExtensionReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/WebExtensionState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/WebExtensionActionTest.kt
  components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
  samples/browser/src/main/AndroidManifest.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/WebExtensionActionPopupActivity.kt
Labels: 🛬 needs landing

#5683 Closes #5682: Remove failedToLaunch property from AppLinksUseCases
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
Labels: 🕵️‍♀️ needs review

#5679 Closes #5677: Catch all known non-fatal push errors
  components/concept/push/src/main/java/mozilla/components/concept/push/PushProcessor.kt
  components/concept/push/src/test/java/mozilla/components/concept/push/PushErrorTest.kt
  components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/AutoPushFeatureKtTest.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/AutoPushFeatureTest.kt
  components/lib/push-amazon/src/test/java/mozilla/components/lib/push/amazon/AbstractAmazonPushServiceTest.kt
  components/lib/push-firebase/src/test/java/mozilla/components/lib/push/firebase/AbstractFirebasePushServiceTest.kt
Labels: 🕵️‍♀️ needs review

#5681 Closes #5661: Caching AppLinksUseCases results
  components/feature/app-links/build.gradle
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🕵️‍♀️ needs review

#5711 Remove colon from feature addons strings
  components/feature/addons/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review

#5713 GeckoView update (beta) (20200124-140827)
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#5703 Bump a-s dependency to 0.48.3.
  buildSrc/src/main/java/Dependencies.kt
  components/browser/storage-sync/build.gradle
Labels: ✏️ needs changes

#5756 Add learn more for NotYetSupportedAddons
  components/feature/addons/src/main/res/values/strings.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/NotYetSupportedAddonActivity.kt
  samples/browser/src/main/res/layout/fragment_not_yet_supported_addons.xml
Labels: 🛬 needs landing

#5753 For mozilla-mobile/fenix#5881 - Avoid tippy top pwa icons
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt
Labels: 🛬 needs landing

#5746 Docs update (20200129-120815) [ci skip]
  docs/api/alltypes/index.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-session/index.md
  docs/api/mozilla.components.browser.engine.gecko/-gecko-engine-session/mark-active-for-web-extensions.md
  docs/api/mozilla.components.browser.engine.system/-system-engine-session/index.md
  docs/api/mozilla.components.browser.session/-legacy-session-manager/-n-o_-s-e-l-e-c-t-i-o-n.md
  docs/api/mozilla.components.browser.session/-legacy-session-manager/find-session-by-id.md
  docs/api/mozilla.components.browser.session/-legacy-session-manager/on-low-memory.md
  docs/api/mozilla.components.browser.session/-legacy-session-manager/remove-all.md
  docs/api/mozilla.components.browser.session/-legacy-session-manager/remove-sessions.md
  docs/api/mozilla.components.browser.session/-legacy-session-manager/remove.md
  docs/api/mozilla.components.browser.session/-legacy-session-manager/select.md
  docs/api/mozilla.components.browser.toolbar.edit/-edit-toolbar/index.md
  docs/api/mozilla.components.browser.toolbar.edit/-edit-toolbar/set-on-edit-focus-change-listener.md
  docs/api/mozilla.components.concept.engine/-engine-session/close.md
  docs/api/mozilla.components.concept.engine/-engine-session/index.md
  docs/api/mozilla.components.concept.engine/-engine-session/mark-active-for-web-extensions.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/get-item-count.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/get-item-view-type.md
  docs/api/mozilla.components.feature.addons.ui/-addons-manager-adapter/on-bind-view-holder.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/add-button.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/icon-view.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/index.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/rating-view.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/summary-view.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/title-view.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-addon-view-holder/user-count-view.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-unsupported-section-view-holder/-init-.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-unsupported-section-view-holder/description-view.md
  docs/api/mozilla.components.feature.addons.ui/-custom-view-holder/-unsupported-section-view-holder/index.md
  docs/api/mozilla.components.support.base.feature/-lifecycle-aware-feature/index.md
  docs/api/mozilla.components.support.webextensions/-web-extension-popup-feature/-init-.md
  docs/api/mozilla.components.support.webextensions/-web-extension-popup-feature/index.md
  docs/api/mozilla.components.support.webextensions/-web-extension-popup-feature/start.md
  docs/api/mozilla.components.support.webextensions/-web-extension-popup-feature/stop.md
  docs/api/mozilla.components.support.webextensions/index.md
Labels: 🛬 needs landing

#5704 For Fenix7902: prevent login dialogs from being dismissed on page load
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/LoginDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/PromptDialogFragment.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#5764 For mozilla-mobile/fenix#8014 - fix feature-pwa manifests db migration
  components/feature/pwa/build.gradle
  components/feature/pwa/schemas/mozilla.components.feature.pwa.db.ManifestDatabase/0.json
  components/feature/pwa/schemas/mozilla.components.feature.pwa.db.ManifestDatabase/2.json
  components/feature/pwa/src/androidTest/java/mozilla/components/feature/pwa/db/ManifestDatabaseMigrationTest.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/db/ManifestDatabase.kt
Labels: 🛬 needs landing
