Repository mozilla-mobile/android-components, pull requests merged in 2021-08, with the labels that each got.

#10701 For #10603 - Adds `createdAt` to `TabSessionState`
  components/browser/session-storage/src/androidTest/java/mozilla/components/browser/session/storage/RestoringBrowsingSessionsTest.kt
  components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt
  components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateWriter.kt
  components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/Keys.kt
  components/browser/session-storage/src/test/java/mozilla/components/browser/session/storage/serialize/BrowserStateWriterReaderTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/recover/RecoverableTab.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/ext/TabSessionStateTest.kt
Labels: 🛬 needs landing

#10728 Workaround for querying geckoView tracking protection exceptions for bugzilla 1723280
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
Labels: 🛬 needs landing

#10722 Issue #10719: Use safe parse URI in app links
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing

#10734 Update Flank to v21.08.0
  taskcluster/docker/ui-tests/Dockerfile
Labels: automation, 🛬 needs landing

#10696 Closes #4805: Remove taobao search plugin.
  components/feature/search/src/main/assets/search/list.json
  components/feature/search/src/main/assets/searchplugins/taobao.xml
  components/feature/search/src/test/java/mozilla/components/feature/search/storage/BundledSearchEnginesStorageTest.kt
Labels: 🛬 needs landing

#10715 Bug 1721675 - Use the local server for testing
  samples/glean/src/androidTest/java/org/mozilla/samples/glean/MainActivityTest.kt
Labels: 🛬 needs landing

#10673 For #10668 - Round the translation value to the nearest integer
  components/feature/session/src/main/java/mozilla/components/feature/session/behavior/EngineViewBrowserToolbarBehavior.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/behavior/EngineViewBrowserToolbarBehaviorTest.kt
Labels: 🛬 needs landing

#10738 For #10737: Also pass isPrivate property to download request.
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/HttpIconLoader.kt
Labels: 🛬 needs landing

#10707 For #10702 - New CombinedHistorySuggestionProvider
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/CombinedHistorySuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryMetadataSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/CombinedHistorySuggestionProviderTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10741 Issue #10719: Ignore number format exception when parsing URI
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing

#10720 Issue #10719: Intent targeting the current app is not an app link
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing

#10751 AwesomeBar(): Add option to autocomplete from suggestions that support it.
  components/compose/awesomebar/build.gradle
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBar.kt
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/Suggestion.kt
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/Suggestions.kt
  components/compose/awesomebar/src/main/res/values/strings.xml
  samples/compose-browser/src/main/java/org/mozilla/samples/compose/browser/browser/BrowserScreen.kt
Labels: 🛬 needs landing

#10756 Issue #10755 - Add photon colors for Ink 30 and Ink 60
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing, 🕵️‍♀️ needs review

#10740 Issue #10719: Check for transparency when determining text colour
  components/support/utils/src/main/java/mozilla/components/support/utils/ColorUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/ColorUtilsTest.kt
Labels: 🛬 needs landing

#10759 Bug 1720138 - Import WebCompat Interventions Addon v25.
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/adform.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/adnexus-prebid.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/apstag.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/chartbeat.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/criteo.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/cxense.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/facebook-sdk.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-ads.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-analytics-and-tag-manager.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-page-ad.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-safeframe.html
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/iaspet.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/moat.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/optimizely.js
Labels: 🛬 needs landing

#10760 Make sure to preserve private state when recreating a RecoverableTab
  components/browser/session-storage/src/test/java/mozilla/components/browser/session/storage/SessionStorageTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/recover/RecoverableTab.kt
Labels: 🛬 needs landing

#10758 Remove AwesomeBar.shouldClearSuggestions
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/BrowserAwesomeBar.kt
  components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/SuggestionsAdapter.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/BrowserAwesomeBarTest.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/SuggestionsAdapterTest.kt
  components/concept/awesomebar/src/main/java/mozilla/components/concept/awesomebar/AwesomeBar.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/CombinedHistorySuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryMetadataSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchActionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/HistoryMetadataSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProviderTest.kt
Labels: 🛬 needs landing

#10757 Add constants of photon colors to be used with Jetpack Compose UI.
  buildSrc/src/main/java/Dependencies.kt
  components/ui/colors/build.gradle
  components/ui/colors/src/main/java/mozilla/components/ui/colors/PhotonColors.kt
Labels: 🛬 needs landing

#10768 Don't rebase version bumps or suffix updates before merging
  .mergify.yml
Labels: 🛬 needs landing

#10735 Update to appservices v82.1.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#10747 Close #10746: Make RestoreUseCase consider createdAt property
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10779 Add new red 30 and ink 10 colours
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing

#10783 github-release fix post python3 migration
  taskcluster/ac_taskgraph/__init__.py
Labels: 🛬 needs landing

#10785 Backout mergify changes for bustage
  .mergify.yml
Labels: 🛬 needs landing

#10780 Bug 1723950 - Import WebCompat Interventions Addon v25.4.0
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/optimizely.js
Labels: 🛬 needs landing

#10790 Add new red 30 and ink 10 colours to PhotonColors
  components/ui/colors/src/main/java/mozilla/components/ui/colors/PhotonColors.kt
Labels: 🛬 needs landing

#10763 Closes #10302: Android Autofill: Always show 'search' item.
  components/feature/autofill/build.gradle
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/handler/FillRequestHandler.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/fill/AuthFillResponseBuilder.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/structure/ParsedStructure.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/ui/AbstractAutofillUnlockActivity.kt
  components/feature/autofill/src/test/java/mozilla/components/feature/autofill/handler/FillRequestHandlerTest.kt
Labels: 🛬 needs landing

#10795 Issue #10794 - Add Focus and Fenix pinned icons into ui-icons
  components/ui/icons/src/main/res/drawable/mozac_ic_pin.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_pin_filled_2.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_pin_remove.xml
Labels: 🛬 needs landing, 🕵️‍♀️ needs review

#10748 Close #10677: Update Mockito to 3.11.2
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  components/browser/awesomebar/src/test/java/mozilla/components/browser/awesomebar/BrowserAwesomeBarTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/BrowserThumbnailsTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/MenuButtonTest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/AccountObserverTest.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/AutoPushObserverTest.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/ConstellationObserverTest.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabWindowFeatureTest.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/verify/OriginVerifierTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/AndroidDownloadManagerTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptContainerTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/AlertDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/ChoiceDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/ColorPickerDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/ConfirmDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/MultiButtonDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/TextPromptDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/TimePickerDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FilePickerTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppShortcutManagerTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/feature/WebAppActivityFeatureTest.kt
  components/feature/qr/src/test/java/mozilla/components/feature/qr/QrFeatureTest.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/internal/ReaderViewConfigTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/PictureInPictureFeatureTest.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/presenter/DefaultPresenterTest.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/prompt/CrashReporterActivityTest.kt
  components/lib/push-amazon/src/test/java/mozilla/components/lib/push/amazon/AbstractAmazonPushServiceTest.kt
  components/lib/push-firebase/src/test/java/mozilla/components/lib/push/firebase/AbstractFirebasePushServiceTest.kt
  components/service/digitalassetlinks/src/test/java/mozilla/components/service/digitalassetlinks/AndroidAssetFinderTest.kt
  components/service/digitalassetlinks/src/test/java/mozilla/components/service/digitalassetlinks/local/StatementApiTest.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/AccountStorageTest.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaDeviceConstellationTest.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/UtilsKtTest.kt
  components/service/sync-autofill/src/test/java/mozilla/components/service/sync/autofill/AutofillCryptoTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/SharedPreferencesTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/WindowTest.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecFxaMigrationTest.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecLoginsMigrationTest.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecMigratorTest.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecProfileTest.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/MigrationObserverTest.kt
  components/support/rustlog/src/test/java/mozilla/components/support/rustlog/RustLogTest.kt
Labels: 🛬 needs landing

#10770 Close #10769: Add DebugAction.UpdateCreatedAtAction with reducer
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/DebugReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/DebugActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/reducer/DebugReducerTest.kt
  components/lib/state/src/main/java/mozilla/components/lib/state/DelicateAction.kt
Labels: 🛬 needs landing

#10796 Remove `dokka` mention (and API reference) from README
  README.md
Labels: 🛬 needs landing

#10799 Issue #10798 - Refactor getRepresentativeSnippet and getRepresentativeCharacter from browser-icons to support-ktx
  components/browser/icons/src/main/java/mozilla/components/browser/icons/generator/DefaultIconGenerator.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/generator/DefaultIconGeneratorTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt
Labels: 🛬 needs landing, 🕵️‍♀️ needs review

#10804 compose-tabstray: Update comment of string mozac_tab_counter_open_tab_tray_plural.
  components/compose/tabstray/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#10805 For #10803 - Force expanding the toolbar if requested by GeckoView
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarBehaviorController.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarBehaviorControllerTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10818 For #10803 - Implement new Toolbar methods in MockToolbar
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt
Labels: 🛬 needs landing

#10686 For #9830: Do not request/use WRITE_EXTERNAL_STORAGE on Android 11 and above
  components/feature/downloads/src/main/AndroidManifest.xml
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/AndroidDownloadManager.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/AndroidDownloadManagerTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/FetchDownloadManagerTest.kt
Labels: 🛬 needs landing

#10819 Suggestion(): Use text color based on theme.
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/Suggestion.kt
Labels: 🛬 needs landing

#10825 Upstream more icons from Fenix to AC
  components/ui/icons/src/main/res/drawable/mozac_ic_add_to_home_screen.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_clear.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_help.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_home.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_settings.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_shield.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_shield_disabled.xml
  docs/changelog.md
Labels: 🛬 needs landing

#10831 Revert "Create facts for autofill feature"
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardSelectBar.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/LoginDialogFacts.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/SaveLoginDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/facts/CreditCardAutofillDialogFacts.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/creditcard/CreditCardSelectBarTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/facts/CreditCardAutofillDialogFactsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10832 Close #10827 show the toolbar Highlight (blue dot) when tracking protection is off for a site
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarPresenter.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarPresenterTest.kt
Labels: 🛬 needs landing

#10829 ui-colors: Add Kotlin plugin and setup Jetpack Compose.
  buildSrc/src/main/java/Dependencies.kt
  components/ui/colors/build.gradle
Labels: 🛬 needs landing

#10716 For #10714 - Expose PocketStoriesUseCases.GetPocketStories
  components/service/pocket/src/main/java/mozilla/components/service/pocket/stories/PocketStoriesUseCases.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/stories/PocketStoriesUseCasesTest.kt
Labels: 🛬 needs landing

#10845 Closes #10844: Only load app links URL if scheme is supported by the engine
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
Labels: 🛬 needs landing

#10850 Set version to 92.0.8.
  version.txt
Labels: 🛬 needs landing

#10821 Update context menu candidates and layout
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFeature.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFragment.kt
  components/feature/contextmenu/src/main/res/layout/mozac_feature_contextmenu_dialog.xml
  components/feature/contextmenu/src/main/res/values/colors.xml
  components/feature/contextmenu/src/main/res/values/style.xml
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuFragmentTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10869 For #10621: Revert change of the proton home icon.
  components/ui/icons/src/main/res/drawable/mozac_ic_home.xml
Labels: 🛬 needs landing

#10872 For #10871 - Remove permissions matching block
  components/feature/search/src/main/assets/extensions/ads/manifest.template.json
  components/feature/search/src/main/assets/extensions/search/manifest.template.json
Labels: 🛬 needs landing

#10875 No issue: Update Flank to v21.08.1
  taskcluster/docker/ui-tests/Dockerfile
Labels: 🛬 needs landing

#10838 Issue #10835: Add first simple version of an Jetpack Compose image loader using a Client implementation
  components/support/images/build.gradle
  components/support/images/src/main/java/mozilla/components/support/images/compose/loader/ImageLoader.kt
  components/support/images/src/main/java/mozilla/components/support/images/compose/loader/ImageLoaderScope.kt
  components/support/images/src/main/java/mozilla/components/support/images/compose/loader/ImageLoaderState.kt
  config/detekt.yml
Labels: 🛬 needs landing

#10898 Closes #10834: Add BrowserIcons.Loader() composable function to load website icons in Jetpack Compose code.
  components/browser/icons/build.gradle
  components/browser/icons/src/main/java/mozilla/components/browser/icons/compose/IconLoaderScope.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/compose/IconLoaderState.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/compose/Loader.kt
Labels: 🛬 needs landing

#10890 For #10880 - New Pocket endpoint and simpler code
  components/browser/engine-gecko/docs/metrics.md
  components/service/pocket/src/main/java/mozilla/components/service/pocket/PocketRecommendedStory.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/PocketStoriesConfig.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/PocketStoriesService.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/api/Arguments.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/api/PocketEndpoint.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/api/PocketEndpointRaw.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/api/PocketGlobalStoryRecommendation.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/api/PocketURLs.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/stories/PocketRecommendationsRepository.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/stories/PocketStoriesUseCases.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/stories/update/PocketStoriesRefreshScheduler.kt
  components/service/pocket/src/main/java/mozilla/components/service/pocket/stories/update/RefreshPocketWorker.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/PocketStoriesConfigTest.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/PocketStoriesServiceTest.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/api/ArgumentsTest.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/api/PocketEndpointRawTest.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/api/PocketEndpointTest.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/api/PocketURLsTest.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/helpers/Assert.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/helpers/MockResponses.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/helpers/Params.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/stories/PocketStoriesUseCasesTest.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/stories/update/PocketStoriesRefreshSchedulerTest.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/stories/update/RefreshPocketWorkerTest.kt
  components/service/pocket/src/test/resources/pocket/stories_recommendations_response.json
  components/service/pocket/src/test/resources/pocket/story.json
  components/service/pocket/src/test/resources/pocket/story_recommendation_response.json
Labels: 🛬 needs landing

#10857 For mozilla-mobile#10560: Fixed bug causing external links to open tabs irrespective of the session's private status
  components/browser/state/src/main/java/mozilla/components/browser/state/selector/Selectors.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/selector/SelectorsKtTest.kt
  components/feature/intent/src/test/java/mozilla/components/feature/intent/processing/TabIntentProcessorTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
Labels: 🛬 needs landing (squash)

#10777 Undo tab position fix - fix for Fenix #18210
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/recover/RecoverableTab.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/store/BrowserStoreExceptionTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/middleware/undo/UndoMiddleware.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/toolbar/TabCounterToolbarButtonTest.kt
Labels: 🛬 needs landing (squash)
