Repository mozilla-mobile/android-components, pull requests merged in 2021-07, with the labels that each got.

#10539 For #10537 - Applies tint to imageView instead of drawable
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItem.kt
Labels: 🛬 needs landing

#10508 Closes #10481 Migrate site permissions DB autoplay values to be block audio only by default
  components/feature/sitepermissions/schemas/mozilla.components.feature.sitepermissions.db.SitePermissionsDatabase/7.json
  components/feature/sitepermissions/src/androidTest/java/mozilla/components/feature/sitepermissions/db/OnDeviceSitePermissionsStorageTest.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDatabase.kt
Labels: 🛬 needs landing

#10554 For #10521 - Simplify how history results are queried and returned
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryMetadataSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/AwesomeBarFeatureTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/HistoryMetadataSuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProviderTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10556 For #10521 - Fix AwesomeBarFeature smoke tests
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/AwesomeBarFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10557 Catch and log history metadata write exceptions
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
Labels: 🛬 needs landing

#10552 For #10551 - Adds `clearFlagOnStop = true` in SecureWindowFeature
  components/feature/privatemode/src/main/java/mozilla/components/feature/privatemode/feature/SecureWindowFeature.kt
  components/feature/privatemode/src/test/java/mozilla/components/feature/privatemode/feature/SecureWindowFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10558 Close #10382: Handle exceptions thrown in RemoteTabsStorage
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/RemoteTabsStorage.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/RemoteTabsStorageTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10452 For #9554: Remove deprecated systemUiVisibility and flags.
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Window.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/WindowTest.kt
Labels: 🛬 needs landing

#10506 For #10505 - Update the icon for the bing search engine
  components/feature/search/src/main/assets/searchplugins/bing.xml
  docs/changelog.md
Labels: 🛬 needs landing

#10566 For #9554: Use WindowInsetsControllerCompat to avoid null controllers.
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Window.kt
Labels: 🛬 needs landing

#10553 Add blog posting about possible next architecture changes after the browser-state migration.
  docs/_posts/2021-07-05-whats-next.md
  docs/assets/images/blog/engine-architecture.png
  docs/assets/images/blog/simplified-engine-architecture.png
  docs/assets/images/blog/simplified-toolbar-architecture.png
  docs/assets/images/blog/toolbar-architecture.png
Labels: 🛬 needs landing

#10426 No issue: Fix addHistoryProvider kdoc in AwesomebarFeature
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/AwesomeBarFeature.kt
Labels: 🛬 needs landing

#10569 Update KDocs for Push API
  components/feature/push/src/main/java/mozilla/components/feature/push/Connection.kt
Labels: 🛬 needs landing

#10578 Bug 1714611 - Ship v24.0.0 of webcompat system addon.
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1719870-lcbo.com-table-clearfix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1714612-www.rfi.it-outertext.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/adsafeprotected-ima.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/empty-shim.txt
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-analytics-and-tag-manager.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-analytics-tag-manager.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-analytics.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-ima.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-publisher-tags.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/rich-relevance.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/vast2.xml
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/vast3.xml
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/vmad.xml
Labels: 🛬 needs landing

#10572 For #10571: Add optional icon tint for Toolbar Button.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/concept/toolbar/build.gradle
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
Labels: 🛬 needs landing

#10589 For #10588 - `ERROR_SECURITY_SSL` no longer shows Advanced button
  components/browser/errorpages/src/main/java/mozilla/components/browser/errorpages/ErrorPages.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10541 For #7249 - New ads / search telemetry
  components/feature/search/.gitignore
  components/feature/search/build.gradle
  components/feature/search/src/main/assets/extensions/ads/adsTelemetry.js
  components/feature/search/src/main/assets/extensions/ads/manifest.template.json
  components/feature/search/src/main/assets/extensions/search/manifest.template.json
  components/feature/search/src/main/assets/extensions/search/searchTelemetry.js
  components/feature/search/src/main/java/mozilla/components/feature/search/middleware/AdsTelemetryMiddleware.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/BaseSearchTelemetry.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/ExtensionInfo.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/SearchProviderCookie.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/SearchProviderModel.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/TrackKeyInfo.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/Utils.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/ads/AdsTelemetry.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/incontent/InContentTelemetry.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/middleware/AdsTelemetryMiddlewareTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/telemetry/BaseSearchTelemetryTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/telemetry/SearchProviderModelTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/telemetry/ads/AdsTelemetryTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/telemetry/incontent/InContentTelemetryTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10602 Close #10601: Add lastAccess to Tab in TabsTray
  components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/Tab.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/TabSessionState.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10451 Issue #10335: Use Java 11.
  buildSrc/src/main/java/Dependencies.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/test/ReflectionUtils.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  components/feature/autofill/src/test/java/mozilla/components/feature/autofill/AutofillUseCasesTest.kt
  components/feature/qr/src/test/java/mozilla/components/feature/qr/QrFeatureTest.kt
  components/tooling/lint/src/test/java/mozilla/components/tooling/lint/LintLogChecksTest.kt
  taskcluster/docker/base/Dockerfile
  taskcluster/docker/ui-tests/Dockerfile
  taskcluster/scripts/decision-install-sdk.sh
  taskcluster/scripts/toolchain/android-gradle-dependencies/before.sh
  taskcluster/scripts/toolchain/repack-android-sdk-linux.sh
Labels: 🛬 needs landing

#10612 For #7249 - Fix permissions matching, avoid warnings
  components/feature/search/src/main/assets/extensions/ads/manifest.template.json
  components/feature/search/src/main/assets/extensions/search/manifest.template.json
Labels: 🛬 needs landing

#10613 For #10614 - Run 'get-secret.py' with Python 3
  automation/taskcluster/helper/get-secret.py
Labels: 🛬 needs landing (squash)

#10593 Issue #10611 - Add a new SelectOrAddUseCase for reopening existing tab with matching HistoryMetadataKey
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#10599 For #10598 - Always display URLs left to right
  components/support/utils/src/main/java/mozilla/components/support/utils/URLStringUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/URLStringUtilsTest.kt
Labels: 🛬 needs landing

#10635 For 10633 - Check directionality before adding the LTR mark
  components/support/utils/src/main/java/mozilla/components/support/utils/URLStringUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/URLStringUtilsTest.kt
Labels: 🛬 needs landing

#10625 For #10624 - Adds recoverable param to `RemoveAllTabsAction`
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TabsRemovedMiddlewareTest.kt
  components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/ThumbnailsMiddlewareTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
  components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddlewareTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/middleware/undo/UndoMiddleware.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionFeatureTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/middleware/undo/UndoMiddlewareTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenterTest.kt
  docs/changelog.md
Labels: <tabs>, 🛬 needs landing

#10640 For #10633 - toDisplayUrl - don't crash for empty strings
  components/support/utils/src/main/java/mozilla/components/support/utils/URLStringUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/URLStringUtilsTest.kt
Labels: 🛬 needs landing

#10649 Bump Android Gradle plugin to 7.0.0-rc01
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#10647 For #10137 - Rename master branch to main
  .github/pull_request_template.md
  .github/workflows/sync-strings.yml
  .github/workflows/update-geckoview.yml
  README.md
  buildSrc/src/main/java/GitHubPlugin.kt
  components/browser/menu/README.md
  components/browser/menu2/README.md
  components/feature/findinpage/README.md
  components/feature/session/README.md
  components/service/firefox-accounts/README.md
  components/service/sync-logins/README.md
  components/support/base/src/main/java/mozilla/components/support/base/utils/LazyComponent.kt
  docs/_archive/2018-08-03-release-0.17.markdown
  docs/_archive/2018-09-13-release-0.23.markdown
  docs/_posts/2018-07-30-firefox-notes-fxa.markdown
  docs/_posts/2018-08-10-fretboard.md
  docs/_posts/2019-02-19-saving-state.md
  docs/_posts/2021-07-05-whats-next.md
  docs/changelog.md
  docs/changelog_archive.md
  docs/components.md
  docs/contribute/app_services_upgrade.md
  docs/contribute/code_coverage.md
  docs/contribute/components_inside_app.md
  docs/contribute/hosting_code_in_repository.md
  docs/contribute/release_checklist.md
  docs/contribute/updating_tracking_protection_lists.md
  docs/contribute/versioning.md
  docs/contributing.md
  docs/rfcs/0004-top-sites-feature.md
  docs/rfcs/0006-search-defaults.md
  docs/rfcs/0007-synchronized-releases.md
  docs/ui/icons.md
  l10n.toml
  samples/browser/README.md
  samples/firefox-accounts/README.md
  taskcluster/ac_taskgraph/loader/build_config.py
Labels: 🕵️‍♀️ needs review

#10654 compose-browser-toolbar: Add initial theming.
  components/compose/browser-toolbar/src/main/java/mozilla/components/compose/browser/toolbar/BrowserDisplayToolbar.kt
  components/compose/browser-toolbar/src/main/java/mozilla/components/compose/browser/toolbar/BrowserEditToolbar.kt
  samples/compose-browser/src/main/java/org/mozilla/samples/compose/browser/BrowserComposeActivity.kt
Labels: 🛬 needs landing

#10653 samples-compose-browser: Use actual suggestion providers.
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBar.kt
  samples/compose-browser/build.gradle
  samples/compose-browser/src/main/java/org/mozilla/samples/compose/browser/Components.kt
  samples/compose-browser/src/main/java/org/mozilla/samples/compose/browser/browser/BrowserScreen.kt
Labels: 🛬 needs landing

#10661 Change the branch name in l10n.toml back to main
  l10n.toml
Labels: 🛬 needs landing (squash)

#10660 Add initial version of a compose-tabstray component
  .buildconfig.yml
  components/compose/tabstray/README.md
  components/compose/tabstray/build.gradle
  components/compose/tabstray/proguard-rules.pro
  components/compose/tabstray/src/main/AndroidManifest.xml
  components/compose/tabstray/src/main/java/mozilla/components/compose/tabstray/Tab.kt
  components/compose/tabstray/src/main/java/mozilla/components/compose/tabstray/TabList.kt
  components/compose/tabstray/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/compose/tabstray/src/test/resources/robolectric.properties
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/BrowserState.kt
  samples/compose-browser/build.gradle
  samples/compose-browser/src/main/java/org/mozilla/samples/compose/browser/BrowserComposeActivity.kt
  samples/compose-browser/src/main/java/org/mozilla/samples/compose/browser/browser/BrowserScreen.kt
  samples/compose-browser/src/main/java/org/mozilla/samples/compose/browser/browser/BrowserScreenAction.kt
  samples/compose-browser/src/main/java/org/mozilla/samples/compose/browser/browser/BrowserScreenState.kt
  samples/compose-browser/src/main/java/org/mozilla/samples/compose/browser/browser/BrowserScreenStore.kt
  taskcluster/ci/config.yml
Labels: 🛬 needs landing

#10676 Closes #10127 expose new GV api for detecting SmartBlock exceptions.
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/content/blocking/TrackerLog.kt
Labels: 🛬 needs landing

#10683 For #10682 - Emit "history_suggestion_clicked"
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryMetadataSuggestionProvider.kt
Labels: 🛬 needs landing

#10671 For #10670: Add optional parameter to filter recent bookmarks based on added date.
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Types.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorageTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/BookmarksStorage.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt
Labels: 🛬 needs landing

#10662 No issue: Update Flank to v21.07.1
  taskcluster/docker/ui-tests/Dockerfile
Labels: 🛬 needs landing

#10618 Closes #10617: Add common domain for icon requests
  components/browser/icons/src/main/java/mozilla/components/browser/icons/preparer/TippyTopIconPreparer.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/preparer/TippyTopIconPreparerTest.kt
Labels: 🛬 needs landing

#10693 For mozilla-mobile#10624 - Adds recoverable param to `RemoveAllTabsAction` to be used by UndoMiddleware.kt to prevent closed tabs from being recoverable
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TabsRemovedMiddlewareTest.kt
  components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/ThumbnailsMiddlewareTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
  components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddlewareTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/middleware/undo/UndoMiddleware.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionFeatureTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/middleware/undo/UndoMiddlewareTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenterTest.kt
Labels: 🕵️‍♀️ needs review

#10674 Add simple TabCounterButton to compose-tabstray.
  components/compose/browser-toolbar/src/main/java/mozilla/components/compose/browser/toolbar/BrowserDisplayToolbar.kt
  components/compose/browser-toolbar/src/main/java/mozilla/components/compose/browser/toolbar/BrowserToolbar.kt
  components/compose/tabstray/src/main/java/mozilla/components/compose/tabstray/TabCounterButton.kt
  components/compose/tabstray/src/main/res/drawable/mozac_tabcounter_background.xml
  components/compose/tabstray/src/main/res/values/strings.xml
  samples/compose-browser/src/main/java/org/mozilla/samples/compose/browser/BrowserComposeActivity.kt
  samples/compose-browser/src/main/java/org/mozilla/samples/compose/browser/browser/BrowserScreen.kt
Labels: 🛬 needs landing

#10703 Use stable version of Jetpack Compose and related tooling/dependencies.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#10680 Add a clear button to the BrowserEditToolbar
  components/compose/browser-toolbar/src/main/java/mozilla/components/compose/browser/toolbar/BrowserDisplayToolbar.kt
  components/compose/browser-toolbar/src/main/java/mozilla/components/compose/browser/toolbar/BrowserEditToolbar.kt
  components/compose/browser-toolbar/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#10507 TrackingProtectionIconView: Always call updateIcon() to initialize.
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconView.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
Labels: 🛬 needs landing
