Repository mozilla-mobile/android-components, pull requests merged in 2021-11, with the labels that each got.

#11203 Add Firefox Focus packages to known browsers list
  components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11191 Bug 1720142 - Ship v28.0.0 of the WebCompat System Addon.
  components/feature/webcompat/src/main/assets/extensions/webcompat/about-compat/AboutCompat.jsm
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1738313-curriculum.gov.bc.ca-bootstrap-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1738316-vuoriclothing.com-flexbox-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1727100-slack.com-ua-override.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/ua_helpers.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/hamropatro.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/kinja.js
Labels: 🛬 needs landing

#11190 Closes #11101 Expose API to allow to persist tracking protection exceptions in private mode
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/GeckoContentPermissions.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorageTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/content/blocking/TrackingProtectionExceptionStorage.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/TrackingProtectionUseCasesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11211 Removal of browser-storage-memory
  .buildconfig.yml
  CODEOWNERS
  README.md
  components/browser/storage-memory/README.md
  components/browser/storage-memory/build.gradle
  components/browser/storage-memory/proguard-rules.pro
  components/browser/storage-memory/src/main/AndroidManifest.xml
  components/browser/storage-memory/src/main/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorage.kt
  components/browser/storage-memory/src/test/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorageTest.kt
  components/browser/storage-memory/src/test/resources/robolectric.properties
  components/concept/storage/README.md
  components/feature/awesomebar/build.gradle
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/CombinedHistorySuggestionProviderTest.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProviderTest.kt
  components/feature/toolbar/build.gradle
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  taskcluster/ci/config.yml
Labels: 🛬 needs landing (squash)

#11235 Close #11234: Re-introduce close support in TabsFeature
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabsAdapter.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsFeature.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenter.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/tabstray/TabsTrayPresenterTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/TabsTrayFragment.kt
Labels: 🛬 needs landing

#11181 Upgrades appservices to 86.2.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#11236 Closes #3784: Properly distinguish between source and target of redirects
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/HistoryDelegateTest.kt
Labels: 🛬 needs landing

#11218 Record when we need to regenerate a logins encryption key
  components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/LoginsCrypto.kt
Labels: 🛬 needs landing

#11183 For #10749 - New NonBlockingHttpIconLoader
  components/browser/icons/build.gradle
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/IconRequest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/HttpIconLoader.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/NonBlockingHttpIconLoader.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/BrowserIconsTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/loader/NonBlockingHttpIconLoaderTest.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryMetadataSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/SyncedTabsStorageSuggestionProvider.kt
Labels: 🛬 needs landing

#11253 Closes #11252: fix for not hiding the keyboard after edit toolbar loses focus
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
Labels: 🛬 needs landing

#11244 Move shouldStoreUri to storage
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/HistoryDelegate.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/HistoryDelegateTest.kt
Labels: 🛬 needs landing

#11243 Make findLoginToUpdate suspend
  components/concept/storage/src/main/java/mozilla/components/concept/storage/LoginsStorage.kt
  components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/SyncableLoginsStorage.kt
Labels: 🛬 needs landing

#11280 Add a method to remove navigation actions from toolbar
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11221 Issue #11273: Filename in "Open" PDF dialog overflows screen
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragment.kt
  components/feature/downloads/src/main/res/layout/mozac_downloads_prompt.xml
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragmentTest.kt
Labels: 🛬 needs landing

#11274 Update Jetpack Compose to 1.0.5 and Activity Compose to 1.4.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#11272 Closes #11208: Add tab partitions and groups to BrowserState
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabGroupReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabPartition.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabGroupActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/store/BrowserStoreExceptionTest.kt
Labels: 🛬 needs landing

#11301 Issue #11300: EngineMiddleware: Add option for disabling TrimMemoryMiddleware
  components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineMiddleware.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineMiddlewareTest.kt
Labels: 🛬 needs landing

#11260 Add end callback to removeAllExceptions
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/content/blocking/TrackingProtectionExceptionStorage.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/TrackingProtectionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/TrackingProtectionUseCasesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11269 Issue #11249: Add support for save credit card prompt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11312 Handle SCOPE_SYNC access tokens missing a 'key'
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Exceptions.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Types.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/State.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/manager/StateKtTest.kt
Labels: 🛬 needs landing

#11321 Improve loading URLs
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProvider.kt
Labels: 🛬 needs landing

#11299 AwesomeBar(): Pass SuggestionFetcher down instead of list of suggestions
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBar.kt
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestions.kt
Labels: 🛬 needs landing

#11248 Closes #11188: Mergify: Replace deprecated "strict mode" merge action
  .mergify.yml
Labels: 🛬 needs landing

#11329 Add prompt type to the invalid prompt exception.
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
Labels: 🛬 needs landing

#11335 Update version files to 95.0.12
  .buildconfig.yml
  version.txt
Labels: 🕵️‍♀️ needs review

#11337 Issue #11336 - Revert support for save credit card prompt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11333 Issue #11311: Remove deprecated and unused GeckoLoginDelegateWrapper
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/autofill/GeckoLoginDelegateWrapper.kt
  docs/changelog.md
Labels: 🛬 needs landing
