Repository mozilla-mobile/android-components, pull requests merged in 2021-02, with the labels that each got.

#9420 For #9418 - Add support for sharing actual website images
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ShareInternetResourceStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/content/ShareInternetResourceState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/reducer/ShareInternetResourceStateReducerTest.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuUseCases.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/share/ShareDownloadFeature.kt
  components/feature/downloads/src/main/res/xml/feature_downloads_file_paths.xml
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/share/ShareDownloadFeatureTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/content/ContextTest.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt
  components/support/test/src/main/java/mozilla/components/support/test/fakes/FakeContext.kt
  docs/changelog.md
Labels: 🛬 needs landing (squash)

#9558 Closes #9553: Sanitize downloads content type
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9560 Revert "For #9101 - Show BrowserMenu at the right location on Android <=23"
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/BrowserMenuTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9586 Fixes #9584 - Catch all the exceptions from Nimbus Rust SDK
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
Labels: 🛬 needs landing (squash)

#9534 Add iOS sample app that integrates multiplatform-lib-dummy.
  .gitignore
  components/multiplatform/lib-dummy/build.gradle.kts
  samples/ios-sample/ios-sample.xcodeproj/project.pbxproj
  samples/ios-sample/ios-sample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  samples/ios-sample/ios-sample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  samples/ios-sample/ios-sample/Assets.xcassets/AccentColor.colorset/Contents.json
  samples/ios-sample/ios-sample/Assets.xcassets/AppIcon.appiconset/Contents.json
  samples/ios-sample/ios-sample/Assets.xcassets/Contents.json
  samples/ios-sample/ios-sample/ContentView.swift
  samples/ios-sample/ios-sample/Info.plist
  samples/ios-sample/ios-sample/Preview Content/Preview Assets.xcassets/Contents.json
  samples/ios-sample/ios-sample/ios_sampleApp.swift
  samples/ios-sample/ios-sampleTests/Info.plist
  samples/ios-sample/ios-sampleTests/ios_sampleTests.swift
  samples/ios-sample/ios-sampleUITests/Info.plist
  samples/ios-sample/ios-sampleUITests/ios_sampleUITests.swift
Labels: 🛬 needs landing

#9591 Closes #9588 Move addCompletedDownload to an IO thread
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing

#9587 Issue #7888: Remove workaround for URI not supported exception
  components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/HttpIconLoader.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/loader/HttpIconLoaderTest.kt
Labels: 🛬 needs landing

#9592 TabsUseCases: Remove methods that take a Session object.
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/TabsTrayFragment.kt
Labels: 🛬 needs landing

#9598 Remove service-fretboard component.
  .buildconfig.yml
  README.md
  components/service/fretboard/.gitignore
  components/service/fretboard/README.md
  components/service/fretboard/build.gradle
  components/service/fretboard/proguard-rules.pro
  components/service/fretboard/src/main/AndroidManifest.xml
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/DeviceUuidFactory.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/Experiment.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/ExperimentDescriptor.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/ExperimentDownloadException.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/ExperimentEvaluator.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/ExperimentPayload.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/ExperimentSource.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/ExperimentStorage.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/ExperimentsSnapshot.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/Fretboard.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/JSONExperimentParser.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/ValuesProvider.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/scheduler/jobscheduler/JobSchedulerSyncScheduler.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/scheduler/jobscheduler/SyncJob.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/scheduler/workmanager/SyncWorker.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/scheduler/workmanager/WorkManagerSyncScheduler.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/source/kinto/KintoClient.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/source/kinto/KintoExperimentSource.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/source/kinto/SignatureVerifier.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/storage/flatfile/ExperimentsSerializer.kt
  components/service/fretboard/src/main/java/mozilla/components/service/fretboard/storage/flatfile/FlatFileExperimentStorage.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/DeviceUuidFactoryTest.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/ExperimentEvaluatorTest.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/ExperimentPayloadTest.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/ExperimentTest.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/FretboardTest.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/JSONExperimentParserTest.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/ValuesProviderTest.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/source/kinto/KintoClientTest.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/source/kinto/KintoExperimentSourceTest.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/source/kinto/SignatureVerifierTest.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/storage/flatfile/ExperimentsSerializerTest.kt
  components/service/fretboard/src/test/java/mozilla/components/service/fretboard/storage/flatfile/FlatFileExperimentStorageTest.kt
  components/service/fretboard/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/service/fretboard/src/test/resources/robolectric.properties
Labels: 🛬 needs landing

#9168 Adds Nimbus events [SDK-61, SDK-65, SDK-126]
  components/service/nimbus/build.gradle
  components/service/nimbus/docs/metrics.md
  components/service/nimbus/metrics.yaml
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/NimbusTest.kt
Labels: 🛬 needs landing

#9626 Closes #9625 - Adds dividers to Login Selection
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/LoginSelectBar.kt
Labels: 🛬 needs landing

#9631 lib-dummy: Cleanup dependencies.
  components/multiplatform/lib-dummy/build.gradle.kts
Labels: 🛬 needs landing

#9618 Make NimbusClient field immutable/thread-safe
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
Labels: 🛬 needs landing

#9632 Remove service-experiments component.
  .buildconfig.yml
  README.md
  components/service/experiments/.gitignore
  components/service/experiments/KintoSchema.md
  components/service/experiments/README.md
  components/service/experiments/build.gradle
  components/service/experiments/proguard-rules-consumer.pro
  components/service/experiments/proguard-rules.pro
  components/service/experiments/src/main/AndroidManifest.xml
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ActiveExperiment.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/Configuration.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/DeviceUuidFactory.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/Experiment.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ExperimentDescriptor.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ExperimentDownloadException.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ExperimentEvaluator.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ExperimentPayload.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/Experiments.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ExperimentsSerializer.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ExperimentsSnapshot.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ExperimentsUpdater.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/FlatFileExperimentStorage.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/JSONExperimentParser.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/KintoClient.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/KintoExperimentSource.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/SignatureVerifier.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/ValuesProvider.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/debug/ExperimentsDebugActivity.kt
  components/service/experiments/src/main/java/mozilla/components/service/experiments/util/VersionString.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/ActiveExperimentTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/DeviceUuidFactoryTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/ExperimentEvaluatorTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/ExperimentPayloadTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/ExperimentTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/ExperimentsSerializerTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/ExperimentsTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/ExperimentsUpdaterTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/FlatFileExperimentStorageTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/JSONExperimentParserTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/KintoClientTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/KintoExperimentSourceTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/SignatureVerifierTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/TestUtil.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/ValuesProviderTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/debug/ExperimentsDebugActivityTest.kt
  components/service/experiments/src/test/java/mozilla/components/service/experiments/util/VersionStringTest.kt
  components/service/experiments/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/service/experiments/src/test/resources/robolectric.properties
Labels: 🛬 needs landing

#9623 Closes #9470: Emit facts for Awesomebar providers
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/facts/AwesomeBarFacts.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchActionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/facts/AwesomeBarFactsTest.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/SyncedTabsStorageSuggestionProvider.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/facts/SyncedTabsFacts.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/facts/SyncedTabsFactsTest.kt
Labels: 🛬 needs landing

#9619 Closes #9613 Fix Intermittent tests on ShareDownloadFeatureTest
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/share/ShareDownloadFeature.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/share/ShareDownloadFeatureTest.kt
Labels: 🛬 needs landing

#9483 For #7718 - Unify BrowserToolbar and EngineView behaviors
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehavior.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarYTranslationStrategy.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarYTranslator.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehaviorTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarYTranslationStrategyTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarYTranslatorTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/behavior/EngineViewBottomBehavior.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/behavior/EngineViewBrowserToolbarBehavior.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/behavior/EngineViewBrowserToolbarBehaviorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9616 Closes #9597 Remove isExternalStorageLegacy check from AbstractFetchDownloadService
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing

#9617 Fixes #9615 - Move exposure recording to background thread
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/NimbusTest.kt
Labels: 🛬 needs landing (squash)

#9620 Closes #8172 Ignore intermittent test AddonUpdaterWorkerTest
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/AddonUpdaterWorkerTest.kt
Labels: 🛬 needs landing

#9561 Closes #9556: Catch GeckoView Image RuntimeException
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
Labels: 🛬 needs landing

#9610 Update to Kotlin 1.4.30.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#9498 Issue #9453: Introduce interface for describing credit card and address storage
  components/concept/storage/src/main/java/mozilla/components/concept/storage/CreditCardsAddressesStorage.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9634 Issue #9366: Create dedicated BrowserAction for "engine session killed" and track engine session lifetime.
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/middleware/SuspendMiddleware.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/middleware/SuspendMiddlewareTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/EngineStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/EngineState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/EngineActionTest.kt
  components/support/base/src/main/java/mozilla/components/support/base/android/Clock.kt
Labels: 🛬 needs landing

#9662 Closes #9605: Build optimization: Also follow 'testImplementation' dependencies.
  taskcluster/ac_taskgraph/loader/build_config.py
Labels: 🛬 needs landing

#9607 For #9606 - Adds defaultSettings when creating a new GeckoEngineSession
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9672 Uplift: Closes #9668: feature-tab-collections: Pass restored tab ID back to caller
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/ext/TabsUseCases.kt
Labels: 🛬 needs landing

#9671 Closes #9668: feature-tab-collections: Pass restored tab ID back to caller
  components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/ext/TabsUseCases.kt
Labels: 🛬 needs landing

#9513 Add ability to reset Nimbus telemetry identifiers.
  buildSrc/src/main/java/Dependencies.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
Labels: 🛬 needs landing

#9663 Limit usage of JCenter
  build.gradle
Labels: 🛬 needs landing

#9676 For #9555: Fix WEBP deprecation in SDK 30.
  components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/IconDiskCache.kt
  components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/utils/ThumbnailDiskCache.kt
Labels: 🛬 needs landing

#9655 Closes #9654: Rework MediaSession Service foreground notification beh…
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/notification/MediaNotificationTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaSessionServiceDelegateTest.kt
Labels: 🛬 needs landing

#9667 For #9665: Avoid TransactionTooLargeException in getDownloaderApps.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
Labels: 🛬 needs landing

#9690 Commit the updated metrics.md files generated from the glean_parser
  components/browser/engine-gecko-nightly/docs/metrics.md
Labels: 🛬 needs landing

#9692 Allow SessionUseCases to be invoked with session ID
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
Labels: 🛬 needs landing

#9664 For #9659 - New forceCollapse api in BrowserToolbarBehavior
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehavior.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarYTranslator.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehaviorTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarYTranslatorTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#9656 Closes #8148 Limit the number of languages fetched when retrieving add-ons.
  components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonsProvider.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AddonCollectionProvider.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt
  components/feature/addons/src/test/java/AddonManagerTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AddonCollectionProviderTest.kt
  components/feature/addons/src/test/resources/localized_collection.json
  components/support/migration/src/test/java/mozilla/components/support/migration/AddonMigrationTest.kt
Labels: 🛬 needs landing

#9633 For #9294: Add Search engine suggestions provider.
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchActionProvider.kt
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchEngineSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchEngineSuggestionProviderTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9680 For #9552: Fix systemWindowInsetTop deprecation in SDK 30.
  components/support/utils/src/main/java/mozilla/components/support/utils/StatusBarUtils.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/ext/WindowInsets.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/ext/WindowInsetsTest.kt
Labels: 🛬 needs landing

#9701 For #9698: Check if media is playing before entering pip
  components/feature/session/src/main/java/mozilla/components/feature/session/PictureInPictureFeature.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/PictureInPictureFeatureTest.kt
Labels: 🛬 needs landing (squash)

#9703 72.0.14 with GV Release 86.0.20210215141125
  .buildconfig.yml
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/activity/GeckoActivityDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/activity/GeckoActivityDelegateTest.kt
  version.txt
Labels: 🛬 needs landing (squash)

#9679 Switch from deprecated digital.wup.android-maven-publish to maven-publish plugin.
  publish.gradle
Labels: 🛬 needs landing

#9637 [nobug] Refactor Nimbus tests to use correct `*OnThisThread()` functions
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/NimbusTest.kt
Labels: 🛬 needs landing

#9695 Closes #9694 Use one shot operation when restoring downloads.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadStorage.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/db/DownloadDao.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
Labels: 🛬 needs landing

#9678 For #8510. Use SessionConfiguration for createCaptureSession
  components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt
  components/feature/qr/src/test/java/mozilla/components/feature/qr/QrFragmentTest.kt
Labels: 🛬 needs landing

#9567 For #8515: Fix setIncludePending deprecation in SDK 30.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
Labels: 🛬 needs landing

#9707 Fix breaking test after Glean 34 upgrade
  samples/glean/src/androidTest/java/org/mozilla/samples/glean/pings/BaselinePingTest.kt
Labels: 🛬 needs landing

#9710 Bug 1688792 - Ship v20.0.0 of feature-webcompat
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1690091-binance.com-page-overflow.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1690158-slack.com-webkit-scrollbar.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1570856-medium.com-menu-isTier1.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1665035-dckids.com-cookieEnabled.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1682238-gamearter.com-ua-change.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-analytics.js
Labels: 🛬 needs landing

#9651 Closes #9636: Narrow exception to ImageProcessingException
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
Labels: 🛬 needs landing

#9716 Provide use case for migrating custom to regular tab
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/CustomTabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/CustomTabsUseCasesTest.kt
Labels: 🛬 needs landing

#9718 Closes #9654: Rework MediaSession Service foreground notification behaviour
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/notification/MediaNotificationTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaSessionServiceDelegateTest.kt
Labels: 🛬 needs landing

#9691 [SDK-197] Fix recording of enrollment events
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
Labels: 🛬 needs landing (squash)

#9721 Increase downloads buffer size to match Firefox desktop
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
Labels: 🛬 needs landing

#9722 Let simple ETP shims ride the release trains (bz1693386)
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#9566 Closes #9521: Support filtering/excluding add-ons in management UI
  components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
Labels: 🛬 needs landing

#9725 Correctly list the Glean team and adjust some links
  components/service/glean/README.md
Labels: 🛬 needs landing

#9719 Replace Asserts in MediaSessionServiceDelegateTest
  components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaSessionServiceDelegateTest.kt
Labels: 🛬 needs landing

#9720 Commit the updated metrics.md files generated from the glean_parser
  components/browser/engine-gecko-nightly/docs/metrics.md
Labels: 🛬 needs landing

#9723 Update application-services to v71.0.0
  buildSrc/src/main/java/Dependencies.kt
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/NimbusTest.kt
Labels: 🛬 needs landing

#9729 Closes #8854 Fix DefaultAddonUpdaterTest intermittent test failure
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/DefaultAddonUpdaterTest.kt
Labels: 🛬 needs landing

#9730 Closes #8172 Fix AddonUpdaterWorkerTest intermittent test failure
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/AddonUpdaterWorkerTest.kt
Labels: 🛬 needs landing

#9728 Update Kotlin to 1.4.30.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#9715 Add prototype component to support Android's autofill framework.
  .buildconfig.yml
  README.md
  buildSrc/src/main/java/Dependencies.kt
  components/feature/autofill/README.md
  components/feature/autofill/build.gradle
  components/feature/autofill/proguard-rules.pro
  components/feature/autofill/src/main/AndroidManifest.xml
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/AbstractAutofillService.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/AutofillConfiguration.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/ext/LoginsStorage.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/handler/FillRequestHandler.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/lock/AutofillLock.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/structure/ParsedStructure.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/structure/ParsedStructureBuilder.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/structure/ViewNodeNavigator.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/ui/AbstractAutofillUnlockActivity.kt
  components/feature/autofill/src/main/res/values/strings.xml
  components/feature/autofill/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/feature/autofill/src/test/resources/robolectric.properties
  samples/browser/build.gradle
  samples/browser/src/main/AndroidManifest.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/autofill/AutofillService.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/autofill/AutofillUnlockActivity.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/storage/DummyLoginsStorage.kt
  taskcluster/ci/config.yml
Labels: 🛬 needs landing

#9681 Issue #9454: browser-storage-sync implementation for credit card and address storage
  buildSrc/src/main/java/Dependencies.kt
  components/browser/storage-sync/build.gradle
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/AutofillCreditCardsAddressesStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Types.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/AutofillCreditCardsAddressesStorageTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9735 Search: Remember and restore order of search engine list for user's region
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/SearchReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/SearchState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/SearchActionTest.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/middleware/SearchMiddleware.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/ext/BrowserStoreKtTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
Labels: 🛬 needs landing

#9744 README: Remove mailing list
  README.md
Labels: 🛬 needs landing

#9316 No issue: Update Flank to v21.01.0
  taskcluster/docker/ui-tests/Dockerfile
Labels: 🛬 needs landing

#9743 Add l10n.toml to list of auto-merge files.
  .mergify.yml
Labels: 🛬 needs landing

#9600 For #9599: Ability to edit top site URLs
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/OnDevicePinnedSitesStorageTest.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/PinnedSiteStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesUseCases.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/DefaultTopSitesStorageTest.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/PinnedSitesStorageTest.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/TopSitesUseCasesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing (squash)

#9727 Close #4166: Make IO in AutoPushFeature initialization async
  components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt
  components/feature/push/src/main/java/mozilla/components/feature/push/Connection.kt
  components/feature/push/src/test/java/mozilla/components/feature/push/RustPushConnectionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9761 Closes #9757 remove downloads notification when private tabs are closed
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/DownloadStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/content/DownloadState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/DownloadActionTest.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9780 Move the TopSitesUseCases.updateTopSites changelog under 74.0.0
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#9751 Upgrade to Glean 35.0.0
  buildSrc/src/main/java/Dependencies.kt
  components/browser/engine-gecko-beta/docs/metrics.md
  components/browser/engine-gecko-nightly/docs/metrics.md
  components/browser/engine-gecko/docs/metrics.md
  components/lib/crash/docs/metrics.md
  components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
  components/service/nimbus/docs/metrics.md
  components/support/migration/docs/metrics.md
  components/support/sync-telemetry/docs/metrics.md
  docs/changelog.md
  samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt
Labels: 🛬 needs landing

#9773 Update application-services to v72.1.0
  buildSrc/src/main/java/Dependencies.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/AutofillCreditCardsAddressesStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Types.kt
Labels: 🛬 needs landing
