Repository mozilla-mobile/android-components, pull requests merged in 2021-01, with the labels that each got.

#9139 Update Kotlin to 1.4.21 and Coroutines to 1.4.2.
  buildSrc/src/main/java/Dependencies.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehaviorTest.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/MimeType.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsDialogFragmentTest.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorageTest.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/toolbar/TabsToolbarFeatureTest.kt
  components/lib/jexl/src/test/java/mozilla/components/lib/jexl/evaluator/EvaluatorTest.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/helpers/HelpersKtTest.kt
Labels: 🛬 needs landing

#9333 Issue #9332: GeckoEngineSessionState: Handle JSONException coming out of GeckoView.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionState.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionState.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionState.kt
Labels: 🛬 needs landing

#9300 For #9299: Get download notification accent color from fenix to match theme
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadNotificationTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9268 [RELENG-209] populate next_version in github-release
  taskcluster/ac_taskgraph/__init__.py
Labels: 🛬 needs landing (squash)

#9349 Closes #9325: engine-gecko: Introduce blocked schemes
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
Labels: 🛬 needs landing

#9344 Closes #9323: Add ability to filter tabs to TabsUseCases.restore
  components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/SessionStorage.kt
  components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt
  components/browser/session-storage/src/test/java/mozilla/components/browser/session/storage/SessionStorageTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
Labels: 🛬 needs landing

#9352 AbstractPrivateNotificationService: Do not clear private tabs when a PWA task is removed.
  components/feature/privatemode/src/main/java/mozilla/components/feature/privatemode/notification/AbstractPrivateNotificationService.kt
Labels: 🛬 needs landing

#9313 Issue #9312: Add additional tests for the rename top sites function
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/PinnedSitesStorageTest.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/DefaultTopSitesStorageTest.kt
Labels: 🛬 needs landing

#9354 Fix unit test classpath in browser-session-storage
  components/browser/session-storage/build.gradle
Labels: 🛬 needs landing

#9355 Closes #8370: Remove EngineSessionState.toJSON().
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionState.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionStateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionState.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionStateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionState.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionStateTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSessionState.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionStateTest.kt
  components/browser/session-storage/src/test/java/mozilla/components/browser/session/storage/SessionStorageTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSessionState.kt
  components/feature/recentlyclosed/src/androidTest/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorageTest.kt
  components/feature/tab-collections/src/androidTest/java/mozilla/components/feature/tab/collections/TabCollectionStorageTest.kt
Labels: 🛬 needs landing

#9358 Closes #8913: Migrate feature-app-links to browser-state
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/AppIntentState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
  components/feature/app-links/build.gradle
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#9364 feature-contextmenu: Remove dependency on browser-session.
  components/feature/contextmenu/build.gradle
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFeature.kt
Labels: 🛬 needs landing

#9367 SDK-158 Add a NimbusDisabled object for builds that don't need nimbus
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/NimbusTest.kt
  docs/changelog.md
Labels: 🛬 needs landing (squash)

#9361 Migrate feature-recentlyclosed to use BrowserStore exclusively and replace ClosedTab with RecoverableTab.
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/RecentlyClosedReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/ClosedTabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/recover/RecoverableTab.kt
  components/feature/recentlyclosed/build.gradle
  components/feature/recentlyclosed/src/androidTest/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorageTest.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddleware.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorage.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/db/RecentlyClosedTabEntity.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/ext/ClosedTab.kt
  components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddlewareTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
Labels: 🛬 needs landing

#9363 Closes #4279: Migrate TabIntentProcessor to use TabsUseCases instead of SessionManager.
  components/feature/intent/build.gradle
  components/feature/intent/src/main/java/mozilla/components/feature/intent/processing/TabIntentProcessor.kt
  components/feature/intent/src/test/java/mozilla/components/feature/intent/processing/TabIntentProcessorTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#9226 Closes #9176 Add support for site specific autoplay permissions
  components/browser/state/src/main/java/mozilla/components/browser/state/state/content/PermissionHighlightsState.kt
  components/feature/sitepermissions/schemas/mozilla.components.feature.sitepermissions.db.SitePermissionsDatabase/5.json
  components/feature/sitepermissions/src/androidTest/java/mozilla/components/feature/sitepermissions/db/OnDeviceSitePermissionsStorageTest.kt
  components/feature/sitepermissions/src/androidTest/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDaoTest.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissions.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsRules.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsStorage.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDatabase.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsEntity.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsRulesTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsStorageTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/db/SitePermissionEntityTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/db/StatusConverterTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing

#9379 Closes #8497: Make RecentlyClosedMiddleware listen to UndoAction.ClearRecoverableTabs.
  components/feature/recentlyclosed/build.gradle
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddleware.kt
  components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddlewareTest.kt
Labels: 🛬 needs landing

#9353 For #9351 - Get camera image even with "Don't keep activities"
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FilePickerTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9337 For #9334 - Dismiss the LoginPicker onBackPressed in PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9404 Closes #9403: Don't submit network exception during 'sendCommand' failures
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaDeviceConstellationTest.kt
Labels: 🛬 needs landing

#9406 For #9405: Do not select PWA session when creating it.
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessor.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/intent/WebAppIntentProcessorTest.kt
Labels: 🛬 needs landing

#9411 Issue #9410: RecentlyClosedMiddleware: Handle UndoAction.AddRecoverableTabs.
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddleware.kt
  components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddlewareTest.kt
Labels: 🛬 needs landing

#9375 Closes #4257: Migrate feature-customtabs from browser-session to brow…
  components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt
  components/feature/customtabs/build.gradle
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabIntentProcessor.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserver.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabIntentProcessorTest.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/CustomTabsUseCases.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserFragment.kt
Labels: 🛬 needs landing

#9393 Closes #9392: Add share and copy link context menu options to images, audio and video
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  components/feature/contextmenu/src/test/java/mozilla/components/feature/contextmenu/ContextMenuCandidateTest.kt
Labels: 🛬 needs landing

#9422 Issue #9409: RecentlyClosedMiddleware: Run database operations on single thread.
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddleware.kt
Labels: 🛬 needs landing

#9415 For #9382: Disable task optimization for pushes to 'master'
  taskcluster/ac_taskgraph/__init__.py
  taskcluster/ac_taskgraph/loader/build_config.py
Labels: 🛬 needs landing

#9374 Close #9130: Add tint styleable attribute to TabCounter
  components/feature/tabs/README.md
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/toolbar/TabCounterToolbarButton.kt
  components/ui/tabcounter/README.md
  components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounter.kt
  components/ui/tabcounter/src/main/res/values/attrs.xml
  docs/changelog.md
Labels: 🛬 needs landing

#9425 Add guide for smoke testing App Services upgrades
  docs/contribute/app_services_upgrade.md
Labels: 🛬 needs landing

#9408 Add dummy multiplatform component.
  .buildconfig.yml
  build.gradle
  components/multiplatform/lib-dummy/build.gradle.kts
  components/multiplatform/lib-dummy/src/androidMain/AndroidManifest.xml
  components/multiplatform/lib-dummy/src/androidMain/kotlin/mozilla/components/multiplatform/lib/dummy/DummyDelegate.kt
  components/multiplatform/lib-dummy/src/androidTest/kotlin/mozilla/components/multiplatform/lib/dummy/DummyDelegateTest.kt
  components/multiplatform/lib-dummy/src/commonMain/kotlin/mozilla/components/multiplatform/lib/dummy/Dummy.kt
  components/multiplatform/lib-dummy/src/iosMain/kotlin/mozilla/components/multiplatform/lib/dummy/DummyDelegate.kt
  components/multiplatform/lib-dummy/src/iosTest/kotlin/mozilla/components/multiplatform/lib/dummy/DummyDelegateTest.kt
  taskcluster/ci/config.yml
Labels: 🛬 needs landing

#9390 Closes #9378: Add dot notification to the toolbar
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/HighlightView.kt
  components/browser/toolbar/src/main/res/drawable/mozac_dot_notification.xml
  components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/HighlightViewTest.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarPresenter.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarPresenterTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing

#9437 Add a link to new app services testing doc
  docs/contribute/app_services_upgrade.md
  docs/contributing.md
Labels: 🛬 needs landing

#9447 Close #9427: Fix intermittent failing test in CustomTabIntentProcessor
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabIntentProcessorTest.kt
Labels: 🛬 needs landing

#9395 Closes #8693: Integrate GeckoWebExecutor#FETCH_FLAG_PRIVATE.
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Request.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/lib/fetch-httpurlconnection/src/main/java/mozilla/components/lib/fetch/httpurlconnection/HttpURLConnectionClient.kt
  components/lib/fetch-okhttp/src/main/java/mozilla/components/lib/fetch/okhttp/OkHttpClient.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9449 70.0.15 with GV Release 85.0.20210118153634
  .buildconfig.yml
  buildSrc/src/main/java/Gecko.kt
  version.txt
Labels: 🛬 needs landing

#9461 Sample browser: Refactor some SessionManager usage.
  samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt
Labels: 🛬 needs landing

#9467 Support invoking GoToHistoryIndexUseCase with session id
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
Labels: 🛬 needs landing

#9469 Bug 1686065 - Ship v19.0.0 of feature-webcompat
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/picture_in_picture_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1682238-gamearter.com-ua-change.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#9465 Closes #7482: Migrate CoordinateScrollingFeature to use BrowserStore instead of SessionManager.
  components/feature/session/src/main/java/mozilla/components/feature/session/CoordinateScrollingFeature.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/CoordinateScrollingFeatureTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing

#9476 Issue #9409: Replace closed tab on insert and switch back to IO scope
  components/feature/recentlyclosed/src/androidTest/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorageTest.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddleware.kt
  components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/db/RecentlyClosedTabDao.kt
Labels: 🛬 needs landing

#9473 Update ac version to 72.0.0
  .buildconfig.yml
  version.txt
Labels: 🛬 needs landing

#9481 For #9480 - Treat GV INPUT_RESULT_IGNORED as INPUT_RESULT_HANDLED
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
Labels: 🛬 needs landing

#9478 Issue #8598: Change signature for ActivityDelegate
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/support/base/src/main/java/mozilla/components/support/base/feature/ActivityResultHandler.kt
  components/support/base/src/main/java/mozilla/components/support/base/feature/ViewBoundFeatureWrapper.kt
  components/support/base/src/test/java/mozilla/components/support/base/feature/ViewBoundFeatureWrapperTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing

#9488 Revert "Closes #8693: Integrate GeckoWebExecutor#FETCH_FLAG_PRIVATE."
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Request.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/lib/fetch-httpurlconnection/src/main/java/mozilla/components/lib/fetch/httpurlconnection/HttpURLConnectionClient.kt
  components/lib/fetch-okhttp/src/main/java/mozilla/components/lib/fetch/okhttp/OkHttpClient.kt
Labels: 🛬 needs landing

#9492 Fix typo in native_messaging description
  components/feature/addons/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#9485 Closes #8679: Emit top sites count fact for top sites telemetry
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/PinnedSitesStorageTest.kt
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/db/PinnedSiteDaoTest.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/PinnedSiteStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesUseCases.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/db/PinnedSiteDao.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/facts/TopSitesFacts.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/DefaultTopSitesStorageTest.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/fact/TopSitesFactsTest.kt
Labels: 🛬 needs landing

#9472 Closes #9471: Fix Confirm and Alert js dialogs don't show buttons when the message is too long
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AbstractPromptTextDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AlertDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/MultiButtonDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/TextPromptDialogFragment.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_many_dialogs_checkbox_dialogs.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_prompt_with_check_box.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_text_prompt.xml
  components/feature/prompts/src/main/res/values/ids.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/AlertDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/MultiButtonDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/TextPromptDialogFragmentTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9489 Closes #9484: Handle multiple add-ons update that require new permissions
  components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/DefaultAddonUpdaterTest.kt
  components/feature/addons/src/test/java/mozilla/components/feature/addons/update/NotificationHandlerServiceTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9365 Closes #9170: Use MediaSession Metadata in Media Notification
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegateTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegateTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/mediasession/MediaSession.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/SessionState.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/notification/MediaNotificationTest.kt
Labels: 🛬 needs landing

#8806 Issue #8690: Specify the frecency threshold for the fetched top frecent sites
  components/browser/storage-memory/src/main/java/mozilla/components/browser/storage/memory/InMemoryHistoryStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Types.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/HistoryDelegateTest.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesConfig.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/presenter/DefaultTopSitesPresenter.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/DefaultTopSitesStorageTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#9499 Revert "For Fenix#16832: Separate facts for addon install and addon enabled"
  components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  components/support/webextensions/src/main/java/mozilla/components/support/webextensions/facts/WebExtensionFacts.kt
  components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
Labels: 🛬 needs landing (squash)

#9512 [RELENG-169] support staging release promotion projects
  .taskcluster.yml
  taskcluster/ac_taskgraph/release_promotion.py
  taskcluster/ci/config.yml
Labels: 🛬 needs landing

#9519 Closes #9518: CustomTabsToolbarFeature: Allow disabling setting toolbar background and forcing action button tint.
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
Labels: 🛬 needs landing

#9511 For fenix#17451: add comment warning about Log.Priority.VERBOSE.
  components/support/base/src/main/java/mozilla/components/support/base/log/Log.kt
Labels: 🛬 needs landing

#9442 For #9441: Move files and media permission check
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9532 Closes #9531: Stop retrieving metadata artwork when in private tabs
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/SessionState.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/ext/SessionStateKtTest.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/notification/MediaNotificationTest.kt
Labels: 🛬 needs landing

#9529 Closes #9528: Exposes BrowserMenu dismiss through BrowserToolbarMenu
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
Labels: 🛬 needs landing

#9527 Closes #9526 guessFileName handle generic content types
  components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9522 For #9480 - Drop INPUT_RESULD_IGNORED from GeckoView
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
Labels: 🛬 needs landing

#9538 Closes #9531: Return content icon if get artwork fails
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/mediasession/MediaSession.kt
  components/feature/media/src/main/java/mozilla/components/feature/media/ext/SessionState.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/ext/SessionStateKtTest.kt
Labels: 🛬 needs landing

#9520 RemoveTabUseCase: Support selecting parent tab
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
Labels: 🛬 needs landing

#9508 Close #3036: Add feature to support WebAuthn
  .buildconfig.yml
  README.md
  components/feature/webauthn/README.md
  components/feature/webauthn/build.gradle
  components/feature/webauthn/proguard-rules.pro
  components/feature/webauthn/src/main/AndroidManifest.xml
  components/feature/webauthn/src/main/java/mozilla/components/feature/webauthn/WebAuthnFeature.kt
  components/feature/webauthn/src/test/java/mozilla/components/feature/webauthn/WebAuthnFeatureTest.kt
  components/feature/webauthn/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/feature/webauthn/src/test/resources/robolectric.properties
  docs/changelog.md
  taskcluster/ci/config.yml
Labels: 🛬 needs landing

#9551 Closes #9550: Check port instance before disconnecting
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
Labels: 🛬 needs landing

#9394 Add methods to cover new methods in NimbusClient
  buildSrc/src/main/java/Dependencies.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/NimbusTest.kt
  docs/changelog.md
  samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/MainActivity.kt
  samples/glean/src/main/res/raw/initial_experiments.json
  samples/glean/src/main/res/values/endpoints.xml
Labels: 🛬 needs landing (squash)

#9557 Re-land: "Closes #8693: Integrate GeckoWebExecutor#FETCH_FLAG_PRIVATE."
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Request.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  components/lib/fetch-httpurlconnection/src/main/java/mozilla/components/lib/fetch/httpurlconnection/HttpURLConnectionClient.kt
  components/lib/fetch-okhttp/src/main/java/mozilla/components/lib/fetch/okhttp/OkHttpClient.kt
Labels: 🛬 needs landing
