Repository mozilla-mobile/android-components, pull requests merged in 2021-09, with the labels that each got.

#10906 For #10905: Add a Two State BrowserMenuImageText menu item.
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/TwoStateBrowserMenuImageText.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/TwoStateBrowserMenuImageTextTest.kt
Labels: 🛬 needs landing

#10837 Issue #10836: Add Facts for Credit Card Autofill Feature
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardPicker.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardSelectBar.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/facts/CreditCardAutofillDialogFacts.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/creditcard/CreditCardSelectBarTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/facts/CreditCardAutofillDialogFactsTest.kt
Labels: 🛬 needs landing

#10917 For #10916: Update layout_goneMarginStart to match display toolbar.
  components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_edittoolbar.xml
Labels: 🛬 needs landing

#10918 Bug 1720139 - Ship v26.0.0 of feature-webcompat
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/trackingProtection.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/trackingProtection.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1610016-gaana.com-input-position-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1712843-snaptik.app-fix-text-input-alignment.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1727080-nexity.fr-svg-size-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1728140-map-size-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1724764-amextravel.com-window-print.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1724868-news.yahoo.co.jp-ua-override.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/addthis-angular.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/vidible.js
Labels: 🛬 needs landing

#10925 Stop generating metrics.md for browser-engine-gecko component.
  components/browser/engine-gecko/build.gradle
  components/browser/engine-gecko/docs/metrics.md
Labels: 🛬 needs landing

#10927 Issue #10922: AwesomeBar(): Use description as fallback if suggestion has no title (like BrowserAwesomeBar).
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestion.kt
Labels: 🛬 needs landing

#10929 ImageLoader(): Avoid effect loading image to leave composition too early.
  components/support/images/src/main/java/mozilla/components/support/images/compose/loader/ImageLoader.kt
  components/support/images/src/main/java/mozilla/components/support/images/compose/loader/ImageLoaderScope.kt
Labels: 🛬 needs landing

#10941 RemoveAllPrivateTabsAction: Clear selectedTabId if no new selection is available.
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
Labels: 🛬 needs landing

#10942 Issue #10922: SuggestionFetcher: Close internal dispatcher when fetcher is no longer needed.
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/SuggestionFetcher.kt
Labels: 🛬 needs landing

#10946 Issue #10922: (compose-awesomebar) Suggestion: Update spacing.
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestion.kt
Labels: 🛬 needs landing

#10947 Issue #10922: AwesomeBar(): Refetch suggestions if fetcher changes.
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBar.kt
Labels: 🛬 needs landing

#10939 Issue #10922: Port Facts from browser-awesomebar to compose-awesomebar.
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBarFacts.kt
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/SuggestionFetcher.kt
Labels: 🛬 needs landing

#10950 Forward search terms to Tabs Tray Tabs
  components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/Tab.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/TabSessionState.kt
Labels: 🛬 needs landing

#10913 Ensure we notice and repair a missing or expired push endpoint.
  components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
Labels: 🛬 needs landing (squash)

#10930 History Metadata delete API
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryMetadataStorage.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10957 Issue #10922: AwesomeBar(): Add test tags for UI testing.
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBar.kt
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestions.kt
Labels: 🛬 needs landing

#10959 Lazily register ktlintFormat task
  build.gradle
Labels: 🛬 needs landing

#9827 For #6225: Make webchannel work with custom fxa server
  components/feature/accounts/src/main/assets/extensions/fxawebchannel/background.js
  components/feature/accounts/src/main/assets/extensions/fxawebchannel/manifest.template.json
  components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FxaWebChannelFeature.kt
  components/feature/accounts/src/test/java/mozilla/components/feature/accounts/FxaWebChannelFeatureTest.kt
Labels: 🛬 needs landing (squash)

#10828 Use new geckoview-omni package, which includes Glean directly
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Gecko.kt
  components/service/glean/build.gradle
  docs/changelog.md
Labels: performance, 🛬 needs landing

#10985 Close #10984: Persist search term in content state
  components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt
  components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateWriter.kt
  components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/Keys.kt
  components/browser/session-storage/src/test/java/mozilla/components/browser/session/storage/serialize/BrowserStateWriterReaderTest.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/recover/RecoverableTab.kt
Labels: 🛬 needs landing

#10991 For #10990 - Assert on color resource value not on a hardcoded one
  components/browser/menu/src/test/java/mozilla/components/browser/menu/BrowserMenuHighlightTest.kt
Labels: 🛬 needs landing, 🕵️‍♀️ needs review

#10983 Add ScrollView as a main container in context menu dialog
  components/feature/contextmenu/src/main/res/layout/mozac_feature_contextmenu_dialog.xml
  docs/changelog.md
Labels: 🛬 needs landing

#11003 Bug 1728594 - fix a SmartBlock regression breaking some links
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-analytics-and-tag-manager.js
Labels: 🛬 needs landing

#11006 Closes #11004: Update lastAccess when tab is selected due to removal
  components/feature/session/src/main/java/mozilla/components/feature/session/middleware/LastAccessMiddleware.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/middleware/LastAccessMiddlewareTest.kt
Labels: 🛬 needs landing

#11009 Issue #11008 - Make HistoryMetadataKey parcelable
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryMetadataStorage.kt
Labels: 🕵️‍♀️ needs review

#10988 No issue: remove redundant header name definitions.
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Client.kt
  components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Response.kt
Labels: 🛬 needs landing

#11019 Set version to 93.0.8.
  .buildconfig.yml
  version.txt
Labels: 🛬 needs landing

#11028 Handle PlacesExceptions when reading history metadata
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
Labels: 🛬 needs landing

#11026 SystemEngine README.md edited (because constructor was changed)
  components/browser/engine-system/README.md
Labels: 🛬 needs landing

#11022 Updates a-s to 85.0.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#11018 Close #11017: Update lastAccess on RestoreAction
  components/feature/session/src/main/java/mozilla/components/feature/session/middleware/LastAccessMiddleware.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/middleware/LastAccessMiddlewareTest.kt
Labels: 🛬 needs landing

#11041 For 11040 - Distinct suggestions from CombinedHistorySuggestionProvider
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/CombinedHistorySuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/CombinedHistorySuggestionProviderTest.kt
Labels: 🛬 needs landing

#11048 Bug 1720140 - Ship v27.0.0 of feature-webcompat
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/trackingProtection.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1645064-s-kanava.fi-invisible-charts.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1722955-frontgate.com-ua-override.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1731825-office365-email-handling-prompt-autohide.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/ua_helpers.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/stackblitz.js
Labels: 🛬 needs landing

#11044 For #11043 - Use the production endpoint for Pocket recommendations.
  components/service/pocket/src/main/java/mozilla/components/service/pocket/api/PocketEndpointRaw.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/api/PocketEndpointRawTest.kt
Labels: 🛬 needs landing

#11053 Closes #11051: NPE parsing search terms when placeholder is missing
  components/feature/search/src/main/java/mozilla/components/feature/search/ext/SearchEngine.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/ext/SearchEngineKtTest.kt
Labels: 🛬 needs landing

#11020 Update to A-S 85.2.0, expose A-S highlights API
  buildSrc/src/main/java/Dependencies.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Types.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryMetadataStorage.kt
Labels: 🛬 needs landing

#11058 Add API for deleting metadata search term groups
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryMetadataStorage.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11032 Closes #11031: AwesomeBar: Use a min height of 56dp for suggestions instead of a fixed height.
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestion.kt
Labels: 🛬 needs landing

#11060 No issue: Expose `createdAt` through tabstray
  components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/Tab.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/TabSessionState.kt
Labels: ✏️ needs changes

#11068 upgrade as to 85.3.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing
