Repository mozilla-mobile/android-components, pull requests merged in 2021-12, with the labels that each got.

#11347 Issue #11346: Use the correct hex value for Pink60
  components/ui/colors/src/main/java/mozilla/components/ui/colors/PhotonColors.kt
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing

#11349 Issue #11348: Add additional photon colors
  components/ui/colors/src/main/java/mozilla/components/ui/colors/PhotonColors.kt
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing

#11351 Issue #11305: Add engine setting for HTTPS-Only mode
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Engine.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11356 Issue #11355: Add DarkGrey30A96 and DarkGrey90A96 to photon colors
  components/ui/colors/src/main/java/mozilla/components/ui/colors/PhotonColors.kt
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing

#11361 Closes #11360: Strip non-digit characters when calling getCreditCardIIN
  components/support/utils/src/main/java/mozilla/components/support/utils/CreditCardUtils.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/ext/String.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/CreditCardUtilsTest.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/ext/StringTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, 🕵️‍♀️ needs review

#11354 Fix for the browser-icons test
  build.gradle
Labels: 🛬 needs landing

#11364 Bug 1720143 - Ship v29.1.0 of the WebCompat System Addon.
  components/feature/webcompat/src/main/assets/extensions/webcompat/about-compat/aboutCompat.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/about-compat/aboutCompat.html
  components/feature/webcompat/src/main/assets/extensions/webcompat/about-compat/aboutCompat.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1740542-tesla.com-footer-links.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1741234-patient.alphalabs.ca-height-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1743041-lu.ma-display-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1743614-storytel.com-flex-min-width.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/about_compat_broker.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/requestStorageAccess_helper.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/run.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/facebook-sdk.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-analytics-legacy.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-publisher-tags.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/humblebundle.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/microsoftLogin.js
Labels: 🛬 needs landing

#11352 Issue #11306: Add minimal error page for HTTPS-Only mode.
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/errorpages/src/main/assets/errorPageScripts.js
  components/browser/errorpages/src/main/assets/error_page_js.html
  components/browser/errorpages/src/main/java/mozilla/components/browser/errorpages/ErrorPages.kt
  components/browser/errorpages/src/main/res/values/strings.xml
  components/browser/errorpages/src/test/java/mozilla/components/browser/errorpages/ErrorPagesTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#11381 Closes #11380: Send Distribution ID to Socorro crash reports
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
Labels: 🛬 needs landing

#11377 For #11376: Add a typealias in MetricAliases for UrlMetricType.
  components/service/glean/src/main/java/mozilla/components/service/glean/private/MetricAliases.kt
Labels: 🛬 needs landing

#11389 Issue #11388 - Add Ink80A96 to photon colors
  components/ui/colors/src/main/java/mozilla/components/ui/colors/PhotonColors.kt
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing

#11390 For #11387 - Remove deprecated constructor from PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
Labels: 🛬 needs landing

#11256 Uniffi sync manager / Upgrade to A-S 87.1.0
  buildSrc/src/main/java/Dependencies.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Connection.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/RemoteTabsStorage.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/concept/sync/src/main/java/mozilla/components/concept/sync/Sync.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceSettingsCache.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/Types.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt
  components/service/sync-autofill/src/main/java/mozilla/components/service/sync/autofill/AutofillCreditCardsAddressesStorage.kt
  components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/SyncableLoginsStorage.kt
Labels: 🛬 needs landing (squash)

#11061 Try loading icons synchronously first from an in-memory cache
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/BrowserIconsTest.kt
Labels: 🛬 needs landing

#11404 For #11402: Add proton quit icon.
  components/ui/icons/src/main/res/drawable/mozac_ic_quit.xml
Labels: 🛬 needs landing

#11401 Closes #11400: Allow overriding title/description of error pages
  components/browser/errorpages/src/main/java/mozilla/components/browser/errorpages/ErrorPages.kt
  components/browser/errorpages/src/test/java/mozilla/components/browser/errorpages/ErrorPagesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11417 Enable parallel builds locally, disable them in CI
  gradle.properties
  taskcluster/docker/base/Dockerfile
Labels: do not land

#11412 Prompt on leaving private while downloading
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ui/DownloadCancelDialogFragment.kt
  components/feature/downloads/src/main/res/layout/mozac_download_cancel.xml
  components/feature/downloads/src/main/res/values/strings.xml
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadCancelDialogFragmentTest.kt
Labels: 🛬 needs landing

#11410 Updates application services to 87.2.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#11399 For #10739 - Add support for the Storage Access API prompt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoSitePermissionsStorage.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/permission/GeckoSitePermissionsStorageTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/permission/PermissionRequest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/permission/SitePermissions.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/permission/SitePermissionsStorage.kt
  components/feature/sitepermissions/build.gradle
  components/feature/sitepermissions/schemas/mozilla.components.feature.sitepermissions.db.SitePermissionsDatabase/8.json
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorage.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsDialogFragment.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsRules.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDatabase.kt
  components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsEntity.kt
  components/feature/sitepermissions/src/main/res/layout/mozac_site_permissions_prompt.xml
  components/feature/sitepermissions/src/main/res/values/strings.xml
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorageTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsDialogFragmentTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsRulesTest.kt
  components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/db/SitePermissionEntityTest.kt
  components/ui/icons/src/main/res/drawable/mozac_ic_cookies.xml
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing

#11436 PromptFeature: Keep references to active prompts
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
Labels: 🛬 needs landing

#11343 Closes #11339: don’t stop private download when the tab is closed
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
Labels: 🛬 needs landing

#11431 No issue: add prefix to download feature strings
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ui/DownloadCancelDialogFragment.kt
  components/feature/downloads/src/main/res/layout/mozac_download_cancel.xml
  components/feature/downloads/src/main/res/values/strings.xml
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadCancelDialogFragmentTest.kt
Labels: 🛬 needs landing (squash)

#11442 For #11387 - Update changelog with an entry on the PromptFeature constructor removal
  docs/changelog.md
Labels: 🛬 needs landing (squash)

#11446 PromptFeature: Only dismiss prompts with shouldDismissOnLoad flag set
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
Labels: 🛬 needs landing

#11445 Close #11444: Add optional user interaction param to goBack/goForward
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/EngineDelegateMiddleware.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing
