Repository mozilla-mobile/android-components, pull requests merged in 2021-03, with the labels that each got.

#9771 For #9770 - Don't animate the dynamic toolbar while tab is loading
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehavior.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehaviorTest.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarBehaviorController.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarFeature.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarBehaviorControllerTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9790 Closes #9789 close the download stream when dismissing the dialog
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9794 Issue #9793: Remove setting the "uniffi.component.autofill.libraryOverride" property in AutofillCreditCardsAddressesStorage
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/AutofillCreditCardsAddressesStorage.kt
Labels: 🛬 needs landing

#9808 Closes #9807: Calls startForeground in media session service onStartCommand
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaSessionServiceDelegateTest.kt
Labels: 🛬 needs landing

#9788 Closes #9787 separate content blocking setting from TrackingProtectionState.enabled
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-beta/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SettingsUseCases.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/SettingsUseCasesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9775 For #9774 - Removes beforeTextChangedIndex, cause for backspace issues
  components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
Labels: 🛬 needs landing

#9820 Remove deprecated references to old MediaSession API
  components/browser/engine-gecko-beta/src/test/java/org/mozilla/geckoview/MockRecordingDevice.kt
  components/browser/engine-gecko-nightly/src/test/java/org/mozilla/geckoview/MockRecordingDevice.kt
  components/browser/engine-gecko/src/test/java/org/mozilla/geckoview/MockRecordingDevice.kt
Labels: 🛬 needs landing

#9819 Secure prefs (read: AndroidKeyStore) reliability experiment
  components/lib/dataprotect/src/main/java/mozilla/components/lib/dataprotect/SecurePrefsReliabilityExperiment.kt
  components/lib/dataprotect/src/test/java/mozilla/components/lib/dataprotect/SecurePrefsReliabilityExperimentTest.kt
Labels: 🛬 needs landing

#9811 Closes #9805 - Add support for opening links from ACTION_MAIN Intents
  components/feature/intent/src/main/java/mozilla/components/feature/intent/processing/TabIntentProcessor.kt
  components/feature/intent/src/test/java/mozilla/components/feature/intent/processing/TabIntentProcessorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9828 Close #9564: Fix intermittent failing test in feature-app-links
  components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
Labels: 🛬 needs landing

#9802 Issue #9455: Introduce Gecko Credit Cards and Addresses Storage Delegate
  components/browser/storage-sync/build.gradle
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/GeckoCreditCardsAddressesStorageDelegate.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/GeckoCreditCardsAddressesStorageDelegateTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/CreditCardsAddressesStorage.kt
Labels: 🛬 needs landing

#9834 Update to GeckoView Nightly 88.0.20210303094110
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
Labels: 🛬 needs landing

#9824 Close issue #9823 Make users aware that download was not performed because of a denied permission
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/main/res/values/strings.xml
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/AlertDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/ChoiceDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/ColorPickerDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/ConfirmDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/MultiButtonDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/SaveLoginDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/TextPromptDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/TimePickerDialogFragmentTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/login/LoginSelectBarTest.kt
  components/support/base/src/main/java/mozilla/components/support/base/dialog/DeniedPermissionDialogFragment.kt
  components/support/base/src/main/res/values/strings.xml
  components/support/base/src/test/java/mozilla/components/support/base/dialog/DeniedPermissionDialogFragmentTest.kt
  components/support/test/src/main/java/mozilla/components/support/test/ext/Context.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9833 Closes #9806 Refactor close download response to be in the DownloadMiddleware
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsUseCases.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
Labels: 🛬 needs landing

#8577 For #8517, use new API's for immersive modes on Android 11
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Activity.kt
Labels: 🛬 needs landing

#9845 Remove unneeded/unused browser session fields
  components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/EngineObserver.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/BrowserStoreExtensions.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/SessionTest.kt
  components/browser/session/src/test/java/mozilla/components/browser/session/engine/EngineObserverTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#9855 For #9614: Integrate new onTouchEventForDetailResult.
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
Labels: 🛬 needs landing

#9818 Closes #9777: Android Autofill: Verify app <-> domain relationship and let user confirm.
  components/feature/autofill/build.gradle
  components/feature/autofill/src/main/AndroidManifest.xml
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/AutofillConfiguration.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/ext/LoginsStorage.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/handler/FillRequestHandler.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/structure/ParsedStructure.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/ui/AbstractAutofillConfirmActivity.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/ui/AbstractAutofillUnlockActivity.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/verify/CredentialAccessVerifier.kt
  components/feature/autofill/src/main/res/values/strings.xml
  components/service/digitalassetlinks/src/main/java/mozilla/components/service/digitalassetlinks/Relation.kt
  samples/browser/src/main/AndroidManifest.xml
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/autofill/AutofillConfirmActivity.kt
Labels: 🛬 needs landing

#9861 Closes #9859: Detect media notification icon size is incorrect
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
Labels: 🛬 needs landing

#9731 Update to Application Services v73.0.1
  buildSrc/src/main/java/Dependencies.kt
  components/service/firefox-accounts/README.md
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Exceptions.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Types.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaDeviceConstellationTest.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9864 Closes #9864: Remove authorizeOAuthCode from the FirefoxAccount API
  components/concept/sync/src/main/java/mozilla/components/concept/sync/OAuthAccount.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9868 For #9806 Close the download response before processing other actions
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadMiddleware.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
Labels: 🛬 needs landing

#9877 Update to GeckoView Nightly 88.0.20210311093001 on master
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
Labels: 🛬 needs landing

#9862 Autofill: Update string description.
  components/feature/autofill/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#9885 Closes #9884: Catch SecurityException in GeckoSelectionActionDelegate when performing action
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt
  components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegateTest.kt
Labels: 🛬 needs landing

#9890 Remove leftover/unneeded decodeURIComponent in readerview
  components/feature/readerview/src/main/assets/extensions/readerview/readerview.js
Labels: 🛬 needs landing

#9898 Set version to 73.0.10.
  .buildconfig.yml
  version.txt
Labels: 🛬 needs landing

#9849 Updating CODEOWNERS
  CODEOWNERS
Labels: 🛬 needs landing

#9900 (Merge day) browser-engine-gecko-beta (87) -> browser-engine-gecko-release (87)
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
Labels: 🛬 needs landing

#9421 Don't run tasks for mergify branches on push
  .taskcluster.yml
Labels: 🛬 needs landing

#9909 Set version to 73.0.11.
  .buildconfig.yml
  version.txt
Labels: 🛬 needs landing

#9759 For #8518: Fix defaultDisplay and getSize deprecations in SDK 30.
  components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt
  components/feature/qr/src/test/java/mozilla/components/feature/qr/QrFragmentTest.kt
Labels: 🛬 needs landing

#9901 For #9839: Upgrade androidx browser to 1.3.0 .
  buildSrc/src/main/java/Dependencies.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/AbstractCustomTabsService.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabConfigHelper.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabConfigHelperTest.kt
  samples/firefox-accounts/src/main/java/org/mozilla/samples/fxa/MainActivity.kt
Labels: 🛬 needs landing

#9920 Uplift: Continue to remove JCenter
  buildSrc/build.gradle
  settings.gradle
Labels: 🕵️‍♀️ needs review

#9479 Closes #9464: Display a list of active Nimbus experiment
  components/service/nimbus/build.gradle
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusDetailAdapter.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusDetailItemViewHolder.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusExperimentAdapter.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusExperimentItemViewHolder.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusExperimentsAdapterDelegate.kt
  components/service/nimbus/src/main/res/layout/mozac_service_nimbus_branch_item.xml
  components/service/nimbus/src/main/res/layout/mozac_service_nimbus_experiment_details.xml
  components/service/nimbus/src/main/res/layout/mozac_service_nimbus_experiment_item.xml
  components/service/nimbus/src/main/res/layout/mozac_service_nimbus_experiments.xml
  components/service/nimbus/src/main/res/values/strings.xml
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/ui/NimbusDetailItemViewHolderTest.kt
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/ui/NimbusExperimentItemViewHolderTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9930 No issue: REVERT renaming add-ons to extensions.
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt
  components/browser/menu/src/main/res/values/strings.xml
  components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilderTest.kt
  components/feature/addons/src/main/java/mozilla/components/feature/addons/menu/WebExtensionNestedMenuCandidate.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/mozilla/components/feature/addons/menu/WebExtensionNestedMenuCandidateTest.kt
  samples/browser/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#9938 Closes #9937: Emit a top sites count fact when retrieving the list of top sites
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesUseCases.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/DefaultTopSitesStorageTest.kt
Labels: 🛬 needs landing

#9941 Closes #9939: Fix placeholder in translation.
  components/ui/tabcounter/src/main/res/values-bg/strings.xml
Labels: 🛬 needs landing

#9934 Add private flag to TabsTray Tab
  components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/Tab.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/TabSessionState.kt
Labels: 🛬 needs landing

#9843 [SDK-217] Allow consumers to set app name and channel for experiment filtering
  buildSrc/src/main/java/Dependencies.kt
  components/browser/engine-gecko/docs/metrics.md
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/NimbusTest.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt
  samples/glean/src/main/java/org/mozilla/samples/glean/MainActivity.kt
  samples/glean/src/main/res/raw/initial_experiments.json
Labels: 🛬 needs landing

#9911 Closes #9910: Use correct lock for accessing syncManager instance
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
Labels: 🛬 needs landing

#9779 Closes #9754: add locale to browser state
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/DownloadStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/LocaleStateReducer.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/LocaleActionTest.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/reducer/LocaleStateReducerTest.kt
  components/feature/privatemode/src/main/java/mozilla/components/feature/privatemode/notification/AbstractPrivateNotificationService.kt
  components/feature/privatemode/src/test/java/mozilla/components/feature/privatemode/notification/AbstractPrivateNotificationServiceTest.kt
  components/support/locale/build.gradle
  components/support/locale/src/main/java/mozilla/components/support/locale/LocaleManager.kt
  components/support/locale/src/main/java/mozilla/components/support/locale/LocaleMiddleware.kt
  components/support/locale/src/main/java/mozilla/components/support/locale/LocaleUseCases.kt
  components/support/locale/src/test/java/mozilla/components/support/locale/LocaleManagerTest.kt
  components/support/locale/src/test/java/mozilla/components/support/locale/LocaleMiddlewareTest.kt
  components/support/locale/src/test/java/mozilla/components/support/locale/LocaleUseCasesTest.kt
  components/support/locale/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  docs/changelog.md
Labels: 🛬 needs landing (squash)

#9955 For #9954: Ignore for intermittent test failure
  components/support/locale/src/test/java/mozilla/components/support/locale/LocaleMiddlewareTest.kt
Labels: 🛬 needs landing

#9956 Closes #9954: intermittent test for locale middleware
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadMiddlewareTest.kt
  components/support/locale/build.gradle
  components/support/locale/src/test/java/mozilla/components/support/locale/LocaleMiddlewareTest.kt
Labels: 🛬 needs landing (squash)

#9957 For #9754: Improve locale manager
  components/support/locale/src/main/java/mozilla/components/support/locale/LocaleManager.kt
Labels: 🛬 needs landing

#9967 For #9964: Use applicationContext to fetch localized strings.
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt
  docs/changelog.md
Labels: 🛬 needs landing

#9896 Issue #9895: Expose getExperimentBranches in NimbusClientInterface
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#9943 For #9840: Add support for icon, label and custom checkbox menu item.
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuImageTextCheckboxButton.kt
  components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_text_checkbox_button.xml
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuImageTextCheckboxButtonTest.kt
Labels: 🛬 needs landing

#9990 Bug 1689162: Upgrade to new version of Glean metrics.yaml schema
  components/browser/engine-gecko-beta/metrics.yaml
  components/browser/engine-gecko-nightly/metrics.yaml
  components/browser/engine-gecko/metrics.yaml
  components/lib/crash/metrics.yaml
  components/service/nimbus/metrics.yaml
  components/support/migration/metrics.yaml
  components/support/migration/pings.yaml
  components/support/sync-telemetry/metrics.yaml
  components/support/sync-telemetry/pings.yaml
  samples/glean/pings.yaml
Labels: 🛬 needs landing (squash)

#9992 Closes #9991: Add ColorStateList support for TabCounter
  components/support/utils/src/main/java/mozilla/components/support/utils/DrawableUtils.kt
  components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounter.kt
  components/ui/tabcounter/src/test/java/mozilla/components/ui/tabcounter/TabCounterTest.kt
Labels: 🛬 needs landing
