Repository mozilla-mobile/android-components, pull requests merged in 2021-05, with the labels that each got.

#10203 No issue: update metrics.md
  components/browser/engine-gecko/docs/metrics.md
  components/support/migration/docs/metrics.md
Labels: 🛬 needs landing

#10174 No issue: Add correct changelog issue numbers for #10133 and #10138
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#10208 Close #10207: Add support for private requests in Glean
  components/service/glean/src/main/java/mozilla/components/service/glean/net/ConceptFetchHttpUploader.kt
  components/service/glean/src/test/java/mozilla/components/service/glean/net/ConceptFetchHttpUploaderTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10204 Refactor engine-gecko tests to remove references to GeckoBundle
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineViewTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/MockWebExtension.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegateTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/MockWebNotification.kt
  components/browser/engine-gecko/src/test/java/org/mozilla/geckoview/MockSelection.kt
  components/browser/engine-gecko/src/test/java/org/mozilla/geckoview/MockWebExtension.kt
  components/browser/engine-gecko/src/test/java/org/mozilla/geckoview/MockWebNotification.kt
  components/browser/engine-gecko/src/test/java/org/mozilla/geckoview/MockWebResponseInfo.kt
Labels: 🛬 needs landing

#10202 Closes #10200: Expose enterpriseRootsEnabled runtime setting
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt
Labels: 🛬 needs landing

#10194 Close #10050: Upstream AbstractBinding from consuming applications
  components/lib/state/src/main/java/mozilla/components/lib/state/helpers/AbstractBinding.kt
  components/lib/state/src/test/java/mozilla/components/lib/state/helpers/AbstractBindingTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10189 Issue #10188: Add UI components for displaying a list of branches for a Nimbus experiment
  components/service/nimbus/build.gradle
  components/service/nimbus/src/main/AndroidManifest.xml
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusBranchAdapter.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusBranchItemViewHolder.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusBranchesAdapterDelegate.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusDetailAdapter.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusDetailItemViewHolder.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusExperimentAdapter.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusExperimentItemViewHolder.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/ui/NimbusExperimentsAdapterDelegate.kt
  components/service/nimbus/src/main/res/layout/mozac_service_nimbus_branch_item.xml
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/ui/NimbusBranchItemViewHolderTest.kt
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/ui/NimbusDetailItemViewHolderTest.kt
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/ui/NimbusExperimentItemViewHolderTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#10196 Second batch of new proton icons
  components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_text.xml
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/icons/lightbulb.svg
  components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json
  components/ui/icons/src/main/res/drawable/mozac_ic_arrowhead_down.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_arrowhead_right.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_arrowhead_up.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_broken_lock.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_menu.xml
Labels: 🛬 needs landing

#10232 Allow setting initial load flags when creating tabs
  components/browser/session/src/main/java/mozilla/components/browser/session/SessionManager.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/engine/middleware/LinkingMiddleware.kt
  components/browser/session/src/main/java/mozilla/components/browser/session/ext/SessionExtensions.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/state/EngineState.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabIntentProcessorTest.kt
  components/feature/intent/src/test/java/mozilla/components/feature/intent/processing/TabIntentProcessorTest.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/CustomTabsUseCases.kt
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
Labels: 🛬 needs landing

#10213 Issue #10205: Add support for select credit card prompt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/CreditCard.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/CreditCard.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/CreditCardTest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#10247 Issue #9457: Add support to display a credit card picker to handle a SelectCreditCard request
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/concept/SelectablePromptView.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardPicker.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardSelectBar.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/LoginSelectBar.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_credit_card_select_prompt.xml
  components/feature/prompts/src/main/res/values/attrs.xml
  components/feature/prompts/src/main/res/values/strings.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/creditcard/CreditCardPickerTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/creditcard/CreditCardSelectBarTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/login/LoginSelectBarTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#10227 Introduce History Metadata storage API
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Types.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryMetadataStorage.kt
Labels: 🛬 needs landing

#10234 Issue #10228: Fix Intermittent AutofillCreditCardsAddressesStorageTest
  components/concept/storage/src/main/java/mozilla/components/concept/storage/CreditCardsAddressesStorage.kt
  components/service/sync-autofill/src/main/java/mozilla/components/service/sync/autofill/AutofillCreditCardsAddressesStorage.kt
  components/service/sync-autofill/src/test/java/mozilla/components/service/sync/autofill/AutofillCreditCardsAddressesStorageTest.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#10259 Issue-10228: Address intermittent test failures in AutofillCreditCardsAddressesStorageTest
  components/service/sync-autofill/src/test/java/mozilla/components/service/sync/autofill/AutofillCreditCardsAddressesStorageTest.kt
Labels: 🛬 needs landing

#10249 For issue Fenix#10231 update proton icons third batch
  components/ui/icons/src/main/res/drawable/mozac_ic_autoplay_blocked.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_broken_lock.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_check.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_fingerprint.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_globe.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_location.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_login.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_microphone.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_notification.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_password_hide.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_password_reveal.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_share.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_storage.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_sync.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_video.xml
Labels: 🛬 needs landing

#10251 Upgrade to Glean v38.0.0
  buildSrc/src/main/java/Dependencies.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10264 Closes #10263: Add Credit Card native name to type mapping.
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/Types.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/sync/TypesTest.kt
Labels: 🛬 needs landing

#10282 Update tab counter menu icons
  components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounterMenu.kt
  components/ui/tabcounter/src/main/res/drawable/mozac_ui_tabcounter_ic_close.xml
  components/ui/tabcounter/src/main/res/drawable/mozac_ui_tabcounter_ic_new.xml
  components/ui/tabcounter/src/main/res/drawable/mozac_ui_tabcounter_ic_private_browsing.xml
Labels: 🛬 needs landing

#10099 For #10092: Allow placeholder item to change tint for the extension icon
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItem.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/WebExtensionPlaceholderMenuItem.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilderTest.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItemTest.kt
Labels: 🛬 needs landing

#10242 Closes #10241: Stop announcing loading to accessibility when progress is at max
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
Labels: 🛬 needs landing

#10256 For #10248 - Obfuscates credit card numbers autofill prompt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/CreditCard.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/CreditCardTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/CreditCardsAddressesStorage.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardItemViewHolder.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/creditcard/CreditCardItemViewHolderTest.kt
  components/service/sync-autofill/src/test/java/mozilla/components/service/sync/autofill/AutofillCreditCardsAddressesStorageTest.kt
Labels: 🛬 needs landing (squash)

#10309 No issue: update metrics.md
  components/browser/engine-gecko/docs/metrics.md
  components/lib/crash/docs/metrics.md
  components/support/migration/docs/metrics.md
  components/support/sync-telemetry/docs/metrics.md
Labels: 🛬 needs landing

#10297 For #4495: Use smaller minimum icon size requirement for browser icons
  components/browser/icons/src/androidTest/java/mozilla/components/browser/icons/decoder/ICOIconDecoderTest.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/ICOIconDecoder.kt
  components/browser/icons/src/main/java/mozilla/components/browser/icons/processor/ResizingProcessor.kt
  components/browser/icons/src/main/res/values/dimens.xml
  components/browser/icons/src/test/java/mozilla/components/browser/icons/decoder/ICOIconDecoderTest.kt
  components/browser/icons/src/test/java/mozilla/components/browser/icons/processor/ResizingProcessorTest.kt
  components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/storage/ThumbnailStorage.kt
  components/support/images/src/androidTest/java/mozilla/components/support/images/decoder/OnDeviceAndroidImageDecoderTest.kt
  components/support/images/src/main/java/mozilla/components/support/images/DesiredSize.kt
  components/support/images/src/main/java/mozilla/components/support/images/decoder/AndroidImageDecoder.kt
  components/support/images/src/test/java/mozilla/components/support/images/DesiredSizeTest.kt
  components/support/images/src/test/java/mozilla/components/support/images/decoder/AndroidImageDecoderTest.kt
Labels: 🛬 needs landing

#10307 Closes #10306: Implement warmUp() for Autofill Storage.
  components/service/sync-autofill/src/main/java/mozilla/components/service/sync/autofill/AutofillCreditCardsAddressesStorage.kt
  components/service/sync-autofill/src/test/java/mozilla/components/service/sync/autofill/AutofillCreditCardsAddressesStorageTest.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#10329 AuthenticationDialogFragment: Update prompt request.
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AutofillEditText.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragmentTest.kt
Labels: 🛬 needs landing

#10332 For #10331 - Allow dynamically toggling CC autofill
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/service/sync-autofill/src/main/java/mozilla/components/service/sync/autofill/GeckoCreditCardsAddressesStorageDelegate.kt
  components/service/sync-autofill/src/test/java/mozilla/components/service/sync/autofill/GeckoCreditCardsAddressesStorageDelegateTest.kt
  docs/changelog.md
Labels: 🛬 needs landing (squash)

#10281 Issue #9813 - Add CreditCardUtils to parse credit card types from a card number and retrieve their logos
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/CreditCard.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardItemViewHolder.kt
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_credit_card_list_item.xml
  components/feature/prompts/src/main/res/layout/mozac_feature_prompts_credit_card_select_prompt.xml
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/creditcard/CreditCardItemViewHolderTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/CreditCardUtils.kt
  components/support/utils/src/main/res/drawable/ic_cc_logo_amex.xml
  components/support/utils/src/main/res/drawable/ic_cc_logo_diners.xml
  components/support/utils/src/main/res/drawable/ic_cc_logo_discover.xml
  components/support/utils/src/main/res/drawable/ic_cc_logo_jcb.xml
  components/support/utils/src/main/res/drawable/ic_cc_logo_mastercard.xml
  components/support/utils/src/main/res/drawable/ic_cc_logo_mir.xml
  components/support/utils/src/main/res/drawable/ic_cc_logo_unionpay.xml
  components/support/utils/src/main/res/drawable/ic_cc_logo_visa.xml
  components/support/utils/src/main/res/drawable/ic_icon_credit_card_generic.xml
  components/support/utils/src/test/java/mozilla/components/support/utils/CreditCardUtilsTest.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#10344 Closes #10283: Add region specific search engine lists for fr-CA, fr-FR and en-AU
  components/feature/search/src/main/assets/search/list.json
  components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
Labels: 🛬 needs landing

#10347 Closes #10126: Expose the new gecko API for controlling CookieBehaviorPrivateMode.
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10342 For #10290: Create facts for credit card autofill feature
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardSelectBar.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/SaveLoginDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/facts/CreditCardAutofillDialogFacts.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/facts/LoginDialogFacts.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/creditcard/CreditCardSelectBarTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/facts/CreditCardAutofillDialogFactsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10362 Closes #10361: Use IO dispatcher for sync and add-on workers
  components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt
Labels: 🛬 needs landing

#10356 Closes #4495: Add missing Amazon icon url for Tippy Top Json
  components/browser/icons/src/main/assets/mozac.browser.icons/icons-top200.json
  components/browser/icons/src/test/java/mozilla/components/browser/icons/preparer/TippyTopIconPreparerTest.kt
Labels: 🛬 needs landing

#10374 Bug 1707797 - Ship v23.0.0 of feature-webcompat
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/trackingProtection.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/trackingProtection.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1653075-livescience.com-scrollbar-width.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1655049-dev.to-unclickable-button-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1690158-slack.com-webkit-scrollbar.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1707795-office365-sheets-overscroll-disable.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1712833-buskocchi.desuca.co.jp-fix-map-height.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1712843-snaptik.app-fix-text-input-alignment.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1677442-store.hp.com-disable-indexeddb.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1711082-m.aliexpress.com-undisable-search.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/eluminate.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/facebook-sdk.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/facebook.svg
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/play.svg
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/tracking-pixel.png
Labels: 🛬 needs landing

#10372 Closes #10371: Telemetry for sync engines - credit cards, addresses, tabs
  components/support/sync-telemetry/docs/metrics.md
  components/support/sync-telemetry/metrics.yaml
  components/support/sync-telemetry/pings.yaml
  components/support/sync-telemetry/src/main/java/mozilla/components/support/sync/telemetry/SyncTelemetry.kt
Labels: 🛬 needs landing

#10376 Issue #10361: Follow up to fix early return case when debouncing
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt
Labels: 🛬 needs landing

#10369 Issue #10363 - Handle authentication of the credit card selection for a prompt request
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardPicker.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/creditcard/CreditCardPickerTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10383 Update appservices to v77.0.2.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#10355 No issue: Update Flank to v21.05.0
  taskcluster/docker/ui-tests/Dockerfile
Labels: 🛬 needs landing

#10354 Issue #10335: Remove dokka.
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#10390 Bug 1713635 - Import v23.1.0 of feature-webcompat.
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/appConstants.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/about_compat_broker.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/run.js
Labels: 🛬 needs landing
