Repository mozilla-mobile/android-components, pull requests merged in 2021-04, with the labels that each got.

#9926 For #9922 - Calculate menu width only once, before layout
  components/browser/menu/src/main/java/mozilla/components/browser/menu/view/DynamicWidthRecyclerView.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/view/DynamicWidthRecyclerViewTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10006 For #10005 - Replace layout manager to effectively change stackFromEnd
  components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/BrowserMenuTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10041 Closes #10040: Media session launch intent will always call startForeground
  components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaSessionServiceDelegateTest.kt
Labels: 🛬 needs landing

#10027 Issue #10026: Make the CreditCard data class parcelable
  components/concept/storage/build.gradle
  components/concept/storage/src/main/java/mozilla/components/concept/storage/CreditCardsAddressesStorage.kt
Labels: 🛬 needs landing

#10031 Closes #10030: Emit suggestion clicked fact in createMultipleSuggestions
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
Labels: 🛬 needs landing

#9858 Issue #9857: Add first test cases for FillRequestHandler.
  components/feature/autofill/build.gradle
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/AbstractAutofillService.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/handler/FillRequestHandler.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/dataset/DatasetBuilder.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/dataset/LoginDatasetBuilder.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/fill/AuthFillResponseBuilder.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/fill/FillResponseBuilder.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/fill/LoginFillResponseBuilder.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/structure/ParsedStructure.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/structure/RawStructure.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/ui/AbstractAutofillConfirmActivity.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/ui/AbstractAutofillUnlockActivity.kt
  components/feature/autofill/src/test/java/mozilla/components/feature/autofill/handler/FillRequestHandlerTest.kt
  components/feature/autofill/src/test/java/mozilla/components/feature/autofill/test/DOMNavigator.kt
  components/feature/autofill/src/test/java/mozilla/components/feature/autofill/test/MockStructure.kt
  components/feature/autofill/src/test/resources/fixtures/app_expensify.xml
  components/feature/autofill/src/test/resources/fixtures/app_facebook.xml
  components/feature/autofill/src/test/resources/fixtures/app_facebook_lite.xml
  components/feature/autofill/src/test/resources/fixtures/app_messenger_lite.xml
  components/feature/autofill/src/test/resources/fixtures/app_twitter.xml
  components/feature/autofill/src/test/resources/fixtures/browser_fenix_amazon.co.uk.xml
  components/feature/autofill/src/test/resources/fixtures/browser_webview_gmail.xml
Labels: 🛬 needs landing

#9769 Closes #9768: Add support for duplicating tabs.
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounterMenu.kt
  components/ui/tabcounter/src/main/res/values/strings.xml
  docs/changelog.md
Labels: 🛬 needs landing

#10033 For #10032 - Handle menu touches in expandable menu on Samsung devices
  components/browser/menu/src/main/java/mozilla/components/browser/menu/view/ExpandableLayout.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/view/ExpandableLayoutTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10039 For #10037: Adjust BrowserMenuImageTextCheckboxButton item to fit UX specs.
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuImageTextCheckboxButton.kt
  components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_text_checkbox_button.xml
Labels: 🛬 needs landing

#10056 Remove multiplatform-lib-dummy component.
  .buildconfig.yml
  components/multiplatform/lib-dummy/build.gradle.kts
  components/multiplatform/lib-dummy/src/androidMain/AndroidManifest.xml
  components/multiplatform/lib-dummy/src/androidMain/kotlin/mozilla/components/multiplatform/lib/dummy/DummyDelegate.kt
  components/multiplatform/lib-dummy/src/androidTest/kotlin/mozilla/components/multiplatform/lib/dummy/DummyDelegateTest.kt
  components/multiplatform/lib-dummy/src/commonMain/kotlin/mozilla/components/multiplatform/lib/dummy/Dummy.kt
  components/multiplatform/lib-dummy/src/iosMain/kotlin/mozilla/components/multiplatform/lib/dummy/DummyDelegate.kt
  components/multiplatform/lib-dummy/src/iosTest/kotlin/mozilla/components/multiplatform/lib/dummy/DummyDelegateTest.kt
  samples/ios-sample/ios-sample.xcodeproj/project.pbxproj
  samples/ios-sample/ios-sample/ContentView.swift
  taskcluster/ci/config.yml
Labels: 🛬 needs landing

#9973 RFC: Synchronizing the branching and versioning of Android Components with the Mozilla release trains
  docs/assets/images/rfc/release-trains.png
  docs/contributing.md
  docs/rfcs/0006-search-defaults.md
  docs/rfcs/0007-synchronized-releases.md
Labels: RFC, 🛬 needs landing

#10068 Issue #10064: Expose Nimbus optInWithBranch as a public API
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
Labels: 🛬 needs landing (squash)

#10046 Issue #9603: Pull trove4j from Maven Central instead of JCenter.
  build.gradle
Labels: 🛬 needs landing

#10075 Workflow to sync strings
  .github/workflows/sync-strings.yml
Labels: automation, 🕵️‍♀️ needs review, 🛬 needs landing (squash)

#10083 Improve prompt/popup handling
  components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptMiddleware.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/ConfirmDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/PromptDialogFragment.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptMiddlewareTest.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/ConfirmDialogFragmentTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#10080 GeckoView 88.0 RC 1
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko/docs/metrics.md
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegateTest.kt
  components/browser/engine-gecko/src/test/java/org/mozilla/geckoview/MockWebExtension.kt
Labels: 🛬 needs landing

#10094 Update GeckoView (Nightly) to 89.0.20210413093459.
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/autofill/GeckoLoginDelegateWrapper.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#10101 Bug 1702011 - Ship v22.0.0 of feature-webcompat
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/aboutConfigPrefs.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/appConstants.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/systemManufacturer.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/trackingProtection.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/trackingProtection.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1690091-binance.com-page-overflow.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1704653-tsky.in-clear-float.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/adsafeprotected-ima.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/rich-relevance.js
Labels: 🛬 needs landing

#10110 No issue: Upstream additional proton colors from Fenix
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing

#10095 Closes #10091 Added style property to WebExtensionBrowserMenuBuilder's constructor
  components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuHighlightableItem.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuImageText.kt
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuImageTextCheckboxButton.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilderTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#10111 For #10108 - Reconcile list and adapter positions in ExpandableLayout
  components/browser/menu/src/main/java/mozilla/components/browser/menu/view/ExpandableLayout.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/view/ExpandableLayoutTest.kt
Labels: 🛬 needs landing (squash)

#10118 Closes #10082: Update port delegate when registering new message handler
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
Labels: 🛬 needs landing

#10117 Issue #10084: Expose Nimbus API to retrieve all available experiments
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
Labels: 🛬 needs landing

#10129 Update tab counter icon
  components/ui/tabcounter/src/main/res/drawable/mozac_ui_tabcounter_box.xml
Labels: 🛬 needs landing

#10132 Update icons
  components/ui/icons/src/main/res/drawable/mozac_ic_back.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_delete.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_device_desktop.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_device_mobile.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_download.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_edit_suggestion.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_extensions.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_forward.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_link.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_lock.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_new.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_private_browsing.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_reader_mode.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_refresh.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_search.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_stop.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_sync.xml
  components/ui/icons/src/main/res/drawable/mozac_ic_warning.xml
Labels: 🛬 needs landing

#10130 Update to GeckoView Nightly 90.0.20210421095627 on master
  buildSrc/src/main/java/Gecko.kt
  components/browser/engine-gecko/src/test/java/org/mozilla/geckoview/MockWebNotification.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing (squash)

#10141 SearchSuggestionProvider: Add additional flag.
  components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
Labels: 🛬 needs landing

#10139 Closes #10138 when opening a file use the download media storage when possible
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10120 Run the sync-strings workflow daily at 2am
  .github/workflows/sync-strings.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing (squash)

#10156 No issue - Format PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
Labels: <autofill>, E1, cc-autofill, 🕵️‍♀️ needs review, 🛬 needs landing

#10119 Update the sync-strings workflow
  .github/workflows/sync-strings.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing (squash)

#10159 Minor icons update
  components/ui/icons/src/main/res/drawable/mozac_ic_close.xml
  components/ui/tabcounter/src/main/res/layout/mozac_ui_tabcounter_layout.xml
Labels: 🛬 needs landing

#10155 No issue - Format PromptRequestTest.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
Labels: <autofill>, E1, cc-autofill, 🕵️‍♀️ needs review, 🛬 needs landing

#10166 Closes #10157 Don't allow data URLs to be stored in the downloads db
  components/feature/downloads/src/androidTest/java/mozilla/components/feature/downloads/OnDeviceDownloadStorageTest.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/db/DownloadEntity.kt
  components/feature/downloads/src/test/java/mozilla/components/feature/downloads/db/DownloadEntityTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10172 Closes #10157 Remove any data urls from the download db
  components/feature/downloads/schemas/mozilla.components.feature.downloads.db.DownloadsDatabase/4.json
  components/feature/downloads/src/androidTest/java/mozilla/components/feature/downloads/OnDeviceDownloadStorageTest.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/db/DownloadsDatabase.kt
Labels: 🛬 needs landing

#10175 Uplift for #10133 - BrowserMenuCompoundButton now reports the right dimensions
  components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BrowserMenuCompoundButton.kt
  components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuCompoundButtonTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#10183 Fixes 10177 Telemetry renewal for expiring migration probes (#10178)
  components/support/migration/metrics.yaml
Labels: 🛬 needs landing

#10182 Fixes 10177 Telemetry renewal for expiring migration probes (#10178)
  components/support/migration/metrics.yaml
Labels: 🛬 needs landing
