Repository mozilla-mobile/android-components, pull requests merged in 2022-03, with the labels that each got.

#11796 Pin Flank to v21.08.1
  taskcluster/docker/ui-tests/Dockerfile
Labels: 🛬 needs landing

#11805 closes #11798: allow engines to be specified during manual syncs
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/SyncManager.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
Labels: 🛬 needs landing

#11777 Closes #11646: Update Sentry version to latest release
  .buildconfig.yml
  buildSrc/src/main/java/Dependencies.kt
  components/lib/crash-sentry-legacy/build.gradle
  components/lib/crash-sentry-legacy/proguard-rules.pro
  components/lib/crash-sentry-legacy/src/main/AndroidManifest.xml
  components/lib/crash-sentry-legacy/src/main/java/mozilla/components/lib/crash/sentry/legacy/SentryService.kt
  components/lib/crash-sentry-legacy/src/test/java/mozilla/components/lib/crash/sentry/legacy/SentryServiceTest.kt
  components/lib/crash-sentry-legacy/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/lib/crash-sentry-legacy/src/test/resources/robolectric.properties
  components/lib/crash-sentry/build.gradle
  components/lib/crash-sentry/proguard-rules.pro
  components/lib/crash-sentry/src/main/AndroidManifest.xml
  components/lib/crash-sentry/src/main/java/mozilla/components/lib/crash/sentry/SentryService.kt
  components/lib/crash-sentry/src/test/java/mozilla/components/lib/crash/sentry/SentryServiceTest.kt
  components/lib/crash-sentry/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  components/lib/crash-sentry/src/test/resources/robolectric.properties
  components/lib/crash/build.gradle
  components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/CrashReporterService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  taskcluster/ci/config.yml
Labels: 🛬 needs landing

#11727 For #11725: Switch to using WindowInsetsCompat instead of WindowInsets.
  components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Activity.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/StatusBarUtils.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/ext/WindowInsets.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/ext/WindowInsetsCompat.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/ext/WindowInsetsCompatTest.kt
  components/support/utils/src/test/java/mozilla/components/support/utils/ext/WindowInsetsTest.kt
Labels: 🛬 needs landing

#11771 Bumps nimbus fml version to 91.1.0
  components/tooling/nimbus-gradle-plugin/src/main/groovy/mozilla/components/tooling/nimbus/NimbusGradlePlugin.groovy
Labels: 🛬 needs landing

#11789 For #11788 - Add support for GeckoView Screen Orientation APIs
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/activity/GeckoScreenOrientationDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/activity/GeckoScreenOrientationDelegateTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Engine.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/activity/OrientationDelegate.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/ScreenOrientationFeature.kt
  components/feature/session/src/test/java/mozilla/components/feature/session/ScreenOrientationFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11740 For #10638 - Remove reflective access to "mSpanSlop" and "mMinSpan"
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetector.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11835 Fix for #11829: Have the additional_note from the context menu sticky
  components/feature/contextmenu/build.gradle
  components/feature/contextmenu/src/main/res/layout/mozac_feature_contextmenu_dialog.xml
  docs/changelog.md
Labels: 🛬 needs landing

#11845 Issue #11844: Take the correct number of Provided top sites
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/DefaultTopSitesStorageTest.kt
Labels: 🛬 needs landing

#11852 No issue: Update search configuration
  components/feature/search/src/main/assets/search/list.json
  components/feature/search/src/main/assets/searchplugins/google-com-nocodes.xml
  components/feature/search/src/test/java/mozilla/components/feature/search/ext/SearchEngineKtTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/storage/BundledSearchEnginesStorageTest.kt
Labels: 🛬 needs landing

#11855 Revert "No issue: Update search configuration"
  components/feature/search/src/main/assets/search/list.json
  components/feature/search/src/main/assets/searchplugins/google-com-nocodes.xml
  components/feature/search/src/test/java/mozilla/components/feature/search/ext/SearchEngineKtTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/storage/BundledSearchEnginesStorageTest.kt
Labels: 🛬 needs landing

#11861 Revert "Revert "No issue: Update search configuration""
  components/feature/search/src/main/assets/search/list.json
  components/feature/search/src/main/assets/searchplugins/google-com-nocodes.xml
  components/feature/search/src/test/java/mozilla/components/feature/search/ext/SearchEngineKtTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/storage/BundledSearchEnginesStorageTest.kt
Labels: 🛬 needs landing

#11867 Issue #11866: Upgrade detekt and its configuration to 1.19.0
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  config/detekt-baseline.xml
  config/detekt.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing (squash)

#11776 for #5271: store loaded tabs when finished loading
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorage.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/controller/DefaultControllerTest.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorageTest.kt
Labels: 🛬 needs landing

#11870 For #11869 - Set PendingIntent as mutable for autofill authentication
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/dataset/LoginDatasetBuilder.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/dataset/SearchDatasetBuilder.kt
  components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/fill/AuthFillResponseBuilder.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11879 Increment version of nimbus-fml to v92.0.0
  components/tooling/nimbus-gradle-plugin/src/main/groovy/mozilla/components/tooling/nimbus/NimbusGradlePlugin.groovy
Labels: 🛬 needs landing

#11838 Bootstrap Taskgraph from pypi in decision task
  .taskcluster.yml
  taskcluster/ac_taskgraph/build_config.py
  taskcluster/ac_taskgraph/job.py
  taskcluster/ac_taskgraph/transforms/build.py
  taskcluster/ac_taskgraph/worker_types.py
  taskcluster/ci/build/kind.yml
  taskcluster/ci/complete/kind.yml
  taskcluster/ci/lint/kind.yml
  taskcluster/requirements.in
  taskcluster/requirements.txt
  taskcluster/scripts/toolchain/android-gradle-dependencies/before.sh
Labels: automation, 🛬 needs landing

#11895 closes #11894: sync devices on authentication
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/presenter/DefaultPresenter.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorage.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/presenter/DefaultPresenterTest.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorageTest.kt
Labels: 🛬 needs landing

#11804 For #11800 - Excluded current app from 'Share link' candidates
  components/feature/contextmenu/src/main/AndroidManifest.xml
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
Labels: 🛬 needs landing

#11918 For #11905 - Delete pocket story also when imageUrl changes
  components/service/pocket/build.gradle
  components/service/pocket/src/main/java/mozilla/components/service/pocket/stories/db/PocketRecommendationsDao.kt
  components/service/pocket/src/test/java/mozilla/components/service/pocket/stories/db/PocketRecommendationsDaoTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11908 For #11876: Bucket native code crashes by process type in GleanCrashReporterService
  components/lib/crash/docs/metrics.md
  components/lib/crash/metrics.yaml
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/GleanCrashReporterService.kt
  components/lib/crash/src/test/java/mozilla/components/lib/crash/service/GleanCrashReporterServiceTest.kt
Labels: 🛬 needs landing

#11923 Update to A-S 91.1.1
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#11891 Issue #11890: Add a new action container in the EditToolbar
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_edittoolbar.xml
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11842 Fix #11841 - Add a header image to the https-only error page
  components/browser/errorpages/src/main/java/mozilla/components/browser/errorpages/ErrorPages.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11938 Bug 1752987 - Ship version 100 of the WebComapt System Addon.
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1653075-livescience.com-scrollbar-width.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1666771-zilow-map-overdraw.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1727080-nexity.fr-svg-size-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1739489-draftjs-beforeinput.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1761930-instagram.com-readablestream-pipeto.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#11937 Close #11877: Add support to sanitize intent
  components/feature/intent/src/main/java/mozilla/components/feature/intent/ext/IntentExtensions.kt
  components/feature/intent/src/test/java/mozilla/components/feature/intent/ext/IntentExtensionsTest.kt
Labels: 🛬 needs landing, 🕵️‍♀️ needs review

#11941 Closes #11940: Disable auto report crashes on the new SentryService sdk
  components/lib/crash-sentry/src/main/java/mozilla/components/lib/crash/sentry/SentryService.kt
Labels: 🕵️‍♀️ needs review
