Repository mozilla-mobile/android-components, pull requests merged in 2022-08, with the labels that each got.

#12589 Update jacoco to version 0.8.8.
  build.gradle
Labels: 🛬 needs landing, 🕵️‍♀️ needs review

#12574 No issue: Ensure suggestion icons are cropped correctly
  components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestion.kt
Labels: 🛬 needs landing

#12539 Close #12538: Crash notification will always trigger the crash prompt dialog
  components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/CrashHandlerService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/notification/CrashNotification.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt
  components/lib/crash/src/main/res/values/strings.xml
  components/lib/crash/src/test/java/mozilla/components/lib/crash/prompt/CrashReporterActivityTest.kt
Labels: 🛬 needs landing

#12560 For #12544: Allow screen to turn off after media is paused/stopped
  components/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeature.kt
  components/feature/media/src/test/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeatureTest.kt
  components/feature/pwa/src/test/java/mozilla/components/feature/pwa/feature/WebAppActivityFeatureTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Activity.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🛬 needs landing (squash)

#12563 For #12562 - Handle onPromptDismiss in ChoicePromptDelegate
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/ChoicePromptDelegate.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/ChoicePromptDelegateTest.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  docs/changelog.md
Labels: 🛬 needs landing

#12575 No issue: Do not save "about:crashparent" tab when saving state
  components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/SessionStorage.kt
  components/browser/session-storage/src/test/java/mozilla/components/browser/session/storage/SessionStorageTest.kt
Labels: 🛬 needs landing

#12615 No issue: Update Nimbus plugin to use version 93.6.0
  components/tooling/nimbus-gradle-plugin/src/main/groovy/mozilla/components/tooling/nimbus/NimbusGradlePlugin.groovy
Labels: 🛬 needs landing

#12591 Bug 1782194 - Enforce a single Glean major version across all dependencies
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#12617 Close #12616: Add message for declarativeNetRequest permission
  components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  components/feature/addons/src/main/res/values/strings.xml
  components/feature/addons/src/test/java/AddonTest.kt
Labels: 🛬 needs landing

#12592 Upgrade version of nimbus-fml to 93.8.0
  buildSrc/src/main/java/Dependencies.kt
  components/tooling/nimbus-gradle-plugin/src/main/groovy/mozilla/components/tooling/nimbus/NimbusGradlePlugin.groovy
Labels: 🛬 needs landing

#12619 Bug 1783843 - Remove the workaround to support Glean in libs
  build.gradle
Labels: 🛬 needs landing

#12277 Close #12267: Add support for Save to PDF in GeckoEngineSession
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/EngineDelegateMiddleware.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/EngineStateReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing, 🕵️‍♀️ needs review

#12640 Fixes #12639: switch SyncState.account to null on log out
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/store/SyncAction.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/store/SyncStoreSupport.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/store/SyncStoreSupportTest.kt
Labels: 🛬 needs landing

#12661 Bug 1776674 - Ship v105.0.0 of feature-webcompat
  components/feature/webcompat/src/main/assets/extensions/webcompat/about-compat/aboutPageProcessScript.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1784141-aveeno.com-unsupported.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1784195-nutmeg.morrisons.com-overflow.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1784199-entrata-platform-unsupported.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1784351-movistar.com.ar-overflow-overlay-fix.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1784546-seznam.cz-popup-height.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1784302-effectiveType-shim.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1784309-bet365.com-math-pow.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/hamropatro.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/humblebundle.js
Labels: 🛬 needs landing

#12665 Upgrades appservices to 94.1.0
  buildSrc/src/main/java/Dependencies.kt
  components/lib/crash/docs/metrics.md
  components/support/sync-telemetry/docs/metrics.md
  components/tooling/nimbus-gradle-plugin/src/main/groovy/mozilla/components/tooling/nimbus/NimbusGradlePlugin.groovy
Labels: 🛬 needs landing

#12677 For #12676 Allow the search widget to match the resized width
  components/feature/search/src/main/res/layout/mozac_search_widget_extra_small_v2.xml
  components/feature/search/src/main/res/layout/mozac_search_widget_medium.xml
  components/feature/search/src/main/res/layout/mozac_search_widget_small.xml
  components/feature/search/src/main/res/layout/mozac_search_widget_small_no_mic.xml
  docs/changelog.md
Labels: 🛬 needs landing

#12670 update NimbusGradlePlugin to use the new `generate` and `generate-experimenter` commands
  components/tooling/nimbus-gradle-plugin/src/main/groovy/mozilla/components/tooling/nimbus/NimbusGradlePlugin.groovy
  docs/changelog.md
Labels: 🛬 needs landing

#12638 Disable find in page for empty queries
  components/feature/findinpage/src/main/java/mozilla/components/feature/findinpage/view/FindInPageBar.kt
  components/feature/findinpage/src/test/java/mozilla/components/feature/findinpage/view/FindInPageBarTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#12690 Revert "Use the local server for testing"
  components/service/glean/src/main/java/mozilla/components/service/glean/testing/GleanTestLocalServer.kt
  samples/glean/src/androidTest/java/org/mozilla/samples/glean/MainActivityTest.kt
Labels: 🛬 needs landing

#12649 Make sharing images work with Direct Share
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt
  docs/changelog.md
Labels: 🛬 needs landing

#12699 Update ac-version-for-fenix-beta version to fix sync-strings action
  .github/workflows/sync-strings.yml
Labels: 🛬 needs landing

#12714 update bot name
  taskcluster/ci/version-bump/kind.yml
Labels: 🛬 needs landing

#12712 For #12711 - Use a separate reader for autocomplete suggestions
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Connection.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#12687 Close #9829: Move IO work in FxaPushSupportFeature to a coroutine
  components/feature/accounts-push/README.md
  components/feature/accounts-push/build.gradle
  components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt
  components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/cache/PushScopeProperty.kt
  components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/cache/ScopeProperty.kt
  components/feature/accounts-push/src/test/java/mozilla/components/feature/accounts/push/FxaPushSupportFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing
