Repository mozilla-mobile/android-components, pull requests merged in 2022-01, with the labels that each got.

#11443 Upgrade Glean to 42.2.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#11375 For # #11374 - Restore immersive mode
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Activity.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
  docs/changelog.md
  samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
Labels: 🛬 needs landing

#11479 For #11477 - Use textUri as inputType to prevent autocomplete spacing
  components/feature/autofill/src/main/res/layout/mozac_feature_autofill_search.xml
Labels: 🛬 needs landing

#11491 Upgrade Glean to 42.3.0
  buildSrc/src/main/java/Dependencies.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11497 Issue #11496: Add Violet70A80 to ui-colors
  components/ui/colors/src/main/java/mozilla/components/ui/colors/PhotonColors.kt
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing

#11505 Issue #11504: Use @color/mozac_ui_icons_fill as fill color for mozac_ic_cookies
  components/ui/icons/src/main/res/drawable/mozac_ic_cookies.xml
Labels: 🛬 needs landing

#11508 Issue #11507: Use @color/mozac_ui_icons_fill as fill color for mozac_ic_web_extension_default_icon
  components/ui/icons/src/main/res/drawable/mozac_ic_web_extension_default_icon.xml
Labels: 🛬 needs landing

#11520 Update to first GeckoView 97 Beta
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#11524 Delete publicsuffixlist/ext/String
  components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/ext/String.kt
  components/lib/publicsuffixlist/src/test/java/mozilla/components/lib/publicsuffixlist/ext/StringTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11530 Close #11383: Ensure each tab group does not have duplicate tab IDs
  components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabGroupReducer.kt
  components/browser/state/src/test/java/mozilla/components/browser/state/action/TabGroupActionTest.kt
Labels: 🛬 needs landing

#11531 Update CODEOWNERS
  CODEOWNERS
Labels: 🛬 needs landing

#11502 Updated Readme.md File
  components/feature/prompts/README.md
Labels: 🛬 needs landing

#11562 Update App Services dependency from 86.2.1 to 86.2.2
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#11566 For #11565 - Add photonDarkGrey90A60 and photonLightGrey05A60
  components/ui/colors/src/main/java/mozilla/components/ui/colors/PhotonColors.kt
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing

#11564 For #11527 - Allow the decor view time to process the incoming insets
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Activity.kt
  components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11573 Issue #11567: Fix assertion in mozilla.components.feature.top.sites.PinnedSitesStorageTest - testAddingPinnedSite
  components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/OnDevicePinnedSitesStorageTest.kt
Labels: 🛬 needs landing, 🕵️‍♀️ needs review

#11518 For #11316: Update leakcanary version to 2.8.1
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#11577 For #11298 - Manifest merger failed : android:exported needs to be explicitly specified
  samples/crash/src/main/AndroidManifest.xml
  samples/dataprotect/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#11579 Close #11563: Add IMMUTABLE intent flag for feature-media
  components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
Labels: 🛬 needs landing

#11561 Upgrade to Glean v43.0.2
  docs/changelog.md
Labels: 🛬 needs landing

#11533 No issue: Add TabPartition tests
  components/browser/state/src/test/java/mozilla/components/browser/state/state/TabPartitionTest.kt
Labels: 🛬 needs landing

#11487 Uniffi Places
  buildSrc/src/main/java/Dependencies.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt
  components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Types.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorageTest.kt
  components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  components/concept/storage/src/main/java/mozilla/components/concept/storage/BookmarksStorage.kt
  components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt
  components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt
  components/service/nimbus/src/test/java/mozilla/components/service/nimbus/NimbusTest.kt
  components/support/migration/src/test/java/mozilla/components/support/migration/FennecMigratorTest.kt
Labels: 🛬 needs landing (squash)

#11546 Replace clearColorFilter with setColorFilter for security icon
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11582 Add baidu search ad telemetry
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/BaseSearchTelemetry.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11592 Fix browser-session dead link in components.md
  docs/components.md
Labels: 🛬 needs landing

#11588 Fixup FML plugin to work on CI
  components/tooling/nimbus-gradle-plugin/src/main/groovy/mozilla/components/tooling/nimbus/NimbusGradlePlugin.groovy
Labels: 🛬 needs landing (squash)

#11601 Issue #11600: Add Violet20A60 to ui-colors
  components/ui/colors/src/main/java/mozilla/components/ui/colors/PhotonColors.kt
  components/ui/colors/src/main/res/values/photon_colors.xml
Labels: 🛬 needs landing

#11500 Update tracking protection icon state
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11606 Fixup calling the wrong method in the FML plugin
  components/tooling/nimbus-gradle-plugin/src/main/groovy/mozilla/components/tooling/nimbus/NimbusGradlePlugin.groovy
Labels: 🛬 needs landing

#11607 No issue: Add validate code set
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/Utils.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/telemetry/incontent/InContentTelemetryTest.kt
Labels: 🛬 needs landing

#11608 Issue #11605: Add option to include provided top sites in TopSitesConfig
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesConfig.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSitesStorage.kt
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/presenter/DefaultTopSitesPresenter.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/DefaultTopSitesStorageTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11603 Update AS version to fix issue when navigating to invalid url
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#11613 No issue: Add null as valid code
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/Utils.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/telemetry/incontent/InContentTelemetryTest.kt
Labels: 🛬 needs landing

#11622 No issue: Add valid channel set
  components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/Utils.kt
  components/feature/search/src/test/java/mozilla/components/feature/search/telemetry/incontent/InContentTelemetryTest.kt
Labels: 🛬 needs landing

#11616 Issue #11615: Remove position property from TopSite.Provided
  components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/TopSite.kt
  components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/DefaultTopSitesStorageTest.kt
  components/service/contile/src/main/java/mozilla/components/service/contile/ContileTopSitesProvider.kt
  components/service/contile/src/test/java/mozilla/components/service/contile/ContileTopSitesProviderTest.kt
Labels: 🛬 needs landing

#11612 for #6215 - Firefox crash notification is not displayed on devices wi…
  components/lib/crash/src/main/java/mozilla/components/lib/crash/notification/CrashNotification.kt
  docs/changelog.md
Labels: 🛬 needs landing

#11631 Issue #11692: Set WebRequest::beConservative in GeckoViewFetchClient
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
Labels: 🛬 needs landing
