Repository mozilla-mobile/android-components, pull requests merged in 2022-10, with the labels that each got.

#12876 For #12874: Add method to duplicate selected tab
  components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  ktlint-baseline.xml
Labels: 🛬 needs landing (squash)

#12888 Update some Gradle dependencies
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  components/lib/crash-sentry/src/main/java/mozilla/components/lib/crash/sentry/SentryService.kt
Labels: 🛬 needs landing, 🕵️‍♀️ needs review

#12903 Fix #12902: update publish/build gradle files to use the local property in the build version instead of a runtime-generated timestamp
  components/tooling/glean-gradle-plugin/build.gradle
  components/tooling/nimbus-gradle-plugin/build.gradle
  docs/changelog.md
  publish.gradle
Labels: 🛬 needs landing

#12911 Update CODEOWNERS
  CODEOWNERS
Labels: 🛬 needs landing

#12922 Update GeckoView (Release) to 106.0.20221010110315
  buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#12897 For #12894 Canceling the "Open in app?" should open the page in focus browser.
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  docs/changelog.md
Labels: 🛬 needs landing

#12927 Close #12926: Use external flag when opening fallback URL
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
Labels: 🛬 needs landing

#12624 Close #12623: Do not match issue ID if preceded by other characters
  .github/workflows/issue-linker.yml
Labels: 🛬 needs landing

#12807 For #12804 - Catch the exception when querying activities
  components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  docs/changelog.md
Labels: 🛬 needs landing

#12837 Fix gradle version code generation on Windows
  settings.gradle
Labels: 🛬 needs landing

#12937 Pin relbot Github Action to the 1.0.0 tag
  .github/workflows/create-release.yml
  .github/workflows/update-geckoview.yml
Labels: 🛬 needs landing

#12956 Start 108.0.0 development cycle
  docs/changelog.md
  version.txt
Labels: 🛬 needs landing

#12957 No issue: Update release checklist example link
  docs/contribute/release_checklist.md
Labels: 🛬 needs landing

#12935 For #12934 - Lower font size for reader mode font controls
  components/feature/readerview/src/main/res/layout/mozac_feature_readerview_view.xml
Labels: 🛬 needs landing

#12961 Strip 'refs/heads/' out of 'base_ref' parameter in .taskcluster.yml
  .taskcluster.yml
Labels: 🛬 needs landing

#12857 For #12877: Make Reader mode default to set theme
  components/feature/readerview/src/main/java/mozilla/components/feature/readerview/internal/ReaderViewConfig.kt
  components/feature/readerview/src/test/java/mozilla/components/feature/readerview/internal/ReaderViewConfigTest.kt
  docs/changelog.md
Labels: 🛬 needs landing (squash)

#12963 base_ref bustage: extend the [11:] hack to action/cron
  .taskcluster.yml
Labels: 🛬 needs landing

#12965 Action base ref fix
  .taskcluster.yml
Labels: 🛬 needs landing

#12790 Close #12645: Add sync engine aware debouncing
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt
  components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorage.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/controller/DefaultControllerTest.kt
  components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorageTest.kt
  components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt
  components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/sync/WorkManagerSyncManagerTest.kt
Labels: <sync>, 🛬 needs landing

#12883 For #12882: Allow the QR functionality to be queried and resumed
  components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFeature.kt
  components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt
  components/feature/qr/src/test/java/mozilla/components/feature/qr/QrFeatureTest.kt
  components/feature/qr/src/test/java/mozilla/components/feature/qr/QrFragmentTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#12933 Create extension for truncating urls
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
Labels: 🛬 needs landing

#12955 The colors of the icons from the status bar should be in contrast with the status bar background color
  components/support/ktx/build.gradle
  components/support/ktx/src/androidTest/AndroidManifest.xml
  components/support/ktx/src/androidTest/java/mozilla/components/support/ktx/TestActivity.kt
  components/support/ktx/src/androidTest/java/mozilla/components/support/ktx/android/view/WindowKtTest.kt
  components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Window.kt
  docs/changelog.md
Labels: 🛬 needs landing

#12980 Issue #12939 - Add ktlint commits to .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: 🛬 needs landing

#12973 Bug 1795949 - Dismiss ChoiceDialogFragment only when it is attached.
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
Labels: 🛬 needs landing

#12999 Bug 1797273 - Bind OverlayAddOnProgressBinding to the included addonProgressOverlay view
  samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt
  samples/browser/src/main/res/layout/fragment_add_ons.xml
Labels: 🛬 needs landing

#13001 No issue: Update AndroidX Annotation to latest version.
  buildSrc/src/main/java/Dependencies.kt
  components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFeature.kt
  components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt
  components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/ChoiceDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/TimePickerDialogFragment.kt
  components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt
  components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppLauncherActivity.kt
  components/feature/search/src/main/java/mozilla/components/feature/search/widget/AppSearchWidgetProvider.kt
  components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarPresenter.kt
  components/lib/crash-sentry-legacy/src/main/java/mozilla/components/lib/crash/sentry/legacy/SentryService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/CrashHandlerService.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/prompt/CrashReporterActivity.kt
  components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SendCrashReportService.kt
  components/service/glean/src/main/java/mozilla/components/service/glean/net/ConceptFetchHttpUploader.kt
  components/service/location/src/main/java/mozilla/components/service/location/MozillaLocationService.kt
  components/support/base/src/main/java/mozilla/components/support/base/android/Padding.kt
  components/support/base/src/main/java/mozilla/components/support/base/utils/LazyComponent.kt
  components/support/images/src/main/java/mozilla/components/support/images/decoder/AndroidImageDecoder.kt
Labels: 🛬 needs landing

#12991 Update Readability to 0.4.2
  components/feature/readerview/src/main/assets/extensions/readerview/manifest.template.json
  components/feature/readerview/src/main/assets/extensions/readerview/readability/JSDOMParser-0.4.2.js
  components/feature/readerview/src/main/assets/extensions/readerview/readability/readability-0.4.2.js
  components/feature/readerview/src/main/assets/extensions/readerview/readability/readability-readerable-0.4.2.js
  components/feature/readerview/src/main/assets/extensions/readerview/readerview.html
Labels: 🛬 needs landing

#12975 Add setting for cookie banner handling mode
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt
  components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#13014 Bug 1776676 - Ship v107.0.0 of the WebCompat System Addon.
  components/feature/webcompat/src/main/assets/extensions/webcompat/about-compat/AboutCompat.jsm
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1784546-seznam.cz-popup-height.css
  components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1610358-pcloud.com-appVersion-change.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/lib/custom_functions.js
  components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  components/feature/webcompat/src/main/assets/extensions/webcompat/shims/stackblitz.js
Labels: 🛬 needs landing

#13005 Upgrade release/106.0 Application Services to v94.2.2
  buildSrc/src/main/java/Dependencies.kt
  components/tooling/nimbus-gradle-plugin/src/main/groovy/mozilla/components/tooling/nimbus/NimbusGradlePlugin.groovy
Labels: 🛬 needs landing

#13006 Upgrade release/107.0 Application Services to v94.2.2
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#12996 Update Sentry to 6.6.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#13027 Bug 1798026 - part 1: Don't run geckoview bumps automatically until t…
  .github/workflows/update-geckoview.yml
Labels: 🛬 needs landing
